### ISSUE TITLE
postgresql 12 failed to install the plugin

### ISSUE THREAD

**Issue by FlickerMi** [pgvector/pgvector#101]
postgresql version: 12.0

run:
```
CREATE EXTENSION vector;
```

error message:

Query 1 ERROR: ERROR:  could not load library "/usr/lib/postgresql/12/lib/vector.so": /usr/lib/postgresql/12/lib/vector.so: undefined symbol: float_overflow_error

**Comment by ankane** [comment]
Hi @FlickerMi, thanks for reporting! It looks like `float_overflow_error` wasn't added until Postgres 12.3. Pushed a fix in the commit above.
