### ISSUE TITLE
Performance tuning issues with pgvector

### ISSUE THREAD

**Issue by RongHouchao** [pgvector/pgvector#103]
I am currently t_ test_ test_ There is 1 million data in the test table, and each data has an original_feature field (vector type) stores a 768-dimensional vector.

**Established index**: CREATE INDEX ON t_ test_ test_ test USING ivfflat (original_feature vector_ip_ops) WITH (lists = 7500);

At present, the top 100 internal product retrieval recall takes over 2.5 seconds. How can I optimize this ？

**Recall statement:**

BEGIN;
SET LOCAL ivfflat.probes = 10;
select (-1 * (original_feature <#> '[${vector}]')) as score from t_ test_ test_ test order by score desc limit 100;
COMMIT;

Where ${vector} is a 768-dimensional vector.

**machine**
My host is an 8C16G machine, using Docker deployed pgvector: v0.4.0

![image](https://user-images.githubusercontent.com/117245915/234463684-6085a387-a09b-439c-9032-65c5488ede62.png)

**Comment by ankane** [comment]
Hi @RongHouchao, it looks like you're ordering by an expression, so the index won't be used (you can confirm with `EXPLAIN ANALYZE`). Use `ORDER BY original_feature <#> '[...]'` instead.
