### ISSUE TITLE
make failing with warning: unknown warning option '-Wno-deprecated-non-prototype'; did you mean '-Wno-deprecated-coroutine'? [-Wunknown-warning-option] #7 1.930 error: unknown argument: '-no-opaque-pointers'

### ISSUE THREAD

**Issue by esobczak1970** [pgvector/pgvector#107]
Getting the following when trying to make inside a docker image:
#7 1.929 warning: unknown warning option '-Wno-deprecated-non-prototype'; did you mean '-Wno-deprecated-coroutine'? [-Wunknown-warning-option]
#7 1.930 error: unknown argument: '-no-opaque-pointers'
#7 1.933 make: *** [/usr/local/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:1071: src/ivfbuild.bc] Error 1
------
executor failed running [/bin/sh -c git clone https://github.com/pgvector/pgvector.git     && cd pgvector     && sed -i 's/-no-opaque-pointers//' Makefile     && make install     && cd ..     && rm -rf pgvector]: exit code: 2

My latest Dockerfile looks like this trying to resolve it:
# Use a slim version of the official PostgreSQL image as the base image
FROM postgres:13-alpine

# Install build dependencies and Python
RUN apk add --no-cache gcc musl-dev postgresql-dev make git python3 py3-pip

# Install the psycopg2 library for Python
RUN pip install psycopg2-binary

# Install pgvector extension
RUN git clone https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && sed -i 's/-no-opaque-pointers//' Makefile \
    && make install \
    && cd .. \
    && rm -rf pgvector

# Expose PostgreSQL port
EXPOSE 5432

# Copy entrypoint script and configuration file to the container
COPY entrypoint.sh /entrypoint.sh
COPY config.yml /config.yml
COPY setenv.sh /setenv.sh

# Set default value for CONFIG_FILE environment variable
ENV CONFIG_FILE=/config.yml

# Run the setenv script to set environment variables from config file
CMD ["sh", "/setenv.sh", "/entrypoint.sh"]

**Comment by ankane** [comment]
Hi @esobczak1970, thanks for reporting. I don't think the error is specific to pgvector (since `-no-opaque-pointers` comes from Postgres/[PGXS](https://www.postgresql.org/docs/current/extend-pgxs.html)), but it can be fixed by using `postgres:13-alpine3.16`.
