### ISSUE TITLE
Please support vector sizes of 20,000 like PinconeDb

### ISSUE THREAD

**Issue by AceHack** [pgvector/pgvector#112]
I would much rather use pgVector with PostgreSQL than Pinecone.  Any suggestions?  Thanks.

**Comment by ankane** [comment]
Hi @AceHack, can you share more about the use case?

**Comment by flexchar** [comment]
If I may, I'd love to hear where you get 20k embeddings, if that of course is your use case. @AceHack

**Comment by ankane** [comment]
Can revisit when there are use cases to discuss

**Comment by ankane** [comment]
You can currently store vectors with up to 16,000 dimensions.

**Comment by ankane** [comment]
For indexing, will hopefully be able to support more than 2,000 dimensions at some point, but you'll need to use dimensionality reduction or another project for now.

fwiw, from the link above, they "strongly recommend using text-embedding-ada-002" over the other models, so I think the Davinci use case will be less common.

**Comment by nreith** [comment]
@ankane Do you have any updates on when it might be on pgvector's roadmap, or postgres' to support more than 2k indexed dimensions? Also, do you have any info on how dimensionality reduction impacts accuracy? I'm basically evaluating between pgvector and redis, and there are a lot of pros with pgvector, but 2k dimensions for indexed seems a limiting factor.

**Comment by jkatz** [comment]
@nreith Do you have a specific dataset with > 2K dimensions that you are looking to index?

**Comment by nreith** [comment]
@jkatz yes. Pretty much all the new big ones in huggingface that come with embeddings.

**Comment by saurik** [comment]
@jkatz Another use case for >2k is that it seems the common facial recognition embedding libraries generate 2622 dimension vectors.
