### ISSUE TITLE
Add arm Docker image

### ISSUE THREAD

**Issue by marius-se** [pgvector/pgvector#115]
Currently the image hosted on Docker Hub only supports amd64. It'd be great to get a native ready-to-use image for arm as well!

Many thanks for pgvector <3

**Comment by ankane** [comment]
Hi @marius-se, thanks for the suggestion. This will officially go out with the next release (0.4.2), but you can use the `ankane/pgvector:test` tag (based on 0.4.1) until then.

**Comment by marius-se** [comment]
Ah nice! Currently I just build my own image. Thanks a lot!

**Comment by ankane** [comment]
Sounds good (in that case, deleting the tag, so no one starts relying on it).

**Comment by FunkyYang** [comment]
where can be download?
