### ISSUE TITLE
Idea / Feature Request: Performance Benchmarking 

### ISSUE THREAD

**Issue by Jeadie** [pgvector/pgvector#116]
# Overview
Improvements, particularly performance focused changes, to pgvector are currently difficult to consider without a clear performance test framework or process. 

This is a feature request (and volunteering) to standardise how and what performance testing should be done. This may include performance regression, large scale or dataset testing. 

### Performance Metrics
Open to suggestion given my familiarity with search engines over databases, but at a minimum:
1. Precision at K
2. Recall at K
3. Queries/second as a function of index size (at least feasible on random vectors)
4. Recall/Precision@K as a function of filtered results (i.e. measure the impact of `WHERE` clauses)
5. Build Speed
   1. Add index to existing column
   2. Build table/index from scratch
   3. Marginal inserts, as a function of current table size (e.g. inserts/second when index has 100, 1000, ... entries)

### Datasets: 
 1. Randomly generated vectors. Easy and fast to create and test with.
 2. [erikbern/ann-benchmarks](https://github.com/erikbern/ann-benchmarks) has a good collection of benchmark datasets that could be used. Importantly these include precomputed (up to k=100) nearest neighbours for a subset of test examples.

**Comment by ydennisy** [comment]
+1 on this @Jeadie I think this would really help those landing on this page and considering this vs the myriad of other options appearing!

**Comment by Jeadie** [comment]
In [erikbern/ann-benchmarks/issues/411](https://github.com/erikbern/ann-benchmarks/issues/411), I have suggested/requested making ann-benchmarks a python installable library. If this can occur, it will make this issue both 1) easier to implement 2) cheaper/lighter to maintain.

**Comment by ankane** [comment]
@Jeadie Thanks for sharing, and sorry for the delay. I think it's fine to do ad hoc testing of performance improvements for now. I've been using both custom scripts (which I can try to clean up and share) and ann-benchmarks, fwiw.

@ydennisy For existing benchmarks, check out the [ann-benchmark results](https://github.com/erikbern/ann-benchmarks#results).

**Comment by Jeadie** [comment]
It'd be great if you could share them, @ankane, even scrappy and on a different branch
