### ISSUE TITLE
Installation via brew fails PG14

### ISSUE THREAD

**Issue by ndrean** [pgvector/pgvector#119]
On MacOS Ventura 13.3.1 and Postgres 14.7, I can't run the extension. Note sure if this is a brew issue, or MacOS or pgvector.

```
> brew install pgvector

> psql
# create extension vector;
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/vector.control": No such file or directory
```

`pgvector` is installed at /opt/homebrew/Cellar/pgvector

Note that `postgis` is installed  in /opt/homebrew/Cellar/Postgis and works ("create extension postgis" works)

**Comment by ankane** [comment]
Hi @ndrean, that error indicates the extension isn't installed on the database server. The Homebrew instructions only work for Homebrew Postgres. Use the main (`git clone`) instructions for Postgres.app.

When it's installed, it'll show up in:

```sql
SELECT * FROM pg_available_extensions WHERE name = 'vector';
```

(fwiw, PostGIS works since it's preinstalled in Postgres.app)

**Comment by ndrean** [comment]
I avoided the git clone make because of "make: arm64-apple-darwin20.0.0-clang: No such file or directory" on an M2 and couldn't solve this neither :(

**Comment by ankane** [comment]
The make error looks like an issue with your environment (you could try reinstalling Xcode command line tools).

For Homebrew, you'll need to use the `postgresql` formula, not `postgresql@15` (it's just how Postgres extensions with Homebrew currently work).

**Comment by ndrean** [comment]
I updated Xcode to 14.3, no success.
