### ISSUE TITLE
Indexing vectors have size 2048

### ISSUE THREAD

**Issue by koseemre** [pgvector/pgvector#120]
Hi. I am trying to index vectors with size 2048.

Firstly I build alpine-based postgresql version 15 with configs below
		--with-blocksize=32 \
		--with-wal-blocksize=32 \

Then build the pgvector image using build postgresql base with the updated IVFFLAT_MAX_DIM value in ivfflat.h.

Finally the block_size seems 32768 in DB, but when I tried to index my vectors, DB gives an error below:

**ERROR: index row requires 8208 bytes, maximum size is 8191.** 

Is there any suggestion about the case ?

postgresql build ref: https://github.com/docker-library/postgres/tree/master/15/alpine

pgvector alpine base build ref: https://github.com/pgvector/pgvector/pull/4

**Comment by ankane** [comment]
Hi @koseemre, thanks for reporting! It looks like the max index tuple size is [hard-coded](https://github.com/postgres/postgres/blob/c5b7f67fcc8c4a01c82660eb0996a3c697fac283/src/include/access/itup.h#L65) as 8191 bytes in Postgres, so the suggestion in the readme won't work. I've removed it in the commit above. The one other option at the moment is dimensionality reduction.

**Comment by nreith** [comment]
@ankane Does this change in the commit you mentioned have any affect on max dimensions of 16k, or max indexed dimensions of 2k?

**Comment by montanalow** [comment]
There is a report that this can be changed pretty easily upstream in PG without significant repercussions, although I've not tested it. Has anyone from pgvector reached out to the core team to see if they're open to a patch to make this configurable similar to blocksize? 

https://dba.stackexchange.com/questions/244624/how-to-increase-index-row-maximum-size-in-postgresql

**Comment by jkatz** [comment]
@montanalow The comment there says "it might have repercussions in other parts of the code" and would warrant further investigation. It may be worth reaching out to -hackers to understand what the ramifications are of changing it.

**Comment by montanalow** [comment]
I've submitted a patch to -hackers to start a discussion on increasing the limit so we can understand the ramifications.
