### ISSUE TITLE
Gradually worsening INSERT performance

### ISSUE THREAD

**Issue by amogh-goalist** [pgvector/pgvector#123]
Hello, I was trying to store OpenAI embedding vectors in using pgvector, and I noticed that the performance gradually as the number of rows stored increases. For example:
![image](https://github.com/pgvector/pgvector/assets/132321485/3d713e34-6b29-4a19-925e-9bac9f30ce16)

Each iteration here inserts 1000 vectors in bulk, and as is visible, the time taken for each insert increases.

Any insights on what could be happening? For reference the query generated by the framework I'm using looks something like this:

```
INSERT INTO langchain_pg_embedding (collection_id, embedding, document, cmetadata, custom_id, uuid) VALUES (%(collection_id__0)s::UUID, %(embedding__0)s, %(document__0)s, %(cmetadata__
0)s, %(custom_id__0)s, %(uuid__0)s::UUID), (%(collection_id__1)s:: ... 131095 characters truncated ...  %(embedding__999)s, %(document__999)s, %(cmetadata__999)s, %(custom_id__999)s, %(uuid__999)s::UUID)
```

Perhaps the insert could be optimized manually in some manner? Or maybe bulk inserts are not the way to go? It would be fine if it was just a few hundred thousand rows, but unfortunately I have around 5 million vectors I need to store. :(

Thank you!

**Comment by amogh-goalist** [comment]
Hello, sorry for the red herring. This turned out to be an issue with the framework, it was making very expensive sequential scans of the table before each insert for some reason. Thanks again for such a great extension!

**Comment by ankane** [comment]
Thanks for following up!
