### ISSUE TITLE
(psycopg2.errors.UndefinedObject) type "vector" does not exist

### ISSUE THREAD

**Issue by Rijoanul-Shanto** [pgvector/pgvector#124]
I was trying to embed some documents with the help of [langchain](https://github.com/hwchase17/langchain). But I'm having the following error:
```python
(psycopg2.errors.UndefinedObject) type "vector" does not exist
LINE 4:  embedding VECTOR(1536), 
                   ^

[SQL: 
CREATE TABLE langchain_pg_embedding (
    collection_id UUID, 
    embedding VECTOR(1536), 
    document VARCHAR, 
    cmetadata JSON, 
    custom_id VARCHAR, 
    uuid UUID NOT NULL, 
    PRIMARY KEY (uuid), 
    FOREIGN KEY(collection_id) REFERENCES langchain_pg_collection (uuid) ON DELETE CASCADE
)
]
```
___
My environment info:

- [pgvector](https://hub.docker.com/layers/ankane/pgvector/v0.4.1/images/sha256-f6eaf4a48794f70f616de15378172a22811c4f3c50a02ddf97ff68f3a242fed1) docker image ankane/pgvector:v0.4.1

- python 3.10.6, psycopg2 2.9.6, [pgvector](https://pypi.org/project/pgvector/0.1.6/) 0.1.6
___
List of installed extensions on postgres
```
  Name   | Version |   Schema   |                Description                 
---------+---------+------------+--------------------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 vector  | 0.4.1   | public     | vector data type and ivfflat access method
```

I've tried fresh installing the postgres image with pgvector extension enabled, manually installing the extension like following:
```sql
CREATE EXTENSION IF NOT EXISTS vector
    SCHEMA public
    VERSION "0.4.1";
```
But no luck.

**Comment by ankane** [comment]
Hi @Rijoanul-Shanto, that error indicates the extension isn't enabled in the database (need to run `CREATE EXTENSION` in each database that uses it) or it's not in the [search_path](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH) (call `SHOW search_path;` from psycopg2 to check).

**Comment by Rijoanul-Shanto** [comment]
Hello @ankane,

Really appreciate your quick response! I've figured it out. The issue was somewhere else. My extension for the database I was supposed to use was totally fine, also the `search_path` had the schema properly. It was my silly environment variable which was responsible for which database to use, got messed up 🥲, and was using the default database `postgres` which didn't have the extension enabled.

Thanks again. 😄

**Comment by gregiorg** [comment]
Hello @Rijoanul-Shanto 

I believe I have a very similar problem (if not the same) as you. I am also using Langchain and trying to store my embeddings.  The code I'm trying is as follows :

```Python
conn = psycopg2.connect(
    host="127.0.0.1",
    port=5432,
    dbname="mydb",
    user="user",
    password="password"
)

with conn.cursor() as cur:
    cur.execute("""
    CREATE EXTENSION vector;
    """)

conString = "postgresql://user:password@localhost:5432/mydb"

# Encode the text data using OpenAIEmbeddings and insert the resulting embeddings into the pgvector database.
PGVector.from_documents(texts, embeddings, index_name="hardis_blog", connection_string=conString)
```
Where `texts` are the texts I want to embed and `embeddings` is the OpenAIEmbedding.

I have set 3 environment variables in the container :
* POSTGRES_PASSWORD == password
* POSTGRES_USER == user
* POSTGRES_DB == mydb

I'm very new to these tools and I don't understand how you fixed your problem. Would you be so kind as to walk me through it ?

**Comment by Rijoanul-Shanto** [comment]
@gregiorg If you are experiencing the same issue as I had **`type "vector" does not exist`**, then it's the database that doesn't have the extension enabled.

make sure your DB has the extension enabled you are trying to embed. If the issue still persists, check if the `search_path` has the schema.

Can you show the error log?

**Comment by gregiorg** [comment]
The error log in question:
```
2023-05-11 10:01:20.491 UTC [145] ERROR:  type "vector" does not exist at character 73
2023-05-11 10:01:20.491 UTC [145] STATEMENT:  
        CREATE TABLE langchain_pg_embedding (
                collection_id UUID, 
                embedding VECTOR(1536), 
                document VARCHAR, 
                cmetadata JSON, 
                custom_id VARCHAR, 
                uuid UUID NOT NULL, 
                PRIMARY KEY (uuid), 
                FOREIGN KEY(collection_id) REFERENCES langchain_pg_collection (uuid) ON DELETE CASCADE
        )
```

Could you please explain how I set up the `search_path` ? (as I said, very new 😅)

**Comment by ankane** [comment]
@gregiorg It looks like you're not committing the `CREATE EXTENSION` transaction.

```python
with conn.cursor() as cur:
    cur.execute('CREATE EXTENSION IF NOT EXISTS vector')

conn.commit()
```

**Comment by gregiorg** [comment]
@ankane @Rijoanul-Shanto 
Thank you very much to both of you. I did not know about committing.
Have a nice day :)
