### ISSUE TITLE
Server closes connections when cosine_distance calculates more than 7 dims

### ISSUE THREAD

**Issue by maxmetalm** [pgvector/pgvector#130]
Hi,

we are testing the addon in the docker env. Vector version is 0.4.1. RAM 4Gb. Postgres version 12. Ubuntu 18.

Simple queries like next with more that 7 dimensions throw exception and db is rolled back.

`select cosine_distance('[ 1, 1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1]','[ 1, 1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1]');
`

Error:
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> The connection to the server was lost. Attempting reset: Failed.

Logs:
> server process (PID 1085) was terminated by signal 4: Illegal instruction
> Failed process was running: select cosine_distance bla bla
> "terminating any other active server processes"
> The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory

We have no idea why this is happening. Are there any guesses?
Thank you

**Comment by ankane** [comment]
Hi @maxmetalm, `illegal instruction` typically means the program was compiled with optimizations that aren't available on the machine where you're trying to run it. You can fix it by compiling with:

```sh
make OPTFLAGS=""
```
