### ISSUE TITLE
Hybrid Search with TS query and PGVECTOR

### ISSUE THREAD

**Issue by aiseei** [pgvector/pgvector#134]
hI @ankane !

we've been using tsquery to great effect but it has its limitations. Would like your thoughts how hybrid search with pgvector can be implemented that leverages both. 

Cheers.

**Comment by ankane** [comment]
Hi @aiseei, the simplest way to implement this would be to perform full-text search and nearest neighbor search queries and then combine them. There's [a Supabase implementation](https://js.langchain.com/docs/modules/indexes/retrievers/supabase-hybrid) in LangChain.js that combines them using the top score, but there are also more advanced approaches like cross-encoders.

Good article and resources: https://news.ycombinator.com/item?id=35053133
