### ISSUE TITLE
Add Clustering query example in the doc

### ISSUE THREAD

**Issue by leoplct** [pgvector/pgvector#138]
Hello, 
I see in the doc is missing a Clustering example. 

If I have a table with the column “embedding” of type pgvector, how can I cluster and label similar rows?

**Comment by ankane** [comment]
Hi @leoplct, pgvector doesn't expose any clustering functions, so you'll need to use another library for it.

**Comment by mtomov** [comment]
Hi @ankane ,

Have you got a suggestion for a library / approach to use?

Thank you!
