### ISSUE TITLE
Suggestions to keep IVFFlat index updated

### ISSUE THREAD

**Issue by xcu** [pgvector/pgvector#139]
I have been using pg_vector in a project to detect similar faces and so far I'm loving it!

One thing that I've noticed is that, when using an IVFFlat index, new insertions are more difficult to find (i.e, for 100 lists they require probes to go to a huge number, like 80-90). I guess that's because, while these new entries get added to the index, they don't run k-means in order to be placed in the proper inverted list. 

The issue goes away by reindexing often. I have added a cronjob that runs a reindex every X new rows, but I was wondering if there's any way to achieve the same thing (or maybe whether there are plans to do it) without this cronjob?

I have seen that https://github.com/pgvector/pgvector/issues/105 and https://github.com/pgvector/pgvector/issues/136 touch a similar subject, so I guess for now the best option would be the cronjob?
Just to clarify, I did create the index after all the initial data was in the table. It's the new rows added after that who worry me.

**Comment by ankane** [comment]
Hi @xcu, I'm not sure how to reproduce (new entries are placed in the closest list). A few questions:

1. What's the output of `EXPLAIN ANALYZE` for the `SELECT` query?
2. How many rows with non-NULL vectors are in the table when you're creating the index?
4. If you're on pgvector 0.4.2 and enable debugging (`SET client_min_messages = DEBUG;`), is there a message when running the `SELECT` query?

**Comment by xcu** [comment]
Hey @ankane , thanks a lot for the quick response! A couple of clarifications before answering your questions:

- The table has ~45M rows, and it's partitioned (via pg_partman) in child tables of 100K rows each. 
- It's done this way so that the cronjob onnly has to reindex the active partition (takes ~10s vs ~1 hour for the whole table). 
- Each vector has 512 dimensions. 
- Each new vector is added to the last partition, so I assume once each partition has its 100K vectors there should be no need to reindex it?


> 1. What's the output of `EXPLAIN ANALYZE` for the `SELECT` query?

I trimmed down the vectors and removed the index scans of the middle, since there is nothing unusual going on. The last partition with data is `vectors_p45000000`, the next ones are empty and are created ahead of time by pg_partman:

```
Limit  (cost=4219625.81..4219691.92 rows=101 width=52) (actual time=22689.535..22733.407 rows=101 loops=1)
   ->  Merge Append  (cost=4219625.81..33240260.07 rows=44342344 width=52) (actual time=22689.522..22733.377 rows=101 loops=1)
         Sort Key: ((vectors.vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector))
         ->  Index Scan using vectors_p0_vector_idx on vectors_p0 vectors_1  (cost=9499.14..69346.13 rows=98095 width=52) (actual time=64.026..64.617 rows=2 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p100000_vector_idx on vectors_p100000 vectors_2  (cost=9499.16..69174.14 rows=97550 width=52) (actual time=59.741..59.745 rows=1 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p200000_vector_idx on vectors_p200000 vectors_3  (cost=9499.80..69308.88 rows=97974 width=52) (actual time=59.340..59.866 rows=2 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p300000_vector_idx on vectors_p300000 vectors_4  (cost=9498.68..69403.91 rows=98162 width=52) (actual time=64.127..64.127 rows=1 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p400000_vector_idx on vectors_p400000 vectors_5  (cost=9499.22..69390.23 rows=98145 width=52) (actual time=58.046..58.504 rows=2 loops=1)

         [ ... ]

         ->  Index Scan using vectors_p44800000_vector_idx on vectors_p44800000 vectors_449  (cost=9487.47..66353.22 rows=99836 width=52) (actual time=47.483..47.483 rows=1 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p44900000_vector_idx on vectors_p44900000 vectors_450  (cost=9494.29..67118.25 rows=99901 width=52) (actual time=45.043..45.459 rows=2 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p45000000_vector_idx on vectors_p45000000 vectors_451  (cost=3300.89..23687.47 rows=35822 width=52) (actual time=14.612..14.616 rows=1 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p45100000_vector_idx on vectors_p45100000 vectors_452  (cost=38.54..190.26 rows=490 width=52) (actual time=0.281..0.282 rows=0 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p45200000_vector_idx on vectors_p45200000 vectors_453  (cost=38.54..190.26 rows=490 width=52) (actual time=0.266..0.266 rows=0 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p45300000_vector_idx on vectors_p45300000 vectors_454  (cost=38.54..190.26 rows=490 width=52) (actual time=0.239..0.239 rows=0 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_p45400000_vector_idx on vectors_p45400000 vectors_455  (cost=38.54..190.26 rows=490 width=52) (actual time=0.270..0.273 rows=0 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
         ->  Index Scan using vectors_default_vector_idx1 on vectors_default vectors_456  (cost=0.28..1.69 rows=1 width=52) (actual time=0.291..0.291 rows=0 loops=1)
               Order By: (vector <-> '[0.052585288882255554, [...], -0.032869718968868256]'::vector)
 Planning Time: 179.463 ms
 Execution Time: 22878.917 ms
(917 rows)
```

> 2. How many rows with non-NULL vectors are in the table when you're creating the index?

Around 45M, with ~40K new rows per day.

> 3. If you're on pgvector 0.4.2 and enable debugging (`SET client_min_messages = DEBUG;`), is there a message when running the `SELECT` query?

Yes, this shows up

```
DEBUG:  rehashing catalog cache id 51 for pg_class; 257 tups, 128 buckets
DEBUG:  rehashing catalog cache id 32 for pg_index; 129 tups, 64 buckets
DEBUG:  rehashing catalog cache id 7 for pg_attribute; 257 tups, 128 buckets
DEBUG:  rehashing catalog cache id 32 for pg_index; 257 tups, 128 buckets
DEBUG:  rehashing catalog cache id 7 for pg_attribute; 513 tups, 256 buckets
DEBUG:  rehashing catalog cache id 32 for pg_index; 513 tups, 256 buckets
DEBUG:  rehashing catalog cache id 7 for pg_attribute; 1025 tups, 512 buckets
DEBUG:  rehashing catalog cache id 32 for pg_index; 1025 tups, 512 buckets
DEBUG:  rehashing catalog cache id 7 for pg_attribute; 2049 tups, 1024 buckets
DEBUG:  rehashing catalog cache id 32 for pg_index; 2049 tups, 1024 buckets
DEBUG:  rehashing catalog cache id 59 for pg_statistic; 257 tups, 128 buckets
DEBUG:  rehashing catalog cache id 59 for pg_statistic; 513 tups, 256 buckets
DEBUG:  rehashing catalog cache id 59 for pg_statistic; 1025 tups, 512 buckets
DEBUG:  rehashing catalog cache id 51 for pg_class; 513 tups, 256 buckets
```

**Comment by xcu** [comment]
Actually....I was browsing the release notes to see what's missing from the version I'm using (0.2.7) to the current 0.4.2 and spot this:

>Fixed issue with inserts silently corrupting ivfflat indexes (introduced in 0.2.7)

Could this be the source of the degrading performance with new insertions? 🤔

**Comment by ankane** [comment]
@xcu Thanks for all the info. That's the cause. You'll want to upgrade to the latest version and [recreate](https://github.com/pgvector/pgvector#031) all `ivfflat` indexes.

Also, if you're querying across all partitions, I think you'll see better query performance without partitioning (and with partitioning, make sure `lists` is set correctly for the active partition to avoid low recall).

**Comment by xcu** [comment]
@ankane ah nice, that makes sense!
Another reason I did not mention about why partitioning is used is that I can split the query in threads (i.e, 10 threads, each taking 45 out of the 450 partitions) and that makes the overall query faster. Do you think partition size could affect the recall? Because maybe I could increase partition size to something greater if it will result in better results. Don't know, maybe something like 200K or 500K.

re. lists, I'm using 100 lists because as per the `rows/1000` suggested [formula](https://github.com/pgvector/pgvector#indexing)

**Comment by ankane** [comment]
I'm not quite sure about partition size vs recall, but would be great to hear the results if you try it.

For the active partition, you'll want to set `lists` based on the current number of rows (rather than the max rows).

Also, I'm hoping to support parallel index scans at some point (so you wouldn't need to split the query manually), but haven't had success with the query planner.

**Comment by xcu** [comment]
Sure, I might give it a try and get back to you. In the meantime, I think I'll close the ticket, as the issue is now sorted :) 
Thanks a lot for the assistance!
