### ISSUE TITLE
Similarity search leads to the same documents be returned no matter the query

### ISSUE THREAD

**Issue by PCIHD** [pgvector/pgvector#142]
I have been using the similarity search function here and somehow always get the same documents as the result.
The top k rows from the postgres table. whatever may be the question.

any ideas why this might be happening?

**Comment by ankane** [comment]
Hi @PCIHD, a few questions:

1. What version of pgvector are you on (`SELECT extversion FROM pg_extension WHERE extname = 'vector';`)?
2. What's the output of `EXPLAIN ANALYZE`?
3. Do you get the expected results without an index?
