### ISSUE TITLE
Any benchmarks available? 

### ISSUE THREAD

**Issue by spy16** [pgvector/pgvector#149]
Is there any performance benchmark available yet?

I have a use case where I am likely to have a few million vectors of 1536-d (OpenAI). 

If these are separated by another indexed column such that a particular namespace has only maybe 20000 vectors, what kind of latency can I expect? Will this secondary namespacing help as a query optimisation?

Also, I read somewhere that pgvector might do worse than other vectors stored in terms of recall. Is that true?

**Comment by KShivendu** [comment]
Try https://ann-benchmarks.com/

At least as per https://ann-benchmarks.com/fashion-mnist-784-euclidean_10_euclidean.html, yes it performs relatively poorly.

**Comment by ankane** [comment]
Hi @spy16, check out #82 and [ann-benchmarks](https://github.com/erikbern/ann-benchmarks) for benchmarks. Recall is tunable via the [ivfflat.probes](https://github.com/pgvector/pgvector#query-options) option.

In general, the IVFFlat index type has lower speed-recall operating points than HNSW (which is often used by other projects).

**Comment by jkatz** [comment]
I do think you need to TIAS (try it and see) with your own benchmarking and see if it makes sense for your use case. While ANN Benchmarks may be a directional start, it is comparing a whole slew of different search systems that are not equivalent to each other, for example: fully in-memory indexes, non-ACID compliant storage systems, and ACID databases. Additionally, some of the testing methodology does not necessarily match how you would set up a PostgreSQL database.

From my testing on data sets of different sizes, I've found that right now, performance tuning can be specific to your total dimensions, query patterns, and size of the data set. That said, this may not fully account for your full data access pattern or ease of development -- it may make sense to keep all of your data stored locally in one place (e.g. PostgreSQL).
