### ISSUE TITLE
query planner not using index

### ISSUE THREAD

**Issue by daviddanialy** [pgvector/pgvector#152]
I created a table as such:

```
CREATE TABLE post_embed_temp (id uuid NOT NULL, "embedding" vector(1536) NOT NULL,CONSTRAINT "FK_2bd78fbd6880ebf63e59b87a1b1" FOREIGN KEY ("id") REFERENCES public.post(id));

CREATE INDEX ON post_embed_temp USING ivfflat (embedding vector_cosine_ops) WITH (lists = 70);

SET ivfflat.probes = 7;

ANALYZE;

SET maintenance_work_mem = '50000MB';
```

and inserted ~70k rows, before creating the index

running this query: `SELECT * FROM post_embed_temp ORDER BY "embedding" <=> ${vector} LIMIT 5;`

gets this query plan:
```
Limit  (cost=2535.66..2535.68 rows=5 width=42) (actual time=833.352..833.355 rows=5 loops=1)
  ->  Sort  (cost=2535.66..2704.91 rows=67698 width=42) (actual time=833.349..833.351 rows=5 loops=1)
        Sort Key: ((embedding <=> vector))
        Sort Method: top-N heapsort  Memory: 25kB
        ->  Seq Scan on post_embed_temp  (cost=0.00..1411.22 rows=67698 width=42) (actual time=0.113..808.498 rows=67698 loops=1)
Planning Time: 1.758 ms
Execution Time: 833.387 ms
```

only way i could get it to use the index was to run `SET enable_seqscan = FALSE;`, then run the query again
which resulted in:

```
Limit  (cost=27158.37..27158.60 rows=5 width=42) (actual time=73.559..73.721 rows=5 loops=1)
  ->  Index Scan using post_embed_temp_embedding_idx3 on post_embed_temp  (cost=27158.37..30264.60 rows=67698 width=42) (actual time=73.557..73.717 rows=5 loops=1)
        Order By: (embedding <=> vector)
Planning Time: 2.129 ms
Execution Time: 73.755 ms
```

**Comment by jkatz** [comment]
@daviddanialy There is an ongoing discussion / PR for helping the query planner to choose the index more often, which would cover your use case: https://github.com/pgvector/pgvector/pull/133

In the interim, I would suggest a couple of ways to help guide the query planner to perform an index scan:

* Use `STORAGE PLAIN` on your `"embedding"` column -- this will move the data out of the TOAST table, but PostgreSQL will calculate a higher cost of performing a sequential scan. You can do this with `ALTER TABLE post_embed_temp ALTER COLUMN "embedding" SET STORAGE PLAIN`, though note that you'll need to rewrite the table.
* Lower `random_page_cost` on an ad-hoc basis for where you run the queries. Lowering it to `2.0` would likely cover this case. I don't recommend lowering this globally.
* You could use the above (i.e. disabling sequential scan) but I wouldn't recommend it particularly if your table continues to grow in size.

**Comment by daviddanialy** [comment]
@jkatz thank you for the fast reply. I have tried both `STORAGE PLAIN` and lowering `random_page_cost`, and neither seemed to do the trick for me. My postgres major version is 14, so I will upgrade to 15 and see if that will fix it.

**Comment by jkatz** [comment]
@daviddanialy Looking more closely, this seems to be a small set of rows (65K) so I can see why my `random_page_cost` recommendation doesn't work there. The sequential scan would still be cheaper. Also note that you'll need to do a table rewrite for `STORAGE PLAIN` and another `ANALYZE` for the costs to reset (it may just be simpler to put the data in a new table).

With upgrading to PG15, In this case, I don't think upgrading would help -- the costs would be the same. You can continue to lower the `random_page_cost` to see if that gets it to use the index in the way you'd like it to.

**Comment by daviddanialy** [comment]
@jkatz thanks for the help again. I was able to get the query to use the index by setting `random_page_cost` to .36. I will take your advice and use transactions to set that variable each time I query.

**Comment by jkatz** [comment]
@daviddanialy I'm not sure how you're connecting to the database, but from within a session you can do something like:

```sql
...
SET random_page_cost TO 0.36;
SELECT ...
RESET random_page_cost;
...
```

From within a session, those are actually 3 separate transactions, but you would achieve the same effect as the changes to `random_page_cost` are session scoped.
