### ISSUE TITLE
Second create index hangs whole database

### ISSUE THREAD

**Issue by rngadam** [pgvector/pgvector#159]
Second create index hangs whole database

* Postgresql 15.3 (https://github.com/smashedtoatoms/asdf-postgres)
* 83K rows with vectors of size 1536
* First time 

```
create table if not exists public."text-embedding-ada-002" (
	id uuid default uuid_generate_v4 (),
	token_id uuid references public.token(id),
	embedding vector(1536),
	primary key(id),
	unique(token_id)
);
```

Index creation:

```
CREATE INDEX  t_ada002_embedding_cosine_idx 
	ON public."text-embedding-ada-002"  
	USING ivfflat (embedding vector_cosine_ops) WITH (lists = 83);
```

Running the index creation the first time worked (although actually made look up performance worse) in about 40s.

Running create index a second time with the index already present locks up database server. 

Unable to shut it down using ```pg_ctl```.

```
 $ pg_ctl stop
waiting for server to shut down............................................................... failed
pg_ctl: server does not shut down
```

No locks visible.

**Comment by rngadam** [comment]
I'm reinstalled the database and reloaded the dump and I'm unable to reproduce the same issue. Filed anyway in case I or someone else encounters the same issue.

**Comment by NikolayS** [comment]
@rngadam this seem to be a general PG question, here are some thoughts.

Index creation produces a lot of WALs. During a stop or restart attempt, a shutdown checkpoint is being created, and if checkpointer is not tuned (e.g. if `max_wal_size` is default `1GB` and disks are weak), it might take significant time – while `pg_ctl stop` has timeout (e.g., `PGCTLTIMEOUT`, which is 60s by default). To mitigate it: 
- perform checkpoint tuning, e.g. consider raising `max_wal_size` -- at least during massive ops (restart is not needed);
- before running pg_ctl stop, issue explicit `CHECKPOINT` first, to make shutdown checkpot smaller -- or jut raise `PGCTLTIMEOUT`.

**Comment by rngadam** [comment]
@NikolayS thanks for the notes. The create index hung for hours so to me it seems doubtful that it is simply the shutdown clearing out the WAL records? I haven't tuned anything, just the default asdf postgres. 

This happened when I was testing that loading the schema.sql was an idempotent operation and the last operation was the ```create index``` without a ```if not exists```.  It should have just errored out with ```ERROR:  relation "t_ada002_embedding_cosine_idx" already exists``` and I'm not sure why it didn't. I must have gotten confused as it shouldn't be possible if the index was already there as I expected.

settings: 

https://gist.github.com/rngadam/32668d9221e8c173ffce552060e862a3
