### ISSUE TITLE
question about lists/probes

### ISSUE THREAD

**Issue by alonziv** [pgvector/pgvector#161]
Thank you for this fantastic extension!  I love being able to do vector searches within postgres.

I have a question about the relationship between lists and ivfflat.probes.  Let's say I have a table with 500K rows:

Scenario A - I create an index with lists=500. Each list will have about 1K rows.  Then I query with probes=5.  My query will check 5 lists or about 5K rows.  

Scenario B - I create an index with lists=100. Each list will have about 5K rows.  Then I query with probes=1.  My query will check 1 list or about 5K rows.  

In both scenarios my query is checking about the same number of rows.  So will these two scenarios have equivalent performance/results?  Or is one better for reasons I'm not thinking of?  

Thanks!

**Comment by ankane** [comment]
Hi @alonziv, a higher number of lists will fit the data better, which can lead to higher recall at the expense of performance. Scenario A requires 5.5k distance calculations on average (5k vectors + 500 lists) while Scenario B requires 5.1k.

Running ann-benchmarks with the `sift-128-euclidean` dataset (which has 1M rows) yields:

500 lists, 5 probes: 0.816 recall, 230 queries/sec
100 lists, 1 probe: 0.580 recall, 248 queries/sec
