### ISSUE TITLE
Issue : Could not open extension control file "/usr/share/postgresql/15/extension/vector.control": No such file or directory

### ISSUE THREAD

**Issue by raorugan** [pgvector/pgvector#162]
I followed below instructions -
![image](https://github.com/pgvector/pgvector/assets/45637559/f1e16750-ad20-4094-8b1c-94abe237383d)
but when I run the docker run and execute below
psql -h localhost -p 5432 -U postgres -d postgres -f examples/providers/supabase/migrations/20230414142107_init_pg_vector.sql

Which is executing "CREATE EXTENSION vector;"  it throws below error - 
 ERROR:  extension "vector" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/vector.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running

I checked the path in the container - /usr/share/postgresql/15/extension and there is not vector.control file. How do I fix this issue?

**Comment by raorugan** [comment]
@ankane 

(https://github.com/pgvector/pgvector/commits?author=ankane)

**Comment by ankane** [comment]
Hi @raorugan, I'm not sure how to reproduce. What command are you using to run the image?

**Comment by yihong0618** [comment]
Try this command and no error
Can you make sure your psql connect the container’s Postgres 
Or you can exec into the container than use the command

**Comment by raorugan** [comment]
Sorry which command @yihong0618 ?

HEre is the command I used to run the image-

docker run -p 127.0.0.1:5432:5432/tcp --name pgvector -e POSTGRES_PASSWORD=mysecretpassword -d postgres

Am I missing something?

**Comment by raorugan** [comment]
the below command is running a postgres image and not the pgvector image

docker run -p 127.0.0.1:5432:5432/tcp --name pgvector -e POSTGRES_PASSWORD=mysecretpassword -d postgres

**Comment by ankane** [comment]
It looks like you're running the `postgres` image rather the `<my_docker_hub_id>/pgvector` image you've built (change the last part of the command).
