### ISSUE TITLE
Precision by Vector Dimension

### ISSUE THREAD

**Issue by olirice** [pgvector/pgvector#163]
We've been digging into performance to improve documentation around required instance sizes, expected queries/sec, precision, etc

I had an unexpected result when measuring precision for different vector sizes and wanted to share to see if you have any insights

Holding the following parameters constant:

| parameter | value |
|-------|---|
| # records| 10_000 |
| # index lists | 30 |
| top k | 10 |
| metric | inner product |
| dataset | random unit vectors |

I varied the dataset's dimension and `ivfflat.probes` to measure the `precision@k=10`

That resulted in:
<img width="576" alt="Screenshot 2023-06-15 at 1 40 43 PM" src="https://github.com/pgvector/pgvector/assets/12958657/93d4c82f-fc58-46c9-81a0-05d83021620e">

*note: the legend was abbreviated, tested dimensions were `[3, 5, 10, 20, 30, 40, 50, ... 1400, 1600]`

Interpreting that chart:
As the number of probes approaches number of index lists, precision approaches 100% (as expected)

Another trend is that as the vector dimension grows, the relative benefit of the index decreases. That is visible as the curves "flatten out"

Another way to think about that is the amount of the dataset that has to be scanned to achieve a given precision.

For example:

<img width="576" alt="Screenshot 2023-06-15 at 1 17 09 PM" src="https://github.com/pgvector/pgvector/assets/12958657/dcf2ec0a-1e63-4b58-b756-993e2f5efd85">

so, to achieve a minimum of 99.0% precision on vector dimensions > 150, we have to compute distances for more than 80% of the records in the dataset.

---

Questions:

- Is that roughly what you expected?

- Is the characterization of the relationships among lists, probes, and vector dimensions (shown above) roughly correct, or am I missing some info?

- Do you think recommendations in the form of
"for approximately `M%` precision on `N` dimensional vectors, set `ivfflat.probes` = `Y%` of `lists` "
would be the right way to summarize for users?

**Comment by jkatz** [comment]
@olirice This seems to be a pretty small data set, i.e. 10,000 rows, along with it being divided up over 30 lists. This is probably skewing the clusters a bit, so it's less likely you're going to find commonality without visiting multiple lists. At the size of this data set, even with higher dimensionality, I would suspect doing a sequential scan (not using the index) is likely the way to go if you're most interested in precision.

I'd be more curious on the results across larger data sets, even at 100,000 rows. At that point you're going to need to rely on the index more for performance, and I think it'll give a better sense of what it will take to get precise results.

**Comment by olirice** [comment]
> 10,000 rows, along with it being divided up over 30 lists. This is probably skewing the clusters a bit

@jkatz I didn't understand what you mean wrt cluster skew

k-means should result in an equal number of entries in each list and each vector/point will always be assigned to its nearest centroid immediately following training. Once we're at a statistically significant number of records I'd expect the precision results to be invariant to both parameters (if probes is taken as a % of lists). 

Could you pls explain how the skew occurs & if increasing the dataset size fully resolves it (I increased it in the chart below to be safe)?

**Comment by olirice** [comment]
(from a separate thread)
>2. It'd be good to run the benchmarking framework with the IVFFlat index type from Faiss to confirm

I re-ran the analysis using faiss and increased dataset size and precision samples to 100k and 10k respectively.

<img width="590" alt="Screenshot 2023-06-20 at 10 07 33 AM" src="https://github.com/pgvector/pgvector/assets/12958657/4c0a2cbd-a9a5-4419-9e86-48e2eae0c95a">

which shows the same result, so looks like that's correct

It's interesting that the number of required probes for a given level of precision starts to decrease after an inflection point between 256 and 512 dimensions in both implementations. Not sure what that's about

**Comment by olirice** [comment]
Here's the code to reproduce that output if anyone's interested

```python
import numpy as np
import faiss
import seaborn as sns
import pandas as pd

# seed RNG for reproducible result
np.random.seed(1234)

nlist = 30

# number of results to return from each query
k = 10

# dataset size
nb = 100000

# number of queries used to calculate mean precision
nq = 10000

precision = []

# Number of dimensions
dimensions = [5, 10, 32, 64, 128, 256, 512, 1024, 1536]

for d in dimensions:
    
    # Vector Dataset
    xb = np.random.random((nb, d)).astype('float32') 
    xb = xb / np.linalg.norm(xb, axis=1)[:, np.newaxis]
    
    # Query Dataset
    xq = np.random.random((nq, d)).astype('float32')
    xq = xq / np.linalg.norm(xq, axis=1)[:, np.newaxis]
    
    # Define the index
    quantizer = faiss.IndexFlatL2(d)  # the other index
    index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)

    # Train the index
    assert not index.is_trained
    index.train(xb)
    assert index.is_trained

    # Load dataset into the index
    index.add(xb)
        
    # Collect the accurate results by setting nprobes == nlists
    index.nprobe = nlist

    # The accurate results for each query vector
    _, correct_results = index.search(xq, k=10)
    
    # For each number of probesm calculate precision@k
    for nprobes in range(1,30):
        index.nprobe = nprobes

        # Results for the given number of nprobes
        _, q_results = index.search(xq, k=k)

        # Compare each row of the correct results with the query results 
        agg = []
        for correct_row, q_row in zip(correct_results, q_results):
            correct_row = set(correct_row)
            q_row = set(q_row)
        
            row_precision = float(len(q_row.intersection(correct_row))) / k
            agg.append(row_precision)

        # Add result to the output (dimensions, nprobes, precision)
        rec = (d, nprobes, sum(agg) / len(agg))
        print(rec)
        precision.append(rec)

# Load dataset into a dataframe for plotting
df = pd.DataFrame(precision, columns=['vector_dim', 'probes', 'precision'])

# Plot the results
sns.lineplot(
    data=df,
    x='probes',
    y='precision',
    hue='vector_dim'
).set(title='precision@k=10 by probes')
```

**Comment by olirice** [comment]
closing as questions were resolved

**Comment by olirice** [comment]
> It's interesting that the number of required probes for a given level of precision starts to decrease after an inflection point between 256 and 512 dimensions in both implementations. Not sure what that's about

We continued investigating this and it turns out to be an expected phenomenon.

As you increase the dimensionality of vectors, the space they occupy becomes more sparse. In the high-dimensional space, data points (vectors) tend to spread out more uniformly and, therefore, become more distinguishable from each other. a.k.a. "curse of dimensionality".

The initial increase in probes required to maintain a certain precision level is due to the increased sparsity of the high-dimensional space. More probes (i.e., more lists to check) are necessary to explore this space efficiently and find the nearest neighbors.

However, once you reach a certain point, the vectors start to occupy the high-dimensional space more uniformly. The distance between vectors becomes more evenly distributed, and therefore the nearest neighbors of a vector are more likely to be in its own cluster. At that point, you see the number of necessary probes start to decrease, since a high number of clusters will likely already include the nearest neighbors of a query vector.

The trend continues in 1k, 2k, 3k, 4k dimensional vectors, as shown below

<img width="576" alt="Screenshot 2023-06-21 at 11 57 54 AM" src="https://github.com/pgvector/pgvector/assets/12958657/fbb04c6a-346a-471c-adaf-7d39639f869c">

**Comment by olirice** [comment]
> It's interesting that the number of required probes for a given level of precision starts to decrease after an inflection point between 256 and 512 dimensions in both implementations. Not sure what that's about

This effect was due normalizing vectors produced by `np.random.random` rather than `np.random.normal`. It has been corrected in the code snippet above and now as the vector dimension increases the value of the index consistently reduces

other conclusions remain unchanged

<img width="592" alt="Screenshot 2023-06-22 at 12 07 22 PM" src="https://github.com/pgvector/pgvector/assets/12958657/7d4df21e-a2df-4e3b-82f8-a8e5f9ef9b52">

thanks @akorotkov for pointing out this error
