### ISSUE TITLE
AWS RDS maintenance_work_mem limitation

### ISSUE THREAD

**Issue by ajdaling** [pgvector/pgvector#164]
Hi there, I am relatively new to RDS Postgresql so I apologize in advance for my ignorance. Any help or advice is appreciated.

I was very excited when pgvector came to AWS RDS and I have had great success using pgvector for vector search using embeddings of various dimensionalities, most recently running version 15.3. However, I recently encountered an issue when trying to create a cos_sim index on a table with vectors of length 1660 and I was curious if there were any known workarounds for this issue.

When I try to create a vector index
`CREATE INDEX ON {table_name} USING ivfflat (portfolio_vector vector_cosine_ops) WITH (lists = {n_lists});`
I get the following error
`memory required is 562 MB, maintenance_work_mem is 516 MB`

From what I can tell, the configuration for maintenance_work_mem is not configurable on AWS RDS, so I was curious if there was another way of getting around this issue. 

I have tried various values for n_lists but it doesn't seem to make a difference and I don't know enough to understand what else I can try. 

Thanks in advance for any help.

**Comment by ankane** [comment]
Hi @ajdaling, you can set it in [parameter groups](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html) or directly in the database session you're using to create the index.

```sql
SET maintenance_work_mem = '1GB';
```

**Comment by jkatz** [comment]
@ajdaling You can also set `maintenance_work_mem` on a one-off basis if you only need to set it temporarily e.g.:

```sql
SET mainetnance_work_mem TO '768MB';
CREATE INDEX ON {table_name} USING ivfflat (portfolio_vector vector_cosine_ops) WITH (lists = {n_lists});
RESET mainetnance_work_mem;
```

**Comment by ajdaling** [comment]
Wow, I am embarrassed. I thought it could only be changed in the config file. 
Thank you for your help, that did it. 
PS I love this extension, keep up the awesome work.
