### ISSUE TITLE
Manhattan distance

### ISSUE THREAD

**Issue by patleb** [pgvector/pgvector#166]
I was wondering if the Manhattan distance could be added to this extension? I'm asking because if any maintainer think it's easy to add and is willing to do it, then I won't bother looking at how to add this myself (since the Euclidean distance is already implemented, I'm guessing that it might be almost trivial to add).

Also, FYI, with 10 or more dimensions, L1 is more suited than L2... the more dimensions you add, the less differences there is in relative distances when using L2. After some radius, the points tend to have a similar distance with increasing dimensions.

**Comment by patleb** [comment]
As a side note, L1 is not always better than L2, even though I have stated such thing earlier: it's highly dependent on your data distribution as the last paper showed, but it's useful to have the choice.

**Comment by ankane** [comment]
Hi @patleb, thanks for the suggestion. I've added the function (without an operator or index operator class) in the [l1_distance branch](https://github.com/pgvector/pgvector/compare/l1_distance), but it doesn't seem as widely used in the vector similarity search space as the other distance functions, so want to hold off on including it for now (added to #27).

**Comment by patleb** [comment]
Thanks, that was fast. It gives me a good starting point to add this myself in the future, so the l1_distance branch is appreciated. I don't know about everyone's vector similarity search use cases, but I definitely build better models with L1 on most of my datasets compared to L2.

I was a bit surprised to see that L1 wasn't in this extension and to be the first to ask, so I guess that it might suggests that it's not that commonly used after all or that my datasets are somewhat unusual or that most people don't bother comparing between both... I don't know. Anyway, thanks again.

**Comment by ankane** [comment]
@jamie0725 The L2 squared distance function (`vector_l2_squared_distance`) is currently considered private, so you'd need to do something like:

```sql
SELECT *, pow(embedding <-> '[0.1,0.2,0.3]', 2) AS score FROM embeddings
    ORDER BY embedding <-> '[0.1,0.2,0.3]' LIMIT 10; -- don't use score or index won't be used
```

(also, please create a new issue for additional follow-up or questions)

**Comment by ankane** [comment]
Just fyi, the `l1_distance` function will be included in 0.5.0 (merged in the commit above).

**Comment by ankane** [comment]
Thanks for the suggestion!

**Comment by patleb** [comment]
No problem, thanks!

**Comment by patleb** [comment]
Otherwise, I was wondering if you plan to fully support L1 norm like in `pg_embedding` [here](https://github.com/neondatabase/pg_embedding/pull/16/files)?

**Comment by ankane** [comment]
I only plan to add the function right now, but you could use it to create an operator and operator class in your own databases (enabling indexing).

```sql
CREATE OPERATOR <|> (
    LEFTARG = vector, RIGHTARG = vector, PROCEDURE = l1_distance,
    COMMUTATOR = '<|>'
);

CREATE OPERATOR CLASS vector_l1_ops
    FOR TYPE vector USING ivfflat AS
    OPERATOR 1 <|> (vector, vector) FOR ORDER BY float_ops,
    FUNCTION 1 l1_distance(vector, vector),
    FUNCTION 3 l1_distance(vector, vector);
```

and

```sql
CREATE INDEX ON items USING ivfflat (embedding vector_l1_ops) WITH (lists = 100);
```

**Comment by patleb** [comment]
Got it. Thx!
