### ISSUE TITLE
Apply Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [pgvector/pgvector#168]
Hi!

Recently I finished my tests about using PGO with Postgres: [link](https://github.com/zamazan4ik/awesome-pgo/blob/main/postrgresql_results.md) Maybe, `pgvector` performance also can be improved by PGO. By the way, enabling LTO also could help.

More articles about applying PGO on different projects are [here](https://github.com/ZaMaZaN4iK/awesome-pgo).

**Comment by ankane** [comment]
Hi @zamazan4ik, thanks for the suggestion. If anyone decides to try it with pgvector, please share.

**Comment by zamazan4ik** [comment]
@ankane I am not sure why did you close the issue? :) Since we have no PGO results yet, I think the issue should remain open. And maybe someone would be interested in testing it, will find the issue and perform the tests.
