### ISSUE TITLE
Rebuild index

### ISSUE THREAD

**Issue by dreamflasher** [pgvector/pgvector#17]
In the documentation you write that the index should be built after a bunch of vectors have been added.
I have an application where there are regularly new vectors being added, do I assume correctly that I need to rebuild the index regularly then?
What would be a good frequency? 

(And as a side question: This library is perfoming exact search, correct?)

**Comment by nikhilweee** [comment]
@ankane Just wanted to confirm if new vectors will be instantly searchable in the index as soon as they are updated (added / removed / edited) in the corresponding table? If I understand correctly, it's just that the centroids corresponding to the clusters in the index won't be updated, and that's the main reason why one should periodically rebuild the index?
