### ISSUE TITLE
开发文档

### ISSUE THREAD

**Issue by gulang2** [pgvector/pgvector#170]
您好， 我是刚学习PG向量数据库的开发者，之前使用的语言是java，现在在部署项目的环节遇到困难，总是部署不起来，请问能否提供一些项目部署的开发文档以及一些资料让我进行学习，我非常希望能参与建设这个项目，谢谢！

**Comment by ankane** [comment]
Hi @gulang2, all of the documentation is in the readme, for both deployment (set up Postgres and follow the [installation instructions](https://github.com/pgvector/pgvector#installation)) and [contributing](https://github.com/pgvector/pgvector#contributing).
