### ISSUE TITLE
ankane/pgvector container image tagging

### ISSUE THREAD

**Issue by acim** [pgvector/pgvector#171]
It would be nice to tag your images with additional information about the postgres version which was the base image, something like v0.4.4-pg15.3 or 0.4.4-15.3-bullseye and it would be also nice if you can build Alpine based images although I am not sure if your code compiles with musl. If not, then it's probably not worth since the image would grow a lot. Thank you.

**Comment by ankane** [comment]
Hi @acim, thanks for the suggestion. There's only one image for each release right now, so don't think additional tagging is needed, but will figure out a convention if that changes.

**Comment by bo0tzz** [comment]
@ankane do you have any interest in building multiple images per release (for example with different postgres versions), or are you intending to stick with the current approach?
