### ISSUE TITLE
项目部署

### ISSUE THREAD

**Issue by gulang2** [pgvector/pgvector#173]
您好，我现在部署项目过程中遇到一个问题，总是找不到数据库的头文件，希望得到指导，具体信息我通过截图表明，谢谢。
![image](https://github.com/pgvector/pgvector/assets/64044697/3c9dfb4a-92db-484d-98ad-510a7e9ded01)
![image](https://github.com/pgvector/pgvector/assets/64044697/027ce928-5913-48db-885b-04a0fdf9369c)
引用的文件路径我也尝试过修改，结果发现不行，详情请看图：
![image](https://github.com/pgvector/pgvector/assets/64044697/3c31436e-29c2-4fa3-9c76-8c65428c27f8)
![image](https://github.com/pgvector/pgvector/assets/64044697/c63cc341-c4e7-4d70-add0-6723aae444ad)
目前我找不到其他方法，希望可以得到指导，感谢！，系统环境：window，开发工具：vsCode

**Comment by ankane** [comment]
Hi @gulang2, you'll need to use `nmake` for Windows ([docs](https://github.com/pgvector/pgvector#windows)). You could also try another installation method like Docker.
