### ISSUE TITLE
Patchset to speed-up ivfflat build

### ISSUE THREAD

**Issue by pashkinelfe** [pgvector/pgvector#175]
When looking at the low-level ivfflat build, I saw that two things take a significant share of time:
1. Calculation of dot product
2. Caclulation of arccos value.

I did some experiments and found that I could speed up these things with a marginal precision decrease (considering that overall ivfflat is approximate and the share of exact answers in select query is significantly < 100% at any reasonable ratio of probes/lists).

The code is as follows:
https://github.com/pashkinelfe/pgvector/tree/index-build-speed-optimizations

There are two patches
1. Use float instead of double at dot product calculation. It has the most pronounced effect as dot product calculation contains floating point multiplication of all vector dimensions. Intentionally I left double the overall distance function and the calculations that are done once per vector pair (not at every dimension) as they will increase speed only marginally (and also for compatibility). The low-level reason for this speed-up is that it makes CPU (armv8) using vector multiply-add instruction (fmadd) instead of vector multiplication + conversion to double + addition (fmul + fcvt + fadd) at each vector dimension. This change can also speed up the select's speed due to faster lists traversal that includes dot product calculation to the pairs of (sample vector - index vector).

2. Caclulate arccos value for spherical big circle distance as a quadratic Lagrange approximation plus sign extension. The effect of this is less pronounced so it could decided to be merged separately.

Overall performance measurements are done at original state (arccos + double dot product), first patch (arccos + float), second (Lagrange approximation + double) and both (Lagrange approximation + float). The dataset is a real 900K sized set of OpenAI vectors (https://huggingface.co/datasets/KShivendu/dbpedia-entities-openai-1M), but the same results are also for random 900K set. Number of lists are chosen at recommended value (900) and 3 time recommended and 1/3 times recommended. The most pronounced effect (55% index build time decrease) is when the number of lists is more than recommended, which has a good reason to be build to increase select speed at cost of index build time. But for recommended value the effect is also very pronounced i.e. 30% index build time decrease with both patches.

Absolute index build times:
<img width="726" alt="image" src="https://github.com/pgvector/pgvector/assets/63344111/e3fdee2a-f98d-4957-9efc-b555a9cf9f63">

Relative index build times as a ratio to original unpatched code:
<img width="710" alt="image" src="https://github.com/pgvector/pgvector/assets/63344111/e585b53c-0e8e-4c04-a8d2-a4c09d234c10">

Regarding index quality I consider that these small changes in distance calculations will not be so pronounced to be seen on precision vs probes/lists plot as in https://github.com/pgvector/pgvector/issues/163#issuecomment-1603041726  Furthermore, this plot is based on FAISS ivfflat optimization, not actual pgvector code, so this could not be easily adapted to measure the same plot with proposed patches applied. While it's possible to adapt the test script to pgvector (using psycopg interface) I can't make this  quick enough. (If anyone could adapt script https://github.com/pgvector/pgvector/issues/163#issuecomment-1598992203  to using table and index from local pg database, I'll readily run this test on my dataset, that I've quoted above). Overall I don't consider to see any changes on precision vs probes/lists plot because it's too rough for these subtle changes in the patches. If anyone has better proposals to check index quality, you're very much welcome!

I tried to make this a PR, not an issue but found that I don't have enough permissions to propose a patch as a branch of this repo.

**Comment by ankane** [comment]
Hi @pashkinelfe, thanks for sharing.

It'd be good to test each of the changes separately with [ann-benchmarks](https://github.com/erikbern/ann-benchmarks), as improvements to Faiss won't necessarily translate to pgvector (it looks like the `KShivendu/dbpedia-entities-openai-1M` dataset was [just added](https://github.com/erikbern/ann-benchmarks/pull/434)).

Also, everyone should have permission to submit PRs.

**Comment by pashkinelfe** [comment]
Hi, @ankane! I see that I can open PR only from the selected list of repositories, which doesn't include [pashkinelfe/pgvector](https://github.com/pashkinelfe/pgvector) into which I can push a branch.

**Comment by ankane** [comment]
Not sure what page you're looking at, but nothing on this end should be preventing it ([relevant docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork))

**Comment by pashkinelfe** [comment]
Maybe this is the clue: (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
"Anyone with write access to a repository can create a pull request from a user-owned fork."
![image](https://github.com/pgvector/pgvector/assets/63344111/5afeaffe-ae93-4a17-b088-d47ffcd45a11)

**Comment by pashkinelfe** [comment]
That's exactly what I unsuccessfully tried to do. But as per manual I still need write access to pgvector/pgvector to create PR **"Anyone with write access to a repository can create a pull request from a user-owned fork."**

**Comment by ankane** [comment]
This hasn't been an issue with other contributions, but we can use issues instead of PRs to discuss if needed. Feel free to create new ones once benchmarks are in.
