### ISSUE TITLE
Querying embeddings + metadata

### ISSUE THREAD

**Issue by CJohnDesign** [pgvector/pgvector#177]
## Context
Building an internal support agent for our development agency
Query: "Summarize retro for sprint L2023W06" 
Most similar searches some come back was L2023W07 and L2023W01

I don't want to include all metadata into the embedding. 

## Questions
How can I include semantic search of the vectors + fuzzy search of the metadata?
Can I vectorize the metadata in addition to the chunks? 

## Options
I found this but asking here if this is the right approach?
https://github.com/pgvector/pgvector#hybrid-search

**Comment by ankane** [comment]
Hi @CJohnDesign, on a technical level, you can use pgvector for semantic search and other Postgres functionality for metadata search, but you'll probably want to seek out other resources for the best way to combine them for your specific application.
