### ISSUE TITLE
PostgreSQL15 pgvector Installation Error

### ISSUE THREAD

**Issue by SuMyatHlaing30** [pgvector/pgvector#179]
Could you help me please. When I install pg vector in my window environment (PostgreSQL 15), I get the following error
"error LNK2019: unresolved external symbol _pgwin32_dispatch_queued_signals referenced in function _InsertTuples"

<img width="745" alt="image" src="https://github.com/pgvector/pgvector/assets/123180196/dc97389b-b2bf-4858-99c6-841935ebf264">

**Comment by ankane** [comment]
Hi @SuMyatHlaing30, I'd recommend using another installation method (like Docker) if you're having trouble compiling on Windows.
