### ISSUE TITLE
Loss of data accuracy after inserting data!

### ISSUE THREAD

**Issue by Haoshuaij** [pgvector/pgvector#182]
## Loss of data accuracy after inserting data!

**Perform the operation of inserting data**

```
CREATE TABLE t_items (embedding vector(2));

INSERT INTO t_items (embedding) VALUES ('[-0.00644659623503685, -0.007357412949204445]');
```

**Execute query operation**
```
select * from t_items;
```

**Output Results**
```
[-0.0064465962,-0.007357413]

Why not [-0.00644659623503685, -0.007357412949204445] ?
```

**My Question:**

Why is there a situation where the data and results you want to save are inconsistent ? 

What I want is accurate data, not modified results. How should I operate? Currently, I suspect that the extension should use float4. How can I use float8? In addition, the leader requires the use of pgvector as a program extension. 

**Thank you.**

**Comment by ankane** [comment]
One more thing to note: you can store the values as `numeric[]` and query / index them as vectors.

```sql
CREATE TABLE items (id bigserial PRIMARY KEY, embedding numeric[]);
INSERT INTO items (embedding) VALUES ('{1,2,3}'), ('{4,5,6}');

-- create expression index (set lists to correct value for real data)
CREATE INDEX ON items USING ivfflat (CAST(embedding AS vector(3)) vector_l2_ops) WITH (lists = 1);

-- for demo to use index
SET enable_seqscan = off;

-- query
EXPLAIN ANALYZE SELECT * FROM items ORDER BY embedding::vector(3) <-> '[3,1,2]' LIMIT 5;
```
