### ISSUE TITLE
Question: Size on a vector column type

### ISSUE THREAD

**Issue by LorneCurrie** [pgvector/pgvector#183]
Hi there.

We are currently using a table that contains a Vector, set to 1536.  We need to now store a vector that is 700.  Is it possible to use the existing column that we have or do we need to create a new column for the smaller vector?

**Comment by vamen** [comment]
@ankane  why cant we do conditional indexing ? using model id for condition ?

**Comment by jkatz** [comment]
@vamen You can do conditional indexing, but if you're trying to use the `vector` column as the condition, you'd need to partition for that to work.
