### ISSUE TITLE
pgvector limited to 65k elements

### ISSUE THREAD

**Issue by davecramer** [pgvector/pgvector#184]
Is this intentional ?
https://github.com/pgvector/pgvector/blob/b56971febeec389a011de7bb40b3349e24757aff/src/vector.c#L354

**Comment by jkatz** [comment]
@davecramer Currently the limit is smaller than that:

https://github.com/pgvector/pgvector/blob/b56971febeec389a011de7bb40b3349e24757aff/src/vector.h#L10

It seems reasonable to limit the dimensionality to 65Kish for the time being, as real world data sets don't get much larger than that for a variety of reasons. That said, perhaps there could be a compile time option to allow expanding/contracting the dimensionality data type as needed.

**Comment by davecramer** [comment]
> @davecramer Currently the limit is smaller than that:
> 
> https://github.com/pgvector/pgvector/blob/b56971febeec389a011de7bb40b3349e24757aff/src/vector.h#L10
> 
> It seems reasonable to limit the dimensionality to 65Kish for the time being, as real world data sets don't get much larger than that for a variety of reasons. That said, perhaps there could be a compile time option to allow expanding/contracting the dimensionality data type as needed.

I would have thought we would need much larger vectors?

**Comment by danielchalef** [comment]
> I would have thought we would need much larger vectors?

What use cases are you considering that would require supporting vectors with dimensionality > 16K?

**Comment by davecramer** [comment]
I was confused. back on track now, thanks

**Comment by jkatz** [comment]
I did learn of some models that folks are trying to store data in PostgreSQL that are returning > 30K dimensions. We could bump up the `VECTOR_MAX_DIM` value to accommodate it, but note that this would be primarily for storage as indexing is still capped (for now) at 2K dimensions.
