### ISSUE TITLE
Question: why doesn't this query use parallel scan?

### ISSUE THREAD

**Issue by david-gang** [pgvector/pgvector#186]
I have a table called vectors with 90k rows

The command

```
explain analyze select id from vectors order by embedding <=> '[516 dimensional vector]' limit 100;
```

gives the plan

```
Sort  (cost=5333.72..5555.71 rows=88797 width=24) (actual time=301.223..301.227 rows=100 loops=1)
         Sort Key: ((embedding <=> [516 dimensional vector]
..skipping 1 line
         Sort Method: top-N heapsort  Memory: 38kB
         ->  Seq Scan on vectors  (cost=0.00..1939.96 rows=88797 width=24) (actual time=0.351..292.639 rows=88797 loops=1)
 Planning Time: 0.416 ms
 Execution Time: 301.333 ms
```

I don't understand why it doesn't do a parallel scan. I tried this in gcp cloud sql and on the local docker machine as well. 

I checked the workers settings:

max_parallel_workers_per_gather = 4
max_parallel_workers=8

How can i debug this issue further?

Building an index does not help as the table will grow eventually so i made an index with 100 lists  (for 100k rows) and if i use more than 5 probes postgresql does not use the index anymore and i fear that my recall will suffer.

**Comment by jkatz** [comment]
@david-gang This likely due to the `STORAGE` setting for the column. By default, the `vector` type will use `EXTENDED` storage, which will attempt to TOAST the value that's over the "TOAST" threshold, which by default is 2KB. When PostgreSQL is generating query paths, this will cause the planner to think it only has to scan a smaller set of pages to calculate the results because it does not consider TOAST pages and thus does not need a parallel scan.

For example, I created a similar dataset -- in `vecplain` I stored it using the `PLAIN` storage type (inline, no compression) vs. `EXTENDED` (out-of-line, compressed). This is the total number of tables in each table:

```
   relname   | relpages 
-------------+----------
 vecplain    |    30000
 vecextended |      574
(2 rows)
```

For the table using PLAIN storage, PostgreSQL executed this plan with parallel workers:

```
Limit  (cost=32902.00..32913.66 rows=100 width=12) (actual time=37.454..38.765 rows=100 loops=1)
   ->  Gather Merge  (cost=32902.00..41652.61 rows=75000 width=12) (actual time=37.453..38.739 rows
=100 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Sort  (cost=31901.97..31995.72 rows=37500 width=12) (actual time=34.451..34.459 rows=7
9 loops=3)
               Sort Key: ((embedding <=> '<vector>'::vector))
               Sort Method: top-N heapsort  Memory: 32kB
               Worker 0:  Sort Method: top-N heapsort  Memory: 33kB
               Worker 1:  Sort Method: top-N heapsort  Memory: 33kB
               ->  Parallel Seq Scan on vecplain  (cost=0.00..30468.75 rows=37500 width=12) (actual
 time=0.007..30.820 rows=30000 loops=3)
 Planning Time: 0.069 ms
 Execution Time: 38.802 ms
```

whereas for extended storage, it executed a serial plan:

```
Limit  (cost=5138.74..5138.99 rows=100 width=12) (actual time=378.954..378.972 rows=100 loops=1)
->  Sort  (cost=5138.74..5363.74 rows=90000 width=12) (actual time=378.952..378.962 rows=100 loo
ps=1)
      Sort Key: ((embedding <=> '<vector>'::vector))
      Sort Method: top-N heapsort  Memory: 32kB
      ->  Seq Scan on vecextended  (cost=0.00..1699.00 rows=90000 width=12) (actual time=0.022..
363.760 rows=90000 loops=1)
Planning Time: 0.084 ms
Execution Time: 379.003 ms
```

I've [raised this on -hackers](https://www.postgresql.org/message-id/flat/ad8a178f-bbe7-d89d-b407-2f0fede93144%40postgresql.org) in the context of parallel index builds, but it's a similar issue.

If you want to use PLAIN storage on your table, you can run:

```sql
ALTER TABLE vectors ALTER COLUMN embedding SET STORAGE PLAIN;
```

If you have existing data in the table, you'll need to do a rewrite (e.g. `VACUUM FULL`).

**Comment by ankane** [comment]
You can also encourage the planner to use it with:

```sql
BEGIN;
SET LOCAL min_parallel_table_scan_size = 1;
SET LOCAL parallel_setup_cost = 1;
SELECT id FROM vector ORDER BY ...;
COMMIT;
```

(but pgvector itself doesn't have any control over the number of parallel workers for table scans)

Not using an index with more than 5 probes is likely due to #133 and can be fixed by upgrading to the latest version (if possible) or:

```sql
BEGIN;
SET LOCAL enable_seqscan = off;
SELECT id FROM vector ORDER BY ...;
COMMIT;
```

**Comment by david-gang** [comment]
> @david-gang This likely due to the `STORAGE` setting for the column. By default, the `vector` type will use `EXTENDED` storage, which will attempt to TOAST the value that's over the "TOAST" threshold, which by default is 2KB. When PostgreSQL is generating query paths, this will cause the planner to think it only has to scan a smaller set of pages to calculate the results because it does not consider TOAST pages and thus does not need a parallel scan.
> 
> For example, I created a similar dataset -- in `vecplain` I stored it using the `PLAIN` storage type (inline, no compression) vs. `EXTENDED` (out-of-line, compressed). This is the total number of tables in each table:
> 
> ```
>    relname   | relpages 
> -------------+----------
>  vecplain    |    30000
>  vecextended |      574
> (2 rows)
> ```
> 
> For the table using PLAIN storage, PostgreSQL executed this plan with parallel workers:
> 
> ```
> Limit  (cost=32902.00..32913.66 rows=100 width=12) (actual time=37.454..38.765 rows=100 loops=1)
>    ->  Gather Merge  (cost=32902.00..41652.61 rows=75000 width=12) (actual time=37.453..38.739 rows
> =100 loops=1)
>          Workers Planned: 2
>          Workers Launched: 2
>          ->  Sort  (cost=31901.97..31995.72 rows=37500 width=12) (actual time=34.451..34.459 rows=7
> 9 loops=3)
>                Sort Key: ((embedding <=> '<vector>'::vector))
>                Sort Method: top-N heapsort  Memory: 32kB
>                Worker 0:  Sort Method: top-N heapsort  Memory: 33kB
>                Worker 1:  Sort Method: top-N heapsort  Memory: 33kB
>                ->  Parallel Seq Scan on vecplain  (cost=0.00..30468.75 rows=37500 width=12) (actual
>  time=0.007..30.820 rows=30000 loops=3)
>  Planning Time: 0.069 ms
>  Execution Time: 38.802 ms
> ```
> 
> whereas for extended storage, it executed a serial plan:
> 
> ```
> Limit  (cost=5138.74..5138.99 rows=100 width=12) (actual time=378.954..378.972 rows=100 loops=1)
> ->  Sort  (cost=5138.74..5363.74 rows=90000 width=12) (actual time=378.952..378.962 rows=100 loo
> ps=1)
>       Sort Key: ((embedding <=> '<vector>'::vector))
>       Sort Method: top-N heapsort  Memory: 32kB
>       ->  Seq Scan on vecextended  (cost=0.00..1699.00 rows=90000 width=12) (actual time=0.022..
> 363.760 rows=90000 loops=1)
> Planning Time: 0.084 ms
> Execution Time: 379.003 ms
> ```
> 
> I've [raised this on -hackers](https://www.postgresql.org/message-id/flat/ad8a178f-bbe7-d89d-b407-2f0fede93144%40postgresql.org) in the context of parallel index builds, but it's a similar issue.
> 
> If you want to use PLAIN storage on your table, you can run:
> 
> ```sql
> ALTER TABLE vectors ALTER COLUMN embedding SET STORAGE PLAIN;
> ```
> 
> If you have existing data in the table, you'll need to do a rewrite (e.g. `VACUUM FULL`).

PLAIN storage, is a great idea. It improves the runtime in my case by 75%. Currently the table row is small so i don't care too much . it is essentially id, embedding and model name, and i always go to involve embedding in the query so it even makes sense to store this inside the table.  I have to think which use cases could be problematic here

**Comment by david-gang** [comment]
Thanks @jkatz and @ankane for your help.

 In the meantime i will stay with the sequential scan and change the column to STORAGE PLAIN because an index with 100 lists and 10 probes misses very good results in our use case.  

I think it would be helpful to add a troubleshooting section with the information of this issue:
* Why is the index not used - Upgrade to > 0.4.3
* Why is the scan not parallel - optimizer does not consider out of line storage for the decision if to run something in parallel or sequential.
*

**Comment by ankane** [comment]
Thanks @david-gang, added in the commit above.
