### ISSUE TITLE
prevent creating duplicate index on same column with same distance

### ISSUE THREAD

**Issue by david-gang** [pgvector/pgvector#188]
Running twice 

> CREATE INDEX ON vectors USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

creates two indices 

    "vectors_embedding_idx" ivfflat (embedding vector_cosine_ops) WITH (lists='100')
    "vectors_embedding_idx1" ivfflat (embedding vector_cosine_ops) WITH (lists='100')

the second command should by my view return an exception

**Comment by jkatz** [comment]
This is a feature in PostgreSQL. If you'd like to see different behavior, you can raise it upstream, but this has historical precedent and would need specific reasons for changing.

You can instead create an index with a specific name, in which case if there's a duplicate with the same name, PostgreSQL will throw an exception.

**Comment by david-gang** [comment]
Thanks for the explanation.  So not relevant here.
