### ISSUE TITLE
Support for postgres@15 homebrew formula

### ISSUE THREAD

**Issue by youngbobby** [pgvector/pgvector#195]
Homebrew setup currently works only for the postgres@14 formula. Just wondering when support for postgres@15 will happen. Having a hard time deciding whether to downgrade to Postgres 14.

**Comment by ankane** [comment]
Hi @youngbobby, I looked into this when adding the formula, but it requires changes to the `postgresql@14` and `postgresql@15` formulas and other extensions (but someone is welcome to try it). More info: https://github.com/Homebrew/homebrew-core/pull/125481#discussion_r1134542118

**Comment by ankane** [comment]
Just fyi: it's now added to the `postgresql@16` and `postgresql@15` formulas (https://github.com/Homebrew/homebrew-core/pull/159683 and https://github.com/Homebrew/homebrew-core/pull/159695).

**Comment by nwalters512** [comment]
@ankane it looks like those changes were reverted: https://github.com/Homebrew/homebrew-core/pull/159723. There, you say that "earlier versions would need something similar to https://github.com/Homebrew/homebrew-core/pull/159557 to work". It looks like that referenced PR landed! Is there a path forward for supporting `pgvector` on `postgresql@15`/`@postgresql@16`?

**Comment by obie** [comment]
Anyone know if there's progress on this?

**Comment by ankane** [comment]
It looks like there's active work in https://github.com/Homebrew/homebrew-core/pull/181862.

**Comment by janhartman** [comment]
@ankane Do you have any idea if pgvector support for `postgresql@16` will land again? I saw it's only enabled for 14/17.

**Comment by ankane** [comment]
See https://github.com/orgs/Homebrew/discussions/5795
