### ISSUE TITLE
Just wanted to say Thank you!

### ISSUE THREAD

**Issue by ashpreetbedi** [pgvector/pgvector#198]
Just wanted to say thank you to this team! 

I'm rooting for pgvector and love using it so far. If there's any way I can help, please let me know.

Will close this "issue" as its not an actual issue but have no other way of expressing my gratitude :)

**Comment by neilt** [comment]
I agree. Thank you.  I was actually looking to use another database when I found this.

**Comment by ankane** [comment]
Thanks for the message!
