### ISSUE TITLE
pgAdmin 4 fails to render SQL for index method ivfflat

### ISSUE THREAD

**Issue by neilt** [pgvector/pgvector#199]
I have filed a bug report for this issue with pgAdmin 4 at https://github.com/pgadmin-org/pgadmin4/issues/6630.

I don't know if there is anything you can do to help, but wanted to let you know.

Thanks for a great product.

**Comment by ankane** [comment]
Hi @neilt, thanks for sharing. I think it'll need to be addressed in pgAdmin.
