### ISSUE TITLE
Approximate Index Cluster Access

### ISSUE THREAD

**Issue by ataudt** [pgvector/pgvector#206]
Hi, thanks for the amazing Postgres extension! I have just started using it and was wondering if there is a way to access the underlying centroids and vector assignments from the approximate index? I wanted to do a k-means with the stored vectors, but it seems that I get this "for free" by creating an index. Do you have any advice on this?

**Comment by jkatz** [comment]
@ataudt What are you trying to do with the k-means values from the already index vectors? I'm trying to understand the use case.

**Comment by ataudt** [comment]
I have around 100e6 rows of embeddings, and I want to do a simple k-means clustering on them (e.g. to find trends in my data, topic clustering, etc.). As far as I understood, the approximate index is the result of a k-means, so by creating the index I also create the clusters/topics. 
In the end I want to assign each vector to its cluster. This is not done for the purpose of searching, but for the purpose of organizing the data for downstream analysis.

**Comment by ahmedrachid** [comment]
hi @jkatz , we have similar use case, we think having centroids information would be beneficial to get more insights on data/trends/patterns..

**Comment by ankane** [comment]
Hi @ataudt, thanks for the suggestion. However, I'd like to keep clustering an internal detail of the index for now.

**Comment by ataudt** [comment]
Alright, thanks for considering.

Am Do., 9. Nov. 2023 um 22:59 Uhr schrieb Andrew Kane <
***@***.***>:

**Comment by danrasmuson** [comment]
This is exact task we are hopping to accomplish as well. +1 for being able to retrieve the centroid information.

**Comment by SitrucL** [comment]
+ 1 here as well
