### ISSUE TITLE
Add to AWS RDS supported extensions?

### ISSUE THREAD

**Issue by arikanev** [pgvector/pgvector#209]
Hi guys, wondering if it's in the works to add your extension to AWS RDS list of supported extensions for Postgres. Thanks!

**Comment by ankane** [comment]
Hi @arikanev, it's already available on Amazon RDS.

**Comment by arikanev** [comment]
I dont see it on Aurora Postgres. When I run SHOW rds.extensions; these are the returned extensions (Note: pgvector is not included!)

address_standardizer, address_standardizer_data_us, apg_plan_mgmt, aurora_stat_utils, amcheck, autoinc, aws_commons, aws_ml, aws_s3, aws_lambda, bool_plperl, bloom, btree_gin, btree_gist, citext, cube, dblink, dict_int, dict_xsyn, earthdistance, fuzzystrmatch, hll, hstore, hstore_plperl, insert_username, intagg, intarray, ip4r, isn, jsonb_plperl, lo, log_fdw, ltree, moddatetime, oracle_fdw, orafce, pgaudit, pgcrypto, pglogical, pgrouting, pgrowlocks, pgstattuple, pgtap, pg_bigm, pg_buffercache, pg_cron, pg_freespacemap, pg_hint_plan, pg_partman, pg_prewarm, pg_proctab, pg_repack, pg_similarity, pg_stat_statements, pg_trgm, pg_visibility, plcoffee, plls, plperl, plpgsql, plprofiler, pltcl, plv8, postgis, postgis_tiger_geocoder, postgis_raster, postgis_topology, postgres_fdw, prefix, rdkit, rds_tools, refint, seg, sslinfo, tablefunc, tcn, tds_fdw, tsm_system_rows, tsm_system_time, unaccent, uuid-ossp

**Comment by arikanev** [comment]
See error when running: CREATE EXTENSION IF NOT EXISTS vector;

Error:

DETAIL:  Installing the extension "vector" failed, because it is not on the list of extensions supported by Amazon RDS.

**Comment by arikanev** [comment]
Doh! I believe the issue was using Postgres version 13.8, which doesnt seem to support pgvector.
