### ISSUE TITLE
Distance queries

### ISSUE THREAD

**Issue by Githubturer** [pgvector/pgvector#211]
so for every distance query i would get the same results (not in the means of actual number, but in ranking order).

i'm using pg_vector to grade(score) each individual document based on input embedding.

i've tried Cosine , dot product & euclidian distance.

Also the scores do not have a big gap in them, i'd say for cosine that i'm getting around .65 - 1. 
I'm not sure if this is a problem with loading vectors or with OpenAIEmbeddings

Looking forward to an positive answer :)

**Comment by ankane** [comment]
Hi @Githubturer, for vectors with length 1, L2 distance, inner product, and cosine distance all have the same ordering.

https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use

**Comment by Githubturer** [comment]
> Hi @Githubturer, for vectors with length 1, L2 distance, inner product, and cosine distance all have the same ordering.
> 
> https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use

Thanks for reply :)
