### ISSUE TITLE
Trying to understand some terms?

### ISSUE THREAD

**Issue by neilt** [pgvector/pgvector#212]
My use case is finding the nearest neighbors where the match distance is less than some limit. My distance search rows will be limited to < 1000. If there is not a good enough match I don't want any results returned.  In my data it is possible that a distance calculation will be the same for multiple rows in the table. I want all of those rows returned.

So I have the following questions with regard to my use case.

In the readme is the statement "SET ivfflat.probes = 10;". And the explanation 
````
A higher value provides better recall at the cost of speed, and it can be set to the number 
of lists for exact nearest neighbor search (at which point the planner won’t use the index)
````

What does "better recall" mean? Does that mean that there may be a better match, but because a full table scan was not performed, it was not found?

What is a probe? Is this the same as a data sample. So if I set the number of probes to 10, the code will take 10 samples and return the best of the samples, even if it is not the closest in the data set?

What are lists and why do I care?

Will exact nearest neighbor return multiple rows if the distance is the same and at the minimum?

Does setting the probes = lists mean that there is no need to have an index and that all accesses will be table scans?

If I don't define an index, I don't set the number of lists, so how do I set the probes equal to lists without an index?  In this case what should I set the number of probes too.

Thanks

**Comment by ankane** [comment]
Hi @neilt, check out [this post](https://www.timescale.com/blog/nearest-neighbor-indexes-what-are-ivfflat-indexes-in-pgvector-and-how-do-they-work/) for an explanation of ivfflat indexes, which includes lists and probes (they only apply to indexes).
