### ISSUE TITLE
Server crash and reboot when create index on vector(512) of 5M records

### ISSUE THREAD

**Issue by bh4cyi** [pgvector/pgvector#213]
The sever crashes then reboots. I have tested many times trying to figure out what going on, but no clue. One thing I'm sure is that this related to the size of records. As you can see from the screen shots below, it happens during loading the tuples, and the actual memory usage is not critical.
<img width="427" alt="Screen Shot 2023-08-04 at 11 15 52 PM" src="https://github.com/pgvector/pgvector/assets/4915084/79863d3b-cd49-4b35-a477-dce92e170b87">
<img width="833" alt="Screen Shot 2023-08-04 at 11 16 11 PM" src="https://github.com/pgvector/pgvector/assets/4915084/d5608594-4d8b-46be-b7c2-fbd3dc004a03">

I created a subset of 1M records and the index was created successfully, but only once. After I delete the index and recreate it on the 1M subset, the server will crash and reboot again.

postgres 15.3
pg_vector 0.4.4
shared_buffers = 64GB
maintenance_work_mem = 10240MB

**Comment by ankane** [comment]
Hi @bh4cyi, the Postgres server log should have more details.

**Comment by bh4cyi** [comment]
Nothing useful there, only thing I can see after the system reboots is:
2023-08-05 03:47:32.831 UTC [2843] LOG:  database system was interrupted; last known up at 2023-08-05 03:34:02 UTC
2023-08-05 03:47:32.885 UTC [2843] LOG:  database system was not properly shut down; automatic recovery in progress

**Comment by bh4cyi** [comment]
I start to think it's a hardware issue.

**Comment by bh4cyi** [comment]
It seems the issue is related to ZFS. I moved the data directory from a ZFS mirrored pool to a XFS drive, and the index was created without any issue.

**Comment by ankane** [comment]
Thanks for following up. This doesn't seem like an issue with pgvector.
