### ISSUE TITLE
IMPOSSIBLE to install

### ISSUE THREAD

**Issue by ucals** [pgvector/pgvector#214]
I'm trying to install pgvector on a Macbook Pro 2017. After hours trying, I'm about to give up.

No method works.

Currently, make fails with the following error:

`ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64`

Can anyone help?
Thanks

**Comment by ankane** [comment]
Hi @ucals, it looks like something is wrong with your build environment. Try [deleting and reinstalling XCode](https://stackoverflow.com/questions/63592445/ld-unsupported-tapi-file-type-tapi-tbd-in-yaml-file) or using another installation method like Docker.

**Comment by ucals** [comment]
Thanks @ankane , but it continues impossible to install...

Now, it complains about `make: x86_64-apple-darwin13.4.0-clang: No such file or directory`

After 20 years, this is simply the hardest software to install I've ever seen...
