### ISSUE TITLE
Dart port

### ISSUE THREAD

**Issue by davidmigloz** [pgvector/pgvector#215]
Do you have plans to create a Dart port? I am willing to help.

Dart Postgres client:
https://pub.dev/packages/postgres

**Comment by ankane** [comment]
Hi @davidmigloz, added a [short example](https://github.com/pgvector/pgvector-dart) for Dart. It looks like the `postgres` package [doesn't support custom types](https://github.com/isoos/postgresql-dart/issues/87), but you can pass vectors to the database as strings and retrieve them by casting to `text`.

**Comment by davidmigloz** [comment]
That was fast! Thank you very much. I'll look into it.
