### ISSUE TITLE
pg-vector not using indexes

### ISSUE THREAD

**Issue by rahulwecp** [pgvector/pgvector#216]
I have a table (showing only the relevant columns)

```
CREATE TABLE question_embedding_duplicates(
    _id VARCHAR PRIMARY KEY, 
    complete_description VARCHAR,
    complete_description_embedding vector(384)
 )
```

I have populated the table with around 1.2 mil entries, then created the cosine index using the below query
```
CREATE INDEX question_embedding_duplicates_complete_description_embedding ON question_embedding_duplicates USING ivfflat (complete_description_embedding vector_cosine_ops) WITH (lists = 1250);
```

Then when i run the below query
```
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
WITH question_in_focus AS (
	SELECT * FROM question_embedding_duplicates
	WHERE _id = '001154ea-7c07-4914-b061-805fd99e64a3'
),
add_similarity AS (
	SELECT
	question_embedding_duplicates._id,
	1 - (complete_description_embedding <=> (SELECT complete_description_embedding FROM question_in_focus))  AS similarity
	FROM question_embedding_duplicates
	WHERE complete_description_embedding IS NOT NULL
)
SELECT * FROM add_similarity
WHERE similarity > 0.9
ORDER BY similarity DESC
```

It takes around 1 min for both cases (before and after creating the index)

This is the explain analyse query
```
"Gather Merge  (cost=180868.92..219790.00 rows=333586 width=66) (actual time=57894.913..57948.239 rows=7 loops=1)"
"  Output: question_embedding_duplicates._id, (('1'::double precision - (question_embedding_duplicates.complete_description_embedding <=> $0)))"
"  Workers Planned: 2"
"  Params Evaluated: $0, $1"
"  Workers Launched: 2"
"  Buffers: shared hit=8136150 read=918785"
"  InitPlan 1 (returns $0)"
"    ->  Index Scan using question_embedding_duplicates_pkey on public.question_embedding_duplicates question_embedding_duplicates_1  (cost=0.55..8.57 rows=1 width=238) (actual time=18.284..18.288 rows=1 loops=1)"
"          Output: question_embedding_duplicates_1.complete_description_embedding"
"          Index Cond: ((question_embedding_duplicates_1._id)::text = '001154ea-7c07-4914-b061-805fd99e64a3'::text)"
"          Buffers: shared read=5"
"  InitPlan 2 (returns $1)"
"    ->  Index Scan using question_embedding_duplicates_pkey on public.question_embedding_duplicates question_embedding_duplicates_2  (cost=0.55..8.57 rows=1 width=238) (actual time=0.030..0.031 rows=1 loops=1)"
"          Output: question_embedding_duplicates_2.complete_description_embedding"
"          Index Cond: ((question_embedding_duplicates_2._id)::text = '001154ea-7c07-4914-b061-805fd99e64a3'::text)"
"          Buffers: shared hit=5"
"  ->  Sort  (cost=179851.75..180268.74 rows=166793 width=66) (actual time=57815.192..57815.197 rows=2 loops=3)"
"        Output: question_embedding_duplicates._id, (('1'::double precision - (question_embedding_duplicates.complete_description_embedding <=> $0)))"
"        Sort Key: (('1'::double precision - (question_embedding_duplicates.complete_description_embedding <=> $0))) DESC"
"        Sort Method: quicksort  Memory: 25kB"
"        Buffers: shared hit=8136145 read=918780"
"        Worker 0:  actual time=57788.824..57788.829 rows=3 loops=1"
"          Sort Method: quicksort  Memory: 25kB"
"          JIT:"
"            Functions: 12"
"            Options: Inlining false, Optimization false, Expressions true, Deforming true"
"            Timing: Generation 3.858 ms, Inlining 0.000 ms, Optimization 1.585 ms, Emission 23.979 ms, Total 29.422 ms"
"          Buffers: shared hit=2695642 read=304234"
"        Worker 1:  actual time=57788.460..57788.466 rows=4 loops=1"
"          Sort Method: quicksort  Memory: 25kB"
"          JIT:"
"            Functions: 12"
"            Options: Inlining false, Optimization false, Expressions true, Deforming true"
"            Timing: Generation 5.357 ms, Inlining 0.000 ms, Optimization 0.869 ms, Emission 40.644 ms, Total 46.870 ms"
"          Buffers: shared hit=2712318 read=306576"
"        ->  Parallel Seq Scan on public.question_embedding_duplicates  (cost=0.00..165384.38 rows=166793 width=66) (actual time=26054.056..57815.004 rows=2 loops=3)"
"              Output: question_embedding_duplicates._id, ('1'::double precision - (question_embedding_duplicates.complete_description_embedding <=> $0))"
"              Filter: ((question_embedding_duplicates.complete_description_embedding IS NOT NULL) AND (('1'::double precision - (question_embedding_duplicates.complete_description_embedding <=> $1)) > '0.9'::double precision))"
"              Rows Removed by Filter: 400702"
"              Buffers: shared hit=8136131 read=918780"
"              Worker 0:  actual time=5614.701..57788.747 rows=3 loops=1"
"                Buffers: shared hit=2695635 read=304234"
"              Worker 1:  actual time=14679.186..57787.984 rows=4 loops=1"
"                Buffers: shared hit=2712311 read=306576"
"Planning Time: 0.346 ms"
"JIT:"
"  Functions: 36"
"  Options: Inlining false, Optimization false, Expressions true, Deforming true"
"  Timing: Generation 11.346 ms, Inlining 0.000 ms, Optimization 3.238 ms, Emission 79.043 ms, Total 93.627 ms"
"Execution Time: 57950.471 ms"
```
From explain result, I can see that the index is not being used.
Any idea what I am doing wrong
I am using the latest pg-vector - [v0.4.4](https://github.com/pgvector/pgvector/releases/tag/v0.4.4) and postgres v14

**Comment by ankane** [comment]
Hi @rahulwecp, it looks like you're ordering by an expression (`1 - (complete_description_embedding <=> ...) DESC`), which won't use an index. Use `complete_description_embedding <=> ... ASC` instead.

`WHERE` filters can also affect whether an index is used. If there are a lot of rows where `complete_description_embedding` is NULL, you may need to use a [partial index](https://github.com/pgvector/pgvector#filtering) by adding `WHERE (complete_description_embedding IS NOT NULL)` to the `CREATE INDEX` statement.

**Comment by rahulwecp** [comment]
Hi,
Thanks for the reply.
So i deleted the old one created this index

`
CREATE INDEX question_embedding_duplicates_complete_description_embedding ON question_embedding_duplicates USING ivfflat (complete_description_embedding vector_cosine_ops) WITH (lists = 1000) WHERE complete_description_embedding IS NOT NULL;
`

Then i used this query

`
WITH question_in_focus AS (
	SELECT * FROM question_embedding_duplicates
	WHERE _id = '001154ea-7c07-4914-b061-805fd99e64a3'
)
SELECT * FROM question_embedding_duplicates
WHERE question_embedding_duplicates.complete_description_embedding IS NOT NULL
ORDER BY complete_description_embedding <=> (SELECT complete_description_embedding FROM question_in_focus) DESC
LIMIT 10;
`

This is the explain Analyze

`
"Limit  (cost=172759.84..172761.01 rows=10 width=1004) (actual time=73868.096..73927.748 rows=10 loops=1)"
"  InitPlan 1 (returns $0)"
"    ->  Index Scan using question_embedding_duplicates_pkey on question_embedding_duplicates question_embedding_duplicates_1  (cost=0.55..8.57 rows=1 width=236) (actual time=5.029..5.033 rows=1 loops=1)"
"          Index Cond: ((_id)::text = '001154ea-7c07-4914-b061-805fd99e64a3'::text)"
"  ->  Gather Merge  (cost=172751.27..289729.91 rows=1002604 width=1004) (actual time=73856.001..73915.635 rows=10 loops=1)"
"        Workers Planned: 2"
"        Params Evaluated: $0"
"        Workers Launched: 2"
"        ->  Sort  (cost=171751.25..173004.50 rows=501302 width=1004) (actual time=73818.871..73818.879 rows=8 loops=3)"
"              Sort Key: ((question_embedding_duplicates.complete_description_embedding <=> $0)) DESC"
"              Sort Method: top-N heapsort  Memory: 51kB"
"              Worker 0:  Sort Method: top-N heapsort  Memory: 52kB"
"              Worker 1:  Sort Method: top-N heapsort  Memory: 50kB"
"              ->  Parallel Seq Scan on question_embedding_duplicates  (cost=0.00..160918.29 rows=501302 width=1004) (actual time=11.098..73130.483 rows=401019 loops=3)"
"                    Filter: (complete_description_embedding IS NOT NULL)"
"                    Rows Removed by Filter: 424"
"Planning Time: 0.283 ms"
"JIT:"
"  Functions: 25"
"  Options: Inlining false, Optimization false, Expressions true, Deforming true"
"  Timing: Generation 4.414 ms, Inlining 0.000 ms, Optimization 2.056 ms, Emission 38.181 ms, Total 44.650 ms"
"Execution Time: 73929.068 ms"
`

The query still takes more than 1 minute and doesn't use the index

**Comment by ankane** [comment]
Try changing the order to `ASC`

**Comment by rahulwecp** [comment]
Ohk, its using the index now and takes < 1sec.
Why is that though?
Also how would i get DESC order?

**Comment by ankane** [comment]
Great. Postgres only supports `ASC` order index scans on operators, but `ASC` will return the closest vectors.

**Comment by rahulwecp** [comment]
Thanks, got it working
