### ISSUE TITLE
Windows compile error

### ISSUE THREAD

**Issue by MBrekhof** [pgvector/pgvector#218]
As you might know compiling on Windows is a bit of a problem. I found a solution (better: someone else has a solution) I thought I would share. It solved the problem for me. The link: https://stackoverflow.com/questions/76269972/resolving-lnk4272-errors

**Comment by ankane** [comment]
Hi @MBrekhof, thanks for sharing. Improved the instructions in the commit above.

**Comment by MBrekhof** [comment]
My pleasure
BlueMail voor Android downloaden 
Op 7 aug. 2023, om 22:57, Andrew Kane ***@***.***> schreef:

Hi @MBrekhof, thanks for sharing. Improved the instructions in the commit above.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pgvector/pgvector/issues/218#issuecomment-1668567568",
"url": "https://github.com/pgvector/pgvector/issues/218#issuecomment-1668567568",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
