### ISSUE TITLE
Returning confidence or similarity score upon returning nearest neighbors

### ISSUE THREAD

**Issue by arikanev** [pgvector/pgvector#219]
Is it possible to run the following code:

`SELECT * FROM items ORDER BY embedding <-> '[3,1,2]' LIMIT 5;`

and also return the similarity scores to see if they're above or below some threshold?

Thanks!

**Comment by ankane** [comment]
Hi @arikanev, check out [this section](https://github.com/pgvector/pgvector#distances) of the readme.

**Comment by x4080** [comment]
Hi @ankane is this the correct way to get similarity ?
```
SELECT 1 - (embedding <=> '[3,1,2]') AS cosine_similarity FROM items;
```
Thanks
