### ISSUE TITLE
Scalar multiplication

### ISSUE THREAD

**Issue by ataudt** [pgvector/pgvector#223]
Hi again. Yet another functionality that would be handy: I want to calculate weighted averages for vectors. I could achieve this by using sum() and scalar multiplication (and division) on the vectors. The element-wise multiplication is implemented for vector * vector. Is there something for scalar * vector?
Thanks a lot for your time.

**Comment by bryanjj** [comment]
@ataudt this has been proposed several times before: e.g. https://github.com/pgvector/pgvector/issues/157

I agree it is a simple and important feature which should be added.

**Comment by bryanjj** [comment]
A workaround for this using unnest with arrays is:

`select array(select unnest(vec::real[]) * scalar)::vector`

**Comment by ataudt** [comment]
Thanks for the workaround. Very helpful!

**Comment by ankane** [comment]
Hi @ataudt, thanks for another suggestion. You can also use `array_fill` for this:

```sql
SELECT array_fill(2, '{3}')::vector * '[1,2,3]';
```

Overall, I don't think there's a strong case for adding this right now.
