### ISSUE TITLE
CloudNativePG compatible Docker Image

### ISSUE THREAD

**Issue by itay-grudev** [pgvector/pgvector#228]
I don't know if you've used [CNPG](https://cloudnative-pg.io/), but it's a brilliant Kubernetes PostgreSQL operator.

A lot of the CNPG users want to use pgvector, but it's not as straight-forward as it requires a Docker image with Postgres, [Barman](https://pgbarman.org/) cloud for backups, `pgaudit` and `pg-failover-slots` to operate.

I've made an adaptation of their Docker image, based on your Dockerfile here:

https://github.com/itay-grudev/pgvector-containers/blob/main/Debian/Dockerfile.template

And that works for me and for a fixed pgvector version. But we want to merge it in a CNPG Helm chart that provisions pgvector automatically and I would like to use the official pgvector Docker image as a source.

Will you be interested in modifying your Docker image to include the `pgaudit` and `pg-failover-slots` extensions and have Barman pre-installed so it can run in a database cluster configuration? 

The additional software is pretty light-weight and would not require active maintenance.

Will you be interested in the change and would you accept PRs for it?

**Comment by ankane** [comment]
Hi @itay-grudev, thanks for the suggestion and adapting it! I'd like to keep the pgvector Docker image simple, so think it's better as a separate project.

**Comment by mishak87** [comment]
FYI it is now included in CNPG https://github.com/cloudnative-pg/postgres-containers/issues/70
