### ISSUE TITLE
How can I get the kmeans lists centers

### ISSUE THREAD

**Issue by ssshai** [pgvector/pgvector#229]
Hi,

Is there any way to get the centers?

Background:
I have about 9M vectors in our table, and created an index with 2500 lists.

I would like to use the internal kmeans clusters for some high order classification of the each vector.
If I could somehow get the list of centers for each of 2500 lists that would be great.

The database is hosted at aws, a solution that will work on aws will be great,

**Comment by MaxBittker** [comment]
@ssshai why did you close? did you figure this out?
