### ISSUE TITLE
Cast to double precision / numeric

### ISSUE THREAD

**Issue by spacemolly** [pgvector/pgvector#23]
Currently, casting to real[] is useful as it allows this to interoperate existing clients however, it looses precision. 

A function that casts to double prevision[] or possibly numeric[], either would be fine really. Would be extremely useful.

**Comment by ankane** [comment]
Hey @spacemolly, vector elements are stored as floats, so there's no loss of precision from the conversion. You can use:

```sql
vec::real[]::double precision[]
# or
vec::real[]::numeric[]
```

if needed.
