### ISSUE TITLE
Getting distance in a nearest neighbors list

### ISSUE THREAD

**Issue by phobrain** [pgvector/pgvector#232]
I like to do weighted random selection on lists, so want the distance as well as the orderings.
Likely it's just my SQL isn't up to this, but it seems a helpful-enough example to add.

    id INTEGER,
    embedding VECTOR(3)

Given the nearest-neighbors example in README.md,

    SELECT * FROM items WHERE id != 1 ORDER BY embedding <-> (SELECT embedding FROM items WHERE id = 1) LIMIT 5;

I want

    SELECT id, <distance>  FROM items WHERE id != 1 ORDER BY embedding <-> (SELECT embedding FROM items WHERE id = 1) LIMIT 5;

Is it possible? It seems like it would need a new keyword if it were that simple. E.g. ORDER_WEIGHT for generality.

**Comment by jkatz** [comment]
@phobrain Are you looking for something like this:

```sql
SELECT
    id,
    embedding <-> (SELECT embedding FROM items WHERE id = 1) AS distance
FROM items
WHERE id != 1
ORDER BY distance
LIMIT 5;
```

**Comment by phobrain** [comment]
@jkatz Thanks! 

Putting the 'new operator' expression in parens made it easier for me to read, might be a useful convention for README.md:

    SELECT
        id,
        (embedding <=> (SELECT embedding FROM table WHERE id = ?))  as distance,
    WHERE
        ...
    ORDER BY distance
    LIMIT 5;

"Oh, what tangled webs we weave / when first we practice to retrieve."
Mimeographed library search intro in the 70's.

**Comment by phobrain** [comment]
Closing.

**Comment by phobrain** [comment]
That green button is too-attractive.
