### ISSUE TITLE
Adding angular distance for nn search

### ISSUE THREAD

**Issue by vgoat21** [pgvector/pgvector#234]
I was wondering if it would be possible to add angular distance for nn search. I am currently relying on cosine distance as an alternative. The reason behind this is the limitation of cosine distance when dealing with small angles.

![image](https://github.com/pgvector/pgvector/assets/93329405/b433b86b-29d1-4667-bb76-a7e7302b0455)

It's apparent that cosine distance tends to produce very similar values for small angles, making it challenging to distinguish the subtle differences in vector orientations. This leads to some ambiguity in these intervals which (at least in my application) is not the most appropriate to use.

Angular distance is sensitive not only to the direction but also to the magnitude of vectors. As depicted in the diagram, it yields more distinguishable values within these intervals, thus making it easier to assess the proximity of two vectors accurately.

In my application (and most likely many others) it is crucial to include these subtle differences to get a more accurate 'closeness'.

I think this would be a great addition to a very useful extension.

**Comment by phobrain** [comment]
It looks potentially feasible to add such functions in

https://github.com/pgvector/pgvector/blob/master/src/vector.c

which I was just considering for Poincare disk distances as in

https://arxiv.org/pdf/1705.08039.pdf

and since I find it empirically allows more fine-grained histogram distance orderings, I wonder naively if the Poincare sphere would be useful in your app.

Authors, is adding a new distance function as simple as l2_distance() seems in vector.c?

**Comment by jkatz** [comment]
>  is adding a new distance function as simple as l2_distance() seems in vector.c

Yes, it's relatively trivial, though note that (1) optimizing how the distance calculation is handled is key to many of the performance characteristics and (2) you need to set up the appropriate [operator classes][1] to allow it to be indexable.

For this, I'd be curious if you're noticing these results currently in pgvector. For `ivfflat`, vectors are normalized before they are stored in the index, so magnitude is not a factor.

[1]: https://github.com/pgvector/pgvector/blob/master/sql/vector.sql#L257

**Comment by phobrain** [comment]
Have any functions been tried and abandoned for speed reasons?

**Comment by ankane** [comment]
Hi @vgoat21, thanks for the suggestion. I may include this at some point, but for now, you can do:

```sql
CREATE FUNCTION angular_distance(a vector, b vector) RETURNS float8
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT
    RETURN acos(1 - cosine_distance(a, b)) / pi();
``` 

It's also possible to enable indexing with the commands below, but there's no guarantee it won't break in a future release.

```sql
CREATE OPERATOR <@> (
    LEFTARG = vector, RIGHTARG = vector, PROCEDURE = angular_distance,
    COMMUTATOR = '<@>'
);

CREATE OPERATOR CLASS vector_angular_ops
	FOR TYPE vector USING ivfflat AS
	OPERATOR 1 <@> (vector, vector) FOR ORDER BY float_ops,
	FUNCTION 1 vector_spherical_distance(vector, vector),
	FUNCTION 2 vector_norm(vector),
	FUNCTION 3 vector_spherical_distance(vector, vector),
	FUNCTION 4 vector_norm(vector);

CREATE OPERATOR CLASS vector_angular_ops
	FOR TYPE vector USING hnsw AS
	OPERATOR 1 <@> (vector, vector) FOR ORDER BY float_ops,
	FUNCTION 1 vector_spherical_distance(vector, vector),
	FUNCTION 2 vector_norm(vector);
```

and

```sql
CREATE INDEX ON items USING ivfflat (embedding vector_angular_ops) WITH (lists = 100);
-- or
CREATE INDEX ON items USING hnsw (embedding vector_angular_ops);
```

**Comment by ankane** [comment]
Added the function in the [angular_distance branch](https://github.com/pgvector/pgvector/compare/angular_distance) and to the list of ideas (#27).
