### ISSUE TITLE
HNSW testing

### ISSUE THREAD

**Issue by ankane** [pgvector/pgvector#239]
_Originally posted by @alanwli in https://github.com/pgvector/pgvector/issues/181#issuecomment-1693821662_

@ankane, not sure if you've run into this in your testing. When I ran it with 86c29b3bf038de50bb2aec21b6d896823ff1fbbe on an usecases, I was hitting what looks like some kind of race condition with the index.

I simplified it down to the following python script - where there is a table with 1k vectors, inserts+deletes workload that always keeps the table at 1k vectors. But when doing an index scan with ef_search set to 1k, I see that the index will not have all 1k vectors - quite a number of occasions where it's missing 10%+ of what should be there, the worst I saw was ~24% missing. Note that I don't see this with ivfflat (uncomment the ivfflat line). Is this expected?

```python
from collections.abc import Sequence

import psycopg
import pgvector.psycopg
import sys
import numpy as np

def main(argv: Sequence[str]) -> None:
  conn = psycopg.connect(host='localhost', port=5432, user="postgres", dbname="postgres", password="postgres")
  conn.autocommit = False
  pgvector.psycopg.register_vector(conn)
  cur = conn.cursor()
  cur.execute("CREATE TABLE items (id int, embedding vector(1024))")
  cur.execute("ALTER TABLE items ALTER COLUMN embedding SET STORAGE PLAIN")
  cur.execute("CREATE INDEX ON items USING hnsw (embedding vector_cosine_ops) WITH (m = 12, ef_construction=40)")
  #cur.execute("CREATE INDEX ON items USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")

  ## insert 1k vectors
  for i in range(1000):
    vector_string = "[" + ",".join([str(v) for v in np.random.random_sample((1024,)) * 1]) + "]"
    cur.execute("insert into items (id, embedding) values (%d, '%s')" % (i, vector_string))
  conn.commit()

  for i in range(100):
    for j in range(100):
      ## delete 100 vectors & insert 100 vectors within a transaction
      k = i*100+j
      cur.execute("delete from items where id = %d" % k)
      vector_string = "[" + ",".join([str(v) for v in np.random.random_sample((1024,)) * 1]) + "]"
      cur.execute("insert into items (id, embedding) values (%d, '%s')" % (k+1000, vector_string))
      conn.commit()

    conn.autocommit = True
    ## should still be 1k vectors in the table
    cur.execute("SELECT id FROM items")
    table_entries = cur.fetchall()

    ## run vacuum
    conn.cursor().execute("vacuum items")
    conn.autocommit = False

    ## force index scans: count vectors according to the vector index, expected to get 1k vectors back
    cur.execute("SET enable_seqscan = off")
    cur.execute("SET ivfflat.probes = 100")
    cur.execute("SET hnsw.ef_search = 1000")
    vector_string = "[" + ",".join([str(v) for v in np.random.random_sample((1024,)) * 1]) + "]"
    print(cur.execute("EXPLAIN ANALYZE SELECT id FROM items ORDER BY embedding <=> '%s'" % vector_string).fetchone())
    cur.execute("SELECT id FROM items ORDER BY embedding <=> '%s'" % vector_string)
    index_entries = cur.fetchall()
    conn.commit()

    ## shouldn't have any deltas?
    diff = list(set(table_entries) - set(index_entries))
    print("table_entries (%d) - index_entries (%d) = %s (%d)" % (len(table_entries), len(index_entries), diff, len(diff)))


if __name__ == "__main__":
  main(sys.argv)
``` 

Example output:
```
$ python3 test.py
('Index Scan using items_embedding_idx on items  (cost=212.36..2976.86 rows=1000 width=12) (actual time=2.689..3.977 rows=999 loops=1)',)
table_entries (1000) - index_entries (999) = [(1056,)] (1)
('Index Scan using items_embedding_idx on items  (cost=232.36..2835.84 rows=918 width=12) (actual time=3.206..4.506 rows=1000 loops=1)',)
table_entries (1000) - index_entries (1000) = [] (0)
('Index Scan using items_embedding_idx on items  (cost=252.36..2719.00 rows=851 width=12) (actual time=2.558..3.916 rows=1000 loops=1)',)
table_entries (1000) - index_entries (1000) = [] (0)
('Index Scan using items_embedding_idx on items  (cost=268.36..2618.31 rows=796 width=12) (actual time=2.327..3.447 rows=929 loops=1)',)
table_entries (1000) - index_entries (929) = [(1143,), (1375,), (841,), (847,), (600,), (1384,), (908,), (1033,), (856,), (441,), (1045,), (865,), (1170,), (1350,), (1344,), (944,), (1063,), (462,), (1188,), (880,), (532,), (892,), (590,), (707,), (413,), (1020,), (1313,), (660,), (1139,), (594,), (1212,), (849,), (736,), (855,), (1209,), (1044,), (443,), (1163,), (681,), (1105,), (516,), (821,), (940,), (699,), (705,), (824,), (1373,), (650,), (1370,), (830,), (1260,), (1205,), (958,), (1089,), (1269,), (1327,), (674,), (497,), (1342,), (1040,), (979,), (1165,), (1229,), (1293,), (518,), (817,), (1296,), (1055,), (878,), (1305,), (954,)] (71)
...
table_entries (1000) - index_entries (894) = [(8331,), (8996,), (8822,), (8340,), (9005,), (8404,), (8950,), (9069,), (9023,), (8715,), (8333,), (8525,), (9016,), (9208,), (8726,), (8799,), (8326,), (9064,), (9009,), (8591,), (9137,), (8545,), (8847,), (8447,), (9066,), (9258,), (9267,), (8959,), (8675,), (9032,), (8385,), (9288,), (9233,), (8348,), (9132,), (8769,), (8961,), (8796,), (9043,), (9162,), (9189,), (8716,), (8661,), (8844,), (9091,), (9036,), (8862,), (8499,), (9109,), (8627,), (8572,), (9182,), (8773,), (8837,), (8956,), (8419,), (8501,), (9047,), (8327,), (8812,), (8876,), (9004,), (8830,), (8958,), (9077,), (9086,), (8375,), (9159,), (8622,), (8512,), (8695,), (8814,), (8585,), (8768,), (8832,), (8777,), (9070,), (8841,), (9216,), (8752,), (8535,), (8971,), (8672,), (9163,), (8681,), (8507,), (8690,), (8635,), (8400,), (8345,), (9129,), (9248,), (8900,), (9202,), (9028,), (8985,), (8820,), (8948,), (9067,), (8475,), (8594,), (8914,), (8740,), (8630,), (8694,), (8813,)] (106)
('Index Scan using items_embedding_idx on items  (cost=372.36..2203.53 rows=574 width=12) (actual time=2.397..3.733 rows=985 loops=1)',)
table_entries (1000) - index_entries (985) = [(8726,), (9070,), (9121,), (8716,), (8594,), (8818,), (8900,), (8956,), (9007,), (8991,), (9036,), (8959,), (8820,), (8833,), (9103,)] (15)
('Index Scan using items_embedding_idx on items  (cost=372.36..2191.49 rows=570 width=12) (actual time=2.348..3.566 rows=983 loops=1)',)
table_entries (1000) - index_entries (983) = [(9051,), (9118,), (9121,), (9240,), (8954,), (8999,), (9127,), (8818,), (8831,), (8900,), (8956,), (9007,), (8991,), (9036,), (8959,), (8833,), (9103,)] (17)
('Index Scan using items_embedding_idx on items  (cost=376.36..2187.45 rows=567 width=12) (actual time=2.781..4.037 rows=981 loops=1)',)
table_entries (1000) - index_entries (981) = [(9118,), (9121,), (9240,), (8999,), (8944,), (9127,), (8831,), (8959,), (9007,), (9071,), (9190,), (8900,), (8833,), (8991,), (9201,), (8954,), (9036,), (9103,), (9112,)] (19)
('Index Scan using items_embedding_idx on items  (cost=376.36..2179.41 rows=564 width=12) (actual time=2.317..3.557 rows=982 loops=1)',)
table_entries (1000) - index_entries (982) = [(9121,), (9240,), (9201,), (8999,), (8944,), (9127,), (9072,), (8831,), (8900,), (9007,), (8991,), (9036,), (9071,), (8959,), (9260,), (9103,), (8974,), (9112,)] (18)
('Index Scan using items_embedding_idx on items  (cost=380.36..2143.37 rows=561 width=12) (actual time=4.483..6.177 rows=980 loops=1)',)
table_entries (1000) - index_entries (980) = [(9121,), (9240,), (8999,), (8944,), (9127,), (9072,), (8831,), (8959,), (8974,), (9007,), (9071,), (8900,), (9260,), (9052,), (8991,), (9073,), (9201,), (9036,), (9103,), (9112,)] (20)
('Index Scan using items_embedding_idx on items  (cost=352.36..2259.92 rows=605 width=12) (actual time=1.833..3.054 rows=1000 loops=1)',)
table_entries (1000) - index_entries (1000) = [] (0)
('Index Scan using items_embedding_idx on items  (cost=356.36..2239.80 rows=595 width=12) (actual time=1.853..3.116 rows=1000 loops=1)',)
table_entries (1000) - index_entries (1000) = [] (0)
```

**Comment by NikolayS** [comment]
my 2 cents, just if helpful

> cur.execute("insert into items (id, embedding) values (%d, '%s')" % (k+1000, vector_string))

would be good to do before index creation (at least faster)

> conn.cursor().execute("vacuum items")

looks like `analyze` is missing here, to collect stats

> print(cur.execute("EXPLAIN ANALYZE SELECT ...

better: `print(cur.execute("EXPLAIN (ANALYZE, BUFFERS) SELECT ...` – to pay attention to the IO numbers (since they are invariant, unlike timing numbers)

**Comment by alanwli** [comment]
HI @NikolayS, I agree with your points if this were for looking at performance, but it's currently just for demonstrating what I think is a correctness issue.

@ankane - let me know if you need any more info from me or if you're not able to reproduce what I'm seeing.

**Comment by ankane** [comment]
Hi @alanwli, thanks for sharing. It's possible for elements to lose all incoming connections with the HNSW algorithm (https://github.com/nmslib/hnswlib/issues/352), but will try to see if it's something more. A higher `m`, like the default 16, will reduce it.

**Comment by alanwli** [comment]
FYI, I tried a higher `m` value of 16 per your suggestion, which seems to help a bit but I still see 4-5% loss of entries and a worst case of 16% loss from a few runs.


...
('Index Scan using items_embedding_idx on items  (cost=376.48..2629.88 rows=752 width=12) (actual time=2.255..3.420 rows=1000 loops=1)',)
table_entries (1000) - index_entries (1000) = [] (0)
('Index Scan using items_embedding_idx on items  (cost=396.48..2569.43 rows=716 width=12) (actual time=2.422..3.692 rows=934 loops=1)',)
table_entries (1000) - index_entries (934) = [(9060,), (9179,), (8950,), (9130,), (8703,), (8654,), (9136,), (9435,), (8843,), (9020,), (9566,), (8788,), (8855,), (9148,), (8919,), (8608,), (9587,), (8980,), (9465,), (9471,), (9533,), (
8690,), (9474,), (8992,), (8632,), (8757,), (9303,), (8679,), (9422,), (9425,), (8885,), (8836,), (9315,), (9254,), (9013,), (8903,), (9083,), (9321,), (8787,), (8961,), (8912,), (9205,), (8976,), (8613,), (8683,), (8628,), (9348,), (92
29,), (9183,), (9543,), (8829,), (9006,), (8832,), (9253,), (9497,), (9387,), (9146,), (9027,), (9451,), (9402,), (9466,), (8685,), (9524,), (8749,), (8874,), (8813,)] (66)
('Index Scan using items_embedding_idx on items  (cost=412.48..2513.06 rows=686 width=12) (actual time=2.429..3.720 rows=993 loops=1)',)
table_entries (1000) - index_entries (993) = [(9276,), (9205,), (9034,), (8965,), (9106,), (9363,), (9572,)] (7)
('Index Scan using items_embedding_idx on items  (cost=428.48..2424.74 rows=661 width=12) (actual time=3.043..4.347 rows=834 loops=1)',)
**_table_entries (1000) - index_entries (834) = [(9597,), (9124,), (9307,), (9252,), (9316,), (9508,), (9334,), (9279,), (9572,), (9398,), (9343,), (9581,), (9407,), (9590,), (9599,), (8943,), (9181,), (9126,), (9364,), (9437,), (9446,), (
8845,), (9400,), (8918,), (9037,), (9583,), (8982,), (8808,), (9165,), (9537,), (8936,), (9174,), (9000,), (9293,), (9302,), (9128,), (9201,), (8838,), (9503,), (9448,), (9567,), (8966,), (8984,), (8810,), (8993,), (9231,), (9057,), (97
77,), (9002,), (9368,), (9194,), (9313,), (9551,), (9331,), (8913,), (9578,), (9105,), (9224,), (9242,), (9361,), (9187,), (9443,), (8842,), (9025,), (9034,), (8933,), (9226,), (9290,), (9354,), (9244,), (9363,), (9189,), (8826,), (9491
,), (9317,), (9436,), (9555,), (9018,), (8844,), (9338,), (8990,), (9182,), (8883,), (9548,), (9502,), (8965,), (9029,), (9093,), (9276,), (9221,), (9230,), (9477,), (8940,), (9486,), (9550,), (9678,), (9077,), (8848,), (9205,), (9150,)
, (9214,), (9397,), (9104,), (9342,), (9406,), (9415,), (9360,), (9479,), (8878,), (9424,), (8823,), (8942,), (9369,), (8841,), (9680,), (9134,), (9024,), (9262,), (9033,), (9271,), (9390,), (9106,), (9399,), (9170,), (8807,), (9353,),
(9472,), (8816,), (9008,), (9127,), (8953,), (9072,), (8898,), (9191,), (9200,), (9319,), (9035,), (9273,), (9282,), (9401,), (9520,), (9346,), (8864,), (9584,), (9065,), (9492,), (8891,), (9248,), (8900,), (9028,), (9330,), (9339,), (9
458,), (9577,), (8985,), (9531,), (8930,), (9357,), (8994,), (9540,), (8939,), (9485,), (9549,), (9131,), (9021,), (9140,)] (166)_**
('Index Scan using items_embedding_idx on items  (cost=408.48..2533.17 rows=695 width=12) (actual time=2.556..3.768 rows=999 loops=1)',)
table_entries (1000) - index_entries (999) = [(9406,)] (1)
('Index Scan using items_embedding_idx on items  (cost=424.48..2488.84 rows=669 width=12) (actual time=2.375..3.621 rows=1000 loops=1)',)
table_entries (1000) - index_entries (1000) = [] (0)
...

**Comment by jkatz** [comment]
This is a really small data set to be indexing. Are there any differences when you add more vectors? 50K? 100K?

**Comment by ankane** [comment]
Found and fixed an issue in 8801832946afa1401f6a0132f16d93dd9e45283b, but still feels like something else is off. Going to keep digging.

**Comment by ankane** [comment]
Still doing more testing, but the commit above seems to improve things significantly.

**Comment by alanwli** [comment]
@ankane, I did a run this morning with HEAD and things have indeed improved for the simplified test case. But I think there's still something lurking because I still see occasional blips, and I also think the problem shows up more with more writers - this was why I thought there might have been some race condition. Are you also seeing this in your testing?

**Comment by ankane** [comment]
I'm not seeing any outstanding issues in my testing, but can take a look if you have another repro script.

**Comment by alanwli** [comment]
Sure, let me put another publicly-shareable script together.

**Comment by alanwli** [comment]
@ankane, see the repro script below. Similar to the previous script, ivfflat index does not exhibit this problem.

```python
from collections.abc import Sequence

import psycopg
import pgvector.psycopg
import sys
import numpy as np
from multiprocessing import Pool
import time
import random

## each worker is responsible for its working set - it deletes one vector & inserts one vector in a single transaction
def doWork(worker_id : int) -> None:
  worker_conn = psycopg.connect(host='localhost', port=5432, user="postgres", dbname="postgres", password="postgres")
  worker_conn.autocommit = False
  pgvector.psycopg.register_vector(worker_conn)
  worker_cur = worker_conn.cursor()
  working_set = list(range((worker_id*100), (worker_id*100)+100))
  for i in range(30):
    try:
      random_idx = random.randint(0, 99)
      k = working_set[random_idx]
      worker_cur.execute("delete from items where id = %d" % k)
      vector_string = "[" + ",".join([str(v) for v in np.random.random_sample((1024,)) * 1]) + "]"
      worker_cur.execute("insert into items (id, embedding) values (%d, '%s')" % (k+1000, vector_string))
      working_set[random_idx] = k+1000
      worker_conn.commit()
      time.sleep(1)
    except (KeyboardInterrupt, SystemExit):
      break

def main(argv: Sequence[str]) -> None:
  conn = psycopg.connect(host='localhost', port=5432, user="postgres", dbname="postgres", password="postgres")
  conn.autocommit = False
  pgvector.psycopg.register_vector(conn)
  cur = conn.cursor()
  cur.execute("CREATE TABLE items (id int, embedding vector(1024))")
  cur.execute("ALTER TABLE items ALTER COLUMN embedding SET STORAGE PLAIN")
  cur.execute("CREATE INDEX ON items USING hnsw (embedding vector_cosine_ops) WITH (m = 12, ef_construction=40)")
  #cur.execute("CREATE INDEX ON items USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")

  ## insert 1k vectors
  for i in range(1000):
    vector_string = "[" + ",".join([str(v) for v in np.random.random_sample((1024,)) * 1]) + "]"
    cur.execute("insert into items (id, embedding) values (%d, '%s')" % (i, vector_string))
  conn.commit()

  ## run vacuum
  conn.autocommit = True
  conn.cursor().execute("vacuum items")
  conn.autocommit = False

  with Pool(processes=10) as pool:
    ## parallel write workers
    results = pool.map_async(doWork, range(10))

    ## while writers are writing, keep reading
    while 1:
      try:
        results.get(1)
        break
      except:
        ## should still be 1k vectors in the table
        cur.execute("SELECT id FROM items")
        table_entries = cur.fetchall()

        ## force index scans: count vectors according to the vector index, expected to get 1k vectors back
        cur.execute("SET enable_seqscan = off")
        cur.execute("SET ivfflat.probes = 100")
        cur.execute("SET hnsw.ef_search = 1000")
        vector_string = "[" + ",".join([str(v) for v in np.random.random_sample((1024,)) * 1]) + "]"
        cur.execute("SELECT id FROM items ORDER BY embedding <=> '%s'" % vector_string)
        index_entries = cur.fetchall()
        conn.commit()

        ## shouldn't have any deltas?
        print("table_entries (%d) - index_entries (%d) = %d" % (len(table_entries), len(index_entries), len(table_entries) - len(index_entries)))

if __name__ == "__main__":
  main(sys.argv)
``` 

Here's sample output using pgvector at e50a79108f95bdc64c3e0c8d1e6c1c7e5aef1c1d.
```
table_entries (1000) - index_entries (999) = 1
table_entries (1000) - index_entries (995) = 5
table_entries (1000) - index_entries (988) = 12
table_entries (1000) - index_entries (981) = 19
table_entries (1000) - index_entries (976) = 24
table_entries (1000) - index_entries (974) = 26
table_entries (1000) - index_entries (971) = 29
table_entries (1000) - index_entries (972) = 28
table_entries (1000) - index_entries (965) = 35
table_entries (1000) - index_entries (960) = 40
table_entries (1000) - index_entries (952) = 48
table_entries (1000) - index_entries (963) = 37
table_entries (1000) - index_entries (955) = 45
table_entries (1000) - index_entries (952) = 48
table_entries (1000) - index_entries (953) = 47
table_entries (1000) - index_entries (944) = 56
table_entries (1000) - index_entries (943) = 57
table_entries (1000) - index_entries (949) = 51
table_entries (1000) - index_entries (948) = 52
table_entries (1000) - index_entries (937) = 63
table_entries (1000) - index_entries (928) = 72
table_entries (1000) - index_entries (942) = 58
table_entries (1000) - index_entries (924) = 76
table_entries (1000) - index_entries (926) = 74
table_entries (1000) - index_entries (912) = 88
table_entries (1000) - index_entries (923) = 77
table_entries (1000) - index_entries (935) = 65
table_entries (1000) - index_entries (932) = 68
table_entries (1000) - index_entries (905) = 95
```

**Comment by alanwli** [comment]
Oh, that's quite interesting behavior - is there a reason why it behaves differently than ivfflat in this respect? For example, if that's the case, setting ef_search to 10 but the top-10 results in the HNSW index happen to be dead, then the query will return 0 results and recall would suffer significantly in this case.

**Comment by jkatz** [comment]
@ankane will answer this better as I haven't fully looked at the HNSW implementation, but for `ivfflat`, pgvector will pass each tuple back to the PostgreSQL executor and lets it decide whether or not to use it. `ivfflat` currently does not do any pruning, so it has available all the tuples that are in the lists you query.

 believe HNSW has already pruned tuples at that point, so the PostgreSQL executor may then rule out any tuples that are no longer visible.

**Comment by alanwli** [comment]
Then shouldn't HNSW ideally prune the tuples that are dead from being considered in the ef_search set? Otherwise, it seems quite difficult to use HNSW when there are deletes or updates that affect recall without any bounded-guarantees.

Now that @jkatz has explained the underlying behavior, it is different than the original problem I saw. So I'm happy to file a separate bug about this behavior against the 0.5.0 release.
