### ISSUE TITLE
Postgres transform for vector ?

### ISSUE THREAD

**Issue by Florents-Tselai** [pgvector/pgvector#241]
I'm not sure if anyone has come across this, but would it make sense to have a [transform](https://www.postgresql.org/docs/current/sql-createtransform.html) that could map a `vector` from SQL into a Python object (like a list of lists or similar) within a Pl/Python call?

That is very different from psycopg adapters etc. but it does need a representation of a vector within the Python world.

That is analogous to [hstore_plpython](https://github.com/postgres/postgres/tree/master/contrib/hstore_plpython) which transforms hstore mappings into simple python dicts, or [jsonb_plpython](https://github.com/postgres/postgres/tree/master/contrib/jsonb_plpython)

**Comment by jkatz** [comment]
It'd at least be worth testing when working with PL/Python to see if there are any performance gains. Today, you can still cast to an ARRAY (e.g. `embedding::real[]`) and have it work within PL/Python.
