### ISSUE TITLE
how to set search/index type while retrieving, there is no index name in the template? how do we know if the query is using a particular index created(exact/ivfflat/HNSW in the same table)? 

### ISSUE THREAD

**Issue by himsgpt** [pgvector/pgvector#242]
I create an index in postgreSQL using below:
`cur.execute(f'CREATE INDEX ON <table name>USING ivfflat (<column name> <index method>) WITH (lists = {num_lists});')`

now i retrieve similar docs using but **nowhere i have mentioned whether it should use the above index?** 
**Let's suppose, i want to do the exact search or i want to create, use and compare HNSW index performance. how can we do that?**
`cur.execute(f"SELECT * FROM <table name> ORDER BY <column name> <=> %s LIMIT 5", (query_embedding,))`

**Also, is there a way to see progress of the index being created like speed, memory, recall?**

**Comment by jkatz** [comment]
There are a few items to unpack here:

The PostgreSQL query planner ultimately determines whether to perform a sequential scan (exact NN search) vs. an index scan (approximate NN search). This is done based on "costing," or estimates based upon the total number of records that PostgreSQL expects to search (it's actually the total number of "pages," which is the atomic unit of storage in PostgreSQL). For `ivfflat`, there are two primary ways that PostgreSQL will decide to use a exact NN search:

* The value of `ivfflat.probes` is high enough that it's cheaper to perform an exact NN search than an approximate NN search
* The value of `enable_indexscan` is set to `off`. I'd advise against this one except in extreme circumstances, as it will disable all index scans while this parameter is disabled.

Both of the above options can be set within your session (e.g. `SET ivfflat.probes TO 100`)

For a detailed discussion on costing, please see: https://github.com/pgvector/pgvector/pull/133

To check on the progress while the index is being created, you can query the [`pg_stat_progress_create_index`](https://www.postgresql.org/docs/current/progress-reporting.html#CREATE-INDEX-PROGRESS-REPORTING). To see the amount of size the index takes up on disk, you can use the `pg_relation_size` function and use the name of the index as the parameter.

For performance/recall, you will have to test that yourself, as this is dependent on your data set, your index building parameters, and your query parameters. [Here is a reference for how to test for this and a few other ANN index attributes](https://jkatz05.com/post/postgres/pgvector-hnsw-performance/).

**Comment by himsgpt** [comment]
Thank you for the prompt answers. 
On the 1st part of the query, does that mean we cannot manually set whether we want to use a sequential scan (exact NN search) or an index scan (approximate NN search)?
I know that probes has a default value as 1 and we can change this like this `cur.execute("SET ivfflat.probes TO 3;")` but 

1. if we don't want to use NN search, how to execute that, do you have a sample code?
2. if we create an ivfflat index **ivf1** and hnsw index **hnsw1**, how do we use this during retrieval, any sample codes?

**Comment by ankane** [comment]
Hi @himsgpt,

1. For exact search, you can not add an index or set `ivfflat.probes` to the number of lists with IVFFlat (there may be an option to do something similar with HNSW at some point). You can also disable index scans for a statement (but note this affects all indexes, so use carefully):

```sql
BEGIN;
SET LOCAL enable_indexscan = off;
SELECT ...
COMMIT;
```

2. The Postgres query planner will automatically use the index with the lowest cost (or no index if a table scan is cheaper). Use `EXPLAIN ANALYZE` to [view details](https://github.com/pgvector/pgvector#performance).
