### ISSUE TITLE
After creating multiple indexes on different columns, how and where to enable particular index during retrieval?

### ISSUE THREAD

**Issue by himsgpt** [pgvector/pgvector#247]
I create two index as below:
`cur.execute(f'CREATE INDEX index1 ON {table_name} USING ivfflat ({column_name1} {index_method1}) WITH (lists = {num_lists});')`

`cur.execute(f'CREATE INDEX index2 ON {table_name} USING ivfflat ({column_name2} {index_method2}) WITH (lists = {num_lists});')`

I want to retrieve document based on either index1 or index2. how and where would i set the index name in a particular retrieval code?
`cur.execute(f"SELECT *  FROM {table_name} ORDER BY column_name {query_operator} %s LIMIT {k}", (query_embedding,))`

**Comment by ankane** [comment]
Hi @himsgpt, there's not a way to specify which index will be used. The Postgres planner will choose the one with the lowest cost (which will be the one with more lists with `ivfflat`).
