### ISSUE TITLE
After creating multiple indexes in postgreSql, how to activate a particular index while retrieving documents

### ISSUE THREAD

**Issue by himsgpt** [pgvector/pgvector#249]
I have created two index like this in postgreSQL:
`cur.execute(f'CREATE INDEX **index1** ON {table_name} USING ivfflat ({column_name} {**index_method1**}) WITH (lists = {num_lists});')`

`cur.execute(f'CREATE INDEX **index2** ON {table_name} USING ivfflat ({column_name} {**index_method2**}) WITH (lists = {num_lists});')`

**How and where can i activate an index(index1 or index2) during retrieval?**
`cur.execute(f"SELECT * FROM {table_name} ORDER BY column_name {query_operator} %s LIMIT {k}", (query_embedding,))`

**Comment by pashkinelfe** [comment]
Generally you don't need to set this. Executor will use what the one having lower cost. In case you want to set it manually set indisvalid = false for the indexes you don't want to be used in the query https://www.postgresql.org/docs/current/catalog-pg-index.html

**Comment by jkatz** [comment]
Another way to choose different indexes to execute is to create a [conditional][1] index, which would execute based upon the value of the `WHERE` clause.

I strongly recommend to not tamper with `indisvalid`. While setting it to `false` would prevent the query planner from considering it in queries, this also impacts other maintenance operations on the index and could lead to a state of retrieving incorrect results once you've re-enabled the index.

[1]: https://www.postgresql.org/docs/current/indexes-partial.html
