### ISSUE TITLE
Vector operations

### ISSUE THREAD

**Issue by Siegi96** [pgvector/pgvector#25]
Hi, is it possible to do type casting between arrays and vectors? I would like to do some operations inside pg (averaging vectors,...), but i could not find anything to do so.

**Comment by ankane** [comment]
Hey @Siegi96, it's already supported for certain array types. Are you seeing a specific error?

**Comment by Siegi96** [comment]
Probably I am overlooking sth, but how can i do so? E.g. I would like to average 2 vectors horizontally, therefore I would like to transform de vecs from type vector to array, do some math and then back to type vector.

**Comment by ankane** [comment]
It'll be the same as built-in types (`::type` or `CAST(value AS type)`).

```sql
SELECT '[1,2,3]'::vector::real[];
SELECT ARRAY[1,2,3]::vector;
```

**Comment by Siegi96** [comment]
Did not know that, thx for you fast answer.

Love your library, keep up the good work 👍
