### ISSUE TITLE
Ordering of distance metrics

### ISSUE THREAD

**Issue by aiseei** [pgvector/pgvector#252]
Hi - please could you advise the natural ordering for 4 metrics supported - cosine, IP, Manhattan  & l 2 distance. 
What advice could you provide for normalized embeddings . When using sentence-transformers is there a best practice?
Much appreciated in advance !

Thanks

**Comment by ankane** [comment]
Hi @aiseei, L2 distance, inner product, and cosine distance will all have the same ordering for vectors with length 1, so any will work.

**Comment by aiseei** [comment]
@ankane thanks. so just to be clear you talking abt normalized vectors ? For L1 would the same stand ? 
Please advise if we to use non noramlized vectors ie not Open ai - then how would the ordering be returned?
Could you point to any docs/blogs that can help me better understand ?

much thanks!
