### ISSUE TITLE
Compatibility with PostGIS

### ISSUE THREAD

**Issue by ckrapu** [pgvector/pgvector#253]
I'm looking to run queries against data with both geospatial coordinates (restricted by 2D bounding box) with the PostGIS extension and vector coordinates. I can't see any straightforward way to reconcile the two. Any insights on whether or not this ability is present, feasible, or completely infeasible from vector embedding side?

**Comment by jkatz** [comment]
Do you have an example of the type of query you're trying to run?

**Comment by pashkinelfe** [comment]
I'm not sure but according to the PostgGIS manual they have ORDER BY geom <-> 'SRID=3005;POINT(1011102 450541)'::geometry limit 10;

**Comment by ckrapu** [comment]
Sure - here's a short example:

```
-- Create a table with spatial and vector data
CREATE TABLE spatial_vector_data (
    id SERIAL PRIMARY KEY,
    name TEXT,
    location GEOMETRY(Point, 4326),  -- 2D spatial coordinates (latitude and longitude)
    embedding VECTOR(4)               -- 4D vector coordinates
);

-- Insert test data
INSERT INTO spatial_vector_data (name, location, embedding) VALUES
('Point A', ST_SetSRID(ST_Point(-70.01, 43.27), 4326), '[1.0, 2.0, 3.0, 4.0]'),
('Point B', ST_SetSRID(ST_Point(-71.01, 44.27), 4326), '[4.0, 3.0, 2.0, 1.0]');

-- Perform a hybrid vector search bounded by a spatial bounding box
-- Here, we're looking for points within a bounding box and then ordering them by vector similarity to a given vector
SELECT 
    name,
    ST_AsText(location) as location_coordinates,
    embedding
FROM 
    spatial_vector_data
WHERE 
    location && ST_MakeEnvelope(-71, 43, -70, 44, 4326)  -- Bounding box filter
ORDER BY 
    embedding <-> '[2.0, 2.0, 2.0, 2.0]'  -- Vector similarity order
```

**Comment by ankane** [comment]
Hi @ckrapu, that query runs fine. I'm not aware of any incompatibilities.

**Comment by ckrapu** [comment]
To follow up, I haven't been able to figure out whether the spatial filtering or the vector lookup is happening first. Would it be possible to get a rough idea of how this works? 

I'm interested in how this might scale with queries with relatively large numbers of vectors in a geo bounding box since it's not very performant in Qdrant which also provides both the geo / vector search functionality.

**Comment by ankane** [comment]
You can use `EXPLAIN ANALYZE` to see how Postgres executes a query (see other online resources for help with the output).

I'd recommend benchmarking it yourself to see how it scales. The two main options for indexing are:

1. Adding an index on the `WHERE` condition (pre-filtering). In this case, pgvector will use exact search.
2. Adding an approximate index on `embedding`, and using a materialized CTE to perform the `ORDER BY`, then applying the `WHERE` condition outside the CTE (post-filtering). In this case, pgvector will use approximate search, but you'll need to make sure `ivfflat.probes` or `hnsw.ef_search` is high enough that enough rows are returned.

**Comment by ckrapu** [comment]
This is really helpful, thanks a ton!
