### ISSUE TITLE
Issue Upgrading from vector 0.4.1 to version 0.5

### ISSUE THREAD

**Issue by christoudias** [pgvector/pgvector#254]
When trying to upgrade from 0.4.1 to version 0.5, we are getting this error: 
```ava=> ALTER EXTENSION vector update TO '0.5';
ERROR:  extension "vector" has no update path from version "0.4.1" to version "0.5"```

The only path forward we can see is to remove the postgres extension (and lose all vector data I assume), and then re-install it. Is there any other path forward? 

For reference, this is on Postgres version 15.2

**Comment by jkatz** [comment]
@christoudias I tested `ALTER EXTENSION vector UPDATE;` and it worked fine. Steps:

1. Installed pgvector v0.4.1 on my local instance. Ran `CREATE EXTENSION vector;`
2. Installed pgvector v0.5.0 on my local instance. Ran `ALTER EXTENSION vector UPDATE;`

**Comment by christoudias** [comment]
Thanks @jkatz . Turns out the issue is that we are on RDS and RDS does not yet support pgvector beyond 0.4.4. We'll be on hold until they do. Thanks again for your help. 
https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html
