### ISSUE TITLE
Performance on pagination: progressively showing closest rows to a particular row

### ISSUE THREAD

**Issue by ucals** [pgvector/pgvector#255]
First of all, congrats for the libray: pgvector is great.

I'm facing a performance problem, and would like to know if it's possible to solve with pgvector, of if I'm going to search for a different solution.

I have a table with ~550k rows with the following structure and indexes:

```sql
CREATE TABLE docs (
    id        VARCHAR(15) PRIMARY KEY,
    title     TEXT NOT NULL,
    embedding vector(768)
);
CREATE INDEX ON docs (id);
CREATE INDEX ON docs USING hnsw (embedding vector_cosine_ops);
```

I want to show the closest docs to a particular doc using pagination, i.e. page 1 from 1-30, page 2 from 31-60, etc.

Doing the standard query is fast, but only retrieves 40 rows, so I cannot get past over page 2.

```sql
-- Page 2 query only shows 10 rows
SELECT *,
       embedding <=>
       (SELECT embedding FROM docs WHERE id = '123') as cs
FROM docs
ORDER BY embedding <=>
       (SELECT embedding FROM docs WHERE id = '123') LIMIT 30 OFFSET 30
```

If I increase `hnsw.ef_search`, the performance erodes pretty fast (doing 3 pages (90) is ok, but the maximum 1000 is pretty slow), and there's no way to incrementally increase this setting without messing with the order of previously shown pages.

Is there a way to progressively show results, page by page, with an acceptable performance? (Ideally for infinite scroll, i.e. no 1000 limit)

Thanks

**Comment by jkatz** [comment]
`hnsw.ef_search` keeps a list of the N number of closest vectors based on distance to the query vector, which comes directly from the HNSW paper (here's a [shorter definition of how it works](https://github.com/nmslib/hnswlib/blob/master/ALGO_PARAMS.md#search-parameters)). What you're describing in terms of increasing `hnsw.ef_search` describes what's expected to happen, i.e. you're able to carry forward more vectors but at a tradeoff of performance.

For `hnsw`, pagination is tricky based on what you identified above -- you'll have to expand `ef_search` based upon the `LIMIT` + `OFFSET` you're looking for.  The `ivfflat` implementation is better suited for it based on how it keeps the full set of `tuples` from all of the lists in memory until you've hit the `LIMIT`/`OFFSET` value, and could work better for this case. For `ivfflat`, the key parameter is `ivfflat.probes`, which typically increases recall with the tradeoff of performance, but based upon the size of your data set, that may be acceptable.

**Comment by ucals** [comment]
@jkatz thank you, indeed ivfflat is much better!

Final question:

The readme says we need to create the index after the table has some data, but does not mention how to update it. Does a `REINDEX` suffice, or should I have to drop and recreate the index every once in a while? (Or nothing is needed anymore?)

Thanks!

**Comment by pashkinelfe** [comment]
@ucals HNSW doesn't need reindex. Ivfflat needs reindex after massive table modification (e.g. after 20% of the table rows are modified or added). 
```
-- Postgres 12+
REINDEX INDEX CONCURRENTLY index_name;
```

**Comment by jkatz** [comment]
@ucals To clarify -- if you make modifications to vectors in your table (add/remove/delete), pgvector does update the `ivfflat` index. As @pashkinelfe states, if you make a lot of modifications, you may need to periodically reindex it to maintain recall.

**Comment by ucals** [comment]
Clear, thanks!
