### ISSUE TITLE
Simple query not using index

### ISSUE THREAD

**Issue by vincenzon** [pgvector/pgvector#257]
I have a table: 

```
CREATE TABLE quotes (
                id int primary key,
                movie_title text,
                movie_line text,
                character text,
                embedding vector(768),
                embedding2 vector(768)  
            );
```

and I create an index on the embedding2 column:

```
CREATE INDEX quotes_embedding2_idx ON public.quotes USING ivfflat (embedding2 public.vector_cosine_ops) WITH (lists='800');
```

If I run the query (using psycopg2 in python):

```
    cur.execute("set ivfflat.probes = 28;")
    cur.execute("""
        select movie_title, movie_line
        from quotes
        order by (embedding2 <=> %s)
        limit 10""", (embedding,))
```

I can tell it isn't using the index (takes the same amount of time before and after creating the index). Using EXPLAIN I can see it is doing a sequential scan.

If, however, I force it to use the index, by adding

```
cur.execute("set enable_seqscan = off;")
```

to the above before the query. It definitely uses the index. Run times are ~4 seconds without the index and ~ 100ms with the index. 

I don't see why postgres isn't using the index, there are none of the typical blockers in the query. 

 I'm guessing it is something dumb on my part, but I am not seeing it. Any help is appreciated.

**Comment by ankane** [comment]
Hi @vincenzon, if you're on pgvector < 0.4.3, it's likely [due to this](https://github.com/pgvector/pgvector#why-isnt-a-query-using-an-index). Otherwise, you can use `EXPLAIN ANALYZE` to see how the costs compare.

**Comment by vincenzon** [comment]
I'm on version 0.5.0 .

Just using EXPLAIN, the cost estimate of the non-index query (not forcing enable_seqscan to off):
```
Limit  (cost=31112.86..31114.03 rows=10 width=86)
```
Forcing it to use the index: 
```
  ->  Index Scan using quotes_embedding2_idx on quotes  (cost=39402.18..107870.07 rows=894000 width=86)
```

so I guess that "explains" why it doesn't use the index. I wonder why the cost estimate is so high though since in reality using the index is much faster. 

Any suggestions on how to dig deeper?

**Comment by jkatz** [comment]
@vincenzon What is the dimensionality of the vectors?

**Comment by vincenzon** [comment]
The vectors have dimension 768.

**Comment by jkatz** [comment]
@vincenzon (Should have also asked for the size of the data set too, i.e. # of rows).

If you're using the default storage (which it looks like in the above), your vector data is being TOASTed, which affects the costs. PostgreSQL sees fewer pages in the table, so it will look as if doing the sequential scan is cheaper.

If you're frequently accessing the vectors, you can consider moving to `PLAIN` storage, which will store them inline:

```sql
ALTER TABLE quotes ALTER COLUMN embedding SET STORAGE PLAIN;'
VACUUM FULL quotes;
ANALYZE quotes;
```

You can also consider lowering the `random_page_cost` on the queries, which should help PostgreSQL to favor an index scan on the queries with higher probes.

**Comment by vincenzon** [comment]
There are 840K rows in the table. I changed the storage to PLAIN and indeed, now postgres uses the index without forcing it to via `enable_seqscan = off`. 

I don't think it should matter, but could the fact that all this is running in a docker container confuse postgres about the relative costs of file reads? I guess the other thing that may be relevant is that everything is on an nvme disk. 

My take away is that index usage may need coercing when the vector types are in play. That is a new thing to me, but maybe I just don't get out enough. 

I'll leave the issue open for the weekend in case anyone had any additional thoughts. Thanks for helping to sort this out, I learned a few things.

**Comment by jkatz** [comment]
This isn't related to the runtime environment -- this has to do with how PostgreSQL costs values that are TOASTed to determine if it should perform a sequential scan or an index scan for the lookup. [Here is an example][1] of how that plays into calculating how many parallel workers to use for a scan; it's a similar case.

Likely, we may need to do some work upstream that considers the true cost of scanning values in a TOAST table if they're part of the scan path, given that's a coming case with vectors. That may help overall with setting the appropriate cost on when to perform an index scan vs. a sequential scan when the large values are actually in the hot path.

[1]: https://www.postgresql.org/message-id/ad8a178f-bbe7-d89d-b407-2f0fede93144%40postgresql.org
