### ISSUE TITLE
Dynamically calculating the number of lists for reindexing

### ISSUE THREAD

**Issue by ir2718** [pgvector/pgvector#258]
I'm working on a system which scrapes articles in real time and I would like to save embeddings of these articles to do semantic search later. Since the scraping is done in real time, my issue is that the number of rows in the table constantly changes, and since a good estimate is to use `sqrt(rows)` for the number of lists, the estimated number of lists often changes. The idea to solve this was using a cron job which would reindex the database every few hours or so.

The problem arises when I try to combine the index creation with a subquery for calculating the number of lists.
```
CREATE INDEX CONCURRENTLY replacement_index ON similarity USING ivfflat (embedding vector_ip_ops) WITH (lists = 
    (SELECT CAST(SQRT(COUNT(id)) AS INTEGER) FROM similarity)
);
```
The query above outputs a syntax error:
```
ERROR:  syntax error at or near "("
LINE 2:     (SELECT CAST(SQRT(COUNT(id)) AS INTEGER) FROM similarity...
```

I tried setting a predefined value for the number of lists instead of the subquery, as well as trying out if the subquery itself is valid:
```
CREATE INDEX CONCURRENTLY replacement_index ON similarity 
USING ivfflat (embedding vector_ip_ops) WITH (lists = 183);

SELECT CAST(SQRT(COUNT(id)) AS INTEGER) FROM similarity;
```
Both of which works fine and doesn't show any syntax errors.

Finally, I would like to ask, how can one achieve this kind of behavior?

**Comment by ankane** [comment]
Hi @ir2718, you'll need to split it into two queries: one to count the rows / calculate the number of lists and another to create the index.

**Comment by jkatz** [comment]
@ir2718 Alternatively, you may want to try to use the `hnsw` index type, which may be helpful in your case when dealing with continuous updates.

**Comment by ir2718** [comment]
@ankane I'm not sure I understand. Do you mean calculating the number of lists using the `WITH` keyword and then using a subquery to set the number of lists?

@jkatz Thanks, I will check it out.

**Comment by ankane** [comment]
No, it's not possible to do in a single statement with Postgres (see the [CREATE INDEX](https://www.postgresql.org/docs/current/sql-createindex.html) syntax), but you can use two separate ones. For instance, in Python:

```python
lists = conn.execute('SELECT CAST(SQRT(COUNT(id)) AS INTEGER) FROM similarity').fetchone()
conn.execute('CREATE INDEX CONCURRENTLY replacement_index ON similarity USING ivfflat (embedding vector_ip_ops) WITH (lists = %d)' % lists)
```
