### ISSUE TITLE
Creating index error:  access method "hnsw" does not exist

### ISSUE THREAD

**Issue by leo-mangold** [pgvector/pgvector#264]
I'm trying to create an `hnsw` index for my embeddings table, but I get the following error:
```
CREATE INDEX ON search.goods_codes_en_1536 USING hnsw (embedding vector_ip_ops);
ERROR:  access method "hnsw" does not exist
```
This seams like an error where it can't find certain parts of pg-vector but creating a index with `ivfflat` works perfectly:
```
CREATE INDEX ON search.goods_codes_en_1536 USING ivfflat (embedding vector_ip_ops) WITH (lists = 100);
```

Thanks for the help in advance

**Comment by ankane** [comment]
Hi @leo-mangold, this likely means the current database doesn't have 0.5.0 installed. You can check with:

```sql
SELECT extversion FROM pg_extension WHERE extname = 'vector';
```

https://github.com/pgvector/pgvector#upgrading

**Comment by leo-mangold** [comment]
Thank you. I also thought about that half an hour ago and since then tried to install the extension with the newer version since the update command did not work...
Now I tried the update statement (`ALTER EXTENSION vector UPDATE;`) again and it worked perfectly and my index also works. 🤷
So my problem is solved thanks.
