### ISSUE TITLE
Add support for `TYPMOD_OUT` to report the vector length

### ISSUE THREAD

**Issue by kareldonk** [pgvector/pgvector#270]
Currently the vector type does not report its length which causes some issues in certain cases. For example when creating database diffs or migrations. You can have a script that creates a vector column of size 3 in a table, and upon checking for changes, the database will just report `vector` as the type instead of `vector(3)` (you can also see this in DBeaver for example when viewing the table column info). Automatic migrations scripts will then take this as a change in the type/size of the column and generate up and down scripts to do database upgrades.

As far as I could see, the issue lies in missing support for the `vector_typmod_out` function. As per [docs](https://www.postgresql.org/docs/current/sql-createtype.html):

> The optional type_modifier_input_function and type_modifier_output_function are needed if the type supports modifiers, that is optional constraints attached to a type declaration, such as char(5) or numeric(30,2). PostgreSQL allows user-defined types to take one or more simple constants or identifiers as modifiers. However, this information must be capable of being packed into a single non-negative integer value for storage in the system catalogs. The type_modifier_input_function is passed the declared modifier(s) in the form of a cstring array. It must check the values for validity (throwing an error if they are wrong), and if they are correct, return a single non-negative integer value that will be stored as the column “typmod”. Type modifiers will be rejected if the type does not have a type_modifier_input_function. The type_modifier_output_function converts the internal integer typmod value back to the correct form for user display. It must return a cstring value that is the exact string to append to the type name; for example numeric's function might return (30,2). It is allowed to omit the type_modifier_output_function, in which case the default display format is just the stored typmod integer value enclosed in parentheses.

There is a [`vector_typmod_in`](https://github.com/pgvector/pgvector/blob/b247b688a8ef56103b2dea1f9dd53a87b27696b6/src/vector.c#L357) function but no `vector_typmod_out`. Also seen [here](https://github.com/pgvector/pgvector/blob/b247b688a8ef56103b2dea1f9dd53a87b27696b6/sql/vector.sql#L26).

It would be nice if you'd add support for `TYPMOD_OUT` .

**Comment by ankane** [comment]
Hi @kareldonk, it shouldn't be needed. From the excerpt above:

> It is allowed to omit the type_modifier_output_function, in which case the default display format is just the stored typmod integer value enclosed in parentheses.

**Comment by kareldonk** [comment]
Hi @ankane were you able to verify that the `vector` type actually does show its length? If you look at it in DBeaver for example, here's what you see (the vector length should have been reported as being 1536, so i would expect to see `vector(1536)`):

![image](https://github.com/pgvector/pgvector/assets/12107205/1ef6066c-940d-48cc-93cb-241ae3a9efd3)

In the source the length is also not reported:

![image](https://github.com/pgvector/pgvector/assets/12107205/354ec8b0-be09-497c-a2e2-1f62ba804deb)

For other types like `varchar`, you see the length reported like this:

![image](https://github.com/pgvector/pgvector/assets/12107205/130fa303-0ee8-4a88-8b39-1496a32293cc)

![image](https://github.com/pgvector/pgvector/assets/12107205/f78a37a3-47d6-4538-819c-eec0232382d8)

It could be that the cause of the issue is something else but I suspect it is because of what I originally reported.

**Comment by kareldonk** [comment]
Very strange, so far I've used typeorm, mikro-orm and DBeaver and none of them are able to get the size.
