### ISSUE TITLE
All distance metrics (cosine, inner, l2) are retrieving same results every time for a particular input question?

### ISSUE THREAD

**Issue by himsgpt** [pgvector/pgvector#271]
I have created an index like this:
```
if query_operator == "<->":
        index_method = "vector_l2_ops"
    elif query_operator == "<#>":
        index_method = "vector_ip_ops"
    elif query_operator == "<=>":
        index_method = "vector_cosine_ops"
cur.execute(f'CREATE INDEX lg_index ON {table_name} USING ivfflat ({embedding_column } {index_method}) WITH (lists = {num_lists});')
```

Now when i retrieve the documents using a **query_operator = "<=>" or "<->", i get same results for a particular input question provided.** 
```
query_embedding = model.encode(question)
`cur.execute(f"SELECT x,y FROM {table_name} ORDER BY embedding_column {query_operator} %s LIMIT 5", (query_embedding,query_embedding,))`
```

**I have tried reindexing when changing from one operator to another but it doesn't work. Please help me identify the catch here?**

**Comment by ankane** [comment]
Hi @himsgpt, if vectors have length 1, all three metrics will have the same ordering. https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use

**Comment by himsgpt** [comment]
The **vectors have length 768**. I don't seem to understand why this could be happening. Could this be because of indexing, i tried setting **sequential scan on** but it still gives me same result.
