### ISSUE TITLE
Listing the size of already created index

### ISSUE THREAD

**Issue by ezalos** [pgvector/pgvector#276]
Hello, I'm looking how to list the index already created with pg_vector, to find which columns they index on which tables, and the index size.

For example, if an index was created with this command :
```sql
CREATE INDEX ON table_1
    USING ivfflat (column_embedding vector_cosine_ops)
    WITH (lists = 2800);
```
I would like to retrieve this index size.

**Comment by jkatz** [comment]
You can use the `pg_relation_size` function:

```sql
SELECT pg_relation_size('table_1_column_embedding_idx');
```

You can get prettier output using `pg_size_pretty` along with it:

```sql
SELECT pg_size_pretty(pg_relation_size('table_1_column_embedding_idx'));
```
