### ISSUE TITLE
pg_vector stores truncated vector values

### ISSUE THREAD

**Issue by Tlaloc-Es** [pgvector/pgvector#277]
Hello, I'm using pg_vector to try to store vgg-face vectors, which are vectors of approximately 2000 float values, something like this:
```0.8351235389709473, 3.1464266777038574, 2.8287644386291504, 0.12804853916168213, 8.0096435546875, 1.05048406124115, 8.818521499633789, 1.7313957214355469, 2.7108941078186035, -2.693708658218384, 11.822422981262207, 2.9562716484069824, 4.272169589996338, 0.103035569190979, 4.3717241287231445, -2.0741119384765625, 3.6317007541656494, 5.009196758270264, -6.160808563232422, 1.5311558246612549, -2.970468044281006, 5.072583198547363, -2.1009788513183594, 8.17024993```

The problem is that when I save the value, it gets truncated and doesn't store all the decimals, causing it to lose a lot of precision compared to another database I used before, like annoy. Is there a way to store all the decimals?

Thank you.

**Comment by ankane** [comment]
Hi @Tlaloc-Es, check out #182.
