### ISSUE TITLE
Correct Way to Detect pgvector vector Type for Trino?

### ISSUE THREAD

**Issue by nathanwilk7** [pgvector/pgvector#278]
Could I ask if you have thoughts on the "correct" way to detect columns of pgvector's vector type for a given table?

I ask because I'm looking into improving pgvector support for [Trino](https://github.com/trinodb/trino). Currently, Trino does not have first-class support for reading pgvector's vector type (the workaround is to convert the vector into a string, and then parse that string into JSON inside Trino, which is obviously slow). Trino does have first-class array support right now, but only for built-in postgres arrays, not for user-defined types like vector. I'm not very familiar with the way that Postgres exposes information on user-defined types, but given my investigation so far I've listed my understanding/questions below.

The first thing I need to explore is how to pull out all vector columns from a given table. I have found the following two approaches (given the [README table](https://github.com/pgvector/pgvector/tree/master#getting-started) `items` w/ vector col `embedding`):

```sql
SELECT attname, typname, typcategory, typinput, typoutput, typreceive, typsend, typmodin
FROM pg_attribute att
  JOIN pg_type attyp ON att.atttypid = attyp.oid
  JOIN pg_class tbl ON tbl.oid = att.attrelid
  JOIN pg_namespace ns ON tbl.relnamespace = ns.oid
WHERE ns.nspname = 'public'
and att.attname = 'embedding'
AND tbl.relname = 'items';

-- outputs

  attname  | typname | typcategory | typinput  | typoutput  | typreceive  |   typsend   |     typmodin     
-----------+---------+-------------+-----------+------------+-------------+-------------+------------------
 embedding | vector  | U           | vector_in | vector_out | vector_recv | vector_send | vector_typmod_in
(1 row)
```

Or

```sql
SELECT column_name, data_type, udt_name
FROM information_schema.columns
WHERE table_name = 'items'
AND table_schema = 'public'
and column_name = 'embedding';

--outputs

 column_name |  data_type   | udt_name 
-------------+--------------+----------
 embedding   | USER-DEFINED | vector
(1 row)
```

I am interested in your thoughts on which of the above queries (or other ideas) you would use to find all the vector columns for a given table in a way that you expect to be as future-proof as possible if you add new vector types (eg quantized/bit vectors) in the future.

Another question I have now is how to disambiguate between a user-defined `vector` type from the `pgvector` extension vs some other user-defined `vector` type.

**Comment by jkatz** [comment]
@nathanwilk7 `vector` supports a cast to a PostgreSQL`real[]` today (see https://github.com/pgvector/pgvector/blob/master/sql/vector.sql#L140) -- does casting it into a `real[]` simplify your use-case?

Pulling the `attname` associated with a `typname` will find the natively stored `vector` columns, which would let you cast it into an array.

**Comment by nathanwilk7** [comment]
Thanks for the pointer. I'll try implementing it per your suggestion and reach out here again if I hit any blockers
