### ISSUE TITLE
Understanding IvfflatIndex lists

### ISSUE THREAD

**Issue by folprates** [pgvector/pgvector#279]
Using the [python Langchain package](https://python.langchain.com/docs/integrations/vectorstores/pgvector), on the PostgresSQL database, we have one single table with multiple embeddings. Considering the logic to calculate the number of probes (`` `rows / 1000` for up to 1M rows and `sqrt(rows)` for over 1M rows``), should I consider the total number of rows of the table or the number of rows per each embedding?

**Comment by ankane** [comment]
Hi @folprates, it's the number of rows in the table (or if using [partial indexing](https://www.postgresql.org/docs/current/indexes-partial.html), the number of rows in the partial index).
