### ISSUE TITLE
question: what does the m parameter mean in hnsw

### ISSUE THREAD

**Issue by david-gang** [pgvector/pgvector#283]
In the readme it is explained:

```
m - the max number of connections per layer (16 by default)
```

What are the pros and cons to set a higher or lower m? what could be the incentive to touch it?

**Comment by raoufchebri** [comment]
`m` impacts the following:
- the index build time: the higher the value of `m` the extended it will take for the index to build
- recall (accuracy): a few number of connections `m` might result in a smaller recall
