### ISSUE TITLE
how to use numeric[] of more than 2000 dimensionality?

### ISSUE THREAD

**Issue by Tlaloc-Es** [pgvector/pgvector#284]
In reference to https://github.com/pgvector/pgvector/issues/277

Hello, thanks @ankane. I checked it, and I have new troubles again.

After filling the database with the following field:

`embedding numeric[],`

and vectors of length 2660,

I tried to create the index:

`CREATE INDEX ON vectors_vgg USING ivfflat (CAST(embedding AS vector(2622)) vector_l2_ops) WITH (lists = 1);`

But I got the error: "column cannot have more than 2000 dimensions for ivfflat index." I tried again with [HNSW], but this doesn't support numeric[].

Is there any other way to do this?

**Comment by jkatz** [comment]
Techniques for indexing vectors greater than 2000 dimensions is documented here:

https://github.com/pgvector/pgvector#what-if-i-want-to-index-vectors-with-more-than-2000-dimensions

Additionally, there are several [roadmap items](https://github.com/pgvector/pgvector/issues/27) that would help increase the limit, including quantization techniques.
