### ISSUE TITLE
palloc0 memory doesn't free?

### ISSUE THREAD

**Issue by JackTan25** [pgvector/pgvector#286]
at https://github.com/pgvector/pgvector/blob/master/src/hnswinsert.c#L142, you palloc0 an etup, but I can't find out where you free it?

**Comment by ankane** [comment]
Hi @JackTan25, it's freed when the memory context [is deleted](https://github.com/pgvector/pgvector/blob/8d7abb659070259e78f5c0974dde26c9e1cda8d3/src/hnswinsert.c#L579).

[More info](https://www.cybertec-postgresql.com/en/memory-context-for-postgresql-memory-management/) on memory contexts.

**Comment by JackTan25** [comment]
thanks very much
