### ISSUE TITLE
Install failure with 0.5 + Ubuntu 22.04

### ISSUE THREAD

**Issue by matthewrobertbell** [pgvector/pgvector#287]
i am attempting to setup postgres with pgvector in ubuntu 22.04 on github actions. I'm getting a weird error that's also happening on a fresh 22.04 vm on linode.

```Error: could not open extension control file "/usr/share/postgresql/14/extension/pgvector.control": No such file or directory```

From the output of "make install":

``` /usr/bin/install -c -m 644 .//vector.control '/usr/share/postgresql/14/extension/'```

note "pgvector.control" vs "vector.control"

Is this a bug in pgvector with the .control file not being named correctly or am I missing something? I've installed this fine on debian 12 before.

```apt-get install -y postgresql postgresql-contrib postgresql-server-dev-14
sudo -u postgres psql -c "CREATE DATABASE test;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO postgres;"
```

I then followed the standard pgvector instructions.

**Comment by ankane** [comment]
Hi @matthewrobertbell, from the error message, it looks like you're running `CREATE EXTENSION pgvector;` instead of `CREATE EXTENSION vector;`.
