### ISSUE TITLE
@ankane meeting the same problem now with seemingly a call to a deprecated sdk (MacOSX11.3.sdk)

### ISSUE THREAD

**Issue by jeanbapt** [pgvector/pgvector#289]
@ankane meeting the same problem now with seemingly a call to a deprecated sdk (MacOSX11.3.sdk)
I run on Mac M1 Pro MacOS ventura. I have installed Postgres.App (15 and 16). 
When using make (and also the flagged variants), I get a 

```
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]
In file included from src/hnsw.c:1:
In file included from /Library/PostgreSQL/15/include/postgresql/server/postgres.h:46:
/Library/PostgreSQL/15/include/postgresql/server/c.h:59:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
'''
```
I tried reinstalling xcode command line tools, using xcode-select etc. with no success.
Do I need to download the deprecated 11.3 sdk ? 

Thank you 🙏

_Originally posted by @jeanbapt in https://github.com/pgvector/pgvector/issues/191#issuecomment-1740741797_

**Comment by jeanbapt** [comment]
I confirm that by downloading the deprecated sdk from https://github.com/phracker/MacOSX-SDKs, it compiles and it solves the problem. It might be a work around for now. Please tell me when the reference is updated.

**Comment by ankane** [comment]
fwiw, that flag comes from your Postgres installation, so the problem would be there.

**Comment by ideavision** [comment]
Any update or news about:
```
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]
In file included from src/hnsw.c:1:
In file included from /Library/PostgreSQL/15/include/postgresql/server/postgres.h:46:
/Library/PostgreSQL/15/include/postgresql/server/c.h:59:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
'''
```

**Comment by ankane** [comment]
See [this section](https://github.com/pgvector/pgvector?tab=readme-ov-file#missing-sdk) of the docs.

**Comment by saaspeter** [comment]
I tried to reinstall xcode command line tool, but there is no 11.3.sdk, the minimum sdk version is: 12.1.sdk, obviously the 11.3.sdk is an old sdk version. Should the make file do some update for the latest command line tool?
