### ISSUE TITLE
bug? - unexpected data beyond EOF in block

### ISSUE THREAD

**Issue by mmisiewicz** [pgvector/pgvector#29]
While using `pgvector` on a table with frequent updates / inserts on Postgres 14 on macOS on Intel, I've been encountering this error frequently on `UPDATES`:

```
psycopg2.errors.InternalError_: unexpected data beyond EOF in block 1638807 of relation base/24349058/41425278
HINT:  This has been seen to occur with buggy kernels; consider updating your system.
```

Looking through the PostgreSQL mailing list about this error, most posts pertain to linux kernels from the ~2010s, and don't seem applicable. 

I've run `VACUUM FULL` on the table a few times, as well as completely dumping the table using `pg_dump`, deleting the table and recreating. The table is ~340 GiB and there is also a 13 GiB IVFFlat index referencing one of the `vector(768)` columns. 

Wondering if there might be a bug in how large vectors are stored. 

My table, notably, contains columns of types:
- `vector(768)`
- `vector(768)[]`
- `character varying[]`
- `character varying` 

And each row is easily around 2 or 3 MiB.

**Comment by ankane** [comment]
Hey @mmisiewicz, it sounds like there may be a bug, but I'm not able to reproduce. Can you update this script (or create your own) to reproduce:

```python
import psycopg

conn = psycopg.connect(dbname='pgvector_repro')
conn.autocommit = True

server_version = conn.execute('SHOW server_version').fetchone()[0]
print('Postgres version:', server_version)

conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
version = conn.execute("SELECT extversion FROM pg_extension WHERE extname = 'vector'").fetchone()[0]
print('pgvector version:', version)

conn.execute('DROP TABLE IF EXISTS tst')
conn.execute('CREATE TABLE tst (i int4 PRIMARY KEY, v vector(768), v2 vector(768)[], vc varchar, vc2 varchar[])')
conn.execute("INSERT INTO tst (i, v, vc) SELECT i, (SELECT array_agg(random()) FROM generate_series(1, 768)), repeat('hello', 10000) FROM generate_series(1, 10000) i")
conn.execute('CREATE INDEX ON tst USING ivfflat (v vector_l2_ops)')

for i in range(1, 10000):
    conn.execute("UPDATE tst SET v = (SELECT array_agg(random()) FROM generate_series(1, 768)), v2 = ARRAY[v, v, v, v, v], vc = repeat('goodbye', 10000), vc2 = ARRAY[vc, vc, vc, vc, vc] WHERE i = (random() * 10000)::int")

print('Success')
```

(uses [psycopg3](https://www.psycopg.org/psycopg3/docs/basic/install.html))

**Comment by mmisiewicz** [comment]
TIL about psycopg3! Cool! I have psycopg2 so I ran some commands manually in psql:

```
pgvector_repro=# show server_version;
-[ RECORD 1 ]--+-----
server_version | 14.4

Time: 0.485 ms
pgvector_repro=# SELECT extversion FROM pg_extension WHERE extname = 'vector';
-[ RECORD 1 ]-----
extversion | 0.2.6

Time: 1.940 ms
```

I also was not able to repro with the script:

```
In [9]: cur.execute("DROP TABLE IF EXISTS tst")
   ...: cur.execute(
   ...:     "CREATE TABLE tst (i int4 PRIMARY KEY, v vector(768), v2 vector(768)[], vc varchar, vc2 varchar[])"
   ...: )
   ...: cur.execute(
   ...:     "INSERT INTO tst (i, v, vc) SELECT i, (SELECT array_agg(random()) FROM generate_series(1, 768)), repeat('hello', 10000) FROM generate_series(1, 10000) i"
   ...: )
   ...: cur.execute("CREATE INDEX ON tst USING ivfflat (v vector_l2_ops)")
   ...:

In [10]: for i in range(1, 10000):
    ...:     cur.execute(
    ...:         "UPDATE tst SET v = (SELECT array_agg(random()) FROM generate_series(1, 768)), v2 = ARRAY[v, v, v, v, v], vc = repeat('goodbye', 10000), vc2 = ARRAY[vc, vc, vc, vc, vc] WHERE i = (random() * 10000)::int"
    ...:     )
    ...:
    ...: print("Success")
Success
```

I should also add:
- I'm on pgvector `56cb5f35036e0585f849454b0093cbc2d65d6015` 
- compiled from source on macOS 11.6.7
- using Postgres from Homebrew
- with Xcode: 
```
➜  clang --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Another data point I thought of, and this might be the key, is that several times in writing that big chonky table, my Postgres server process crashed due to OOM until I got my memory settings tuned correctly. Also, the table is stored on an external SSD (apfs formatted) that I unplugged a few times by accident. 

All of this to say is that there have been a few WAL recoveries on said table. This might be where the bug is, perhaps rows with pgvector (or arrays of vectors) are not recovering correctly in the WAL recovery procedure. 

In general, when I've been encountering these warnings, dropping the affected rows works, and I don't mind the data loss particularly (easy for me to recreate, I'm storing embeddings of texts, so I can just embed again) but I'd definitely like to get to the bottom of it.

**Comment by nikolain** [comment]
I have a very similar case as well, "unexpected data beyond EOF in block 8425154 of relation base/33074/34341" that happens consistently after the following sequence
1. build a table, no index - everything works fin, just slow
2. build an vector index - it builds and using it accelerates the search.
3. Try to update the data in the table (specifically, delete old and insert new rows as part of the transaction) - one gets an error.

The table involved has about 25 million rows, and I get it extremely consistently (I've rebuild the DB twice just for fun). If you care, I can share a copy with you.

**Comment by ankane** [comment]
Hey @nikolain, thanks for reporting as well. I'm still having trouble reproducing, but if you have time, can you try updating this script to reproduce?

```python
import psycopg

conn = psycopg.connect(dbname='pgvector_repro')
conn.autocommit = True

server_version = conn.execute('SHOW server_version').fetchone()[0]
print('Postgres version:', server_version)

conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
version = conn.execute("SELECT extversion FROM pg_extension WHERE extname = 'vector'").fetchone()[0]
print('pgvector version:', version)

conn.execute('DROP TABLE IF EXISTS tst')
conn.execute('CREATE TABLE tst (i bigserial PRIMARY KEY, v vector(768))')

print('Inserting data')
conn.execute("INSERT INTO tst (v) SELECT (SELECT array_agg(random()) FROM generate_series(1, 768)) FROM generate_series(1, 100000) i")

print('Creating index')
conn.execute("SET maintenance_work_mem = '1GB'")
conn.execute('CREATE INDEX ON tst USING ivfflat (v vector_cosine_ops)')

print('Running queries')
for i in range(1, 10000):
    conn.execute("UPDATE tst SET v = (SELECT array_agg(random()) FROM generate_series(1, 768)) WHERE i = (SELECT (random() * 100000)::int)")

print('Success')
```

(requires [psycopg3](https://www.psycopg.org/psycopg3/docs/basic/install.html))

**Comment by ankane** [comment]
Was able to reproduce with concurrent connections. Will see what's going on.

**Comment by mmisiewicz** [comment]
That makes a ton of sense, in my case I had many concurrent connections as well, which was not tested in the script above.

**Comment by ankane** [comment]
The issue was it was committing the pointer to the new page before the new page was committed, causing concurrent inserts to fail. Now they are committed together. Will push out a new release shortly.

Thank you both for reporting!

**Comment by Kedao98** [comment]
Same problem. Before creating index on embedding, I insert data with no error. After created index, inserting data with 30 concurrency and the error occurs occasionally.

**Comment by ankane** [comment]
Hey @Kedao98, please make sure you have the latest version installed (0.2.7). If that doesn't fix it, please create a new issue with more details about your setup (OS, Postgres version, pgvector installation method) and the queries causing the error.

**Comment by Kedao98** [comment]
> Hey @Kedao98, please make sure you have the latest version installed (0.2.7). If that doesn't fix it, please create a new issue with more details about your setup (OS, Postgres version, pgvector installation method) and the queries causing the error.

thx for your reply! It works perfectly on 0.2.7
