### ISSUE TITLE
PageSize Setting Problem

### ISSUE THREAD

**Issue by JackTan25** [pgvector/pgvector#290]
pgvector advise the dimensions up to 16,000, and so the size of a vector is (4 * 16000 + 8) = 64008 bytes, but pg's default page size is 8K, so in this case, only one vector will overflow, what's the advice?

**Comment by jkatz** [comment]
Vectors that exceed the 8KB limit (which really, is vectors that exceed `toast_tuple_target`) are stored in a [TOAST table](https://www.postgresql.org/docs/current/storage-toast.html).
