### ISSUE TITLE
Multi-column index

### ISSUE THREAD

**Issue by tysonzero** [pgvector/pgvector#293]
Are there any plans to support indexes where one column is a vector and one (or more) columns is a standard btree-able type?

We have a variety of different clients/projects that share a data table with a pgvector column and distinguished from one another via a uuid foreign key to the client/project.

It seems impractical to do the partial index approach because it'd involve creating way too many indices, and they'd have to be created and removed dynamically at run time which is more than a little awkward.

We could create a global index, but it's unclear if it'll even work all that well given how much of the index is not being used for any single query.

**Comment by jkatz** [comment]
There is a discussion of different approaches to this here: https://github.com/pgvector/pgvector/issues/259

**Comment by ankane** [comment]
You can also currently use partitioning for this: https://github.com/pgvector/pgvector#filtering

**Comment by tysonzero** [comment]
@ankane sadly partitioning is not practical for our use case as there are too many different clients/projects and they change quite dynamically.

Thanks @jkatz for the link
