### ISSUE TITLE
Docker images for other Postgres versions

### ISSUE THREAD

**Issue by mertalev** [pgvector/pgvector#296]
Hi! I'm wondering if it would be possible for you to release images for Postgres versions other than 15. The use-case is for a self-hosted app that uses Postgres 14 to be able to easily adopt pgvector without requiring its users to make a manual database upgrade. 

As always, thank you for making and maintaining this project!

**Comment by ankane** [comment]
Hi @mertalev, I don't plan to release them right now, but check out [this section](https://github.com/pgvector/pgvector#docker) of the readme for how to build them.

**Comment by jrasm91** [comment]
> I don't plan to release them right now

Does this imply you may release them in the future? Is there a particular reason why you would not publish them right now? It seems quite trivial to update the GitHub actions to build and push multi-arch and multi-version images for the extension.

**Comment by etnoy** [comment]
Another question would be: would you accept a PR that adds github action steps for other versions?

**Comment by bo0tzz** [comment]
Hi @ankane, I put together a build for pgvector images with different postgres versions over at https://github.com/bo0tzz/pgvector-images. If you're interested, I would be happy to move that repository over to the pgvector organisation or to contribute that build process in some other way. (And if you would like to see changes to it, that is of course no problem.) Please let me know what you think :)

**Comment by ramsrib** [comment]
**Another one:**
https://hub.docker.com/r/ramsrib/pgvector
https://github.com/ramsrib/pgvector

**Comment by ankane** [comment]
These are now released as part of the project, fwiw: https://github.com/pgvector/pgvector?tab=readme-ov-file#docker-1
