### ISSUE TITLE
ERROR: access method "hnsw" does not  exist

### ISSUE THREAD

**Issue by dudu78** [pgvector/pgvector#297]
Hello,
(sorry I can't post issue on the pgvector-go repo)

I am building pgvector with ent exactly like in the example: 

`func (Insight) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("embedding").
			Annotations(
				entsql.IndexType("hnsw"),
				entsql.OpClass("vector_l2_ops"),
			),
	}
}`

`field.Other("embedding", pgvector.Vector{}).
			SchemaType(map[string]string{
				dialect.Postgres: "vector(384)",
}),`

When doing `go generate ./ent` it generates correctly but when I do the migration/creation :

`ent.Schema.Create(context.Background(),
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
	); errEntMigration != nil {
		logger.Error("Failed creating schema resources: %v", errEntMigration)
}`

it gives me this error :

```
time=2023-10-09T00:55:35.387+02:00 level=ERROR msg="Failed creating schema resources: %v" !BADKEY="sql/schema: create index \"insight_embedding\" to table: \"insights\": ERROR: access method \"hnsw\" does not exist (SQLSTATE 42704)"
```

do you have any Idea how to fix that ?

**Comment by jkatz** [comment]
You need to run pgvector 0.5.0 or later.
