### ISSUE TITLE
Need tips on partial indexing

### ISSUE THREAD

**Issue by dudu78** [pgvector/pgvector#298]
I am using the HNSW to query from the table **insight**, according to my data architecture, each insight belongs to one **space**, so each time I am querying insights, it is always with the mention `WHERE space = "id1"`
do you think I must create a partial indexe for each space ?

**Comment by jkatz** [comment]
It depends how many vectors are in a given space. If a query like `WHERE space = 'id1'` returns 10 vectors, you don't need an index on it as a sequential scan would be faster. However, if it returns 50,000 vectors, you would benefit from a partial index.

**Comment by dudu78** [comment]
Thank you ! That what I wanted to know
