### ISSUE TITLE
pgvector-php

### ISSUE THREAD

**Issue by Siegi96** [pgvector/pgvector#30]
Do you plan to build a pgvector libraray for PHP?

**Comment by ankane** [comment]
Hey @Siegi96, just pushed a pgvector-php repo with a simple example of how to use it. We could probably add integrations with Laravel or other frameworks as well.

**Comment by ankane** [comment]
Added an example for Laravel, and will likely turn it into a package to make things even easier. Let me know if you use another framework or have any feedback.

**Comment by Siegi96** [comment]
Wow, that was fast, thank you so much! Keep up the awsome work!! :)
