### ISSUE TITLE
HNSW | Slow Build Times For DB With 10m Vectors

### ISSUE THREAD

**Issue by jordanparker6** [pgvector/pgvector#300]
I have a HNSW index build that is taking +24hrs for a DB with 10M vectors of shape 768. 

The DB is running in GCP with pgvector 0.5.0 on a 4 CPU and 16 GB instance. CPU utilisation is hovering around 10%.

```
SET max_parallel_maintenance_workers = '8';
SET maintenance_work_mem = '1GB';
CREATE INDEX "documentChunk_hnsw_index" ON "DocumentChunk" 
USING hnsw (embedding vector_ip_ops);
```

Do you have any suggestions on how to speed this up and use more cores? 

Would the only resolutions be to change `m` and `ef_construction`? 

Also, to get the most of pgvector at query time, i need to set the `shared_buffers` to be greater than the hnsw index size and then `prewarm`? I think in my case that would be a 7GB * 10 = 70GB of RAM.

Happy to contribute to the README.md on practical performance configurations as I think it would be useful.

**Comment by ankane** [comment]
Hi @jordanparker6, I'd recommend setting `maintenance_work_mem` much higher for the session (you'll see a notice when the index build no longer fits into memory and becomes slow). You could also create the index when the table is empty and insert the data in-parallel (w/ custom scripts).

Also, note that 0.5.1 speeds up HNSW builds significantly, and parallel index builds are planned for the future.

For queries, having enough memory for the entire index (and more) should be best for performance, and I'd recommend starting with general advice for shared buffers (25% of total memory). The index should warm up as it's used, but you can use pg_prewarm to eager load it.

**Comment by jimmythepad** [comment]
Hey @jordanparker6 and @ankane, wondering if you gained any other insights on this?

We are facing a similarly long build time (24hrs) with a smaller vector and size (3.8m vectors with dimension 128) on GCP:

8cpu 52gb
postgres 14
using the built in cloudsql - 0.6.0 i think

(m = 100, ef_construction = 1000);

SET max_parallel_maintenance_workers = 7; -- plus leader
SET maintenance_work_mem = '8GB';

**Comment by jkatz** [comment]
0.6.2 included an improvement to locking that will speed up your build.
