### ISSUE TITLE
How does the IVF-FLAT index search work when "where" clause is provided in SQL query?

### ISSUE THREAD

**Issue by snehith26** [pgvector/pgvector#301]
Hi ALL,

We've a Postgres table where one of the column is of vector datatype. We've created IVF-FLAT index on it (without using partial indexing). Command used - "CREATE INDEX ON <TABLE_NAME> USING IVFFLAT (<VECTOR_COLUMN_NAME> VECTOR_IP_OPS) WITH (LISTS = <N>);"

Now, when I run SELECT query with "where" clause and LIMIT as 10 on this table to get the inner product with a query embedding vector, when will the indexing be used?
(1) Will the where clause is executed first to retrieve the rows and then IVFFLAT indexing is used to return the top-10 rows? Or
(2) First IVFFLAT index search is performed and then the where clause filter is applied on the results to get the top-10 results?

Thanks in advance!!

**Comment by fanfuxiaoran** [comment]
@snehith26  IVFFLAT index search is performed first and then the where clause filter applied to the results, but it can not guarantee to return ten items.   For more details, you can check the issue at https://github.com/pgvector/pgvector/issues/263

**Comment by jkatz** [comment]
If you'd like a deep dive into this topic, please see: https://github.com/pgvector/pgvector/issues/259

**Comment by snehith26** [comment]
@fanfuxiaoran Thanks for the reply. In the other issue that you pointed above, it was mentioned that there were some plans/POCs to index based on (embedding, category_id) pair. Is it actively being looked at? We are using pgvector as our vector database and our use case requires getting Approximate nearest neighbors along with filtering on other column.

For now, I will explore the PostgreSQL partial indexes to see if it helps in our use case.

Thanks!!

**Comment by jcrupi** [comment]
Just so I understand. With IVFFlat if I have: SELECT  chunk, category, tags from embeddings where category = '101' ORDER BY embedding <-> '[3,1,2]' LIMIT 5;

It will do the similarity search first on the table and then filter by where clause?

**Comment by ankane** [comment]
@snehith26 It's being investigated, but there's no timeline.

@jcrupi In general, the Postgres planner will choose the path with the lowest cost. In the example above, this could be a table scan, an index on `category`, or an approximate index on `embedding`. You can use `EXPLAIN ANALYZE` to see the plan it chooses (and other Postgres resources for how to interpret the output).
