### ISSUE TITLE
SQL Upgrade - ERROR: could not find function "l1_distance" in file "/usr/lib/postgresql/14/lib/vector.so"

### ISSUE THREAD

**Issue by vgoat21** [pgvector/pgvector#302]
After running:

`SELECT * FROM pg_available_extension_versions WHERE name ='vector';`

I got the listed versions:
![image](https://github.com/pgvector/pgvector/assets/93329405/e7e62b4a-d24a-4519-b34d-98a7ae134d54)

I then tried to run `ALTER EXTENSION vector UPDATE;` and recieved the following error: `SQL Error [42883]: ERROR: could not find function "l1_distance" in file "/usr/lib/postgresql/14/lib/vector.so"`

I am upgrading from version 0.4.4 on postgresql version 14.

**Comment by ankane** [comment]
Hi @vgoat21, from the error message, it looks like `vector.so` may be compiled for a previous version. How was pgvector originally installed, and how did you upgrade it?

**Comment by vgoat21** [comment]
originally it was installed using `CREATE EXTENSION vector;` and that's it, I have installed the other versions by pulling them from git. Do i just need to replace that file with the one pulled from git?

**Comment by ankane** [comment]
If you installed it from the [Git instructions](https://github.com/pgvector/pgvector#installation) initially, you'll want to follow those instructions again for upgrading (cloning and running `make`/`make install`).
