### ISSUE TITLE
On the issue of HnswElement storage

### ISSUE THREAD

**Issue by suppersam1** [pgvector/pgvector#305]
Can the vec data in hnswelement not be stored? We can directly obtain it from the base table through a row pointer in heaptids.

**Comment by jkatz** [comment]
This is an expensive lookup. I did similar testing for `ivfflat` and did not see any performance gain on lookups (in fact, quite the opposite). While HNSW has different search characteristics and there could possibly be a gain here, this methodology would significantly slow down index builds.

**Comment by ankane** [comment]
Hi @suppersam1, I don't think I've seen this with other index types, but someone is welcome to try to prototype and benchmark it.
