### ISSUE TITLE
Creating an HNSW index causes SSL error

### ISSUE THREAD

**Issue by samrat** [pgvector/pgvector#307]
Hello, thanks for working on this extension. 

I ran into a problem when creating an index on a DigitalOcean managed Postgres instance. It's important to note that the pgvector version there is `0.5.0`(latest as of now is `0.5.1`) so perhaps this issue is already fixed. 

I've also opened a support ticket with DigitalOcean to get them to upgrade the extension.

When I create an index in my DB, it seems to cause an SSL error:

```
=> CREATE INDEX ON chunks USING hnsw (embedding vector_cosine_ops);
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?>
!?> ^C
```

(the table being indexed is empty)

**Comment by ankane** [comment]
Hi @samrat, the Postgres log will have more details, but it's likely an issue that needs to be addressed by your provider (unrelated to the specific pgvector version).

**Comment by john-bicknell** [comment]
I have an application running on digital ocean just using a simple query on a vector field, I setup a new instance and it crashes on the same query, I only get 'Connection to the server has been lost.' 
The only difference between the two environments is the new crashing one has extension version 0.5.0 and the working version has version 0.4.2.
