### ISSUE TITLE
 Reciprocal Rank Fusion

### ISSUE THREAD

**Issue by Siegi96** [pgvector/pgvector#309]
Thanks again for the awsome package. Any future plans to integrate rank fusion, e.g. rrf into pgvector? Or do you have any idea on how one could aggregate multiple search rankings(e.g. multiple embedding searches, keyword search,....) into a final ranked set?

**Comment by ankane** [comment]
Hi @Siegi96, you can implement RRF in SQL (added an [example](https://github.com/pgvector/pgvector-python/blob/master/examples/hybrid_search_rrf.py)). Another approach for combining results / re-ranking is cross-encoders ([example](https://github.com/pgvector/pgvector-python/blob/master/examples/hybrid_search.py)).
