### ISSUE TITLE
Q: max dimensions / page size

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [pgvector/pgvector#31]
Hi,
if PG page size 8192 (8KB), and
"Each vector takes 4 * dimensions + 8 bytes of storage"
why the limit is 1024? it looks like it can be bigger (considering other columns in the same table)

can I just increase it to 1080 in src/vector.h? 
Without having PG compiled with 16KB page?

10x!

**Comment by ankane** [comment]
Hey @LazyDBA247-Anyvision, 1024 is the highest power of two that'll fit on a single page with the default size. You should be able to increase it to any size that fits on a single page.

**Comment by ankane** [comment]
Hey @LazyDBA247-Anyvision, just fyi, version 0.4.0 supports up to 16000 dimensions for vectors and 2000 dimensions for indexes by default.

**Comment by LazyDBA247-Anyvision** [comment]
great, 10x for the update.

so need to remove the FAQ:
https://github.com/pgvector/pgvector#what-if-i-want-to-index-vectors-with-more-than-2000-dimensions

**Comment by ankane** [comment]
That one's still relevant (just updated it before the release).

**Comment by LazyDBA247-Anyvision** [comment]
ha ha, i didn't even read it fully :pleading_face:  i just remembered that FAQ

good job! :)
