### ISSUE TITLE
Avoiding storing copies of shared documents

### ISSUE THREAD

**Issue by mgoldenbe** [pgvector/pgvector#314]
I have a database of documents represented by 384-dimensional embedding vectors. Each document belongs to one or more users. My goal is to search for K best matching documents *belonging to the user submitting the query* for a given search query (also represented by 384-dimensional embedding vector).

Whenever a new user subscribes (at which time he does not own any documents), I want to construct a partial index for that user. Whenever a user assumes ownership over a document, the vector embedding of that document is to be added to that partial index.

Obviously, if I had a single table `Documents (doc_id, user_id, embedding)`, then I could construct the new user's partial index as:

```python
CREATE INDEX ON Documents USING hnsw(embedding) WHERE user_id=new_user_id;
```

However, I want to avoid storing embedding of a document owned by many users multiple times. So, the database would be something like this:

- `Documents  (doc_id, embedding)`
- `Ownership (user_id, doc_id)`

How can I construct a partial index for the given user in this case?

**Comment by ankane** [comment]
Hi @mgoldenbe, it's only possible to create an index on a single table or materialized view, so you'd need to get the data you want to index into that form. If the number of documents for each user is small, you can create a b-tree index on `Ownership (user_id)` to speed up exact search.

**Comment by mgoldenbe** [comment]
@ankane 

There are many documents per user, so I have to use approximate search. So:

- Did I understand you correctly that I could create a materialized view as a natural join of `Documents` and `Ownership`, and create a partial index for the new user on that view?
- If I did understand correctly, do you know whether the embedding for a document belonging to say two users will be duplicated and take twice as much space or Postgres is smart enough to use references in the internal representation of the materialized view ?
