### ISSUE TITLE
README recommends inner product for OpenAI embeddings

### ISSUE THREAD

**Issue by hammady** [pgvector/pgvector#316]
The official [docs](https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use) for OpenAI which is linked in the README recommend using cosine similarity. The README itself recommends inner product. Did that change or it was copied by mistake? I can fix in a PR, just need to understand the context.

**Comment by ankane** [comment]
Hi @hammady, the performance tip is mentioned in the link:

> Cosine similarity can be computed slightly faster using just a dot product

**Comment by hammady** [comment]
You are right. I am copying it here for reference.

OpenAI:
> We recommend [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity). The choice of distance function typically doesn’t matter much.
OpenAI embeddings are normalized to length 1, which means that:
Cosine similarity can be computed slightly faster using just a dot product
Cosine similarity and Euclidean distance will result in the identical rankings

pgvector:
> If vectors are normalized to length 1 (like [OpenAI embeddings](https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use)), use inner product for best performance.
