### ISSUE TITLE
CREATE EXTENSION vector; command is returning with Error.

### ISSUE THREAD

**Issue by ProSoumya** [pgvector/pgvector#318]
While Creating the Extension vector with the above command it is giving the error :

ERROR:  could not open extension control file "C:/Program Files/PostgreSQL/14/share/extension/vector.control": No such file or directory.

Can anybody help  on this ? 

PG Version - Postgresql 14.9-1

**Comment by ankane** [comment]
Hi @ProSoumya, this means the extension isn't installed.
