### ISSUE TITLE
Categorical HNSW

### ISSUE THREAD

**Issue by mgoldenbe** [pgvector/pgvector#319]
Are there plans for [Categorical HNSW](https://blog.vasnetsov.com/posts/categorical-hnsw/) in `pgvector`?

**Comment by jkatz** [comment]
There is a longer discussion around approaches here: https://github.com/pgvector/pgvector/issues/259

Today, you can categorize rows either by using partitioning and building a HNSW indexes on individual partitions, or by building a partial index. Both options are discussed here:

https://github.com/pgvector/pgvector#filtering

**Comment by mgoldenbe** [comment]
@jkatz 

Assuming there are several thousand categories and the searches are always on a single value (e.g. `WHERE category_id = 327`), it seems that having a separate table for each category is the most straightforward approach. What do you think?

For my application, this will result in many vectors duplicated across many tables. It would be great if there was a way to build index on a foreign key, i.e. store in the index references to a centralized source-of-truth table that stores the actual vectors...
