### ISSUE TITLE
Issue when using L2 distance 

### ISSUE THREAD

**Issue by atanastrpceski** [pgvector/pgvector#32]
I have a issue when using the 'L2 distance' operator. No matter what I'm comparing it to, it's not respecting the limit operator and it always returns just 1 (and always the same) exact record.

Here is an example query: 

`SELECT * FROM public.connected c  ORDER BY factors  <-> '[0.05613021180033684,-0.046761274337768555,-0.04585694149136543]' LIMIT 5;`

I have no problems with cosine (`<=>`) and inner product (`<#>`), they work as expected.

**Comment by ankane** [comment]
Hey @atanastrpceski, can you paste the `EXPLAIN` output? Also, if there's an index on that column, try dropping and recreating it to see if that fixes it.

**Comment by atanastrpceski** [comment]
Seems the index is making the problem

- Dropping the index and running the query => works
- Dropping and recreating the index, and then running the query => also works

I'm using the following index: 
`CREATE INDEX index_connected ON public.connected USING ivfflat (factors) WITH (lists='100');`
(created with sql_alchemy)

Just a note, the real vectors that I'm storing are with a dim of 768, (very big to be pasted here)

The query plan
`Limit  (cost=11440.49..11449.99 rows=5 width=3135)
  ->  Index Scan using ivfflat_connected on connected c  (cost=11440.49..1093934.13 rows=569731 width=3135)
        Order By: (factors <-> '[0.05613021180033684,-0.046761274337768555,-0.04585694149136543, .... ]'::vector)`

**Comment by ankane** [comment]
Great, thanks for checking.

With an IVFFlat index, pgvector divides the data into lists (100 by default) and for each vector, assigns it to the closest list. When querying, it only checks a certain number of lists closest to the queried vector (one by default). You can change this at the expense of slower queries with:

```sql
SET ivfflat.probes = 3;
```

If you create the index when there's no data, the centers of the lists will be random, so it's possible some lists have few or no vectors, which it sounds like is what's happening here. The key is to create the index after there's at least some data to avoid this.

**Comment by atanastrpceski** [comment]
Thanks for the explanation @ankane , I can work with this.

**Comment by aakside** [comment]
Any guidance on when to create the index? How much is "some data?"

As data is added, does the index need to be recreated?

**Comment by ankane** [comment]
Hey @aakside, you'll typically want to create it after importing all your initial data. See #21 for more info.
