### ISSUE TITLE
Indexing progress: tuples_total not populated while loading tuples

### ISSUE THREAD

**Issue by mzur** [pgvector/pgvector#320]
I want to create a HNSW index and followed the instructions in the readme. When I check the indexing progress I get something like this:

```sql
SELECT phase, tuples_done, tuples_total FROM pg_stat_progress_create_index;
             phase              | tuples_done | tuples_total 
--------------------------------+-------------+--------------
 building index: loading tuples |      394848 |            0
(1 row)
```

So `tuples_total` is not populated even if the phase is `loading tuples`. I understand from the readme that it should be populated, is this correct?

My pgvector version is 0.5.1.

**Comment by jkatz** [comment]
@mzur I've made an attempt at addressing this in #321 -- The issue is we don't have the exact total of tuples available without first performing the scan or doing a potentially expensive count operation. However, the proposed method gets the latest available value from `pg_class.reltuples`.

**Comment by mzur** [comment]
Awesome, thanks!

**Comment by ankane** [comment]
Hi @mzur, thanks for reporting. Updated the docs with a better query for HNSW in the commit above.

**Comment by ankane** [comment]
Updated the queries to show % progress in de1f2b09dd2a40a606ffdf317f1e6396b854107a (just fyi)
