### ISSUE TITLE
Docker Installation - Server port 5432

### ISSUE THREAD

**Issue by AkimParis** [pgvector/pgvector#323]
Hello guys,

Thank you for PGVector!

I used to have Postgres locally on Windows. I decided to delete it and create a clean installation via Docker. So I have installed pgvector with the following command.

````
docker pull ankane/pgvector
````
and then... 
````
docker run --name pgvector -e POSTGRES_PASSWORD=test -p 5432:5432 -d ankane/pgvector
````
When I run the command "docker ps -a", I can see that the container is running on PORTS "[0.0.0.0:5432](http://0.0.0.0:5432/) -> 5432/tcp. 

However when I try to create a server via PgAdmin4 on Docker (name: vector_db and host name: localhost). I got the following error:

>  Unable to connect to server: Connection failed: Connection refused Is the server running on that host and accepting TCP/IP connections? connection to server at "localhost" (::1) port 5432 failed: Address not available Is the server running on that host and accepting TCP/IP connections?

Thank you in advance for your help,

Akim

**Comment by ianpurton** [comment]
@AkimParis 

Can you try `host.docker.internal:5432`

See here https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach for why

**Comment by AkimParis** [comment]
Thx @ianpurton 

I solved it by installing PgAdmin4 on Windows, not the docker plugin PgAdmin4... I lost two days on that stupid thing. : )
