### ISSUE TITLE
Variable size Vector? VARVECTOR

### ISSUE THREAD

**Issue by ianpurton** [pgvector/pgvector#324]
Currently we have to set the vector size i.e. vector(384)

We're using pgVector for https://github.com/bionic-gpt/bionic-gpt

So requests we have as that users want to be able to use different embeddings generators and then each different generator has a different set of dimensions.

Currently the user would have to select the vector size one time and can only use embeddings that mach those dimensions.

So I guess I'm looking for something like

```sql
CREATE TABLE embeddings (
    id SERIAL PRIMARY KEY, 
    document_id INT NOT NULL, 
    text VARCHAR NOT NULL, 
    embeddings VARVECTOR 
...
```

Then when running a query pgVector could generate an error if the number of dimensions in the VARVECTOR doesn't match the dimension in the query.

**Comment by ankane** [comment]
Hi @ianpurton, you can use `vector` for variable-dimension vectors (instead of `vector(384)`), but won't be able to index the column.
