### ISSUE TITLE
Using byte vectors to save space

### ISSUE THREAD

**Issue by mgoldenbe** [pgvector/pgvector#325]
To save space, my vectors consists of integers in the range [-128, 127] and are stored in a ByteA column. The conversion `::vector` from `ByteA` fails:

```
psycopg2.errors.CannotCoerce: cannot cast type bytea to vector
```

Is there a workaround?

**Comment by ankane** [comment]
Hi @mgoldenbe, support for a `tinyint` type is on the list of ideas (#27).

**Comment by mgoldenbe** [comment]
Is there a workaround for *exact search*? That is, can I make something like the following work:

 ```
ORDER BY column_of_some_byte_array_type::vector <#> key
```

**Comment by ankane** [comment]
You could [define your own cast](https://www.postgresql.org/docs/current/sql-createcast.html), but it'd be more performant to create your own distance function to compare the `bytea` directly. These are both beyond the scope of pgvector, so please use other resources for additional help.

**Comment by mgoldenbe** [comment]
@ankane 

It turns out that there is a type `"char"` (with quotation marks) in PostgreSQL as documented [here](https://www.postgresql.org/docs/current/datatype-character.html).

Thus, one can do:

```
insert into MyTable values ('{0,1,2}'::int[]::"char"[]);
```

Now this works:

```
select vector::int[]::vector<#>'[1,2,3]' from MyTable;
```

**Comment by ankane** [comment]
Thanks for sharing. Just note that (from the link) `"char"` is "not intended for general-purpose use, only for use in the internal system catalogs."

**Comment by mgoldenbe** [comment]
@ankane 

What does this mean practically? Does it mean that this type may cease to be available in a future version?
