### ISSUE TITLE
Cannot adapt type 'ndarray' with placeholder %s

### ISSUE THREAD

**Issue by AbhiPawar5** [pgvector/pgvector#327]
Hi team, I'm new to PGVector and I would like to do semantic search over a table in postgres. I have embeddings stored as vector already.

I do semantic search as follows:
```
def semantic_search(query):
    global model, conn

    embed = model.encode(query)
    results = conn.execute('SELECT id, Class, AssetTypeName, Name, Value, FormattedValue FROM assets ORDER BY embedding <=> %s LIMIT 5', (embed,))
    return results
```

Here, I get an error saying - 
```
ProgrammingError: cannot adapt type 'ndarray' using placeholder '%s' (format: AUTO)
```

Please let me know what I have missed. Thanks.

**Comment by ankane** [comment]
Hi @AbhiPawar5, check out [pgvector-python](https://github.com/pgvector/pgvector-python) for the Python docs. If you're still having trouble, please create a minimal reproducible example in that repo.
