### ISSUE TITLE
Supported Library , Datatypes , Querytype and Index types 

### ISSUE THREAD

**Issue by pauldintel** [pgvector/pgvector#328]
hi Team , 
Like other vector DB I am looking what Libraries and Index type from below is supported by pgvector 

HNSWlib
DiskANN / Vamana
ScaNN
FAISS-IVFP
NGT

Also are all these datatypes supported ?
FLOAT
INT8 , UINT8
FLOAT16
BFLOAT16

And does pgvector has support of Intel AVX instructions like AVX512 ?

What are the query types from below it supports ?

Search
Filter + Search

thanks

**Comment by ankane** [comment]
Hi @pauldintel, check out the readme for what's supported.

**Comment by pauldintel** [comment]
@ankane - I could find some information but not all .. Could you comment on below if you are not in hurry to close this ! 

Also are all these datatypes supported ?
FLOAT
INT8 , UINT8
FLOAT16
BFLOAT16

And does pgvector has support of Intel AVX instructions like AVX512 ?

**Comment by jkatz** [comment]
@pauldintel Currently pgvector stores each dimensions as a 4-byte float (or in PostgreSQL a `float4` or `real`). You can still store data in a different data type in a different column (e.g. a `float8[]`) and map it to a vector, but the current representation is a 4-byte float. There are a few branches in the project that lay the groundwork to support other data types, such as the ones you mention.

By default, the pgvector `Makefile` uses autovectorization in its compile flags to use underlying instruction sets, including AVX. There is a [PR][1] ([https://github.com/pgvector/pgvector/pull/311][1]) to add explicit support for SIMD instructions, including AVX-512, but that is currently under discussion + testing.

[1]: https://github.com/pgvector/pgvector/pull/311

**Comment by pauldintel** [comment]
thanks @jkatz  - Good information . would be interested when INT8 or BFLOAT16 support added with AVX512 .Looking at the PR# large optimization is possible with SIMD usages.
