### ISSUE TITLE
Q: Index Creation

### ISSUE THREAD

**Issue by atanastrpceski** [pgvector/pgvector#33]
I have a question about index creation. 

What happens if you don't specify the index operation type

So instead of doing it like this:

```
CREATE INDEX ON items USING ivfflat (embedding vector_l2_ops);
CREATE INDEX ON items USING ivfflat (embedding vector_ip_ops);
CREATE INDEX ON items USING ivfflat (embedding vector_cosine_ops);
```

I just do:

`CREATE INDEX ON items USING ivfflat (embedding); `  (it does allow me to do this)

Am I getting something if I do it like this?

What will be the approach if I like to use all 3 operations in my app (l2, ip, cosine), should I create 3 indexes?

**Comment by ankane** [comment]
Hey @atanastrpceski, the default opclass is `vector_l2_ops` if one isn't specified (in hindsight, I wish I hadn't set a default to avoid confusion and may try to remove it in the future, but it's a breaking change).

And exactly - you'll want to create 3 indexes if you want to index all 3 operations.

**Comment by atanastrpceski** [comment]
Thanks!
