### ISSUE TITLE
how can i install pgvector using docker-compose.yml

### ISSUE THREAD

**Issue by BriskyGates** [pgvector/pgvector#331]
Thank you for your amazing work!!!
 when I use postgresql to store some embedding data, I meet with errors:

(<class 'Exception'>, Exception('Failed to create vector extension: (psycopg.errors.UndefinedFile) could not open extension control file "/usr/share/postgresql/14/extension/vector.control": No such file or directory\n[SQL: CREATE EXTENSION IF NOT EXISTS vector]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)'), <traceback object at 0x000002150F2D4080>)

this is docker-compose.yml
`version: "3.3"
services:
 postgres:
  image: postgres
  container_name: postgresql
  restart: always
  environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 7zb1aYoFq2hIbfmn
  ports:
    - 5432:5432
  volumes:
    - /root/PostgreSQL/data:/var/lib/postgresql/data
~                                                                                                                                           
~ `
I am confused about how to solve it, I try to docker pull pgvector, but I don't know how to fit it with my postgresql database

**Comment by ankane** [comment]
Hi @BriskyGates, replace `image: postgres` with `image: ankane/pgvector`.
