### ISSUE TITLE
Getting server disconnect when adding 1M vectors to HNSW index

### ISSUE THREAD

**Issue by mgoldenbe** [pgvector/pgvector#332]
I am on AWS RDS Postgres v. 15.4 db.m7g.large instance with 8GB of RAM. Extension version 0.5.1.

I have set the parameters:

```
searchdb=> SHOW maintenance_work_mem;
 maintenance_work_mem
----------------------
 1GB

searchdb=> SHOW shared_buffers;
 shared_buffers
----------------
 2GB
```

I created an empty table, built the HNSW index with its default parameters, and am adding 1M 384-dimensional vectors from another table:

```
insert into MyTableHNSW select content_id, part, vector::int[]::vector(384) from MyTableSmall;
```

After a few minutes, I get:
```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

What might I be missing?

**Comment by mgoldenbe** [comment]
It looks like the unit is not 1 byte as I assumed:

```
searchdb=> SELECT unit, setting, max_val, pg_size_pretty(max_val::numeric)
  FROM pg_settings WHERE name='maintenance_work_mem';
 unit | setting |  max_val   | pg_size_pretty
------+---------+------------+----------------
 kB   | 128828  | 2147483647 | 2048 MB
(1 row)

searchdb=> SELECT unit, setting, max_val, pg_size_pretty(max_val::numeric)
  FROM pg_settings WHERE name='shared_buffers';
 unit | setting |  max_val   | pg_size_pretty
------+---------+------------+----------------
 8kB  | 245579  | 1073741823 | 1024 MB
```

**Comment by mgoldenbe** [comment]
I have set the parameters:

```
searchdb=> SHOW maintenance_work_mem;
 maintenance_work_mem
----------------------
 1GB
(1 row)

searchdb=> SHOW shared_buffers;
 shared_buffers
----------------
 256MB
(1 row)
```

I created an empty table, built the index, and am adding 1M 384-dimensional vectors from another table:

```
insert into MyTableHNSW select content_id, part, vector::int[]::vector(384) from MyTableSmall;
```

After a few minutes, I get:
```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Is there anything else I am missing? To reiterate, I am on AWS RDS Postgres v. 15.4 db.m7g.large instance with 8GB of RAM.

**Comment by mgoldenbe** [comment]
Oops, I did not read #35 well. It says that `shared_buffers` should be 25% of the server memory, not of `maintenance_work_mem`. I am trying that and will report.

**Comment by mgoldenbe** [comment]
Still the same issue with `shared_buffers=2GB`...

**Comment by mgoldenbe** [comment]
I am going to consolidate everything in a single

**Comment by ankane** [comment]
Hi @mgoldenbe, a few questions:

1. What do the RDS logs say about the error?
2. What does memory usage look like before the error?
3. Does it happen when there's no HNSW index on the table?

It looks like `array_to_vector` isn't freeing memory allocated by `deconstruct_array`, which could be the cause, but I'm having trouble getting runaway memory usage from it.

**Comment by ankane** [comment]
Addressed the allocations in e115773a5516aca16617ffa403d1aa5952198dd8 and 8e507f3bf51825a748fa60000ca051c824d23d21.

**Comment by ankane** [comment]
I don't think the `deconstruct_array` allocations are the cause. From [this thread](https://www.postgresql.org/message-id/20230216213554.vintskinrqqrxf6d%40awork3.anarazel.de) on pgsql-hackers:

> Most SQL callable functions don't need to be careful about not leaking O(1) memory, the exception being functions backing btree opclasses.
>
> In fact, the detailed memory management often is *more* expensive than just relying on the calling memory context being reset.

Test script for reference:

```python
import psycopg

conn = psycopg.connect(dbname='repro', autocommit=True)

pid = conn.execute('SELECT pg_backend_pid()').fetchall()[0][0]
print('pid:', pid)

conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
conn.execute('DROP TABLE IF EXISTS items')
conn.execute('DROP TABLE IF EXISTS items2')

conn.execute('CREATE TABLE items (id serial PRIMARY KEY, embedding int[])')
conn.execute('CREATE TABLE items2 (id serial PRIMARY KEY, embedding vector(384))')
conn.execute('CREATE INDEX ON items2 USING hnsw (embedding vector_cosine_ops)')

print('items')
conn.execute('INSERT INTO items (embedding) SELECT array_fill(1, ARRAY[384]) FROM generate_series(1, 1000000) i')

print('items2')
conn.execute('INSERT INTO items2 SELECT id, embedding::vector(384) FROM items')
```

**Comment by mgoldenbe** [comment]
@ankane 

Regarding the script for reference: do you mean that you ran this script on RDS and it worked or that you are asking me to run it?

To answer your questions, I re-ran it again. However, I suspected that the problem could originate from my SSH client under WSL, which gave me problems before. So, I am running psql in PythonAnywhere terminal and it's been running for some 40 minutes now! I will update.

**Comment by mgoldenbe** [comment]
Sorry for this. I guess it was a problem with WSL...
