### ISSUE TITLE
slow insertion of vector fields

### ISSUE THREAD

**Issue by heyufeng666888** [pgvector/pgvector#334]
Vector fields are inserted quickly without indexing, but after indexing, data insertion is slow. Can we build an index asynchronously

**Comment by jkatz** [comment]
There is always overhead when you are modifying data when there are indexes on a table. What kind of index are you building? If it's HNSW, one strategy you can use is concurrently inserting the data, i.e. multiple simultaneous COPY/INSERT statements.

**Comment by heyufeng666888** [comment]
I am using the HNSW index, with an order of magnitude of 100k. When inserting data with vector fields and data with regular index fields through testing, the throughput shows a multiple difference. My idea is to build a vector index in an asynchronous manner, which does not affect the data tps. Is it feasible?

**Comment by jkatz** [comment]
Yes. 100k is not that many vectors. One approach you can take is to start with an empty table and concurrently insert the vectors. If you'd prefer to build it all at once, you can run `CREATE INDEX CONCURRENTLY` on a populated table, but you'd likely build the index more quickly if you use the concurrent insert strategy.

**Comment by heyufeng666888** [comment]
I am using a strategy of concurrent insertion. Initially, 40K data was quite fast, but later it became slower and slower, increasing thread efficiency. My actual business is that the retrieval is not affected during the insertion process, so I first establish an index before inserting data. My vector is 512 dimensions, M is 32, ef_construction is 200, and the test results show that the dataset is 100k, but the actual dataset is over one million and at the level of ten million.

**Comment by ankane** [comment]
Hi @heyufeng666888, using a lower `m` and / or `ef_construction` should have better insert performance. I'd recommend trying different values to find a good tradeoff between insert performance and recall for your dataset.
