### ISSUE TITLE
Question: What is the best way to mock PostgreSQL with pgvector extension for unit tests?

### ISSUE THREAD

**Issue by tasansal** [pgvector/pgvector#337]
Hi, we are building an application with [langchain](https://github.com/langchain-ai/langchain) and using its pgvector integration as our vectorstore. I want to write unit tests that can run without a full postgres instance + vector extension running. 

Do you have any recommendations on how to do this? 

The modules I want to test are:
* Connect langchain's PGVector vectorstore
* Use it as retriever to get pre-defined results

**Comment by ankane** [comment]
Hi @tasansal, please use other resources for help with LangChain / mocking.
