### ISSUE TITLE
Changing dimensions without dropping columns

### ISSUE THREAD

**Issue by aronweiler** [pgvector/pgvector#338]
Hello @ankane!  

First, I just want to say what an amazing job you've done here with pgvector, giving us a viable open-source alternative to the major paid vector database engines out there.  I really appreciate all of the hard work you've put into this project.

Second, I have a question regarding being able to change the number of dimensions for a vector... I currently use SQLAlchemy to create the tables/columns, which when creating a `vector` in a migration script looks like this:

`op.add_column('table_name', sa.Column('column_name', pgvector.sqlalchemy.Vector(dim=768), nullable=True))`

My question to you is: is it possible to change the vector dimension size on a column without dropping the column?  Say I want to remove the dimension specification altogether (I understand that this would prevent indexing) in order to support a column that can hold vectors with multiple dimensions.

Alternatively, I am looking for a best-practice solution to maintaining multiple different vectors of the same data (with different dimensions) in the same table, ideally in the same column.  (e.g.: row 1 has a 1536 dimension vector in column A, and row 2 has a 768 dimension vector in column A)

Maybe this is really simple and I've missed it somewhere, but any help would be appreciated (doesn't need to use SQLAlchemy, either).  If it's not possible to cram everything into one column, then any help in pointing me to an alternate solution would be much appreciated.

Thanks!

**Comment by ankane** [comment]
Hi @aronweiler, you can change the column type in SQL with:

```sql
ALTER TABLE items ALTER COLUMN embedding TYPE vector;
```

Ref: https://www.postgresql.org/docs/current/sql-altertable.html

**Comment by aronweiler** [comment]
Holy crap, it's that simple... I'm an idiot.  Thanks!

**Comment by jcrupi** [comment]
Are you asking if you can have a vector column with different dimension sizes in rows?

**Comment by aronweiler** [comment]
> Are you asking if you can have a vector column with different dimension sizes in rows?

Yeah, basically. But it's really as simple as just removing the dimension specification on the column. Then you can put anything in there (on different rows).
