### ISSUE TITLE
`ALTER EXTENSION vector UPDATE` is not finding 0.5.1

### ISSUE THREAD

**Issue by Anjum48** [pgvector/pgvector#339]
I'm trying to update pgvector, but running `ALTER EXTENSION vector UPDATE` returns:

```
NOTICE:  version "0.4.4" of extension "vector" is already installed
ALTER EXTENSION
```

I have also tried `ALTER EXTENSION vector UPDATE TO '0.5.1';`

Any ideas on how I can update to enable HNSW?

**Comment by jkatz** [comment]
Please ensure the system you're running on as `0.5.0` or `0.5.1` installed.

**Comment by Anjum48** [comment]
Ah think I know where I'm going wrong - these instructions here (https://github.com/pgvector/pgvector#upgrading) are to update the database not the extension. The extension update needs to be done in the same way as a fresh install...

**Comment by ankane** [comment]
Tweaked the instructions in the commit above to hopefully make it more clear.

**Comment by Anjum48** [comment]
Hmm I still seem to be stuck on 0.4.4.

I reinstalled using this: https://github.com/pgvector/pgvector#installation

Also tried: https://github.com/pgvector/pgvector#apt (for v16)

`SELECT extversion FROM pg_extension WHERE extname = 'vector';` is still only listing the original version...

**Comment by ankane** [comment]
You'll need to use the same method as the original installation. Also, if you have multiple Postgres installations, make sure you're installing it to the [right one](https://github.com/pgvector/pgvector#postgres-location).

**Comment by Anjum48** [comment]
Thank you :) Your suspicions were right, I did have multiple installations... Thanks for your patience & help!
