### ISSUE TITLE
dimensions for type vector cannot exceed 1024

### ISSUE THREAD

**Issue by BriskyGates** [pgvector/pgvector#340]
Hello!
Firstly thank you for responding to me so quickly, I corrected the images name of  docker-compose.yml file 
to ankane/pgvector
when I inserted the openai embedding data(which dimensions of embedding is 1536 ), I met with new problem:dimensions for type vector cannot exceed 1024.
How can we support 1536 dim

**Comment by ankane** [comment]
Hi @BriskyGates, make sure you're using version 0.4.0 or greater.

**Comment by BriskyGates** [comment]
> Hi @BriskyGates, make sure you're using version 0.4.0 or greater.
you're right,I find the properies of vector are as follow:

CREATE EXTENSION vector
	SCHEMA "public"
	VERSION 0.2.0

I don't know how to update the version of vector using docker-compose.yml,could you do me a favor
