### ISSUE TITLE
how to update the version of pgvector using docker-compose.yml

### ISSUE THREAD

**Issue by BriskyGates** [pgvector/pgvector#341]
you're right,I find the properies of vector are as follow:

CREATE EXTENSION vector
SCHEMA "public"
VERSION 0.2.0

I don't know how to update the version of vector using docker-compose.yml,could you do me a favor?

I tried:
opened the sql script and input "ALTER EXTENSION vector UPDATE;", but failed to update, only got version 0.2.0 instead

the version of postgresql:
Postgresql Version : PostgreSQL 14.0 (Debian 14.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by ankane** [comment]
Hi @BriskyGates, `docker-compose pull` should get the latest image, and please use other resources for additional help.
