### ISSUE TITLE
How much memory is necessary for HNSW indexes?

### ISSUE THREAD

**Issue by dylanrb123** [pgvector/pgvector#343]
I tried using pgvector on Google Cloud SQL to create a table with a large number of rows (~580M) with an HNSW index. The database is running on a machine with 8 CPU and 64GB memory. I tried to add an index after all of the data was added to the table but it pretty quickly used all available memory on the machine and slowed to a trickle. I let the index job run for over a week and it is still only 6.8% through the `building index` step. 

Is there any guidance on how much memory is needed to create an HNSW index? Does the entire table/index need to be able to fit in memory? 

Some more info on the data I am working with:
total number of vectors: 580M
dimensions: 80
size of table: 259GB
HNSW parameters: default

**Comment by dylanrb123** [comment]
Interesting read, thanks! I only assumed that memory was the limiting factor here since when looking at the metrics of the machine running the database CPU usage was very low (~2%) but memory usage was at 100%. I'm trying again now with a larger machine that has enough memory to hold the entire dataset (which may be overkill). One thing I haven't tried is creating the index before I add all of the vectors to the table, I will give that a shot next. 

The reason I was asking about how much memory might be needed is I know that e.g. Vespa requires the cluster to have enough memory to hold the entire vector dataset in order to efficiently search the index so I was wondering if there were a similar constraint here.

**Comment by ankane** [comment]
Hi @dylanrb123, having enough memory to fit the data isn't a requirement, but you should see better performance with it (I'd recommend benchmarking it on your hardware). Also, check out #299 for more on memory used for index creation.
