### ISSUE TITLE
How to Upgrade IVFFlat to HNSW

### ISSUE THREAD

**Issue by IchiharaGaku** [pgvector/pgvector#344]
I am currently defining Postgres in docker-compose and installing pgvector v0.4.4 in the Dockerfile. I wanted to use HNSW by default instead of the originally used IVFFlat, so I changed the version to 0.5.1.

```Dockerfile
FROM postgres:15.3

RUN apt-get update && \
    apt-get install -y git make gcc postgresql-server-dev-15

RUN git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install && \
    cd ../ && rm -rf pgvector
```

By just writing the above, will HNSW be automatically applied?
If there are any other necessary steps, please let me know.

**Comment by jkatz** [comment]
> By just writing the above, will HNSW be automatically applied?

No, you will need to build a new index. Instructions for how to build a HNSW index are here: https://github.com/pgvector/pgvector#hnsw

**Comment by IchiharaGaku** [comment]
@jkatz 
Thank you for your prompt reply. 
I am currently using Prisma to define a vector column.

```prisma
model Vector {
  id                Int                          @id @default(autoincrement())
  ...
  embedding         Unsupported("vector(1536)")?
  embedding_content String
  metadata          Json?
  namespace         String                       @default("default")
  created_at        DateTime                     @default(now())
  updated_at        DateTime                     @default(now())
}
```

I would like to use HNSW for the column named embedding, but how can I create the index for this? 
Would you know?

**Comment by ankane** [comment]
Hi @IchiharaGaku, from what I can tell, Prisma doesn't currently support custom index types in the schema ([docs](https://www.prisma.io/docs/concepts/components/prisma-schema/indexes)), so you'd need to run the `CREATE INDEX` SQL outside of that.
