### ISSUE TITLE
Any plans to support encryption?

### ISSUE THREAD

**Issue by bprager** [pgvector/pgvector#345]

**Comment by jkatz** [comment]
Can you please be more specific about what type of encryption you're looking for? "Encryption" is very broad.

**Comment by bprager** [comment]
The documents stored with the embeddings might contain sensitive content which should be protected at rest. It would be great if we could encrypt this column. This will most likely also require the embeddings to be encrypted, otherwise the content will be vulnerable to rainbow attacks. I am not sure what that means for the neighbor search. Is that something that might be possible?

**Comment by ankane** [comment]
Hi @bprager, the short answer is there are [a number of ways](https://www.postgresql.org/docs/current/encryption-options.html) to encrypt data with Postgres, so you can use one or more of those methods (and methods that limit efficient searching of other data will also limit it for pgvector). I'd recommend checking out other resources on Postgres encryption for more info.
