### ISSUE TITLE
How to Automate HNSW Parameter Configuration Based on Dataset Characteristics?

### ISSUE THREAD

**Issue by JamesirYao** [pgvector/pgvector#347]
### Feature Request

Thanks in advance for the great work 👍
I'm using `pgvector` 0.5.1 now for vector similarity search in my app and have to finetune the HNSW parameters (`m`, `ef_construction`, and `ef_search`) manually. Considering the diverse nature of datasets and their dimensions, it becomes crucial to have a method for automatically adjusting these parameters to ensure good performance. I would like to request the addition of functions that could help in setting these parameters based on the dataset's capacity (# of maximum possible records) and embedding size for `m` and `ef_construction`, and the number of records for `ef_search`.

#### Functions to Implement
Specifically, the functions I'm envisioning would be as follows:

1. Function to get `m` and `ef_construction`:
```python
def get_m_and_ef_construction(capacity: int, embedding_size: int) -> (int, int):
    # capacity: number of maximum possible records
    # embedding_size: vector dimension
    return (m, ef_construction)
```

2. Function to get ef_search:
```python
def get_ef_search(capacity: int, num_records: int, embedding_size: int) -> int:
    # capacity: number of maximum possible records
    # num_records: current number of records
    # embedding_size: vector dimension
    return ef_search
```

#### Expectations for the Functions
My expectation for these functions is to have a robust and empirical method that abstracts away the complexities of parameter tuning for HNSW. Given that each index in my application will not exceed 1 million records, a function that operates on predefined capacity levels (such as 1k, 10k, 100k, 1M) would be quite practical. The functions could either be an empirical formula that intelligently adjusts parameters based on capacity and embedding size, or it could be a simple lookup table with well-researched default values for each capacity level.

Such functions would greatly simplify the configuration process, especially for users who are not familiar with the underlying mechanics of HNSW. Automated tuning based on data characteristics could make pgvector more accessible and reduce the barrier to entry for efficient vector search utilization.

Thank you again for considering this. I look forward to the possibility of these functions being incorporated into pgvector, thereby streamlining the user experience and fostering optimal index performance out-of-the-box.

**Comment by ankane** [comment]
Hi @JamesirYao, thanks for the suggestion. I think it'd be better to do this outside of pgvector (at least for now), but feel free to share the details and results if you have an approach that works well.
