### ISSUE TITLE
Potential operator conflict with pg full text search 

### ISSUE THREAD

**Issue by VoVAllen** [pgvector/pgvector#349]
`<->` is overloaded by PostgreSQL's text search facility like `to_tsquery('fat') <-> to_tsquery('rat') → 'fat' <-> 'rat'`. [^1] And it's common to jointly use pgvector with tsquery as a hybrid search method to improve performance. Will pgvector consider having a different operator for the l2 distance?

[^1]: https://www.postgresql.org/docs/current/functions-textsearch.html

**Comment by jkatz** [comment]
`<->` is used for L2 distance search between [`point` and other geometric data types](https://www.postgresql.org/docs/current/functions-geometry.html) and [`cube` data types](https://www.postgresql.org/docs/current/cube.html). Additionally, there aren't any casts (that I'm aware of) between `tsquery` and `vector` / any form of `ARRAY` so I don't see this as an issue.

**Comment by VoVAllen** [comment]
https://github.com/search?q=repo%3Apostgres%2Fpostgres+%3C-%3E+language%3ASQL&type=code&p=2&l=SQL

I did some search in the postgres source code. Multiple library used <-> with the string, which is also the case in pgvector like 'e <-> [0, 1, 2]'. I think the conflict exists if user use the string to represent the vector

**Comment by jkatz** [comment]
[PostGIS also uses `<->` for L2 distance](https://postgis.net/docs/geometry_distance_knn.html).

The PostgreSQL operator system is set up to be flexible and allows for developers to define operators for how they want to implement data types. There are some best practices around them (e.g. `&&` for overlapping, `<@` for containment, and `<->` for distance) but ultimately an extension author can decide how to define them. Arguably, you can overload `=` to mean `<>` , though that would not be an ideal experience.

This is to say, I don't believe keeping `<->` as the L2 instance is an issue as it's already widely accepted with other data types, and I think any confusion with the text search types is minimal, given `<->` has traditionally meant "distance" in PostgreSQL.

**Comment by VoVAllen** [comment]
Thanks for your explanations!
