### ISSUE TITLE
Error during indexing large data

### ISSUE THREAD

**Issue by vkhizanov** [pgvector/pgvector#35]
I'm experiencing an unknown error during creating indices for large table. I tried to create index for smaller chunk and it works well, but for larger it throws an error. Could you please suggest where to dig to solve that issue?

```
osm=# CREATE INDEX ON emb_planet_osm_nodes USING ivfflat (embedding vector_l2_ops) WHERE id < 10;
CREATE INDEX
osm=# CREATE INDEX ON emb_planet_osm_nodes USING ivfflat (embedding vector_l2_ops) WHERE id < 1000;
CREATE INDEX
osm=# CREATE INDEX ON emb_planet_osm_nodes USING ivfflat (embedding vector_l2_ops) WHERE id < 10000000;
CREATE INDEX
osm=# CREATE INDEX ON emb_planet_osm_nodes USING ivfflat (embedding vector_l2_ops) WHERE id < 1000000000;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?>
```

What information should I provide to debug the problem?

**Comment by ankane** [comment]
Hey @vkhizanov, thanks for reporting. A few questions to help debug:

1. What version of pgvector are you on (`SELECT * FROM pg_extension WHERE extname = 'vector';`)?
2. What installation method did you use (source, Docker, Homebrew, or PGXN)?
3. What OS are you on (Ubuntu 20.04, macOS 12, etc)?
4. What information does the server log provide about the crash?
5. Are you seeing high memory usage with the process that's creating the index before the crash? (you can get the process id with `SELECT pid, query FROM pg_stat_activity;` and use a tool like `ps` to get the memory)

**Comment by vkhizanov** [comment]
1. pgvector version
```
  oid   | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
--------+---------+----------+--------------+----------------+------------+-----------+--------------
 161913 | vector  |       10 |         2200 | t              | 0.2.7      |           |
 ```
2. Installed from source
3. Ubuntu 20.04.1 LTS
4. Can you please point out where I can find that?
5. Will check again and let you know

**Comment by ankane** [comment]
Thanks @vkhizanov. From the log, it looks like the server is [running out of memory](https://www.postgresql.org/message-id/2009137.1634680908%40sss.pgh.pa.us).

```text
server process (PID 86997) was terminated by signal 9: Killed
Failed process was running: CREATE INDEX ON emb_planet_osm_nodes USING ivfflat (embedding vector_l2_ops);
```

What's `SHOW maintenance_work_mem;` return?

**Comment by vkhizanov** [comment]
osm=# SHOW maintenance_work_mem;
 maintenance_work_mem
----------------------
 10GB
(1 row)

osm=# SHOW shared_buffers;
 shared_buffers
----------------
 1GB
(1 row)

Should I reduce those values?

**Comment by ankane** [comment]
I think that's the cause. `shared_buffers` look fine (25% of server memory), but I'd decrease `maintenance_work_mem` to 1GB or less to ensure the server doesn't run out of memory ([tuning suggestions](https://pgtune.leopard.in.ua/)).

**Comment by vkhizanov** [comment]
@ankane Thanks a lot!
