### ISSUE TITLE
 the latest docker image occur ERROR: dimensions for type vector cannot exceed 1024 (SQLSTATE 22023)

### ISSUE THREAD

**Issue by pomnb** [pgvector/pgvector#351]
the 0.4.0 version is ok

**Comment by ankane** [comment]
Hi @pomnb, based on the error message, you're on an earlier version. Please use other resources if you need help updating it.

**Comment by pomnb** [comment]
> Hi @pomnb, based on the error message, you're on an earlier version. Please use other resources if you need help updating it.

![img_v3_0252_16ac73df-62db-447e-b3b7-1719e913424g](https://github.com/pgvector/pgvector/assets/119058285/1b4ce45e-6b52-41a8-9e70-ef7ef7d168a4)
but i used this image tag
