### ISSUE TITLE
Page Size Setting?

### ISSUE THREAD

**Issue by JackTan25** [pgvector/pgvector#353]
I plan to run high dimensions vector like 1024, but this is very large. The default size is 8k，so this will cause a Toast. So in this way maybe all pages will store very small vectors. And toast will reduce the query performance?

**Comment by JackTan25** [comment]
and in this way，every page holds only one vector? in this way，the whole hnsw index maybe useless

**Comment by ankane** [comment]
Hi @JackTan25, you can prevent vectors from being toasted with:

```sql
ALTER TABLE items ALTER COLUMN embedding SET STORAGE PLAIN;
```

With larger vectors, HNSW index pages will only hold one vector and its neighbors (if they fit), but it's still significantly faster than a table scan.

**Comment by JackTan25** [comment]
So you mean forbidden toast must be faster then not?

**Comment by jkatz** [comment]
With HNSW, you're less likely to be impacted by TOAST. The bulk of the scan will occur on the index, which as @ankane says, is significantly faster. In this case, most of the penalty with TOAST is minimal, but you may see some small (if any) performance penalties with ingestion / retrieval as PostgreSQL tries to compress/decompress the value (which won't occur as this data doesn't compress nicely).

The impact of TOAST is greater with IVFFLAT for multiple reasons, but this is due query costing vs. the actual performance of the index scan.

**Comment by C0rWin** [comment]
> With HNSW, you're less likely to be impacted by TOAST.

Would that imply that HNSW is not toasting tuples? It stores them inside index pages.
