### ISSUE TITLE
Support for lower precision floating point vectors

### ISSUE THREAD

**Issue by lrotim** [pgvector/pgvector#356]
Are there any plans on the roadmap to support specifying floating point size (in this context, often referred to as quantization)?

I see that there is already a [PR](https://github.com/pgvector/pgvector/pull/231) in progress for some time to quantize to 8bits. 

However, its often the middle ground - (16 or 32bits floating point) that gets you the "right" performance for your usecase. Do you have any plans/roadmaps to introduce this feature?

**Comment by jkatz** [comment]
pgvector already supports 32-bit floating point, that's currently the only supported type. There are a few branches out there that support smaller data types (https://github.com/pgvector/pgvector/commits/half for 16-bit floats, https://github.com/pgvector/pgvector/tree/tinyint for 8-bit ints) so it's feasible to do this, but it helps to have specific use cases you'd like to see supported. Thanks!

**Comment by ankane** [comment]
Let's centralize the discussion / use cases in #326.
