### ISSUE TITLE
Contribution Ideas

### ISSUE THREAD

**Issue by ankane** [pgvector/pgvector#359]
Here are a few places that could currently use some help:

1. Explore updating cost estimates to not use an index when a large % of rows will be filtered by a `WHERE` condition (to avoid returning no results) - #263
    - [x] `hnsw-filtering-cost` branch
2. Investigate why `l2_distance` (not just `vector_l2_squared_distance`) is called for index scans</strike> - [gist](https://gist.github.com/ankane/2ea49423534051eb76565435e76b4b83)
    - [x] Explanation in https://github.com/pgvector/pgvector/issues/359#issuecomment-1840786021
    - [x] See if this can be addressed in the Postgres executor
3. Investigate why the index condition isn't used for `bigint` attributes (like with `integer`) - [hqann-bigint branch](https://github.com/pgvector/pgvector/compare/hqann...hqann-bigint)
    - [x] Works with casting ([thread](https://www.postgresql.org/message-id/flat/ed47a9150911231508i1fa6d163qa7748893dc04c5e7%40mail.gmail.com))
4. Investigate why parallel index scans aren't used when `amcanparallel` is set - [parallel-index-scan3 branch](https://github.com/pgvector/pgvector/compare/parallel-index-scan3)
5. Explore updating cost estimates to not use an index when the limit > `hnsw.ef_search`
    - [x] `index-limit` branch

**Comment by hbhanawat** [comment]
@ankane Possible fix for point number 2: https://github.com/pgvector/pgvector/pull/372

**Comment by ankane** [comment]
Hi @hbhanawat, thanks for the PR, but 2 is about being called during the index scan rather than the index build.

**Comment by ankane** [comment]
Hi @MMeent, thanks for the explanation. It sounds like this would need to be addressed in the executor (updated the list to reflect this).

fwiw, pgvector doesn't currently set `scandesc->xs_orderbyvals` / `scandesc->xs_orderbynulls`, but it doesn't make a difference when it does, which fits the above.

**Comment by ankane** [comment]
Amazing, huge thanks @hlinnaka!

**Comment by torsstei** [comment]
Same here @ankane. Really interested in the progress of the IVFPQ PR and if any further support is needed. AlloyDB apparently runs this in prod already for a while. @bohanliu5 @jkatz

**Comment by jkatz** [comment]
The PR in reference is for scalar quantization (SQ), not PQ.

Andrew has a few branches that implement the vector type with a smaller dimension size (fp16, unit8) - that would effectively enable SQ using an expression index.

I'd still like to hear more about use cases for both SQ/PQ - these techniques do reduce storage, but I'd like to see how much they do reduce search time over the same dataset particularly if recall is impacted.

**Comment by torsstei** [comment]
Google states here  https://cloud.google.com/alloydb/docs/ai/work-with-embeddings#pgvector "When enabled, scalar quantization can significantly speed up queries that have larger dimensional vectors, and lets you store vectors with up to 8,000 dimensions."  @bohanliu5, can you comment on your key use cases?

It would also be good to get Ann benchmark numbers for this, also to see how severely recall is impacted.

**Comment by jkatz** [comment]
@torsstei Thanks; I'm familiar with the PR referenced (left a few comments on it) and the SQ and PQ techniques. As you mentioned, I'd like to see more benchmarks vis-a-vis an accepted technique (ANN Benchmarks) to see what search speeds you can achieve under identical recall targets.
