### ISSUE TITLE
Weird behavior of LIMIT clause

### ISSUE THREAD

**Issue by acim** [pgvector/pgvector#361]
Here is the query example:

`SELECT e.snippet, e.embedding <=> '[1536 dimensions vector]' AS distance, ei.score, n.title FROM evidence_indicator AS ei INNER JOIN evidences AS e ON ei.evidence_id=e.id INNER JOIN news AS n ON e.news_id = n.id WHERE ei.indicator_id=5 ORDER BY distance LIMIT 5000`

With the lower amount of data this works as expected, but if there are over a half million records, for example, it starts returning less than 5000 results, sometimes even 0.

If I add outer query like:

`SELECT COUNT(*) FROM (SELECT e.snippet, e.embedding <=> '[1536 dimensions vector]' AS distance, ei.score, n.title FROM evidence_indicator AS ei INNER JOIN evidences AS e ON ei.evidence_id=e.id INNER JOIN news AS n ON e.news_id = n.id WHERE ei.indicator_id=5 ORDER BY distance LIMIT 5000) AS sq`

I get 5000, but when I drop the outer query and do just the inner one, I get blank record set.

Field e.embedding is indexed using HNSW and the index is used, I checked that. So it seems this problem occurs when the index is used and this is maybe related to issue #263.

**Comment by ankane** [comment]
Hi @acim, sounds like it could be the same as #263, but the `EXPLAIN ANALYZE` output will have more details.
