### ISSUE TITLE
Can I set L2 distance, Inner product, and Cosine distance indexes for the same column simultaneously?

### ISSUE THREAD

**Issue by yan4821567** [pgvector/pgvector#363]
Hello! In my project, I am using Pgvector to store vector data in a column of 768 dimensions. I may perform searches on this vector data using one of the three algorithms: L2 distance, Inner product, or Cosine distance. I can switch between these algorithms as needed. 

I would like to know if it is possible to apply all three indexes to the same column containing the vectors to accelerate the search. Do you have any other suggestions? 

Thank you!

**Comment by ankane** [comment]
Hi @yan4821567, yes, you can create three indexes (one for each distance function) on the same column.
