### ISSUE TITLE
Benchmark between HNSW and IVFFlat

### ISSUE THREAD

**Issue by FingerLiu** [pgvector/pgvector#364]
Are there any official benchmark data of creating index?

![img_v3_025e_9ff23bb1-773f-495a-ab25-8a0ef74f040g](https://github.com/pgvector/pgvector/assets/3981064/91f6c9a7-2218-4a5b-bbbc-5740881274b4)
I have 10 million vectors, when using IVFFlat, it cost me about 30 minutes to build index, but when I switch to HNSW, it cost me about 30 hours to create the index(about 20 times than IVFFlat)!

Through the doc, I know HNSW is slower when build index, but I did not realize it could be so slow. Is this time cost reasonable?

BTW, I noticed 0.5.2 will optimize this, when will it be released？

**Comment by jkatz** [comment]
I recently shared some experiments on [how to speed up using HNSW][1] including how to [improve HNSW build times][1]. In 0.5.1, you can use concurrent inserts to speed up an HNSW build -- start with an empty table, and use multiple INSERT/COPY jobs to build the index. While the tests there did not show total build time, you can see the rate of TPS increase as you increase the concurrency.

The next release of pgvector is planning to support [parallel builds for HNSW][2], which will also speed up build times, but I have not profiled yet the difference in speed.

[1]: https://aws.amazon.com/blogs/database/accelerate-hnsw-indexing-and-searching-with-pgvector-on-amazon-aurora-postgresql-compatible-edition-and-amazon-rds-for-postgresql/
[2]: https://github.com/pgvector/pgvector/commit/dfee5d404570ad78ca9c7f5e44e471ca864bb1e3

**Comment by ankane** [comment]
Hi @FingerLiu, setting a higher `maintenance_work_mem` will also improve HNSW build times. There's not a timeline for the next release yet.
