### ISSUE TITLE
I have a problem with hnsw index creation. Can you check if it is a bug?

### ISSUE THREAD

**Issue by frg01** [pgvector/pgvector#366]
1.first ,I created a table have VECTOR type. 
CREATE TABLE test_vectorType (id bigserial,embedding vector(3));
2.second I create index on VECTOR type filed five times;
CREATE INDEX ON test_vector USING ivfflat (embdding vector_ip_ops) WITH (lists = 1);
CREATE INDEX ON test_vector USING ivfflat (embdding vector_ip_ops) WITH (lists = 1);
CREATE INDEX ON test_vector USING ivfflat (embdding vector_ip_ops) WITH (lists = 1);
CREATE INDEX ON test_vector USING ivfflat (embdding vector_ip_ops) WITH (lists = 1);
CREATE INDEX ON test_vector USING ivfflat (embdding vector_ip_ops) WITH (lists = 1);

3. TABLE structure
![image](https://github.com/pgvector/pgvector/assets/107344363/aebb7342-6524-46e9-9f69-531c7bbd41fd)

We can find that it can create the same type of index field 5 times, but the names are different. Is it normal to successfully create many index fields of the same type? Or is it a feature, I'm a bit confused and hope someone can shed some light on it. Thanks

**Comment by ankane** [comment]
Hi @frg01, check out #188.

**Comment by frg01** [comment]
> Hi @frg01, check out #188.

thanks
