### ISSUE TITLE
diffenrence between "order by val<#>select null::vector" and "order by val <#> (null::vector)"?

### ISSUE THREAD

**Issue by ViolaElrics** [pgvector/pgvector#368]
hi~I create a table
```
set enable_seqscan=off;
create table t (val vector(3));
insert into t (val) values ('[0,0,0]'),('[1,2,3]'),('[1,1,1]'),(null);
create index on t using ivfflat (val vector_ip_ops) with (lists=1);
select * from t order by val <#> (select null::vector);
```
when I try to run `select * from t order by val <#> (select null::vector);` ,I notice that the result has 0 rows, and the planner uses index scan,
but if I try to run `select * from t order by val <#> (null::vector);`,the result has 4 rows, the planner just uses seq scan.
I feel confused what is the difference between  (select null::vector) and  (null::vector)? and what causes the different results? 
thank you sooooo much!!

**Comment by ankane** [comment]
Hi @ViolaElrics, I'm not exactly sure why the planner uses a seq scan for one and an index scan for the other, but prior to 0.5.0, index scans for `NULL` returned no results (#205). With 0.5.0+, you should see 3 rows for the index scan (`NULL` values in the table aren't stored in the index).
