### ISSUE TITLE
Question: does pgvector support disk-based index lookup?

### ISSUE THREAD

**Issue by mkornacker** [pgvector/pgvector#369]
I apologize in advance if this is already documented somewhere. I'm curious whether pgvector needs the entire index (or substantial portion thereof) to be memory-resident in order to perform lookups. Any pointers to documentation of the runtime resource requirements would be appreciated.

**Comment by ankane** [comment]
Hi @mkornacker, check out https://github.com/pgvector/pgvector#do-indexes-need-to-fit-into-memory.

**Comment by mkornacker** [comment]
Ah, thanks, missed that.

Follow-on question: what's the lookup complexity? Logarithmic in the total number of pages? I understand HNSW in principle, but it's not completely clear to me how to map that onto disk pages, given the much less regular structure than a B-tree.

**Comment by ankane** [comment]
It'll be the same as HNSW (logarithmic).
