### ISSUE TITLE
Using this extension on Windows OS

### ISSUE THREAD

**Issue by cdtaichen** [pgvector/pgvector#37]
Hi, I am using this extension on my Windows Based project, PGSQL is v14, I tried to compile this extension both with MSVC 2019 and GCC minggw64.
the dll compiled with GCC could not work, PGSQL will crash when you try to touch the vector interface.
the dll compiled with MSVC 2019 can work without creating index, but when you start to create an index on vector, the PGSQL service process will crash immediately.
Is there anyone have experiences with Windows OS to use this extension?

**Comment by ankane** [comment]
Hey @cdtaichen, can you try the `windows` branch? https://github.com/pgvector/pgvector/compare/windows

This adds `PGDLLEXPORT`, which may help (from looking at [this thread](https://www.postgresql.org/message-id/flat/A737B7A37273E048B164557ADEF4A58B539300BD%40ntex2010a.host.magwien.gv.at)).

**Comment by cdtaichen** [comment]
Ok, I will try this right now, thanks!

**Comment by ankane** [comment]
Great. Would also be good to see the error message from the Postgres server log when it crashes (not sure where that'll be on Windows).

**Comment by ankane** [comment]
fwiw, I was able to get the tests passing with MSYS2 (without the `PGDLLEXPORT` change).

Code: https://github.com/pgvector/pgvector/compare/windows-ci
Logs: https://github.com/pgvector/pgvector/actions/runs/3201375566/jobs/5229281611

**Comment by cdtaichen** [comment]
Hi Kane,

This is my GCC compile batch file, is it  ok for this project?

//---

@echo Compile Windows Dll using GCC
@echo.
@echo off

gcc -shared -W ^
-std=c99 ^
-fPIC ^
src/ivfbuild.c src/ivfflat.c src/ivfinsert.c src/ivfkmeans.c src/ivfscan.c src/ivfutils.c src/ivfvacuum.c src/vector.c ^
-o vector.dll ^
-I ../../../_Include/Kernel/TCDBLib/PostgreSQL/PG14/server/port/win32_msvc ^
-I ../../../_Include/Kernel/TCDBLib/PostgreSQL/PG14/server/port/win32 ^
-I ../../../_Include/Kernel/TCDBLib/PostgreSQL/PG14/server ^
-I ../../../_Include/Kernel/TCDBLib/PostgreSQL/PG14 ^
-L ../../../_Output/Runtime/PostgreSQL/PG14/lib ^
-l:postgres.lib ^
-l:libpgcommon.lib ^
-l:libpgport.lib

@echo.

pause

**Comment by ankane** [comment]
Sorry echo, it looks like you were accidentally tagged. Moved to #38 to reduce noise.
