### ISSUE TITLE
question about HNSW index size

### ISSUE THREAD

**Issue by alonziv** [pgvector/pgvector#370]
I love pgvector and now that it supports HNSW, it's even better.  Thank you for your hard work!

I'm experimenting with HNSW and I'm trying to be conscious of index size because it seems important for performance that it fit in memory. I have a table with about 900K rows of 1280-dimensional vectors.  If I run this:

CREATE INDEX idx_hnsw_cosine ON embeddings_table USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

And then:  SELECT pg_size_pretty(pg_relation_size('idx_hnsw_cosine')); 

it tells me that my index is 7036MB.  Which seems reasonable.

But if I run the same queries with m=2 and ef_construction=4, the index is 7043 MB.

Can that be right?  I assumed a smaller m would generate a smaller index, but maybe I'm misunderstanding how the index is generated.  For the record, queries using the second index (m=2) are faster, so the index is definitely different.

**Comment by ankane** [comment]
Hi @alonziv, with 1280 dimension vectors, each element in the index will likely take up a single 8KB page (with both m=2 and m=16), so the indexes should be roughly the same size.
