### ISSUE TITLE
Requesting for support of homebrew installation with postgresql 14,15,16

### ISSUE THREAD

**Issue by rlam3** [pgvector/pgvector#373]
Requesting for support of homebrew installation with postgresql 14,15,16

```bash
❯ psql -d spike_memgpt -c "Create Extension vector;"
ERROR:  extension "vector" is not available
DETAIL:  Could not open extension control file "/opt/homebrew/opt/postgresql@16/share/postgresql@16/extension/vector.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

I am unable to get this working. Is there a workaround or a support channel? Thank you.

**Comment by ankane** [comment]
Hi @rlam3, check out #195.

**Comment by ankane** [comment]
Just fyi: it's now added to the `postgresql@16` and `postgresql@15` formulas (https://github.com/Homebrew/homebrew-core/pull/159683 and https://github.com/Homebrew/homebrew-core/pull/159695).

**Comment by Nithur-M** [comment]
Hey @rlam3, were you able to get this fixed?

**Comment by adammpolak** [comment]
> #195

Still being worked on: https://github.com/pgvector/pgvector/issues/195#issuecomment-2372293893
