### ISSUE TITLE
Slow vectors retrieval

### ISSUE THREAD

**Issue by cile98** [pgvector/pgvector#374]
Hi all, 

I'm using pgvector to store 384-dimensional embeddings. I've noticed that for the same select query execution time varies strongly depending on whether the select statement includes embeddings or not. For comparison getting 50k embeddings takes around 1.3s and taking 50k corresponding ids is just 0.1s and the difference continues to grow as 350k entries times are 10.5s and 0.5s respectively. Is there any way to speed this up?  Additionally, when querying for embeddings more than 6 GB of ram gets taken, is that expected behavior?

I'd be grateful for any help and advice!

**Comment by ankane** [comment]
Hi @cile98, vectors will typically be much larger than ids, so retrieval will be slower. If you need to retrieve a lot of data, you can use a client that supports the [binary format](https://www.postgresql.org/docs/current/protocol-overview.html#PROTOCOL-FORMAT-CODES) for faster retrieval. For instance, with [psycopg](https://www.psycopg.org/psycopg3/docs/basic/params.html#binary-parameters-and-results):

```python
conn.execute('SELECT id, embedding FROM items', binary=True).fetchall()
```
