### ISSUE TITLE
'Error: column does not have dimensions' when creating index

### ISSUE THREAD

**Issue by Stevod** [pgvector/pgvector#375]
I have this table with around 50K rows and 384 dimensions populated in the vector column

CREATE TABLE public.table_name (
	col_text text NULL,
	count int8 NULL,
	embedding public.vector NULL,
	last_updated timestamptz NULL,
	is_valid_embedding bool NULL
);

However whenever I issue this statement:
CREATE INDEX ON allowed_domain_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50);
I always get this error:
SQL Error [XX000]: ERROR: column does not have dimensions

There are no NULL values in the embedding column.

Can anyone shed some light on how to fix this please?

select version; gives:
PostgreSQL 15.3 (Ubuntu 15.3-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

select * FROM pg_extension; gives
13576	plpgsql	10	11	false	1.0	NULL	NULL
18606530	vector	10	2200	true	0.4.2	NULL	NULL

**Comment by ankane** [comment]
Hi @Stevod, check out #330.

**Comment by jkatz** [comment]
You need to specify the number of dimensions on the vector column, e.g.

```
embedding public.vector(1536)
```

**Comment by Stevod** [comment]
Thanks. Not sure how I missed that.

**Comment by Junyi-99** [comment]
> You need to specify the number of dimensions on the vector column, e.g.
> 
> ```
> embedding public.vector(1536)
> ```

It solved my problem too!
