### ISSUE TITLE
invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by acoffin76** [pgvector/pgvector#376]
My vector load is failing on this file.  What can I do to resolve the issue?

$ cat -vET SpinnerConfig.ts 

```
export interface SpinnerConfig {$
  show: boolean$
  message?: string$
}$
```

docker-flowise-1  |   driverError: error: invalid byte sequence for encoding "UTF8": 0x00
docker-flowise-1  |       at /usr/local/lib/node_modules/flowise/node_modules/pg/lib/client.js:526:17
docker-flowise-1  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
docker-flowise-1  |       at async PostgresQueryRunner.query (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
docker-flowise-1  |       at async InsertQueryBuilder.execute (/usr/local/lib/node_modules/flowise/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
docker-flowise-1  |       at async SubjectExecutor.executeInsertOperations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
docker-flowise-1  |       at async SubjectExecutor.execute (/usr/local/lib/node_modules/flowise/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
docker-flowise-1  |       at async EntityPersistExecutor.execute (/usr/local/lib/node_modules/flowise/node_modules/typeorm/persistence/EntityPersistExecutor.js:140:21)
docker-flowise-1  |       at async TypeORMVectorStore.addVectors (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/typeorm.cjs:156:17)
docker-flowise-1  |       at async TypeORMVectorStore.fromDocuments (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/typeorm.cjs:246:9)
docker-flowise-1  |       at async Postgres_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Postgres/Postgres.js:51:41) {
docker-flowise-1  |     length: 147,
docker-flowise-1  |     severity: 'ERROR',
docker-flowise-1  |     code: '22021',
docker-flowise-1  |     detail: undefined,
docker-flowise-1  |     hint: undefined,
docker-flowise-1  |     position: undefined,
docker-flowise-1  |     internalPosition: undefined,
docker-flowise-1  |     internalQuery: undefined,
docker-flowise-1  |     where: 'unnamed portal parameter $67',
docker-flowise-1  |     schema: undefined,
docker-flowise-1  |     table: undefined,
docker-flowise-1  |     column: undefined,
docker-flowise-1  |     dataType: undefined,
docker-flowise-1  |     constraint: undefined,
docker-flowise-1  |     file: 'mbutils.c',
docker-flowise-1  |     line: '1665',
docker-flowise-1  |     routine: 'report_invalid_encoding'
docker-flowise-1  |   },
docker-flowise-1  |   length: 147,
docker-flowise-1  |   severity: 'ERROR',
docker-flowise-1  |   code: '22021',
docker-flowise-1  |   detail: undefined,
docker-flowise-1  |   hint: undefined,
docker-flowise-1  |   position: undefined,
docker-flowise-1  |   internalPosition: undefined,
docker-flowise-1  |   internalQuery: undefined,
docker-flowise-1  |   where: 'unnamed portal parameter $67',
docker-flowise-1  |   schema: undefined,
docker-flowise-1  |   table: undefined,
docker-flowise-1  |   column: undefined,
docker-flowise-1  |   dataType: undefined,
docker-flowise-1  |   constraint: undefined,
docker-flowise-1  |   file: 'mbutils.c',
docker-flowise-1  |   line: '1665',
docker-flowise-1  |   routine: 'report_invalid_encoding'
docker-flowise-1  | }

**Comment by ankane** [comment]
Hi @acoffin76, it looks like the error is coming from your ORM rather than pgvector. Please use other resources for help.
