### ISSUE TITLE
Update the ankane/pgvector Docker image to use Postgres 16

### ISSUE THREAD

**Issue by stummjr** [pgvector/pgvector#377]
It looks like the latest version of the [`ankane/pgvector`](https://hub.docker.com/r/ankane/pgvector/) Docker image is based on Postgres 15.

I apologize if this is not the right place to ask this, but are there any plans to release an update to that Docker image using Postgres 16 instead?

Thanks a lot for the amazing work!

**Comment by ankane** [comment]
Hi @stummjr, check out #346.

**Comment by stummjr** [comment]
I'm sorry I missed that issue. Will be waiting for 0.6.0 then. 😄 

Thank you for the update!
