### ISSUE TITLE
pgvector upgrade questions

### ISSUE THREAD

**Issue by yinan8128** [pgvector/pgvector#379]
Hi,

There are questions about pgvector upgrade:
1. Once we do pgvector upgrade, is it possible that app usage affect upgrade? Do we need to block users of pgvector database?
2. If question 1 answer is yes, do we need to block users connected to other databases or only pgvector?

Thanks

**Comment by ankane** [comment]
Hi @yinan8128, app usage shouldn't affect upgrading / no need to block users.
