### ISSUE TITLE
Add json and jsonb inout casts

### ISSUE THREAD

**Issue by Komzpa** [pgvector/pgvector#380]
Hello,

I started using pgvector and found that I can't cast json / jsonb expressions into vectors although syntax is the same.
The fix is to create them using inout. I expect both sides to work, so this piece of code needs to land in proper spot in the SQL files:

```
create cast (json as vector) with inout;
create cast (vector as json) with inout;
create cast (jsonb as vector) with inout;
create cast (vector as jsonb) with inout;
```

In action:

```
16:13:13 [gis] > select '[1,2,3]'::json::vector;
ERROR:  42846: cannot cast type json to vector
LINE 1: select '[1,2,3]'::json::vector;
                              ^
LOCATION:  transformTypeCast, parse_expr.c:2657
Time: 0.612 ms
16:15:46 [gis] > create cast (json as vector) with inout;
CREATE CAST
Time: 0.508 ms
16:15:59 [gis] > select '[1,2,3]'::json::vector;
┌─────────┐
│ vector  │
├─────────┤
│ [1,2,3] │
└─────────┘
(1 row)

Time: 0.406 ms

```

Thanks for getting this extension for us!

**Comment by Komzpa** [comment]
Hey, this got closed really fast - will you be willing to accept a pull request about this? It's quite literally four lines of code that I posted above so I am not sure about your concern of being not common enough. I met this when calling OpenAI embeddings generation directly from SQL using [pgsql-http](https://github.com/pramsey/pgsql-http).

**Comment by jkatz** [comment]
@Komzpa Do you have any benchmarks to compare your implementation over what Andrew suggested (`jsonb::text::vector`)? It'd be good to see if it reduces overhead.

**Comment by Komzpa** [comment]
@jkatz it connects the in function of the new type to out function of old type. The main benefit of such arrangement is that one day you may decide that you want to write a specialized high-performance converter from json(b) into vector and all the codebase will immediately benefit for that, as it will not get stuck with ::text:: inbetween. Non-scientific oneliner benchmark shows 12% faster conversion.

```

20:18:08 [kom] > select count(embedding::text::jsonb) from cache_openai_embeddings;
...
(1 row)

Time: 1946,248 ms (00:01,946)


20:18:31 [kom] > select count(embedding::jsonb) from cache_openai_embeddings;
....
(1 row)

Time: 1702,943 ms (00:01,703)

```
