### ISSUE TITLE
vector.so missing fillRelOptions

### ISSUE THREAD

**Issue by elfayoumi** [pgvector/pgvector#381]
Hi, 
I am using the latest master as of 17 of December 2023, and postgresql version 15, 
followed instruction but when I am activate the pgvector extention:
 CREATE EXTENSION vector;
ERROR:  could not load library "/usr/lib/postgresql/15/lib/vector.so": /usr/lib/postgresql/15/lib/vector.so: undefined symbol: fillRelOptions

doing ldd vector so
gives lots of undefined symbols, I do not think it is linked with proper shared objects..

Regards
Ibrahim

**Comment by ankane** [comment]
Hi @elfayoumi, I'm not sure how to reproduce this. I'd try recompiling/reinstalling the extension.

**Comment by georgejxu** [comment]
When I did make and the files are copied into  /usr/pgsql-12/, but my install is in /usr/share/pgsql/.  How do I make it work in my location?  tried to find there is a way to change the location - but I could not.  how do I overcome this?

I also tried to copy files into my location, and run into the above error with the following vector.control
comment = 'vector data type and ivfflat and hnsw access methods'
default_version = '0.7.0'
module_pathname = '/usr/share/pgsql/lib/vector'
relocatable = true


copy script:
/usr/bin/install -c -m 755  vector.so '/usr/pgsql-12/lib/vector.so'
/usr/bin/install -c -m 644 .//vector.control '/usr/pgsql-12/share/extension/'
/usr/bin/install -c -m 755  vector.so '/usr/share/pgsql/lib/vector.so'
/usr/bin/install -c -m 644 .//vector.control '/usr/share/pgsql/extension/'
/usr/bin/install -c -m 644 .//sql/vector--0.1.0--0.1.1.sql .//sql/vector--0.1.1--0.1.3.sql .//sql/vector--0.1.3--0.1.4.sql .//sql/vector--0.1.4--0.1.5.sql .//sql/vector--0.1.5--0.1.6.sql .//sql/vector--0.1.6--0.1.7.sql .//sql/vector--0.1.7--0.1.8.sql .//sql/vector--0.1.8--0.2.0.sql .//sql/vector--0.2.0--0.2.1.sql .//sql/vector--0.2.1--0.2.2.sql .//sql/vector--0.2.2--0.2.3.sql .//sql/vector--0.2.3--0.2.4.sql .//sql/vector--0.2.4--0.2.5.sql .//sql/vector--0.2.5--0.2.6.sql .//sql/vector--0.2.6--0.2.7.sql .//sql/vector--0.2.7--0.3.0.sql .//sql/vector--0.3.0--0.3.1.sql .//sql/vector--0.3.1--0.3.2.sql .//sql/vector--0.3.2--0.4.0.sql .//sql/vector--0.4.0--0.4.1.sql .//sql/vector--0.4.1--0.4.2.sql .//sql/vector--0.4.2--0.4.3.sql .//sql/vector--0.4.3--0.4.4.sql .//sql/vector--0.4.4--0.5.0.sql .//sql/vector--0.5.0--0.5.1.sql .//sql/vector--0.5.1--0.6.0.sql .//sql/vector--0.6.0--0.6.1.sql .//sql/vector--0.6.1--0.6.2.sql .//sql/vector--0.6.2--0.7.0.sql .//sql/vector--0.7.0.sql  '/usr/share/pgsql/extension/'

Thanks!

**Comment by georgejxu** [comment]
or which version of this source works (?). getting anxious... but really appreciated!!!
