### ISSUE TITLE
[Question] Planned release time for "svector" branch?

### ISSUE THREAD

**Issue by zhandao** [pgvector/pgvector#382]
Hi @ankane !

I use pgvector to work with my high dimensional sparse vectors, and I noticed that the `svector` branch may be released in version `0.6.0`. I would like to know if there is a specific release time at present?

I need and love this very much, Thank you.

**Comment by ankane** [comment]
Hi @zhandao, there's not a timeline at the moment (see #326 for related discussion).

**Comment by ankane** [comment]
Support for sparse vectors is now merged (abac7a3f776d4edbb423a000ba5234d3e8eab465) and will be included in 0.7.0 (#508).
