### ISSUE TITLE
pg_vector insert throw error: terminated by signal 4: Illegal instruction

### ISSUE THREAD

**Issue by chenqingspring** [pgvector/pgvector#389]
On CentOS 7.6, I installed **PostgreSQL 14** and **pgvector_14** by **yum**. The creation of the vector plugin `CREATE EXTENSION vector` and the creation of tables containing vector data types `CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3))` proceeded without issues.

However, when attempting to insert vectors or select from vector tables:

The client reported an error: "An I/O error occurred while sending to the backend."
The database log displayed an error: "terminated by signal 4: Illegal instruction."

Cause: The plugin installed using "yum install pgvector_14" uses the default parameter OPTFLAGS = -march=native. The compilation result is optimized according to the specified parameters at compile time, but these optimizations may not be suitable for the machine environment where the code is executed. Therefore, OPTFLAGS="" needs to be set.
> Form Issue: https://github.com/pgvector/pgvector/issues/143

Solution: Compile and install pgvector from its source code.

- Download pg_vector
wget https://github.com/pgvector/pgvector/archive/refs/tags/v0.5.1.tar.gz
tar -xzvf v0.5.1.tar.gz && cd pgvector-0.5.1

- Install the pg_config tool for compilation:
yum provides "*/pg_config"

- Change pg_confg path of Makefile
sed -i 's|pg_config|/usr/pgsql-14/bin/pg_config|' Makefile

- Compile and install pg_vector:
make clean && make OPTFLAGS="" && make install && mkdir /usr/share/doc/pgvector && cp LICENSE README.md /usr/share/doc/pgvector

**Comment by ankane** [comment]
Hi @chenqingspring, thanks for reporting. I've passed this along to the PostgreSQL Yum Repository: https://redmine.postgresql.org/issues/7920

**Comment by hlinnaka** [comment]
How about removing -march=native from the pgvector Makefile? It seems like an option that a distribution should set if appropriate (Gentoo?), not something that's set by default.

**Comment by chenqingspring** [comment]
> Hi @chenqingspring, thanks for reporting. I've passed this along to the PostgreSQL Yum Repository: https://redmine.postgresql.org/issues/7920

Welcome! Thanks for your efforts :)

**Comment by ankane** [comment]
Hi @chenqingspring, it looks like the Yum repository maintainer isn't able to reproduce it, so I'd recommend following up on the ticket with details about your machine and repro instructions.

**Comment by chenqingspring** [comment]
Hi @ankane, 
Thanks for following up. I already post my machine details into that thread. Let's see if they could find any clues.

**Comment by mbanck-ntap** [comment]
> How about removing -march=native from the pgvector Makefile? It seems like an option that a distribution should set if appropriate (Gentoo?), not something that's set by default.

This has not been answered yet. I agree with Heikki that `-march=native` is something that maybe should not be in the Makefile by default. On the other hand, Debian already patches it out (see https://salsa.debian.org/postgresql/pgvector/-/blob/develop/debian/patches/no-native?ref_type=heads) so the rpm builds should as well. I added another comment on the redmine ticket for that.

**Comment by ankane** [comment]
I'm planning to try out a version of #311 for 0.7.0, which would eliminate the need for this.
