### ISSUE TITLE
Can't install using make, sqlvector 0.2.7 not available

### ISSUE THREAD

**Issue by JordanTPhysics** [pgvector/pgvector#39]
#After cloning into extensions folder

C:\Program Files\PostgreSQL\Extensions>cd pgvector

C:\Program Files\PostgreSQL\Extensions\pgvector>make
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:15: pipe: No error
process_begin: CreateProcess(NULL, pg_config --pgxs, ...) failed.
Makefile:40: pipe: No error
cp sql/vector.sql sql/vector--0.2.7.sql
process_begin: CreateProcess(NULL, cp sql/vector.sql sql/vector--0.2.7.sql, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:35: sql/vector--0.2.7.sql] Error 2

The sql file even had all versions up to 0.2.7

**Comment by ankane** [comment]
Hey @JordanTPhysics, check out #37 and #38 for the current state of building on Windows.
