### ISSUE TITLE
Getting error on AWS RDS Postgres v 14.7

### ISSUE THREAD

**Issue by mappers209** [pgvector/pgvector#392]
Hi,

I assumed that AWS RDS Postgres version 14.7 is supported. However, when I try to run the command "CREATE EXTENSION vector;", I encounter an error. This may be because the extension is not included in AWS Postgres RDS. How can I install it on our AWS RDS instance?

Thanks in advance.

ERROR:  could not open extension control file "/rdsdbbin/postgres-14.7.R1/share/extension/vector.control": No such file or directory

**Comment by jkatz** [comment]
Hi @mappers209,

pgvector is available on RDS for PostgreSQL from version 14.8 and higher. You can find the list of available extension versions here:

https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-14x

I'd recommend starting from the latest version of pgvector as there are quite a few performance enhancements added.

**Comment by mappers209** [comment]
Thanks for the info. Which mean we can't use it unless we upgrade our RDS for PostgreSQL from 14.7 to 14.8, will the manual install works?

**Comment by jkatz** [comment]
@mappers209 To use pgvector on RDS for PostgreSQL, you need to upgrade from 14.7 to a newer version, such as 14.10 which has the latest version of pgvector. Additionally, the PostgreSQL community has provided numerous security and bug fixes since 14.7 was released in Feb 2023 and generally [recommends to run newer versions](https://www.postgresql.org/support/versioning/) of PostgreSQL where possible.

**Comment by mappers209** [comment]
> @mappers209 To use pgvector on RDS for PostgreSQL, you need to upgrade from 14.7 to a newer version, such as 14.10 which has the latest version of pgvector. Additionally, the PostgreSQL community has provided numerous security and bug fixes since 14.7 was released in Feb 2023 and generally [recommends to run newer versions](https://www.postgresql.org/support/versioning/) of PostgreSQL where possible.

Yes, I'm thinking of upgrading the RDS PostgreSQL engine to 14.8 first. If all is good, then I will upgrade to 14.9 and 14.10

Thanks,

**Comment by jkatz** [comment]
@mappers209 If your plan is to go to 14.10 anyway, I'd recommend preparing to upgrade straight to that version. Minor updates are all inclusive, i.e. you have the fixes from 14.8 and 14.9 in 14.10. This limits the amount of testing you have to do if you only perform the upgrade to a single version. If you use a lot of extensions, you may need to be mindful of extension version upgrades -- that may be the one issue that prevents you from making the bigger jump, but overall, it's generally easier to do 14.7 => 14.0 than 14.7 => 14.8 => 14.9 => 14.10.

**Comment by mappers209** [comment]
> @mappers209 If your plan is to go to 14.10 anyway, I'd recommend preparing to upgrade straight to that version. Minor updates are all inclusive, i.e. you have the fixes from 14.8 and 14.9 in 14.10. This limits the amount of testing you have to do if you only perform the upgrade to a single version. If you use a lot of extensions, you may need to be mindful of extension version upgrades -- that may be the one issue that prevents you from making the bigger jump, but overall, it's generally easier to do 14.7 => 14.0 than 14.7 => 14.8 => 14.9 => 14.10.
Oh, thanks for the info again.
