### ISSUE TITLE
SELECT query not using (HNSW) index

### ISSUE THREAD

**Issue by MichaelKarpe** [pgvector/pgvector#396]
Given a table of about 1 mil. rows with columns `id` of type integer and `embedding` of type vector(2000), I ran the following query in pgAdmin query tool:

```
CREATE INDEX ON table USING hnsw (embedding vector_cosine_ops);
```

Whatever the SELECT query I ran after, I'm not seeing the index being used when prefixing the query with `EXPLAIN ANALYZE`.

After seeing @ankane's comments "[ordering by an expression [...] won't use the index](https://github.com/pgvector/pgvector/issues/216#issuecomment-1668244772)" and "[Postgres only supports ASC order index scans on operators](https://github.com/pgvector/pgvector/issues/216#issuecomment-1671959593)", I tried a simple `SELECT id, embedding <=> $1 FROM table` but it's still not using the index.

Many blog articles such as [this GCP one](https://cloud.google.com/blog/products/databases/faster-similarity-search-performance-with-pgvector-indexes) and [this other one](https://www.crunchydata.com/blog/hnsw-indexes-with-postgres-and-pgvector) recommend to use `EXPLAIN` to check if the index is used.

Thus my following questions:
- How can I check that the index is actually built? With `EXPLAIN` I can see that even with the simplest query does not use the index, thus I'm even wondering if the index has actually been created (despite the `CREATE INDEX` having "returned successfully in 1 hr 6 min.")
- How to use the HNSW index with a `SELECT` statement?
- Assuming an index has been created, what happens if I rerun a `CREATE INDEX` statement? If I create an HNSW index, I assume it overwrites the existing index (is it?), does it overwrite if I create an `IVFFLAT` index instead?

Related issues: #174, #216

**Comment by jkatz** [comment]
@MichaelKarpe A few questions:

1. How many rows are in the table?
2. Can you provide the full query with any sensitive info redacted?
3. Can you provide the output of `EXPLAIN ANALYZE` from your query (`EXPLAIN ANALYZE SELECT ...`) with any sensitive info redacted?

**Comment by MichaelKarpe** [comment]
@jkatz thanks for your help. A bit more info thanks to investigations I performed in the meantime:

- I believe the index should be created after execution of `CREATE INDEX ON table USING hnsw (embedding vector_cosine_ops);` since the following query returns a list of indexes including the HNSW index:
```
SELECT *
FROM pg_indexes
WHERE tablename NOT LIKE 'pg%'
```

- Experimenting the IVFFLAT indexing instead, with `CREATE INDEX ON table USING ivfflat (embedding vector_cosine_ops) WITH (lists = 1000);`, I found that the query of my initial message still does not work, but after modifying the query as follows, I'm seeing the Index Scan use:
```
EXPLAIN ANALYZE SELECT id
FROM table
ORDER BY embedding <=> '[0.01, 0.02, ..., 0.01]'
```
returns
```
Index Scan using table_embedding_idx on table (cost=93.27..7200.10 rows=1000000 width=12) (actual time=2.745..3.121 rows=80 loops=1)
Order By: (embedding <=> '[0.01, 0.02, ..., 0.01]'::vector)
Planning Time: 0.120 ms
Execution Time: 3.177 ms
```

However, I dropped all indexes on `embedding` column, recreated the HNSW one and used the `SELECT` query working with IVFFLAT index, but with the HNSW index even the correct query does not use the index. Thus, I'd say the issue I'm facing is only with HNSW index. So, to answer your questions:

1. Around 1 million rows are in the table where I make the experiment (I replaced myself the exact number by 1 million in previous and below query outputs)
2. The last query I am now testing is the same working with IVFFLAT index:
```
EXPLAIN ANALYZE SELECT id
FROM table
ORDER BY embedding <=> '[0.01, 0.02, ..., 0.01]'
```
3. Here is what it returns:
```
Sort  (cost=178058.67..180814.49 rows=1102326 width=12) (actual time=5070.614..5227.907 rows=1000000 loops=1)
Sort Key: ((embedding <=> '[0.01, 0.02, ..., 0.01]'::vector))
Sort Method: external merge  Disk: 28088kB
Seq Scan on table (cost=0.00..48588.08 rows=1000000 width=12) (actual time=0.068..4531.571 rows=1000000 loops=1)
Planning Time: 0.599 ms
Execution Time: 5320.397 ms
```

**Comment by jkatz** [comment]
@MichaelKarpe Thanks. I have a suspicion there may be something here related to costing. I'm going to try to reproduce on my end with a similar data set (1MM 2000-dim vectors, HNSW w/cosine ops).

**Comment by jkatz** [comment]
@MichaelKarpe I was unable to reproduce based on the above info, and on my end the costing appeared to be accurate. Did you set a `LIMIT` on query? Have you tuned any other parameters?

**Comment by MichaelKarpe** [comment]
@jkatz as far as I remember I only performed `CREATE INDEX`, `DROP INDEX` and `SELECT` queries, for testing both ivfflat and hnsw. I can also try to reproduce from scratch tomorrow CET.

However, if I also remember well, the first time I created the HNSW index I had a message
```
CREATE INDEX
Query returned successfully in 1 hr 7 min.
```
but I also wasn't querying well (cosine operation in `SELECT` and not `ORDER BY`).

Whereas after recreating the index with `DROP INDEX` and again `CREATE INDEX` for HNSW, I got the following message
```
ERROR:  Key (relname, relnamespace)=(table_embedding_idx, 2200) already exists.duplicate key value violates unique constraint "pg_class_relname_nsp_index" 

ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
SQL state: 23505
Detail: Key (relname, relnamespace)=(table_embedding_idx, 2200) already exists.
```
although the index is listed in the result of 
```
SELECT *
FROM pg_indexes
WHERE tablename NOT LIKE 'pg%'
```

Thus, the error I got when recreating HNSW (but not when recreating IVFFlat) may be the reason.

I will try (tomorrow CET) to recreate a table, create a HNSW index and execute a correct `SELECT` query for index scan.

Since I don't know if the ERROR message is expected when dropping and recreating the HNSW index (since I don't have this behavior for IVFFlat), if it's not expected, you could eventually try to delete, recreate the index and `SELECT` to see if you're facing the same ERROR message as above.

**Comment by jkatz** [comment]
The catalog errors make me suspect there's something odd going on in your environment. How did you install pgvector and what version are you running?

I'd also suggest adding a `LIMIT` to your query as that's the most common query type -- the `LIMIT` sets the `k` in k-NN. In my tests (using an unreleased pgvector), the number of results for a HNSW query are still bounded by the value of `hnsw.ef_search` even if the `LIMIT` is not set, but it'd be good to understand the impact on your plan.

**Comment by MichaelKarpe** [comment]
Hey @jkatz, in short, after adding the `LIMIT` argument, I'm actually seeing the HNSW being used. For my 1 million rows tables, I see that for a LIMIT value until around 50,000, the index is used and the query takes about 1 ms, whereas for greater `LIMIT` values or without `LIMIT`, the index is not used.

Regarding the error I got, it actually seems not to be a problem. Since I discovered I needed a `LIMIT` statement in the query to benefit from index scan, I used one on the table where I got the error and I'm also getting the index scan there.

I don't know if not using the index after a big `LIMIT` value is expected, or if it's worth investigating this since in practice we don't need that many similar embeddings. Feel free to close the issue or I can close it if you confirm.

**Comment by ankane** [comment]
@MichaelKarpe That's the default behavior of the Postgres planner with a high limit or no limit (since a table scan will likely be faster for exact indexes).

When the limit is greater than `hnsw.ef_search / (some factor to account for dead and filtered tuples)`, an HNSW index is probably not a good fit for the query (since it'll cause low recall), so it probably makes sense to incorporate this into the cost estimate if possible (added to #359).
