### ISSUE TITLE
Proposal: Explicitly set HNSW build workers

### ISSUE THREAD

**Issue by jkatz** [pgvector/pgvector#397]
## Problem

Selecting parallel workers for HNSW follows a similar method to IVFFLAT, i.e. leveraging the PostgreSQL [`plan_create_index_workers`](https://github.com/pgvector/pgvector/blob/81d13bd40f03890bb5b6360259628cd473c2e467/src/hnswbuild.c#L868) function, which uses the number of [heap (table) pages](https://github.com/postgres/postgres/blob/5e8674dc83926f52516f847f1a77e8d38e94e143/src/backend/optimizer/plan/planner.c#L6782) return from `estimate_rel_size` to determine the number of parallel workers to use.

This makes sense for B-tree / IVFFLAT as the time spent is in the loading the data from the table vs. calculations. But for HNSW, we're likely underestimating the number of workers we could use to speed up the builds as the HNSW process is much more CPU heavy. For example, review the [charts in this blog post][1] that show how we can increase concurrent inserts and can continue scaling the amount of inserts per second.

We can see this play out in practice. Using a similar sample to [aforementioned blog post][1] on a 64-core m7gd.16xlarge instance, I created a table with 1,000,000 128-dim vectors. With enabling parallel builds, PostgreSQL elected to spawn 4 parallel workers (+ leader). 

```
DEBUG:  building index "vecs_embedding_idx1" on table "vecs" serially
DEBUG:  using 4 parallel workers
DEBUG:  worker processed 195944 tuples
DEBUG:  worker processed 188874 tuples
DEBUG:  worker processed 191066 tuples
DEBUG:  worker processed 202636 tuples
DEBUG:  leader processed 221480 tuples
CREATE INDEX
Time: 1231821.044 ms (20:31.821)
```

For the same data set, I hardcoded to use 8 parallel workers (+leader), and saw a significant speedup:

```
CREATE INDEX ON vecs USING hnsw(embedding vector_l2_ops);
DEBUG:  building index "vecs_embedding_idx1" on table "vecs" serially
DEBUG:  using 8 parallel workers
DEBUG:  worker processed 115220 tuples
DEBUG:  worker processed 107338 tuples
DEBUG:  worker processed 107044 tuples
DEBUG:  worker processed 113260 tuples
DEBUG:  worker processed 112210 tuples
DEBUG:  worker processed 116858 tuples
DEBUG:  worker processed 109480 tuples
DEBUG:  worker processed 107654 tuples
DEBUG:  leader processed 110936 tuples
CREATE INDEX
Time: 472148.986 ms (07:52.149)
```

We're still likely falling to [underestimating parallel workers due to TOAST][2], but this case is not affected by that as a 128-dim vector is not TOAST'd. Additionally, as mentioned, HNSW index builds are CPU bound, so we'd want to maximize the number of cores we can use for the process. (There's still considerations around shared/temporary memory, but I'm seeing the brunt of the issue around using CPU)

## Proposal

I propose allowing for a parameter to explicitly set the number of workers used , `hnsw.parallel_workers_for_build`. If the user sets this parameter, we would honor it as long as it is less-than-or-equal-to `max_parallel_maintenance_workers` (and possibly `max_parallel_workers`, but i'd want to check the checks for launching parallel workers to see if we need those checks).

[1]: https://aws.amazon.com/blogs/database/accelerate-hnsw-indexing-and-searching-with-pgvector-on-amazon-aurora-postgresql-compatible-edition-and-amazon-rds-for-postgresql/
[2]: https://www.postgresql.org/message-id/ad8a178f-bbe7-d89d-b407-2f0fede93144%40postgresql.org

**Comment by ankane** [comment]
Hey @jkatz, since it's currently possible to set the number of parallel workers with:

```sql
SET max_parallel_maintenance_workers = 8;
SET min_parallel_table_scan_size = 1;
```

I'm hesitant to add a new option for this (as it can be set in the session used for `CREATE INDEX` without affecting other sessions).

**Comment by jkatz** [comment]
@ankane I'll rerun the tests with those settings, but I believe it will still (significantly) undercount the number of workers for the purposes of a HNSW build.

**Comment by ankane** [comment]
I think setting `min_parallel_table_scan_size` to 1 will pretty much always have it use `max_parallel_maintenance_workers` ([relevant code](https://github.com/postgres/postgres/blob/REL_16_1/src/backend/optimizer/path/allpaths.c#L4248-L4255)), but let me know if you're seeing something different.

**Comment by jkatz** [comment]
@ankane I took your recommendation and applied it on a table with 10MM 1536-dim vectors. I have `max_parallel_maintenance_workers` set to 64. I used `min_parallel_table_scan_size` of `1`.

The initial stats were such:

```
CREATE INDEX ON vecs USING hnsw (embedding vector_cosine_ops) WITH (ef_construction=100);
DEBUG:  building index "vecs_embedding_idx" on table "vecs" serially
DEBUG:  using 11 parallel workers
```

I just completed a run using 24 parallel workers (hardcoded) that took ~3h30m. I'm working on the 11 parallel workers now to get the time comparison, but based on previous testing my hypothesis is that we're leaving [significant performance on the table][1].

[1]: https://aws.amazon.com/blogs/database/accelerate-hnsw-indexing-and-searching-with-pgvector-on-amazon-aurora-postgresql-compatible-edition-and-amazon-rds-for-postgresql/

**Comment by ankane** [comment]
My bad, should have tried it with higher values. There's also:

```sql
ALTER TABLE vecs SET (parallel_workers = 64);
```

but setting it on the table isn't ideal, so a new option makes sense.

I think `hnsw.max_parallel_maintenance_workers` would be good for consistency. I also think there should probably be simple formula for it (for instance, it probably doesn't make sense to use 64 workers for 100 rows), and it should use the value on the table if set.

**Comment by ankane** [comment]
Another idea would be to use `max_parallel_maintenance_workers` directly in a simple formula (this way, users don't need to set three different values - `max_parallel_workers`, `max_parallel_maintenance_workers`, and a new option - to increase it).

**Comment by jkatz** [comment]
I'd originally thought of proposing `hnsw.max_parallel_maintenance_workers` but when thinking through how someone would use it, they'd more likely end up with selecting the value of parallel workers they want.

I'm not opposed to the formula-based approach, and leveraging `parallel_workers`, but I think we're then giving an opinion on how a parallel sequential scan on the table should behave vs. just the index build process. For example, for a parallel sequential scan it may make sense to use *less* workers as it's not doing the same amount of distance calculations per operation and we're more likely to be memory bound. It also **is** the number of workers that PostgreSQL will choose for a parallel sequential scan ([source][2]), only `max_parallel_workers` will override it (vs. `max_parallel_workers_per_gather`).

I do think there is a delicate balance here between what a developer / data scientist would do here vs. a DBA, and I do agree we should find the simplest approach.

(Also, as it sounds like you're OK with this approach, I'm going to cancel my 11 worker run as it is exceeding the original runtime and I'd like to kick off some other tests before the night ends :smile:)

[1]: https://www.postgresql.org/docs/current/sql-createtable.html#RELOPTION-PARALLEL-WORKERS
[2]: https://github.com/postgres/postgres/blob/43b46aae12b220b7eca8250c6c361083f35985a0/src/backend/optimizer/path/allpaths.c#L4219

**Comment by ankane** [comment]
`max_parallel_maintenance_workers` (over a new option) seems simplest to me, and I think it'd be good to respect `parallel_workers` if set on the table to be consistent with btree and ivfflat (although it shouldn't be common). If that sounds good, will go ahead and merge the branch.

For the formula, I think we could use the specified value in most cases (just prevent extremes), but happy to hold off for now.

**Comment by jkatz** [comment]
Ah I misread something in the formula -- I agree with the [hnsw-parallel-workers][1] proposal!

[1]: https://github.com/pgvector/pgvector/compare/hnsw-parallel-workers

**Comment by ankane** [comment]
Yeah, planning to add to the readme right before the release. Great find!

**Comment by jkatz** [comment]
@ankane Thanks for the quick turnaround!

**Comment by jkatz** [comment]
FYI I did test this patch and it works as expected. In my case I had `max_parallel_maintenance_workers` set to `64` and for the same data set in https://github.com/pgvector/pgvector/issues/397#issuecomment-1879384408, had this runtime:

```
Time: 10582211.740 ms (02:56:22.212)
```

While I was at the point of diminishing returns at that data set with 64 workers, it was inline with the 24 worker test (which I had previously hardcoded) and definitely better than the 11 workers that were being spawned. As such, this patch will help with letting users speed up initial HNSW indexing. Thanks!
