### ISSUE TITLE
Is there any way to get all records present in a collection?

### ISSUE THREAD

**Issue by rpanda-techgrit** [pgvector/pgvector#398]
Usecase: I want to summarize an entire document at some point after embedding. I wish to use all chunks from the document. This can be possible only if we get all the doc chunks at once.

I wish get_relevant_documents worked with empty query. Filters would still work the way they are working currently.

**Comment by ankane** [comment]
@rpanda-techgrit For the `get_relevant_documents` suggestion, I'd recommend following up with LangChain.
