### ISSUE TITLE
Output returns 1 result although setting LIMIT 5 after creating index

### ISSUE THREAD

**Issue by khang-nguyen2907** [pgvector/pgvector#40]
Hi, I am using pgvector to store 128-dimensional embedding vectors. I am using `<->` operation to calculate L2 distance between a given 128-dimensional embedding vector and more than my 100 128-dimensional embedding vectors I already stored in postgresql. Before creating index with ```CREATE INDEX ON <my_table_name> USING ivfflat (embedding vector_l2_ops);```. I query with ```SELECT * FROM <my_table_name> ORDER BY embedding <-> '<given_vector>' LIMIT 5;```, it returns 5 results. However, after creating index, run the same query command, it just returns 1 result, sometimes is 2 but there are not 5 results returned. I am very confused and have been doing research about this problem but it is hopeless. Would anybody help me? Thank you in advance.

**Comment by ankane** [comment]
Hey @khang-nguyen2907, check out #32.
