### ISSUE TITLE
HNSW performance questions

### ISSUE THREAD

**Issue by AlexandrosKal** [pgvector/pgvector#400]
I have a couple of questions regarding the HNSW index:

1. I have seen the user "jkatz" that seems to be an active contributor recommend to first create the HNSW index and then do concurrent inserts to the table for it to build faster. I have tried this and compared it with first bulk inserting all the vectors and then creating the index. The second approach is faster and the gap gets bigger as I benchamrk bigger datasets. If there is some Python snippet that properly implements the concurrent inserts please point me to it because I am afraid I might be missing something.
2. For some of the parameters related to postgres such as: max_parallel_maintenance_workers, maintenance_work_mem, work_mem, etc. what is a recommended value that one should start experimenting with ? I used 25% of my RAM for maintenance_work_mem, work_mem and the number of cores of my cpu for max_parallel_maintenance_workers. 
3. Can someone please clarify what happens in the case that I create an HSNW index on a huge dataset, and the index cannot fit in memory completely. How is the performance impacted in that case ? Will the ANN searches slow down considerably ?

Thanks for your effort in developing this extension !

**Comment by jkatz** [comment]
@AlexandrosKal For (1), which version of pgvector are you using? Can you provide some more information about your data set (e.g. how many vectors, what dimensionality) and the various build parameters you are using for your index? Do you have additional info about your client/server machine specs. Can you also share an example of the code you are using to perform the concurrent inserts?

(2) This is difficult to answer without knowing more about the environment you are running in as well as your anticipated workload.

(3) This depends on a number of factors, e.g. the size/storage of your vectors, the valueof `hnsw.ef_search`, how much of your workload will be in memory vs. on disk etc. Having more info about your workload will help provide guidance.

**Comment by AlexandrosKal** [comment]
Thanks for the quick reply! For (1) I am using pgvector 0.5.1 through docker. For my index I have tried different parameters and all provide the same discrepancy in performance, my latest tests where with m=64 and ef_construction=128 (I wanted to test for very high recall). For my dataset, I will be using SentenceTransformer 512-dim vectors, right now I am benchmarking with randomly generated vectors. I am currently testing in my laptop and it has an 8 core M1 pro cpu and 16 GB of RAM. 


I will provide some code snippets now:

```python
import psycopg2
from pgvector.psycopg2 import register_vector
from psycopg2 import pool
# db params defined here
conn_pool = pool.ThreadedConnectionPool(1, 10, **db_params)

conn = conn_pool.getconn()
conn.autocommit = True
cur = conn.cursor()
register_vector(conn)
cur.execute('CREATE EXTENSION IF NOT EXISTS vector')
cur.execute('DROP TABLE IF EXISTS documents')
cur.execute('CREATE TABLE documents (id bigserial PRIMARY KEY, content text, embedding vector(512))')
cur.execute('CREATE INDEX ON documents USING hnsw (embedding vector_cosine_ops) WITH (m = 64, ef_construction = 128);')
conn_pool.putconn(conn)

import numpy as np
import time

vectors = np.random.rand(10000, 512)
inputs = ["My dog is lazy" for i in range(10000)]

embeddings = list(vectors)

print("Data generated")


start = time.time()
from concurrent.futures import ThreadPoolExecutor

def insert(content, embedding):
    # get a connection from the pool
    conn = conn_pool.getconn()
    conn.autocommit = True
    with conn:
        with conn.cursor() as cur:
            cur.execute('INSERT INTO documents (content, embedding) VALUES (%s, %s)', (content, embedding))
    conn_pool.putconn(conn)

with ThreadPoolExecutor(max_workers=8) as executor:
    for content, embedding in zip(inputs, embeddings):
        executor.submit(insert, content, embedding)

print('Insertion took: ', time.time() - start)
```

For the bulk insert I do this without creating the index from the start:
```python
### ... ###
from psycopg2.extras import execute_values
start = time.time()
conn = conn_pool.getconn()
conn.autocommit = True
execute_values(cur, 'INSERT INTO documents (content, embedding) VALUES %s', [(content, embedding) for content, embedding in zip(inputs, embeddings)])
cur.execute('CREATE INDEX ON documents USING hnsw (embedding vector_cosine_ops) WITH (m = 64, ef_construction = 128);')
print('Insertion took: ', time.time() - start)
```

For 10k vectors the multithreading approach takes ~2 min while the other ~1 min. If I increase the number of vectors the gap increases. (Should I use different processes instead of threads ?)

(2) I am thinking of running this in a VM with an 8 core cpu and 32gb of RAM. A web application will also run in that VM and that application will consume ~20 GB of RAM so the majority of it. 

(3) The last question was more of a theoretical one for the edge case. Let's say I index 1TB of those 512dim vectors and the index is larger than the available ram and I have an ef_search=64 then what will happen ? How is the disk vs memory workload decided is it automatically done by pgvector or do I configure it somehow ? Does it load parts of the index in memory ?


Thanks in advance, I really appreciate the time you put here with the community.

**Comment by AlexandrosKal** [comment]
@jkatz Mentioning you here in case you missed my reply.

**Comment by ankane** [comment]
Hi @AlexandrosKal,

1. Parallel index builds should be coming soon (#409)

2. [PgTune](https://pgtune.leopard.in.ua/) is a good place to start for server parameters. If you're also running a web app on the same server, use the memory you want to dedicate to Postgres rather than the total memory (for instance, 10 GB). 

    Increasing `maintenance_work_mem` can speed up HNSW index creation if it allows the graph to stay in memory ([more info](https://github.com/pgvector/pgvector#index-build-time)). If you need to increase it, I'd only do this in the session used to create the index (and the leave the server value as the PgTune recommendation).

3. Postgres handles memory management. Pages (8 KB blocks) that are accessed often will stay in memory (pages of the index will go in and out of memory as needed).
