### ISSUE TITLE
Memory is becoming fully exhausted during the generation of embeddings, leading to a complete server crash.

### ISSUE THREAD

**Issue by vjaideep08** [pgvector/pgvector#401]
Hi all
I am trying to create embeddings for 15 lakh rows of data using sentence-transformers/all-MiniLM-L6-v2 for an application and upload embeddings to pgVector database.
While creating embeddings the server memory (RAM) is getting completely exhausted and getting crashed.
In future we want to scale thie same for 20 Crore rows if data 

Please help me here.

**Comment by ankane** [comment]
Hi @vjaideep08, this doesn't seem like an issue with pgvector. Please use other resources for help.
