### ISSUE TITLE
I would like help understanding how to operate an app with vector indexes

### ISSUE THREAD

**Issue by danthedaniel** [pgvector/pgvector#403]
Hopefully any answers here can get added to the readme.

It seems implied by the readme that we need to have data already in an indexed column in order for a newly built index to be useful. That makes me think that I can not index as I would for a normal column type, ex:

1. Define the table's schema, including the index
2. Deploy my app and run a migration, now I have an empty table and index
3. Users add data to the table. As rows are appended the index gets incrementally re-organized to keep the tree balanced. Lookups remain fast throughout this process.

But if there needs to be data already in the column for a index to be useful, this might be significantly more complicated. Not to mention that each user's vectors could be from wildly different domains, which would make one global index less useful than an index for each domain.

So this looks like it could be significantly more complicated - but maybe I don't understand right. If anyone has some practical experience in using pgvector with real user data I'd love to hear more about this. And any good advice should get added to documentation for the repo.

For me, thankfully, it seems indexing on a foreign key and then doing a scan for embedding distance will work short-term. But I'd love to know more for when that starts to become a performance bottleneck.

**Comment by ankane** [comment]
Hi @danthedaniel, that's exactly how indexing works with HNSW. For IVFFlat, there's a training step when the index is created, so it's a bit more complicated, but [documented here](https://github.com/pgvector/pgvector#ivfflat).

**Comment by jkatz** [comment]
How you index the data depends on the index type. For HNSW, you can iteratively add data as you do for other index types. For IVFFLAT, you need to have data that already exists in your table to build the index. If you're curious more about the difference between the two, I [recently gave a presentation][1] (and [slides][2] from another version of the same talk) that goes deep into how both work.

[1]: https://www.youtube.com/watch?v=PhIC4JlYg7A&ab_channel=AWSEvents
[2]: https://www.postgresql.eu/events/pgconfeu2023/sessions/session/4592/slides/435/pgconfeu2023_vectors.pdf

**Comment by danthedaniel** [comment]
Ah thank you! I missed this sentence:

> There’s also no training step like IVFFlat, so the index can be created without any data in the table.

Here's what I'd add to the docs to make it easier for readers to see what differences exist: https://github.com/pgvector/pgvector/pull/404
