### ISSUE TITLE
Does ivvflat index has max query result limit?

### ISSUE THREAD

**Issue by FingerLiu** [pgvector/pgvector#405]
I have 20 million embeddings indexed with ivvflat, it can't return any record when I set offset to a large value.

Is this by design or bug?

Question: If by design, does ** lists** when creating index, and **probes** when querying effect the max return record limit?
I want to get all records sorted by similarity to the given embedding， is it possible?

Example:

This can return 20 records.
``` sql
select * from my_embedding order by embedding <=> '[0,0,1,...]' offset 10 limit 20;
```

This return nothing.
``` sql
select * from my_embedding order by embedding <=> '[0,0,1,...]' offset 10000 limit 20;
```

I noticed after setting ivfflat.probes = 10, it is "better" than default probes 10, it can return records with offset 10000, but when I set a larger offset(100000), it returns anything.

**Comment by ankane** [comment]
Hi @FingerLiu, this is part of the index type. If you have 20 million rows and 4,000 lists, each list will have 5,000 rows on average. For probes = 1, you'll get back 5,000 rows on average, for probes = 2, 10,000 rows, etc. If the offset is greater than this, you won't get any rows. A good place to start for the number of probes is `sqrt(lists)`.

If you want to get all the rows sorted by distance, a few options are:

1. Don't add an index
2. Set `ivfflat.probes` to the number of lists
3. Set `enable_indexscan` to `off`

**Comment by FingerLiu** [comment]
Thanks!
