### ISSUE TITLE
[Question]Need help with the pgvector Installation with pgAdmin & version mismatch error

### ISSUE THREAD

**Issue by nx-chen** [pgvector/pgvector#408]
Hello,

I have installed 'pgAdmin 4 v8.2' on macOS. After successfully installing the software, I proceeded to run the command CREATE EXTENSION vector;

However, I encountered an error: 
![image](https://github.com/pgvector/pgvector/assets/74989793/3058862e-498a-4067-a8f7-e2fdba4e602b)

so I attempted to solve the issue by using the following commands in my terminal:
`cd /tmp
git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git
cd pgvector
make
make install `

The error is still the same, i've tried `brew install pgvector`too. 

In the folder "pgvector", 

I also tried this line of command `export PG_CONFIG=/Library/PostgreSQL/16/bin/`

and copy "pgvector/sql/vector--0.5.1.sql" and "vector.control" into the folder "extension"
<img width="730" alt="Screenshot 2024-01-15 at 16 26 26" src="https://github.com/pgvector/pgvector/assets/74989793/40a29e2d-0824-4a88-9cf8-d7444b0066af">
![image](https://github.com/pgvector/pgvector/assets/74989793/9ca2a14a-9003-43a7-b6b1-c02de3165497)

Unfortunately, the error evolved to ![image](https://github.com/pgvector/pgvector/assets/74989793/9fb7a1c8-4525-4fdd-99b9-40795354e1d0)

I am reaching out for assistance. Could anyone provide guidance or insights into resolving this matter?

Thanks

**Comment by jkatz** [comment]
This sounds like the PostgreSQL instance that you're connecting to from pgAdmin is not the same one you're installing the pgvector package to.

**Comment by nx-chen** [comment]
> This sounds like the PostgreSQL instance that you're connecting to from pgAdmin is not the same one you're installing the pgvector package to.

Thank you for your response. After checking in pgAdmin, I found that it is connected to the path `/Library/PostgreSQL/16/data`,  You can find the confirmation in the screenshot below:
![image](https://github.com/pgvector/pgvector/assets/74989793/9e7f3189-6e28-4d19-b139-03b6bae67c6b)

And I installed pgvector in the path `/Library/PostgreSQL/16/share/postgresql/extension`

I'm not sure that is the issue., or perhaps I didn't get it right ?

**Comment by ankane** [comment]
Hi @nx-chen, from the error message, it looks like pgvector isn't properly installed at that location.

Make sure `PG_CONFIG` points to the `pg_config` program (rather than the `bin` directory) before compiling (run `make clean` after changing) and that the `make install` output has the correct location ([more info](https://github.com/pgvector/pgvector#postgres-location)).

**Comment by nx-chen** [comment]
> Hi @nx-chen, from the error message, it looks like pgvector isn't properly installed at that location.
> 
> Make sure `PG_CONFIG` points to the `pg_config` program (rather than the `bin` directory) before compiling (run `make clean` after changing) and that the `make install` output has the correct location ([more info](https://github.com/pgvector/pgvector#postgres-location)).

Hi, thank you for your response. I followed your instructions:

In the "pgvector" folder, I relaunched the command `export PG_CONFIG=/Library/PostgreSQL/16/bin/pg_config`, then I ran `sudo make clean` and `sudo make`.

However, when attempting to execute the command `sudo --preserve-env=PG_CONFIG make install`, I encountered some error messages (The same error occurs when I run `make install` without using `sudo`):

<img width="843" alt="Screenshot 2024-01-17 at 09 41 21" src="https://github.com/pgvector/pgvector/assets/74989793/36013e13-7fb5-4a7c-aa12-acd3b3bb93b3">


I forgot to mention that I am working on MacOS (Apple Silicon). Could this be causing the installation issues?

**Comment by ankane** [comment]
It seems like something may be off with either your build environment or Postgres installation. I'd try reinstalling Xcode Command Line Tools to see if it gets rid of the `no such sysroot directory` warning. If that doesn't work, I'd try to see if it installs with Homebrew Postgres, or try [another installation method](https://github.com/pgvector/pgvector#additional-installation-methods).

**Comment by nx-chen** [comment]
> It seems like something may be off with either your build environment or Postgres installation. I'd try reinstalling Xcode Command Line Tools to see if it gets rid of the `no such sysroot directory` warning. If that doesn't work, I'd try to see if it installs with Homebrew Postgres, or try [another installation method](https://github.com/pgvector/pgvector#additional-installation-methods).

I have resolved the issue of the 'no such sysroot directory' warning, and all 'make' commands now run successfully. 

However, when attempting to retry `CREATE EXTENSION IF NOT EXISTS vector; ` In PostgreSQL, I encountered a version mismatch error:
<img width="776" alt="Screenshot 2024-01-18 at 10 57 32" src="https://github.com/pgvector/pgvector/assets/74989793/461eb9d4-9152-448c-a905-fe44db233bd9">

I tried rerun : 
`sudo make uninstall`
`sudo make clean`
`sudo make`
`sudo make install`

Unfortunately, this did not resolve my problem. Is there a way to update the version of pgvector, or should I consider installing version 14 of PostgreSQL?"

**Comment by ankane** [comment]
That error means the extension is being compiled against a different installation of Postgres. Can you delete `/tmp/pgvector`, then paste the full output of the following commands (with any personal info removed)?

```sh
export PG_CONFIG=/Library/PostgreSQL/16/bin/pg_config
cd /tmp
git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git
cd pgvector
make
sudo --preserve-env=PG_CONFIG make install
```

**Comment by nx-chen** [comment]
I followed your advice, and it worked! I have successfully created the 'vector' extension just now 
Thanks a lot :) 

FYI, I still left the full output here :
<img width="1150" alt="Screenshot 2024-01-19 at 09 44 49" src="https://github.com/pgvector/pgvector/assets/74989793/bc1d6698-0d51-4f9d-80a7-fb321111b97f">

**Comment by nx-chen** [comment]
> That error means the extension is being compiled against a different installation of Postgres. Can you delete `/tmp/pgvector`, then paste the full output of the following commands (with any personal info removed)?
> 
> ```shell
> export PG_CONFIG=/Library/PostgreSQL/16/bin/pg_config
> cd /tmp
> git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git
> cd pgvector
> make
> sudo --preserve-env=PG_CONFIG make install
> ```

**Comment by rjindal14** [comment]
@nx-chen - could you advice on the steps which you took to resolve CLANG warning?

**clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]**

I'm also trying to install pgvector extension on PostgreSQL 16. I executed the below instructions as given by @ankane and also mentioned in pgvector's github page but to no avail. Also, I dont have any other installation of postgresql on my machine.

`export PG_CONFIG=/Library/PostgreSQL/16/bin/pg_config
cd /tmp
git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git
cd pgvector
make
sudo --preserve-env=PG_CONFIG make install`

Lastly, I checked and my machine is having xcode command line tools.
`xcode-select version 2405.`

I'm on MacOS Sonoma running on M2.
