### ISSUE TITLE
[BUG] extension "pgvector" is not available

### ISSUE THREAD

**Issue by fccoelho** [pgvector/pgvector#414]
I get this extension not available message when I try to to run the 

```sql
create extension pgvector;
```
I am on ubuntu with postgresql-15 and postgresql-15-pgvector installed via DEB packages.

I also   built and installed pgvector from source, to no avail. Although the compilation and installation terminated without errors.

What am I missing?

**Comment by hlinnaka** [comment]
The name of the extension is `vector`, rather than `pgvector`. Try:
```
CREATE EXTENSION vector;
```

**Comment by fccoelho** [comment]
found my mistake! it's
```sql
create extension vector;
```
solved.
