### ISSUE TITLE
Drop support for PostgreSQL v11

### ISSUE THREAD

**Issue by hlinnaka** [pgvector/pgvector#415]
Last minor release of PostgreSQL v11 was in Nov 2023, and it is now end-of-life (see [versioning policy](https://www.postgresql.org/support/versioning/)). I propose that we bump up the minimum required version to v12, to allow cleaning up a bunch of #ifdefs.

```
$ git grep -E "PG_VERSION_NUM.*1200??" | wc -l
55
```

I can create a PR if you agree, @ankane.

**Comment by jkatz** [comment]
I'm not opposed, but I'd suggest waiting until a minor version bump (e.g. `0.6.0`) before doing so.

**Comment by ankane** [comment]
Yeah, I'd like to only do this in minor versions (rather than patch).

**Comment by ankane** [comment]
Since the next release will now be 0.6.0, did this in a1e526ef828842ff4b04af6536f0a28692d13eb0.
