### ISSUE TITLE
Can HNSW/ IVVFlat INDEXES co exist?

### ISSUE THREAD

**Issue by aiseei** [pgvector/pgvector#420]
A noob question: 
If we create index using both - will they conflict at query time ? what is the best way to  force to use or the other ?

Any advice is much appreciated!

Thanks

**Comment by ankane** [comment]
Hi @aiseei, the Postgres planner will choose the one with the lowest cost (use `EXPLAIN ANALYZE` to see which). You can discourage the planner from using an IVFFlat index by setting `ivfflat.probes` to the same value as `lists`. There's not really a great way to encourage it to use an IVFFlat index over an HNSW index right now (but I don't think this situation is common).
