### ISSUE TITLE
Pgvector v0.5.1 compatibility with PostgreSQL 16.1 - MacOS

### ISSUE THREAD

**Issue by rjindal14** [pgvector/pgvector#425]
Hi,

I'm trying to install Pgvector v0.5.1 with PostgreSQL 16.1 on my MacOS (Macbook Pro M2). 
However, I've been unsuccessful with the error: server is 16 but library is 14.

The steps which I've been following are:
1) Installed PostgreSQL 16.1 by EBD
2) I checked via Pgadmin 4 and the postgresql is working fine. I successfully created a new database
3) I did: git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git using terminal
4) Ran the command inside pgvector folder: sudo --preserve-env=PG_CONFIG make install
5) Executed the sql command to create vector extension with the database

Could you confirm if pgvevtor v0.5.1 is compatible with PS 16.1 on MacOS?

**Comment by ankane** [comment]
Hi @rjindal14, it is compatible. Check out #408.
