### ISSUE TITLE
Querying variable dimension vector with pgvector 0.5.1

### ISSUE THREAD

**Issue by ostefano** [pgvector/pgvector#426]
I am using pgvector 0.5.1 and I can't select vector fields with different dimensionality than the last vector I have inserted.

The error I receive when ordering by a vector with dimensionality 4  is `Error in query: ERROR: different vector dimensions 3 and 4` if the last inserted record had dimensionality 3.

**Comment by ankane** [comment]
Hi @ostefano, vectors must have the same dimensions to have a distance. If you use a variable dimension column, you'll need to filter for vectors that have the same dimensions.

```sql
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector);
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5]');
SELECT * FROM items WHERE vector_dims(embedding) = 3 ORDER BY embedding <-> '[3,1,2]' LIMIT 5;
```

**Comment by itinance** [comment]
> ```sql
> SELECT * FROM items WHERE vector_dims(embedding) = 3 ORDER BY embedding <-> '[3,1,2]' LIMIT 5;
> ```

Thank you so much @ankane! I was looking for such a solution as well.

In order to support indexes on the term `vector_dims(embedding)` it would make sense to have a separate column that contains the respective value. Or is there a better approach?

**Comment by ankane** [comment]
You'll typically want to have another column like `model_id` since you don't want to compare embeddings across models, even if they have the same number of dimensions ([example](https://github.com/pgvector/pgvector?tab=readme-ov-file#can-i-store-vectors-with-different-dimensions-in-the-same-column)).
