### ISSUE TITLE
`ERROR:  different vector dimensions` When there are vectors of different dimensions

### ISSUE THREAD

**Issue by Abirdcfly** [pgvector/pgvector#428]
Here is an example of minimal replication:
```
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector);
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]');
```
Then the query is returning results as expected:
```
SELECT*,embedding<=>'[3,1,2]' FROM items WHERE embedding<=>'[3,1,2]'<0.5 
```
But the query goes wrong when inserting vectors of different dimensions:
```
INSERT INTO "public"."items" ("embedding") VALUES ('[7,8]');
```
Then the query will return an error `ERROR:  different vector dimensions 2 and 3`

The same error is reported even if the vector's dimension is specified in the query:

```
SELECT*,embedding<=>'[3,1,2]' FROM items WHERE embedding<=>'[3,1,2]'<0.5 AND vector_dims(embedding)=3
```

So, what should I do if I want to filter by distance in a table that stores vectors of different dimensions?

**Comment by ankane** [comment]
Hi @Abirdcfly, it looks like you'll need to use a materialized CTE to make sure filtering on dimensions happens first.

```sql
WITH filtered_items AS MATERIALIZED (SELECT * FROM items WHERE vector_dims(embedding)=3) 
    SELECT*,embedding<=>'[3,1,2]' FROM filtered_items WHERE embedding<=>'[3,1,2]'<0.5;
```

pgvector could possibly return `NaN` instead of throwing an error for different dimensions in a future release to avoid the need for this, but need to think it through more.
