### ISSUE TITLE
HNSW Indexing Times Issue

### ISSUE THREAD

**Issue by jcrupi** [pgvector/pgvector#430]
We have a table with about 7.5 mil rows which has a "vector" field.

Initially we were using a flat index. Now we want to reindex using HNSW.

The approach we are taking is to 

1. Create another table "like original" but with HNSW index
2. Iterate through original table, take 10k batch of rows and insert in new table with HNSW

See full script we are using attached.

Initially a batch of 10k took about 6 min to insert. 

psql:script.sql:60: INFO:  Copying Data count = 7638206 with step = 10000, starting time 16:01:56.892499+00 ...
psql:script.sql:60: INFO:  Sleeping for 10 seconds 1 of 763. 16:06:53.862974+00
psql:script.sql:60: INFO:  Sleeping for 10 seconds 2 of 763. 16:12:46.032663+00

However now when we on batch 477 it takes 40 min

psql:script.sql:60: INFO:  Sleeping for 10 seconds 476 of 763. 13:55:45.686266+00
psql:script.sql:60: INFO:  Sleeping for 10 seconds 477 of 763. 14:32:34.734031+00

The DB is not stressed, we are using about 30% of RAM and 10% of CPU. 

Is it expected that with HNSW inserts performance degrades so much as the number of rows in the table grows.

Is there a better way to accomplish our goal - create an HNSW index on a large table.

8 vCores, 32 GiB memory, 12800 max iops

Below is the script we are using. 

DO
$$
    DECLARE
        ddl_completed    BOOLEAN := FALSE;
        embeddings_count INT8;
        step             INT4    := 10000;
        embedding_ids    UUID[];
        counter          INT4    := 0;
        sleeps_count     INT4;
    BEGIN
        RAISE INFO 'Starting copying table embedding...';
        CREATE TABLE IF NOT EXISTS "public".embedding_copy
        (
            LIKE "public".embedding_text_embedding_ada_002 INCLUDING ALL
        );

 	RAISE INFO 'Creating index...';
        CREATE INDEX  IF NOT EXISTS embedding_ada_002_hnsw_24_200_cosine_idx
            ON "public".embedding_copy USING hnsw (vector_content vector_cosine_ops) WITH (m = 24, ef_construction = 200);

        RAISE INFO 'Creating array of ids...';
        SELECT array(SELECT id FROM "public".embedding_text_embedding_ada_002)
        INTO embedding_ids;

        SELECT array_length(embedding_ids, 1) INTO embeddings_count;
        RAISE INFO 'Copying Data count = % with step = %, starting time % ...', embeddings_count, step, CURRENT_TIME;
        sleeps_count := embeddings_count / step;

        FOR i IN 1..embeddings_count BY step
            LOOP
                INSERT INTO "public".embedding_copy (id, vector_content, chunk_id, collection_id)
                SELECT id, vector_content, chunk_id, collection_id
                FROM "public".embedding_text_embedding_ada_002
                WHERE id IN (SELECT *
                             FROM (SELECT unnest(embedding_ids)) AS arr
                             OFFSET i LIMIT step);
                COMMIT;

                counter := counter + 1;
                RAISE INFO 'Sleeping for 10 seconds % of %. %', counter, sleeps_count,CURRENT_TIME;

                DO
                $SLEEP$
                    BEGIN
                        PERFORM pg_sleep_for(INTERVAL '10 sec');
                    END;
                $SLEEP$;
            END LOOP;

        ddl_completed := TRUE;

        IF
            ddl_completed THEN
            RAISE INFO 'DDL has been successfully completed, finished time % ...', CURRENT_TIME;
        ELSE
            RAISE EXCEPTION 'Failed to perform DDL.';
        END IF;
    END
$$ LANGUAGE plpgsql;

**Comment by ankane** [comment]
Hi @jcrupi, you should see better performance by inserting the data before creating the index and increasing `maintenance_work_mem` so as much of the graph as possible fits into memory ([docs](https://github.com/pgvector/pgvector#index-build-time)). With 7.5 million 1536-dimensional vectors, the graph won't fit into 32 GB of memory, which is fine, but the [build progress](https://github.com/pgvector/pgvector#indexing-progress) will slow down when that happens. Currently, it'll only use one core, but this will be addressed in 0.6.0 (#409).
