### ISSUE TITLE
Error creating index on materialized view

### ISSUE THREAD

**Issue by ucals** [pgvector/pgvector#431]
I created a materialized view in which a column is a vector resulting from a pre-processing step (averaging embeddings and grouping to get the centroids for each group).

The materialized view is created without any problems.

Now, I'm trying to create an index over this vector column, as I would do with a table. 
However, running this command outputs the following error message:

**ERROR: column does not have dimensions**.

Can someone please help me understand what I'm doing wrong?

Here's a simple example reproducing the error
```SQL
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3), topic_id integer);

INSERT INTO items (embedding, topic_id) VALUES ('[1,2,3]', 1);
INSERT INTO items (embedding, topic_id) VALUES ('[4,5,6]', 1);

INSERT INTO items (embedding, topic_id) VALUES ('[3,2,1]', 2);
INSERT INTO items (embedding, topic_id) VALUES ('[6,5,4]', 2);
INSERT INTO items (embedding, topic_id) VALUES ('[9,8,7]', 2);

CREATE MATERIALIZED VIEW my_view AS
    SELECT topic_id, avg(embedding) AS embedding FROM items GROUP BY topic_id
WITH NO DATA;

REFRESH MATERIALIZED VIEW my_view;

-- This last line is not executed; it throws the error
CREATE INDEX ON my_view USING hnsw (embedding vector_cosine_ops);
```

**Comment by hlinnaka** [comment]
Try this:
```
CREATE MATERIALIZED VIEW my_view AS
    SELECT topic_id, avg(embedding)::vector(3) AS embedding FROM items GROUP BY topic_id
WITH NO DATA;
```
Note the `::vector(3)`

**Comment by ucals** [comment]
Worked perfectly, thanks!
