### ISSUE TITLE
Follow up #425 - pgvector issues with postgresql 16.1 on macOS Sonoma

### ISSUE THREAD

**Issue by rjindal14** [pgvector/pgvector#432]
Hi @ankane 
I'm raising another issue on top of #425.

I followed the process as described in the thread #408 but 'm seeing the below issues. Can you help how can I get rid of this error?
----------------

**clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk' [-Wmissing-sysroot]**
In file included from src/hnsw.c:1:
In file included from /Library/PostgreSQL/16/include/postgresql/server/postgres.h:45:
**/Library/PostgreSQL/16/include/postgresql/server/c.h:59:10: fatal error: 'stdio.h' file not found**

----------------

Below is some info from Terminal:
**echo $SDKROOT**
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk     # not sure why sysroot is pointing to MacOSX11.3.sdk. Also, I dont have MacOSX11.3.sdk on my machine as I'm on Sonoma.

**postgres --version** 
postgres (PostgreSQL) 16.1

**pg_config --includedir-server**
/Library/PostgreSQL/16/include/postgresql/server

**pg_config --libdir**
/Library/PostgreSQL/16/lib. # this was installed using EDB installer

**xcode-select -p**
/Library/Developer/CommandLineTools

xcode-select version 2405

Machine: Macbook Pro M2 running macOS Sonoma

**Comment by ankane** [comment]
Hi @rjindal14, check out https://github.com/pgvector/pgvector#missing-sdk (this is an issue with your build environment rather than pgvector).

**Comment by Luminilion** [comment]
Here's my fix https://github.com/pgvector/pgvector/issues/592#issuecomment-2182679096
