### ISSUE TITLE
text-embedding-3-small not working

### ISSUE THREAD

**Issue by zakariamehbi** [pgvector/pgvector#436]
Hello,

Switched from `text-embedding-ada-002` to `text-embedding-3-small` with the same output dimensions of 1536, but the search isn't working correctly, anyone successfully made it work?

Thank you

**Comment by ankane** [comment]
Hi @zakariamehbi, pgvector works fine with that model (when changing models, you'll need to regenerate the embeddings).

**Comment by zakariamehbi** [comment]
Hey @ankane, I did it but the search returned results with text-embedding-ada-002 but not with text-embedding-3-small, for a basic query
