### ISSUE TITLE
Q: How to estimate max dimensions supported?

### ISSUE THREAD

**Issue by TuhinNair** [pgvector/pgvector#44]
Hey, thanks for authoring this project; really fantastic work.

What is the maximum possible vector size with the pg blocksize set at 32k?

A 1024 dimensions vector would take `4 * 1024 + 8 = 4104 bytes`. This is approximately half of the default 8k blocksize.

I'm unfamiliar with pg internals, but I'm assuming this relationship (max vector memory = 1/2 blocksize) has significance.

Assuming so, would I be correct in estimating ~4000 dimensions (~16k bytes) as an upper limit with the blocksize set at 32k?

The real reason I'm asking this is because I'd like to store and use the largest embeddings provided by OpenAI's davinci model. That's around 12K dimensions. Not possible without dimensionality reduction?

Again, thanks for the amazing work!

**Comment by ankane** [comment]
Hey @TuhinNair, you should be able to fill most of the block, so it'll be closer to 8000 (the current limit is just the largest power of two that'll fit on a single block). However, search speed might be really slow with that number of dimensions. For indexing, you'd probably want to use [product quantization](https://mccormickml.com/2017/10/13/product-quantizer-tutorial-part-1/), which isn't supported yet.
