### ISSUE TITLE
OpenAI's text-embedding-3-large model not compatible with pgvector 5.1

### ISSUE THREAD

**Issue by wmwsagara** [pgvector/pgvector#442]
OpenAI says its new "text-embedding-3-large" embedding model with 3072 dimensions is the "new best performing model" with significantly higher score than "ada v2".
See: https://openai.com/blog/new-embedding-models-and-api-updates

I use only HNSW indexing with cosine distance.

I gave it a try by modifying the src/hnsw.h as follows:
-#define HNSW_MAX_DIM 2000
+#define HNSW_MAX_DIM 8192

But when insert records, it gives following error:
Database error: failed to add index item to "xyz_cosine_idx"

The "failed to add index item to" are only referenced in following files:
./src/ivfbuild.c
./src/ivfinsert.c
./src/hnswinsert.c
./src/hnswvacuum.c
./src/hnswbuild.c

They point to BlockNumber and OffsetNumber based functions which I'm not familiar with.

If someone could develop a patch against pgvector 5.1, I can give it a try and update here.

Best regards
Sagara

**Comment by jkatz** [comment]
Noting that `text-embedding-3-small` is 1536 dimensions and fits within current indexing. The OpenAI docs also mention you can reduce the dimensions for `text-embedding-3-large` if you pass in the dimensions parameter.

I'm not quickly finding this in the docs, but is `text-embedding-3-large` using 4-byte or 2-byte floats? I wonder if releasing the `half` patch would help with the indexing issue.

**Comment by wmwsagara** [comment]
Andrew (@ankane) please let me ask to reopen this issue for the benefit of wider pgvector user community.

1. Which embedding model is suitable for a specific application?
text-embedding-3-small:
"text-embedding-3-small is our new highly efficient embedding model and provides a significant upgrade over its predecessor..."

NOTE: "new highly efficient embedding model"

Comparing text-embedding-ada-002 to text-embedding-3-small, ... the average score on a commonly used benchmark for English tasks (MTEB) has increased from 61.0% to 62.3%.


text-embedding-3-large:
"text-embedding-3-large is our new next generation larger embedding model and creates embeddings with up to 3072 dimensions."

NOTE: "new next generation larger embedding model"

text-embedding-3-large is our new best performing model. Comparing text-embedding-ada-002 to text-embedding-3-large: ... while on MTEB, the average score has increased from 61.0% to 64.6%.


Other models:

voyage-lite-02-instruct: 
MTEB the average score: 67.13 (Best performer on MTEB leaderboard)

https://docs.voyageai.com/embeddings/
Note, "But More advanced and specialized models are coming soon:
    voyage-finance-2: coming soon
    voyage-law-2: coming soon
    voyage-multilingual-2: coming soon
    voyage-healthcare-2: coming soon"

This means, voyage-lite-02-instruct may not be good enough for finance, law, healthcare.

Therefore, text-embedding-3-large (MTEB 64.6%) may be better for finance, law, healthcare than voyage-lite-02-instruct (MTEB 67.13%) unless tests prove otherwise.

Similarly, text-embedding-3-large (MTEB 64.6%) may be better for finance, law, healthcare than text-embedding-3-small (MTEB 62.3%) unless tests prove otherwise.

Of course, from the text-embedding-3-small one may retrieve 1024 dimensions, or may use a lower dimension model and save storage and RAM but what's the point, if real world tests shows for a user a significant loss of accuracy?

See: https://huggingface.co/spaces/mteb/leaderboard

Is MTEB average score 64.6% (text-embedding-3-large) good enough? How about a future model proves to be over 95%?

Please note, I'm not saying higher dimensions are always better, but I'm stressing is, users must have the ability to test which model is suitable for them.


2. Why two different maximum dimensions?

src/vector.h
#define VECTOR_MAX_DIM 16000

src/hnsw.h
#define HNSW_MAX_DIM 2000

Is there a technical reason that HNSW index cannot support VECTOR_MAX_DIM?

**Comment by wmwsagara** [comment]
Jonathan (@jkatz), please note the above comment. Thanks.

**Comment by mateusmirandaalmeida** [comment]
I don't understand why the issue was closed, the problem doesn't seem resolved, the indices don't accept dimensions above 2,000, is that right?

**Comment by wmwsagara** [comment]
Yes, dimensions above 2,000 is still not supported yet.

The decision to ignore the elephant in the room (OpenAI's text-embedding-3-large) is puzzling.

**Comment by jkatz** [comment]
@wmwsagara The 2K indexing limit is not being ignored. There have been numerous discussions about this topic both within the pgvector project and at events. At PGCon 2023, I gave a lightning talk discussing this exact point, as well as various strategies we can use in PostgreSQL to work beyond the limit. Also as mentioned, there are several open branches that can help address it.

That said, @ankane did provide an alternative approach to using the `text-embedding-3-large`. Additionally, you could considering doing some prefiltering of the data with PCA or other information to store it. You can also store it without an index and perform an exact nearest neighbor search. It all depends on your application, which I'm not sure you've provided information about.

The stats you provided showed a 2-4% gain in using the larger dimensionality. I'm many years removed from my machine learning studies, so that could be quite a significant gain. With my database hat on, I read it as having to store 3x the amount of information for a small gain, whereas I could store less and increasing some of my indexing tuning parameters to get better relevancy.

pgvector is open source, and ideas for how to support indexing larger vectors while still utilizing PostgreSQL's storage system (i.e. maintaining ACID compliance) are welcome.

**Comment by xfalcox** [comment]
We are already using `text-embedding-3-large` with pgvector in production by simply passing the dimensions parameter with `2000` as the value.

**Comment by touhi99** [comment]
does hnsw work with halfvec or its still a blocker?

**Comment by touhi99** [comment]
im quite new to the topic. sorry to ask, how do i convert my text-embedding-3-large vector to halfvec or is this part done in pgvector side?

**Comment by jkatz** [comment]
@touhi99 I have some examples in this blog post on [scalar and binary quantization](https://jkatz05.com/post/postgres/pgvector-scalar-binary-quantization/), e.g.:

```sql
CREATE TABLE documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text,
    embedding vector(3072)
);

CREATE INDEX ON documents
    USING hnsw ((embedding::halfvec(3072)) halfvec_cosine_ops);
```
