### ISSUE TITLE
How can Use Max vCPUs at HNSW?

### ISSUE THREAD

**Issue by Tieck-IT** [pgvector/pgvector#444]
- instance: db.r7g.4xlarge (aws RDS)
- dataset : 4.5M ( 1040 dim, np.float32)
- postgres 15.4
- pgvector 0.5.0
- config setting
```sql
SET max_parallel_workers = 16
SET max_parallel_workers_per_gather = 4;
SET maintenance_work_mem = '120GB';
SET max_parallel_maintenance_workers = 16;
SET client_min_messages = DEBUG;   
CREATE INDEX ON image_embedding  USING hnsw (embedding vector_l2_ops) WITH (m = 16, ef_construction = 200);
```

when I change max_parallel_workers , `CREATE INDEX ON` use only 1 vCPU at aws rds(check at aws dashboard). The build time is too slow. how can I use all vCPU at instace's max?

**Comment by ankane** [comment]
Hi @Tieck-IT, parallel index builds for HNSW will be available in 0.6.0. #409
