### ISSUE TITLE
pgvector doesn't get installed if the required LIBS are not in same directory as in PGROOT argument

### ISSUE THREAD

**Issue by Lakshmishirisha** [pgvector/pgvector#445]
We have recently tried to install the pgvector extension and faced issues while running the command, _nmake /F Makefile.win_
The issue that we faced was the file wasn't able to check for required .h files from system environment variables or user environment vars, only the path set for PGROOT was being checked.
So we had to edit the .win file to take another variable and included that path for LIBS in the .win file.
Also we had to add lots of paths to INCLUDE variable, so it can run as expected. 
Could you please edit the .win file so that no one would face such issues, thanks.

**Comment by ankane** [comment]
Hi @Lakshmishirisha, we may be able to update it, but will need more info. Can you share the following (with any personal info removed)?

1. How Postgres was installed
2. The full output of `pg_config`
3. What didn't work - the commands you ran and the full output
4. What worked - the `Makefile` diff, the commands you ran, and the full output
