### ISSUE TITLE
Clarify build instructions for Windows (the missing postgres.h header)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [pgvector/pgvector#448]
I'd be grateful for a more specific hint on how to deal with `fatal error: postgres.h: No such file or directory` on Windows if postgreSQL was deployed using the official pre-built installer.

In https://github.com/pgvector/pgvector?tab=readme-ov-file#missing-header there are only hints for selected Linux distros (to install `postgresql-server-dev-16` package).

**Comment by ankane** [comment]
Hi @jan-tosovsky-cz, can you paste the commands you ran to install pgvector and their full output (with any personal info removed)?

**Comment by jan-tosovsky-cz** [comment]
Trying same steps again, per https://github.com/pgvector/pgvector?tab=readme-ov-file#windows and now it compiles without problems. I suspect I made a typo in PGROOT settings. Feel free to close this.
