### ISSUE TITLE
Publish v0.6.0 to Postgres apt repo

### ISSUE THREAD

**Issue by pratheekrebala** [pgvector/pgvector#449]
First, wanted to say thank you for your work #409. I have been testing that branch against my index of ~3m image embeddings and have seen an improvement in the range of ~10-12x after parallel builds are enabled.

I was checking to see if there's a planned date to publish v0.6.0 to `apt.postgresql.org`? This would greatly simplify the upgrade for us..

I'm happy to help in anyway I can to move this forward.

**Comment by jkatz** [comment]
@pratheekrebala Packaging is independent of pgvector. Please see the PostgreSQL APT project for details: https://wiki.postgresql.org/wiki/Apt

**Comment by pratheekrebala** [comment]
ah! I didn't realize that the packages were maintained outside the project. Looks like @bradfordboyle has write access to the [package repo](https://salsa.debian.org/postgresql/pgvector) and has cut releases in the past...

**Comment by ankane** [comment]
I'm sure there's an existing process for updates.
