### ISSUE TITLE
Problem creating HNSW index after upgrading to 0.6.0

### ISSUE THREAD

**Issue by ucals** [pgvector/pgvector#453]
Hi,
I just upgraded pgvector to 0.6.0 in order to use the parallel index builds for HNSW. Using the 0.5.0 version takes very long for large tables/indexes.

Upgrading was simple: I followed the documentation steps, installing the latest version, and run `ALTER EXTENSION vector UPDATE;` in the database.

Then, when I tried to use it...
```sql
SET maintenance_work_mem = '21GB';  -- server has 32 GB of RAM, and I already know index needs 20 GB
SET max_parallel_maintenance_workers = 7;  -- server has 8 vCPUs
CREATE INDEX ON my_table USING hnsw (embedding vector_cosine_ops);
```

... I saw the following error:
**ERROR:  could not resize shared memory segment "/PostgreSQL.3784411016" to 22545550688 bytes: No space left on device**

However, the server has more than enough disk space and RAM memory available.

Reverting back to pgvector 0.5.0 makes it work... but the index building is slow.

Can anyone help? Thanks

**Comment by ankane** [comment]
Hi @ucals, are you running Postgres in Docker? If so, you'll need to set `--shm-size` ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#docker-1)).

**Comment by ucals** [comment]
Yes! Oh, I missed that... worked perfectly, thanks @ankane ! 
The upgrade is great!!
