### ISSUE TITLE
Does the vector query with distance return result in sorted order?

### ISSUE THREAD

**Issue by gsiddh** [pgvector/pgvector#454]
Hi Folks

The vector query, with distance filter (`SELECT * FROM items WHERE embedding <-> '[3,1,2]' < 5;` ), mentioned in the documentation here (https://github.com/pgvector/pgvector?tab=readme-ov-file#querying) doesn't say explicitly if the results are going to be returned sorted by distance. Questions:

1.  Is it fair to presume that no sorting order is implied? And behavior can change in the future?
2. If I want to return the result in the sorted order, I would have to then add an order by clause, with the nearest neighbor query repeated. Something like `SELECT * FROM items WHERE embedding <-> '[3,1,2]' < 5 ORDER BY embedding <-> '[3,1,2]' LIMIT 5 ;`. It seems a bit awkward. Any suggestions to make it more elegant?

Thanks.

**Comment by ankane** [comment]
Hi @gsiddh, you'll need to use `ORDER BY` to sort the results. It should be fine to repeat the query vector, but if you use parameterized queries, you can use the same parameter for both:

```sql
SELECT * FROM items WHERE embedding <-> $1 < 5 ORDER BY embedding <-> $1 LIMIT 5;
```

**Comment by gsiddh** [comment]
This clarifies it. Thanks @ankane.
