### ISSUE TITLE
Normalize vectors

### ISSUE THREAD

**Issue by ucals** [pgvector/pgvector#458]
Frequently after computing the centroids of clusters we end up with unnormalized vectors:
```sql
SELECT cluster_id, avg(embedding) AS centroid, vector_norm(avg(embedding)) AS norm
FROM clusters
GROUP BY cluster_id
```
The result of the query above shows most values of `norm` column between 0.9 and 1, although in the original table `cluster` all vectors in the `embedding` column were properly normalized.

Fixing this is simple: just normalize the `centroid` column. The math is simple: in numpy, for example, I would do `centroid` / `norm`; in C, I would just divide every element of the centroid vector by its norm.

However, when I try to do the operation `vector / vector_norm(vector)`, I get the error:
**ERROR: operator does not exist: vector / double precision**

I realize that this is not a bug but a feature request. But conceptually it's pretty simple. So, if anyone could give me a hint on where to implement this operation, I would happily implement. 

From what I saw in the code (`/src/vector.c`), I think creating a new method `vector_normalize` would be something like:

```c
/*
 * Normalize a vector
 */
PGDLLEXPORT PG_FUNCTION_INFO_V1(vector_normalize);
Datum
vector_normalize(PG_FUNCTION_ARGS)
{
    Vector	   *a = PG_GETARG_VECTOR_P(0);
    float	   *ax = a->x;
    double	    norm = 0.0;
    Vector	   *result;
    float	   *rx;
    
    /* Auto-vectorized */
    for (int i = 0; i < a->dim; i++)
        norm += (double) ax[i] * (double) ax[i];

    norm = sqrt(norm);

    result = InitVector(a->dim);
    rx = result->x;
    
    for (int i = 0; i < a->dim; i++)
        rx[i] = ax[i] / norm;

    PG_RETURN_POINTER(result);
}
```

Enabling the operation of a division between a vector and a float conceptually shouldn't be hard as well. Anyway...

Can anyone help? Thanks!

**Comment by ankane** [comment]
Hi @ucals, check out #220.
