### ISSUE TITLE
 Issue with Installing pgvector Extension on PostgreSQL 14

### ISSUE THREAD

**Issue by mladencucakSYN** [pgvector/pgvector#459]
Subject: Issue with Installing pgvector Extension on PostgreSQL 14

Hello pgvector team,

I've encountered an issue while trying to install the pgvector extension on PostgreSQL 14. Despite following the installation instructions (compiling from source and using sudo make install), I am unable to create the extension within PostgreSQL, receiving the error:

`ERROR: could not open extension control file "/usr/share/postgresql/14/extension/pgvector.control": No such file or directory`

The installation process completes without any errors, and the files seem to be correctly placed in /usr/share/postgresql/14/extension/ and /usr/lib/postgresql/14/lib/. However, when attempting to create the extension with CREATE EXTENSION pgvector;, PostgreSQL does not recognize it. Restarting the PostgreSQL service does not resolve the issue.

Could you provide guidance on troubleshooting this issue or suggest any steps I might have missed?

Thank you for your assistance.

**Comment by ankane** [comment]
Hi @mladencucakSYN, check out #287.
