### ISSUE TITLE
Vector values are changed after inserting them to the database!

### ISSUE THREAD

**Issue by Hadryan** [pgvector/pgvector#46]
I inserted this in the database:
```
INSERT INTO items VALUES
('[0.459, 0.276, 1, -12.803, 1, 0.0804, 0.889, 0.009, 0.217, 0.354, 89.477, 56253, 3]');
```

After fetching the same vector, the result is as follows:
```[0.458999991416931,0.275999993085861,1,-12.8030004501343,1,0.0803999975323677,0.888999998569489,0.00899999961256981,0.216999992728233,0.354000002145767,89.4769973754883,56253,3]```

Are they stored as `double precision` or `float`s?

**Comment by ankane** [comment]
Hey @Hadryan, values are [stored as floats](https://github.com/pgvector/pgvector#vector-type) (but the same thing could happen with `double precision` since neither types are exact).

**Comment by Hadryan** [comment]
Ok, but the question is why the values changed?
 How to keep the original values?

**Comment by ankane** [comment]
Pushed a change in the commit above to make the text representation more friendly. It now uses the same function that Postgres uses for `float`, so the output is:

```text
[0.459,0.276,1,-12.803,1,0.0804,0.889,0.009,0.217,0.354,89.477,56253,3]
```

The underlying values are still the same (inexact), so you'll want to use a different type like `numeric[]` if storing the exact values is important.
