### ISSUE TITLE
server crash at startup with pgvector installed

### ISSUE THREAD

**Issue by stephane-martin** [pgvector/pgvector#460]
OS: ubuntu jammy with all updates
postgresql and pgvector extensions installed through pdpg apt repository
postgresql 14.11-1.pgdg22.04+1
pgvector 0.6.0-1.pgdg22.04+1

I've just upgraded the server from 14.10 to 14.11. postgresql now crashes at startup. If I disable pgvector in `shared_preload_libraries`, the server starts normally.

[segfault.log](https://github.com/pgvector/pgvector/files/14289689/segfault.log)

**Comment by ankane** [comment]
Hi @stephane-martin, you shouldn't add pgvector to `shared_preload_libraries`, but will see if there's something that can be done about the crash.

**Comment by stephane-martin** [comment]
Oh. Looks like you're damn right! So kind of solved for me :) Still strange: when I was running PG 14.10 with pgvector and shared_preload_libraries was including "vector", there used to be no crash.

**Comment by ankane** [comment]
I'm guessing pgvector was updated as well, as it likely worked before 0.6.0. Anyways, pushed a fix in the commit above. Thanks for reporting!
