### ISSUE TITLE
pgvector.control missing

### ISSUE THREAD

**Issue by HenrikPedDK** [pgvector/pgvector#467]
Hi

Using Postgres 16 on Ubuntu.
Run make install
PSQL

Vector=# CREATE EXTENSION pgvector;
ERROR:  extension "pgvector" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/16/extension/pgvector.control": No such file or directory.

Result from make install

develop@PGVector:/tmp/pgvector$ sudo make install
/bin/mkdir -p '/usr/lib/postgresql/16/lib'
/bin/mkdir -p '/usr/share/postgresql/16/extension'
/bin/mkdir -p '/usr/share/postgresql/16/extension'
/usr/bin/install -c -m 755  vector.so '/usr/lib/postgresql/16/lib/vector.so'
/usr/bin/install -c -m 644 .//vector.control '/usr/share/postgresql/16/extension/'
/usr/bin/install -c -m 644 .//sql/vector--0.1.0--0.1.1.sql .//sql/vector--0.1.1--0.1.3.sql .//sql/vector--0.1.3--0.1.4.sql .//sql/vector--0.1.4--0.1.5.sql .//sql/vector--0.1.5--0.1.6.sql .//sql/vector--0.1.6--0.1.7.sql .//sql/vector--0.1.7--0.1.8.sql .//sql/vector--0.1.8--0.2.0.sql .//sql/vector--0.2.0--0.2.1.sql .//sql/vector--0.2.1--0.2.2.sql .//sql/vector--0.2.2--0.2.3.sql .//sql/vector--0.2.3--0.2.4.sql .//sql/vector--0.2.4--0.2.5.sql .//sql/vector--0.2.5--0.2.6.sql .//sql/vector--0.2.6--0.2.7.sql .//sql/vector--0.2.7--0.3.0.sql .//sql/vector--0.3.0--0.3.1.sql .//sql/vector--0.3.1--0.3.2.sql .//sql/vector--0.3.2--0.4.0.sql .//sql/vector--0.4.0--0.4.1.sql .//sql/vector--0.4.1--0.4.2.sql .//sql/vector--0.4.2--0.4.3.sql .//sql/vector--0.4.3--0.4.4.sql .//sql/vector--0.4.4--0.5.0.sql .//sql/vector--0.5.0--0.5.1.sql .//sql/vector--0.5.1--0.6.0.sql .//sql/vector--0.6.0.sql  '/usr/share/postgresql/16/extension/'
/bin/mkdir -p '/usr/include/postgresql/16/server/extension/vector/'
/usr/bin/install -c -m 644   .//src/vector.h '/usr/include/postgresql/16/server/extension/vector/'
/bin/mkdir -p '/usr/lib/postgresql/16/lib/bitcode/vector'
/bin/mkdir -p '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/hnsw.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/hnswbuild.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/hnswinsert.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/hnswscan.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/hnswutils.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/hnswvacuum.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfbuild.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfflat.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfinsert.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfkmeans.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfscan.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfutils.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/ivfvacuum.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
/usr/bin/install -c -m 644 src/vector.bc '/usr/lib/postgresql/16/lib/bitcode'/vector/src/
cd '/usr/lib/postgresql/16/lib/bitcode' && /usr/lib/llvm-15/bin/llvm-lto -thinlto -thinlto-action=thinlink -o vector.index.bc vector/src/hnsw.bc vector/src/hnswbuild.bc vector/src/hnswinsert.bc vector/src/hnswscan.bc vector/src/hnswutils.bc vector/src/hnswvacuum.bc vector/src/ivfbuild.bc vector/src/ivfflat.bc vector/src/ivfinsert.bc vector/src/ivfkmeans.bc vector/src/ivfscan.bc vector/src/ivfutils.bc vector/src/ivfvacuum.bc vector/src/vector.bc

I do have a vector.control file there.. Is it a bug?

Regards

Henrik

**Comment by redadmiral** [comment]
It's not. As mentioned in the [Getting Started section of the README](https://github.com/pgvector/pgvector?tab=readme-ov-file#getting-started) the correct command is 

```sql
CREATE EXTENSION vector;
```
