### ISSUE TITLE
pgvector on conda-forge

### ISSUE THREAD

**Issue by mmcauliffe** [pgvector/pgvector#47]
Hello, I've just created some staged recipes for pgvector and pgvector-python on conda forge's staged-recipes and gotten them building: https://github.com/conda-forge/staged-recipes/pull/21432.  I'm happy to maintain the feedstocks, but wanted to reach out and ask if there was anyone else that I should add to them.

**Comment by ankane** [comment]
Hi @mmcauliffe, thanks for creating and sharing! It'd be great to include Windows support in this project, so no patch is needed. Will try to spend some time on it in the future.

**Comment by ankane** [comment]
Added `#include "port.h"` for `random()` on platforms where it's not defined.

**Comment by ankane** [comment]
Going to add this to the readme. Cool if I include your GitHub handle?

**Comment by mmcauliffe** [comment]
Sure, no problem!

**Comment by ankane** [comment]
Great. I really appreciate all the work on this!
