### ISSUE TITLE
Cant find PGXS during install

### ISSUE THREAD

**Issue by lovgrandma** [pgvector/pgvector#471]
I just wanted to share this even though it seems obvious but it took me a while to resolve on an AWS Fedora EC2 instance. I had libpq installed via yum but postgres installed via dnf. In my case I had to run sudo yum remove libpq-devel-15.0-2.amzn2023.0.1.x86_64 when it showed the conflicting dependency when running dnf install postgresql15-server-devel.x86_64

Ensure that you have installed the following:
postgresql<version>
postgresql<version>-server-devel
postgresql<version>-upgrade
postgresql<version>-contrib

via the SAME package manager. Do not install postgres via dnf and libpq devel via yum or else it will not be able to find the pgxs file.
If you have installed appropriate dependencies with same package manager you should be able to install under EC2 instance (non-RDS)

Then you can use simple linux git install instructions for pgvector

**Comment by ankane** [comment]
Hi @lovgrandma, thanks for sharing.

**Comment by jkatz** [comment]
If you're doing source builds, I recommend following the dependency guide in the PostgreSQL wiki:

https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code

**Comment by nathanKramer** [comment]
Thanks for these instructions! helped me install it on fedora.
