### ISSUE TITLE
Passing CFLAGS to the Makefile

### ISSUE THREAD

**Issue by Gnyblast** [pgvector/pgvector#473]
We are having some trouble on few of our machines that they don't support `AVX512` instructions set. So we decided to compile postgres on these machines with `CFLAGS` of `-O3 -march=x86-64-v3 -mtune=znver3`.

I don't see such option available on your `Makefile`, not only that, it hard codes it to `-march=native` which we don't want, even though it seems OK, we having some other implementation of syncing built binaries to other machines and it's not the compilation machine has the incompatibility but the other machines. So, we want to compile `AVX2` even though the machine support `AVX512`. So other syncing machines can still work even if they are not compatible with `AVX512`.

Using some `sed` like tools doesn't sound maintainable to me for the future, but what would be best is to be able to set this `OPTCFLAGS` from outside and hard code it only if it's not passed from outside.

Is such thing possible? Or maybe is there anything I'm missing and this is somehow available already?
Can you please assist?

**Comment by Gnyblast** [comment]
Looks like `PG_CFLAGS` are overriding the `OPTCFLAGS` so below line worked:
`make USE_PGXS=1 PG_CFLAGS='-O3 -march=x86-64 -mtune=znver3' && make USE_PGXS=1 PG_CFLAGS='-O3 -march=x86-64 -mtune=znver3' install`

**Comment by ankane** [comment]
Hi @Gnyblast, you can override `OPTFLAGS` with:

```sh
make OPTFLAGS="-march=x86-64-v3 -mtune=znver3"
```

**Comment by Gnyblast** [comment]
> Hi @Gnyblast, you can override `OPTFLAGS` with:
> 
> ```shell
> make OPTFLAGS="-march=x86-64-v3 -mtune=znver3"
> ```

Hi @ankane, do you thinks it's more relaible than `PG_CFLAGS` and recommended?

**Comment by ankane** [comment]
Yes, that's the purpose of it.
