### ISSUE TITLE
Is subtraction operator self-commutative ?

### ISSUE THREAD

**Issue by HowardQin** [pgvector/pgvector#475]
In vector.sql , the subtraction operator is defined as self-commutative, it seems not right for me:

CREATE OPERATOR - (
     LEFTARG = vector, RIGHTARG = vector, PROCEDURE = vector_sub,
     COMMUTATOR = -
);

Is this a bug or by design?

**Comment by ankane** [comment]
Hi @HowardQin, thanks for reporting! Fixed in the commit above.

For reference, `ALTER OPERATOR` won't work for this.

```text
ALTER OPERATOR - (vector, vector) SET (COMMUTATOR = NONE);
ERROR:  operator attribute "commutator" cannot be changed
```
