### ISSUE TITLE
why does the parameter  ivfflat.probes losts when reconnecting the session? 

### ISSUE THREAD

**Issue by lulalalulalaly** [pgvector/pgvector#476]
<img width="777" alt="企业微信截图_17091743093793" src="https://github.com/pgvector/pgvector/assets/138679006/83e39384-d28e-4a48-b9ba-1933340d4a9a">
<img width="582" alt="企业微信截图_17092071712630" src="https://github.com/pgvector/pgvector/assets/138679006/36d732d8-3064-4ed5-bcab-c6def7b4368d">

**Comment by jkatz** [comment]
@lulalalulalaly This is due to setting `ivfflat.probes` as a session variable (e.g., with `SET ivfflat.probes TO n`).

If you would like to retain the value of `ivfflat.probes` through multiple sessions, you'll have to set it in the configuration file, for example:

```sql
ALTER SYSTEM SET ivfflat.probes TO n;
```

**Comment by ankane** [comment]
Also, extensions in Postgres aren't loaded until needed (unless in `shared_preload_libraries`).

```text
db=# SHOW ivfflat.probes;
ERROR:  unrecognized configuration parameter "ivfflat.probes"
db=# SELECT '[1,2,3]'::vector;
 vector  
---------
 [1,2,3]
(1 row)

db=# SHOW ivfflat.probes;
 ivfflat.probes 
----------------
 1
(1 row)
```
