### ISSUE TITLE
Building hnsw index fail with memory is temporarily unavailable

### ISSUE THREAD

**Issue by GreateFang** [pgvector/pgvector#478]
HI guys， I have worked with pgvector5.0.0 in database developed base on postgres.  and I got error when building hnsw index because process_used_memory>max_process_memory.
How is the memory usage calculated during the construction of an HNSW index? Are there any test reports reflecting the relationship between the memory consumption of building an HNSW index and the number of entries in the table?
Do you have any recommended parameter settings when my vector data may be in the millions?

Thanks for your answer!

**Comment by ankane** [comment]
Hi @GreateFang, if you're using pgvector with a fork of Postgres, it'd be better to get help there. Memory usage will depend on the size of the vectors, number of rows, and value of `m`, and when it reaches `maintenance_work_mem`, the build will switch to using disk. For parameters, the default values are a good place to start.
