### ISSUE TITLE
Build a hierarchical structure for each tenant

### ISSUE THREAD

**Issue by baseballyama** [pgvector/pgvector#479]
This may be paraphrased as introducing a concept similar to the Pinecone's namespace.
For applications that manage multi-tenancy, the SQL query is always as follows:

```sql
SELECT * FROM some_table
WHERE tenant_id = 'tenant_01'
ORDER BY embedding <=> '[0,1,0,...]';
```

However, my research indicates that, at least with HNSW, it will return fewer results than expected when the number of records is greater than a certain number. (Presumably I would expect this issue in IVFFlat also.)

This seems to me to be a major factor discouraging the use of `pgvector` in multi-tenant services.
Currently the only way to solve this seems to be to create a table for each tenant, but it would be great if this could be solved with the `pgvector` feature.

I'm not familiar with PostgreSQL extensions at all, but could something like the `composite_vector` type solve this?
`composite_vector` type is kind of tuple type like `('tenant_id', '[0,1,0,...]')`.

And SQL will be...
```sql
SELECT * FROM some_table
WHERE tenant_id = 'tenant_01'
ORDER BY embedding <=> ROW('tenant_id', '[0,1,0,...]');
```

**Comment by jcrupi** [comment]
What about a partition per tenant.
Sent from my iPhone 12

On Mar 2, 2024, at 10:23 AM, Yuichiro Yamashita ***@***.***> wrote:

﻿

This may be paraphrased as introducing a concept similar to the Pinecone's namespace.
For applications that manage multi-tenancy, the SQL query is always as follows:

SELECT * FROM some_table
WHERE tenant_id = 'tenant_01'
ORDER BY embedding <=> '[0,1,0,...]';

However, my research indicates that, at least with HNSW, it will return fewer results than expected when the number of records is greater than a certain number. (Presumably I would expect this issue in IVFFlat also.)

This seems to me to be a major factor discouraging the use of pgvector in multi-tenant services.
Currently the only way to solve this seems to be to create a table for each tenant, but it would be great if this could be solved with the pgvector feature.

I'm not familiar with PostgreSQL extensions at all, but could something like the composite_vector type solve this?
composite_vector type is kind of tuple type like ('tenant_id', '[0,1,0,...]').

And SQL will be...

SELECT * FROM some_table
WHERE tenant_id = 'tenant_01'
ORDER BY embedding <=> ROW('tenant_id', '[0,1,0,...]');

**Comment by baseballyama** [comment]
Oh I had missed the partition part in the README. I'll try this.

**Comment by baseballyama** [comment]
Using PARTITION solved the issue!
Thank you @jcrupi!
