### ISSUE TITLE
How to insert vector values as numeric[]?

### ISSUE THREAD

**Issue by Hadryan** [pgvector/pgvector#48]
Hey @ankane, regarding [this issue](https://github.com/pgvector/pgvector/issues/46), how to insert values as numeric? I was unable to achieve that

```CREATE TABLE items (embedding vector(10));```

I need the exact values to be stored (not just the text representation).

**Comment by ankane** [comment]
You can use:

```psql
CREATE TABLE items (embedding numeric[]);
INSERT INTO items (embedding) VALUES ('{1.23456789123456789, 2, 3}');
SELECT * FROM items;
```

Note that this doesn't use/require pgvector.

**Comment by Hadryan** [comment]
Oh! Of course I still want to use pgvector. And that's why I couldn't find a solution to insert numeric values to pgvector table.

Do you have any idea to how to insert and keep exact numbers to pgvector and query them?

**Comment by ankane** [comment]
pgvector stores values as floats as mentioned in #46, so it's not possible.
