### ISSUE TITLE
Query with HNSW index returns only small portion of results

### ISSUE THREAD

**Issue by Keeo** [pgvector/pgvector#480]
I created table, added data, basically following the documentation and then created HNSW index over it. The resulting table has 14 million not-normalized rows (including large amount of duplicates in embedding column), 90gb in size and the index itself has 20gb.

Then I tried to select rows, that are close related to some vector using query
```sql
set local enable_seqscan = off;

select * from items
where  embedding <=> '[1,2,3,4,.., 768]' < 0.23
order by embedding <=> '[1,2,3,4,.., 768]';
```
from plan and based on speed I can confirm it is using the index.

This query returns only small portion of expected data. It can be influenced a bit by setting `SET hnsw.ef_search = 1000;` but even then it returns only small portion. Moreover, if I remove the `where..` part, it still returns the same subset.

Where is this limit comming from and is there something that I can tweak?

**Comment by ankane** [comment]
Hi @Keeo, the number of results is limited by `hnsw.ef_search`. The current max is 1000, but you could try forking and updating [this line](https://github.com/pgvector/pgvector/blob/c6ddf62a29f4790d386a60f9826583d2a228ef68/src/hnsw.h#L46). You can also do a table scan to get all of the results.

Can you share more about your use case?

**Comment by Keeo** [comment]
Wow, thank you for quick reply.

I want to build query that can answer "What are all the unique values that are close to the provided embedding." The result is then used to help user see what additional filters can be applied to narrow down the search.
```sql
select
    array_agg(distinct country),
    array_agg(distinct language),
    array_agg(distinct institution)
from items
where embedding <=> '[1, 2, 3, 4, ..., 768]' < 0.23
```

I already tested full table scan and it performed as expected. Now I am focused on understanding how pgvector works with indexes and impact they can have compared to full table scan. For my data the similarity search usually filters out 95% of the rows.

What is the reason for the limit to exists and how does it relate to number of results?
In my case I get only around 500 results with `hnsw.ef_search = 1000`.

**Comment by ankane** [comment]
Thanks for sharing. Added a section to the readme on this in the commit above.

The main reason for the limit is to limit memory usage. A higher limit like 10,000 may be fine, but if you need 700,000 results from the index (5% of 14M), an IVFFlat index is probably better.

**Comment by Keeo** [comment]
Just tried IVFFlat, and can confirm that it works much better for this use case and returns expected numbers of results after tweaking the probe count.

Thank you for help!
