### ISSUE TITLE
Is here any possibility to crush?

### ISSUE THREAD

**Issue by GreateFang** [pgvector/pgvector#481]
Could the code on lines 82 and 87 potentially cause a null pointer issue? When there is only one node in the heap, this node will not have any children. `pairingheap_add` also does not assign any values to the child nodes.
<img width="894" alt="image" src="https://github.com/pgvector/pgvector/assets/32962590/54b6ad50-ceb1-4707-b472-3f331d2bdafb">
<img width="735" alt="image" src="https://github.com/pgvector/pgvector/assets/32962590/3ef4b36d-7122-44ee-869b-e546b31d1443">
<img width="655" alt="image" src="https://github.com/pgvector/pgvector/assets/32962590/f759e073-b657-480c-884a-caa2e199846e">

**Comment by GreateFang** [comment]
maybe need to add this logic before 82L
if (!pairingheap_is_empty(so->listQueue))

**Comment by ankane** [comment]
Hi @GreateFang, it's fine to call `pairingheap_remove_first` on a non-empty pairing heap. `result->first_child` will be `NULL`, but the rest of the code handles that case.

**Comment by ankane** [comment]
It looks like you're using a different project.

**Comment by GreateFang** [comment]
yes yes, it was ivfflat.probes loaded fail in my project. Thanks for your reply!
