### ISSUE TITLE
Does postgres extension support primary-secondary synchronization?

### ISSUE THREAD

**Issue by GreateFang** [pgvector/pgvector#483]
I wondering is pgvector support primary-secondary synchronization?
I hava not seen similar func like btree_redo.
and I found it fail to sync index file to secondary database in my project(use pgvector5.0.0). 

THANKS A LOT FOR YOUR TIME!

**Comment by jkatz** [comment]
For general PostgresQL capability questions, I suggest using [PostgreSQL community resources](https://www.postgresql.org/support/).

For pgvector specifically, pgvector uses PostgreSQL's storage mechanisms (e.g. WAL), which allows it to be used with replication and archival processes.
