### ISSUE TITLE
How to add to existing docker postgresql ?

### ISSUE THREAD

**Issue by ducknificient** [pgvector/pgvector#484]
While this code is working
`docker run -d --name pgvectorsql pgvector/pgvector:pg16`

Is there any method to add the extension for regular postgresql image ?

**Comment by yihong0618** [comment]
> While this code is working `docker run -d --name pgvectorsql pgvector/pgvector:pg16`
> 
> Is there any method to add the extension for regular postgresql image ?

you can exec into the container then install pgvector the way in README

**Comment by ankane** [comment]
Hi @ducknificient, you can [build the image manually](https://github.com/pgvector/pgvector?tab=readme-ov-file#docker).
