### ISSUE TITLE
HNSW Index scan is not called with vector_cosine_ops

### ISSUE THREAD

**Issue by vinayak-shanawad** [pgvector/pgvector#485]
Hi Team,

Here is my table.

CREATE TABLE REVIEW (id uuid PRIMARY KEY, user_id VARCHAR(64), review_id VARCHAR(64), review text, embedding vector(768));

- HNSW index scan is called when using L2 distance.
CREATE INDEX hnsw_index ON REVIEW USING hnsw (embedding vector_l2_ops) WITH (m = 16, ef_construction = 64);

Explain query results:
[('Limit  (cost=164.60..167.78 rows=10 width=525) (actual time=8.574..8.821 rows=10 loops=1)',),
 ('  ->  Index Scan using hnsw_index on review  (cost=164.60..3345.60 rows=10000 width=525) (actual time=8.572..8.817 rows=10 loops=1)',),
 ("        Order By: (embedding <-> '[0.019593516,0.07317043,-0.011720092,................-0.014938663,0.0026845431,-0.0026375963]'::vector)",),
 ('Planning Time: 1.908 ms',),
 ('Execution Time: 8.996 ms',)]

- **Issue:** HNSW index scan is **not** called when using Cosine distance.
CREATE INDEX hnsw_index ON REVIEW USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

Explain query results:
[('Limit  (cost=1105.10..1105.12 rows=10 width=525) (actual time=48.008..48.011 rows=10 loops=1)',),
 ('  ->  Sort  (cost=1105.10..1130.10 rows=10000 width=525) (actual time=48.007..48.008 rows=10 loops=1)',),
 ("        Sort Key: ((embedding <-> '[0.019593516,0.07317043,-0.011720092,....................-0.031099815,-0.014938663,0.0026845431,-0.0026375963]'::vector))",),
 ('        Sort Method: top-N heapsort  Memory: 38kB',),
 ('        ->  Seq Scan on review  (cost=0.00..889.00 rows=10000 width=525) (actual time=0.024..44.391 rows=10000 loops=1)',),
 ('Planning Time: 0.063 ms',),
 ('Execution Time: 48.029 ms',)]

**Note:** Execution time is quite similar with and without the HNSW index using vector_cosine_ops.

Please check and confirm. Thanks

**Comment by jkatz** [comment]
```
(" Sort Key: ((embedding <-> '[0.019593516,0.07317043,-0.011720092,....................-0.031099815,-0.014938663,0.0026845431,-0.0026375963]'::vector))",),
```

It looks like your query is using the L2 (`<->`) operator, and not the cosine distance (`<=>`) operator. That would result in PostgreSQL not choosing to perform a scan on the HNSW index built using the cosine distance.

**Comment by vinayak-shanawad** [comment]
**Issue:** HNSW index scan is not called when using Cosine distance.
CREATE INDEX hnsw_index ON REVIEW USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

Here is the query results using cosine distance:

[('Limit  (cost=19328.82..19329.99 rows=10 width=525) (actual time=351.840..355.341 rows=10 loops=1)',),
 ('  ->  Gather Merge  (cost=19328.82..38774.54 rows=166666 width=525) (actual time=351.839..355.338 rows=10 loops=1)',),
 ('        Workers Planned: 2',),
 ('        Workers Launched: 2',),
 ('        ->  Sort  (cost=18328.79..18537.13 rows=83333 width=525) (actual time=348.901..348.902 rows=8 loops=3)',),
 ("              Sort Key: (('1'::double precision - (embedding <=> '[0.019593516,0.07317043,-0.011720092,-0.04541941,0.06921865,..........,-0.011935262,-0.03259274,-0.031099815,-0.014938663,0.0026845431,-0.0026375963]'::vector))) DESC",),
 ('              Sort Method: top-N heapsort  Memory: 36kB',),
 ('              Worker 0:  Sort Method: top-N heapsort  Memory: 35kB',),
 ('              Worker 1:  Sort Method: top-N heapsort  Memory: 39kB',),
 ('              ->  Parallel Seq Scan on review  (cost=0.00..16528.00 rows=83333 width=525) (actual time=0.095..331.604 rows=66667 loops=3)',),
 ('Planning Time: 0.139 ms',),
 ('Execution Time: 355.379 ms',)]
 
 **Expected behavior:** Retrieve top K results using hnsw_index with cosine distance.

**Comment by ankane** [comment]
See #216
