### ISSUE TITLE
Unrelevant results by DB similarity search

### ISSUE THREAD

**Issue by nikitamobile** [pgvector/pgvector#488]
Hello everyone,

    I'm trying to use pgvector db.similarity_search_with_score function (query, k=3) from the indexes created with the Open AI Embeddings (text-embedding-3-large model) from the source text in Uzbek language. 
    In 50% of the queries I'm getting 3 chunks of unrelevant text with the low score (less than 0.5). I suspect that poor results might be due to the source language. 
    Would be much appreciated if somebody could advise something as an improvement.

**Comment by ankane** [comment]
Hi @nikitamobile, please use other resources for help with LangChain.
