### ISSUE TITLE
Can I use index without ORDER BY or with ORDER BY different value? 

### ISSUE THREAD

**Issue by adrianryt** [pgvector/pgvector#489]
Hi, 
I am using Ivfflat index and my table has 9 000 000 rows.

I have two queries
```
SELECT "items"."X", ("items"."embedding" <=> ‘[vector]’) AS "distance"
FROM "items"
WHERE ("items"."embedding" <=> ‘[vector]) <= 0.2
ORDER BY "distance" ASC
LIMIT 101;
```
First query works fast, EXPLAIN show that it is using Ivfflat index and execution time is 23ms which is fine.
```
SELECT "items"."X", ("items"."embedding" <=> ‘[vector]’) AS "distance"
FROM "items"
WHERE ("items"."embedding" <=> ‘[vector]) <= 0.2
ORDER BY "X" ASC
LIMIT 101;
 ```
Second query is slow, it is using index for column X and not using Ivfflat index, execution takes over 2minutes which is very bad.
The second query without WHERE clause is fast, which makes me pretty sure the WHERE clause is the slow part of the query.
 
I also tried to run the query without ORDER BY - explain shows that it is using Seq Scan and the query took 70+ seconds

**My questions are:** 
- Can Ivfflat index(or HNSW index) be used by planner without Order By, and how? 
- Can Ivfflat index(or HNSW index) be used by planner with Order By different value than(in my case) similarity, and how? 
- Is there any smart way to achieve my goal, which is: Filter the rows by cosine distance and order by some value? 
- Can partitioning help in this problem? 

Additional information: 
- `pg_vector` version: 0.5.1
- Index is created with parameter lists=3000

 Thanks.

**Comment by jkatz** [comment]
```
Second query is slow, it is using index for column X and not using Ivfflat index, execution takes over 2minutes which is very bad.
The second query without WHERE clause is fast, which makes me pretty sure the WHERE clause is the slow part of the query.
```

In the second query, when you remove the `WHERE` clause, PostgreSQL is performing the ordering on `"X"` column. If it seems to going fast, you likely have an index on `"X"` that PostgreSQL is using.

The reason the second query is slower with the `WHERE` clause is because you're trying to filter on all rows where the distance between the query vector and the stored vector is less than 0.2, but you're ordering on the `"X"` column. Scans through IVFFlat/HNSW indexes are done based upon the ordered distance between the query vector and the stored vectors. Because you're ordering on the `"X"` column, PostgreSQL is going to have to perform a full table scan and do a vector comparison on all the rows in order to order it.

To your questions:

> Can Ivfflat index(or HNSW index) be used by planner without Order By, and how?

No, but can you provide more examples of what you're trying to achieve?

> Can Ivfflat index(or HNSW index) be used by planner with Order By different value than(in my case) similarity, and how?
> Is there any smart way to achieve my goal, which is: Filter the rows by cosine distance and order by some value?

It'd help to understand what the end goal is (It looks like you want to keep the distance within a particular bound -- curious on the use case), but you can do some things like:

```sql
SELECT *
FROM (
  SELECT "items"."X", ("items"."embedding" <=> ‘[vector]’) AS "distance"
  FROM "items"
  WHERE ("items"."embedding" <=> ‘[vector]) <= 0.2
  ORDER BY "distance"
  LIMIT 101
) x
ORDER BY x."X" ;
```

> Can partitioning help in this problem?

I'd need to better understand what you're trying to solve before recommending partitioning.

**Comment by adrianryt** [comment]
Hi @jkatz 
Thank you for your answer! 
`you likely have an index on "X" that PostgreSQL is using.` - yes, there is an index on `"X"`.

`Can Ivfflat index(or HNSW index) be used by planner without Order By, and how?`
`No, but can you provide more examples of what you're trying to achieve?`
I wanted to better understand pgvector and make sure order by is required for postgres to use index. Right now I don't have example of query where I **don't** order by any value.

Thank you for the example query, it indeed speed up things. I am aiming for query more like this(which also is fast):
```
SELECT *
FROM (
  SELECT "items"."X", ("items"."embedding" <=> ‘[vector]’) AS "distance"
  FROM "items"
  WHERE ("items"."embedding" <=> ‘[vector]) <= 0.2
  ORDER BY "distance"
) x
ORDER BY x."X" LIMIT 101;
```
Please notice the difference where the LIMIT is placed. 

**My end goal**
All I want is to find a fast way to filter out all items with cosine distance <= 0.2. Because I have 9 000 000 items full table scan and a vector comparison on all the rows is slow - as you said. To speed it up I want to use index, then in some cases I want to take filtered items and order them by one of the item fields. Only then I want to Limit them(or Offset + limit).

Once again thanks for the response.

**Comment by jkatz** [comment]
```sql
SELECT *
FROM (
  SELECT "items"."X", ("items"."embedding" <=> ‘[vector]’) AS "distance"
  FROM "items"
  WHERE ("items"."embedding" <=> ‘[vector]) <= 0.2
  ORDER BY "distance"
) x
ORDER BY x."X"
LIMIT 101;
```

I'm not sure why you'd want to move the limit outside of the subquery. If you have `>= 101` results that are within `0.2` distance, then the subquery will only return 101. Likewise, if you have less than 101 results that satisfy that query, again the subquery will return just those results already filtered, and you'd have less than 101 results.

> Right now 60% of items have embedding equal null, maybe partitioning or different way of creating index can use this information to speed up queries?

`NULL` vectors won't be indexed. If you're doing a full table scan, then partitioning could help here, but given your goal is to use the index I don't think changing the strategy would yield any performance gains.

**Comment by ankane** [comment]
Hi @adrianryt, when the `LIMIT` is outside of the subquery, you can encourage the planner to use the index with:

```sql
BEGIN;
SET LOCAL enable_seqscan = off;
SELECT ...
COMMIT;
```

(however, note that the subquery results will still be limited by `ivfflat.probes` and approximate)
