### ISSUE TITLE
Can one use the HNSW index without the `LIMIT` clause?

### ISSUE THREAD

**Issue by rsomani95** [pgvector/pgvector#490]
Tangential question to https://github.com/pgvector/pgvector/issues/489 -- can HNSW indexes be used for distance computation without the `LIMIT` clause?

In the following query, if I don't comment out the `LIMIT` clause, using `EXPLAIN ANALYZE` shows that the index is being used. Removing this clause makes the query a lot slower as the query doesn't use the index anymore.

```sql
SELECT "items"."X", ("items"."embedding" <=> '[vector]') AS "distance"
FROM "items"
WHERE ("items"."embedding" <=> '[vector]') <= 0.2
ORDER BY "distance" ASC
# LIMIT 101;
```

The motivation behind not using LIMIT is to get all `items` whose _embedding_ is within a distance of `0.2` from the `vector`.

I've tried setting the `LIMIT` to an abritrarily high number but this isn't viable because if the set limit is higher than the number of returned rows, the index doesn't get used either. 

Thanks.

**Comment by ankane** [comment]
Hi @rsomani95, you can encourage the planner to use the index with:

```sql
BEGIN;
SET LOCAL enable_seqscan = off;
SELECT ...
COMMIT;
```

However, results will still be limited by `hnsw.ef_search` and approximate. If you need exact results, use exact search (no index), or a high number of results, use IVFFlat.

**Comment by rsomani95** [comment]
Thanks!
