### ISSUE TITLE
[enhancement] Supporting Top-p (Nucleus Sampling) for cut off

### ISSUE THREAD

**Issue by GitIgnoreMaybe** [pgvector/pgvector#491]
From what I understand the only way to do a cut off is via top K e.g.:
`SELECT * FROM items ORDER BY embedding <-> '[3,1,2]' LIMIT 5;`

It would be great to have a cut off that is not determand by the amount of items. 
https://nn.labml.ai/sampling/nucleus.html

**Comment by ankane** [comment]
Hi @GitIgnoreMaybe, this doesn't seem applicable to nearest neighbor search.

**Comment by GitIgnoreMaybe** [comment]
Hey @ankane,

Thank you for the lighting fast response. Top P it is a very common used filter in nearest neighbor search. It uses the similarity scores to "fill up" the top p until the value is reached. Haystack integrated you in their framework and they are using it https://docs.haystack.deepset.ai/docs/toppsampler.

The reason why it's so neat is, that one don't want to miss important information based on a static cut off.

**Comment by ankane** [comment]
From the link, it seems like something you'd do after nearest neighbor search (and the documents have been reranked). That being said, you could likely implement top-p sampling in SQL (independent of pgvector).
