### ISSUE TITLE
Is there anyone could find a helm chart to install pgvector?

### ISSUE THREAD

**Issue by LinuxSuRen** [pgvector/pgvector#495]
As mentioned in the title.

**Comment by ankane** [comment]
Hi @LinuxSuRen, there doesn't seem to be one on Artifact Hub. You could try using a Postgres one like [this](https://github.com/bitnami/charts/tree/main/bitnami/postgresql) with a custom image with pgvector installed.

**Comment by LinuxSuRen** [comment]
I got the following error when I install it via `pgvector/pgvector:0.6.2-pg16`. I'm wonderfing if I missed anything. Nothing changed exepct the custom image.

```shell
chmod: changing permissions of '/var/run/postgresql': Read-only file system
PostgreSQL Database directory appears to contain a database; Skipping initialization                                                                                        2024-03-19 06:54:18.285 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-03-19 06:54:18.285 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-03-19 06:54:18.285 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-03-19 06:54:18.296 UTC [1] FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Read-only file system
2024-03-19 06:54:18.300 UTC [1] LOG:  database system is shut down
```

**Comment by ankane** [comment]
You'll probably want to add it to the default chart image (`bitnami/postgresql`) rather than replace it (https://github.com/bitnami/containers/issues/32677). This is beyond the scope of the project, so please use other resources for help.

**Comment by LinuxSuRen** [comment]
Consider someone might have  the similar situation, I just created [an image](https://github.com/LinuxSuRen/pgvector-docker) which include this extension. Hopefully it is helpful to someone.

**Comment by cauldyclark15** [comment]
created one https://github.com/cauldyclark15/pgvector-helm
