### ISSUE TITLE
Allow double precision in Avg

### ISSUE THREAD

**Issue by sean-idea9** [pgvector/pgvector#496]
Hi, pgvector is incredible!

Is it possible to have double precision when averaging vectors instead of only float8?

For reference here is where averages are hardcoded to float8.
https://github.com/pgvector/pgvector/blob/96ff19be4487a843fa96f8801afcfdd49ac3eeac/src/vector.c#L1138

**Comment by ankane** [comment]
Hi @sean-idea9, `float8` is double precision, but since `avg` returns a `vector`, the final result will be single precision. I don't think it makes sense to change this.

**Comment by sean-idea9** [comment]
Hi @ankane, thanks for your quick response! But that's a loss of precision right? I don't understand why the loss of precision would be a good thing. Maybe there's something I don't understand.

**Comment by ankane** [comment]
`vector` uses single precision to save space and memory, and `avg` uses double precision for the (intermediate) sum for better accuracy.
