### ISSUE TITLE
Using IVFFlat index for inner product

### ISSUE THREAD

**Issue by chingan-tsc** [pgvector/pgvector#498]
Hi I am trying to ORDER my datasets based on their inner product, but as per the documentation <#> returns the negative inner product, meaning I need to * -1 which would technically work. However due to the size of my datasets, I need indexes to speed up the query but since the index only works for ASC order, if I simply

`SELECT * FROM my_dataset
ORDER BY embedding <#> '[vector,...]'` 

returns the farthest data from my input vector? If I used DESC order I believe it doesn't use the index, if I add * -1 to the expression it also doesn't uses the index.

What are my options?

PS: I am aware of HNSW index but due to memory footprint I am giving IVFFlat a try at the moment.

**Comment by ankane** [comment]
Hi @chingan-tsc, typically you want to maximize the inner product, so `<#>` will give you the correct order (which is why it's designed this way).
