### ISSUE TITLE
Index Build Time Does Not Improve as Expected When Changing "Workers"

### ISSUE THREAD

**Issue by iamsabhoho** [pgvector/pgvector#500]
Hello, 

I'm Sabrina, a data scientist at GSI Technology. I've been working on a pgvector benchmarking project on deep-1B dataset. 

The documentation states that I can improve index build time by changing the parameters **max_parallel_maintenance_workers** and **max_parallel_workers**. 

Unfortunately, if I increase the values of the parameters beyond 10, I do not see an improvement. We tested with 1M records of deep-1B and here are some results: 
| number of workers | index build time in seconds |
| ----------- | ----------- |
| default | 4041 |
| 10 | 2043 |
| 20 | 2090 |

I am using the following hardware:
- Intel(R) Xeon(R) Gold
- 104 cores

Here are the loaded extensions:
| Name   | Version |   Schema   |                     Description                   |   
| ----------- | ----------- |  ----------- | ----------- |
| plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language | 
| vector  | 0.6.1   | public     | vector data type and ivfflat and hnsw access methods |

Should I expect to see better performance as I increase the value of workers? Thank you!

I am happy to provide my code or any additional machine information needed.

**Comment by ankane** [comment]
Hi @iamsabhoho, pgvector 0.6.2 reduces lock contention for HNSW builds with a large number of parallel workers, so I'd recommend trying that. Also, the build times look very slow compared to previous benchmarks (https://github.com/pgvector/pgvector/issues/409), so I'd double check that `maintenance_work_mem` ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#index-build-time)) and other settings like `shared_buffers` ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#tuning)) are set correctly. With only 1M records, it's possible you won't see much difference with more than 10 workers.

**Comment by iamsabhoho** [comment]
Hi @ankane, 
Thanks for the fast response! I couldn't find `shared_buffers` with the link provided. Could you recommend a setting for me to try it out? Thanks again!

**Comment by ankane** [comment]
`shared_buffers` should typically be 25% of your memory.

**Comment by iamsabhoho** [comment]
@ankane thanks for the tips! We re-ran the experiments based on your suggestions. The build time matches your 1M benchmark closely. As you mentioned, adding more workers does not improve the time linearly. 

![Screenshot 2024-03-25 at 2 18 38 PM](https://github.com/pgvector/pgvector/assets/19927448/71649e85-7196-411a-aee8-dae808e215f4)

How do you suggest we increase the worker memory as we build indexes up to 1B records? Thank you!

**Comment by ankane** [comment]
If you set `maintenance_work_mem` to a lower value like 100MB, there will be a notice that shows how many tuples fit into that much memory.

```text
NOTICE:  hnsw graph no longer fits into maintenance_work_mem after N tuples
DETAIL:  Building will take significantly more time.
HINT:  Increase maintenance_work_mem to speed up builds.
```

From that, you can extrapolate roughly how much memory it would take to fit the entire graph (and set `maintenance_work_mem` above that if possible).

**Comment by iamsabhoho** [comment]
We are using Python library to interact with PostgreSQL, is there any way to get those messages mentioned above? thanks!

**Comment by jkatz** [comment]
@iamsabhoho Those messages will be in the server logs.

FWIW, I've done and worked with folks who have done builds of 1B indexes with pgvector (particularly with 0.6.2). I've used datasets with 128 dimensions, and the build time would be somewhere in the 2-3 day range.

**Comment by ankane** [comment]
Getting messages on the client will depend on the library. For psycopg 3, you can use:

```python
def log_notice(diag):
    print(f"{diag.severity}:  {diag.message_primary}")

conn.add_notice_handler(log_notice)
```

**Comment by iamsabhoho** [comment]
Thanks for the help! We will update on the benchmarking results as we get them in the next few days.

**Comment by iamsabhoho** [comment]
Hi @ankane @jkatz, 

I've finished the benchmarks up to 100M now. Here are the results: 

![pgvector_hnswlib_gxl_index_build_time_total](https://github.com/pgvector/pgvector/assets/19927448/a7d08474-f242-4162-b3b7-6d4c6c62f2e7)

I will continue benchmarking till 1B and share the results here!

**Comment by jkatz** [comment]
@iamsabhoho Thanks! That seems a bit slow to me; I'm able to build a m=16, ef_construction=256 index for 1B 128-dim vectors in about 60 hours with 64 cores. Which version of pgvector are you using? Also, for the `hnswlib` and `gxl` tests (can you please share a reference to gxl?), do those tests also flush the data to disk? Thanks!

**Comment by jkatz** [comment]
Just for a quick comparison, I'm running the DEEP1B test from ANN Benchmark (~10MM 96-dim vectors) from d7354a86a8 -- with m=16, ef_construction=128 on a r7gd.16xl (64 vCPU) and writing to the local NVMe, the index build in about 5 minutes. Using a linear extrapolation (which at least at this scale is not too far off), this would take about 50min to run in the 100MM case.

**Comment by iamsabhoho** [comment]
Hi @jkatz , 

It looks like a significant portion of time is spent inserting the vectors into the table, 20-30%.  

![pgvector_insert_index_build](https://github.com/pgvector/pgvector/assets/19927448/cd828ea0-9007-4061-992f-b24dee6a26f9)

Is there a way to optimize that?  Also, can you share your pgvector parameters for your experiment?  As for GXL, it's an algorithm my company works on.  We'll have a blog on it in the near future. Thank you!

**Comment by ankane** [comment]
Hi @iamsabhoho, check out [this example](https://github.com/pgvector/pgvector-python/blob/master/examples/bulk_loading.py) for bulk loading. The build times still seem pretty slow, so I don't think the setup is optimized.

**Comment by iamsabhoho** [comment]
@jkatz we will rerun on a machine with an NVMe drive and report back here. Thanks!

**Comment by jkatz** [comment]
To be pedantic - the example that @ankane references using the binary mode with COPY - this should significantly speed up the load as you won't have to convert from binary to text to binary.

**Comment by iamsabhoho** [comment]
Hi @jkatz @ankane,

![pgvector_index_build_only](https://github.com/pgvector/pgvector/assets/19927448/ed79ca93-00b5-4243-afc2-9e1afbc85c50)

We've integrated all the optimizations suggested, please see the subtitle above. The plot is only index build time, we will update the plot to include the bulk insert of vectors later. This plot uses the latest 0.6.2 pgvector extension, which speeds up the index build time significantly. We've also tried running in a psql console and the pgvector message helped with the worker memory optimization. 

If there is any other optimizations I can try it out that would also be great! Thanks again!

**Comment by phobrain** [comment]
Could the write speeds of the NVMe vary enough to be worth reporting? Could writing dump files and loading them add speed? It benchmarked better than inserts for me in pre-pgvector days on lesser hardware on an O(N^2) load that pgvector has made vestigial.

**Comment by jkatz** [comment]
@iamsabhoho Glad the results are improving. A few more thoughts:

* I looked up your process and it supports 26 cores / 52 threads. I don't know how busy the machien is, but you can set `max_parallel_maintenance_workers` higher (e.g. 32)
* The unreleased pgvector 0.7.0 is adding support for casting to a 2-byte float -- however for the DEEP1B dataset, I don't believe you'll see much gains (at least based on the [SIFT128 test](https://jkatz05.com/post/postgres/pgvector-scalar-binary-quantization/))

**Comment by ankane** [comment]
Cleaning up issues, but feel free to share if there are more results.

**Comment by schuemie** [comment]
Just wanted to leave these results somewhere: I have 37 million vectors (PubMed), each of 768 dimensions (Snowflake Arctic M 1.5). I've loaded them as `halfvec`.  I know from my development environment that I need 80GB of RAM to build the HSNW index. However, I don't have that amount of memory in a second environment (and no way to copy the index). There, I'm restricted to roughly 8GB of RAM, which I provide to a single worker:
```sql
SET maintenance_work_mem = '8GB'
SET max_parallel_maintenance_workers = 0
CREATE INDEX ON public.vectors_snowflake_arctic_m USING hnsw (embedding halfvec_cosine_ops)
```
I've plotted progress over time:

![pgVectorIndexing](https://github.com/user-attachments/assets/fa574fcd-99ad-464f-a2c8-ea995650f90a)

As you can see, after you run out of memory ('*NOTICE:  hnsw graph no longer fits into maintenance_work_mem after 3707009 tuples*`), which is at 10%, progress slows down significantly. Not only that, it progressively becomes slower over time, meaning it will likely never finish. I'll switch to IVFFlat, but that is slow to search and has lower accuracy. 

It would be great if there was some way to create HSNW indices without the large memory requirements. Maybe split the index into *n* parts that fit in memory, and then when searching under the hood perform *n* searches and combine them (so for me that would be 10x slower searches but equal accuracy)?

**Comment by phobrain** [comment]
Could you use memory mapping on a file? 

Bill

--

Phobrain.com 

On 2024-09-23 23:04, Martijn Schuemie wrote:

> Just wanted to leave these results somewhere: I have 37 million vectors (PubMed), each of 768 dimensions (Snowflake Arctic M 1.5). I've loaded them as halfvec. I know from my development environment that I need 80GB of RAM to build the HSNW index. However, I don't have that amount of memory in a second environment (and no way to copy the index). There, I'm restricted to roughly 8GB of RAM, which I provide to a single worker:
> 
> SET maintenance_work_mem = '8GB'
> SET max_parallel_maintenance_workers = 0
> CREATE INDEX ON public.vectors_snowflake_arctic_m USING hnsw (embedding halfvec_cosine_ops)
> 
> I've plotted progress over time: 
> 
> pgVectorIndexing.png (view on web) [1] 
> 
> As you can see, after you run out of memory ('_NOTICE: hnsw graph no longer fits into maintenance_work_mem after 3707009 tuples_`), which is at 10%, progress slows down significantly. Not only that, it progressively becomes slower over time, meaning it will likely never finish. I'll switch to IVFFlat, but that is slow to search and has lower accuracy. 
> 
> It would be great if there was some way to create HSNW indices without the large memory requirements. Maybe split the index into _n_ parts that fit in memory, and then when searching under the hood perform _n_ searches and combine them (so for me that would be 10x slower searches but equal accuracy)? 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you commented.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/user-attachments/assets/fa574fcd-99ad-464f-a2c8-ea995650f90a
[2]
https://github.com/pgvector/pgvector/issues/500#issuecomment-2370265830
[3]

**Comment by ankane** [comment]
Hi @schuemie, if you partition the table, it'll create a separate index for each partition. Also, if you increase `max_parallel_maintenance_workers`, you'll likely see faster build times.

**Comment by schuemie** [comment]
Thanks @ankane! It sounds like table partitioning is what I was looking for, I'll give it a try.

I don't think I can increase `max_parallel_maintenance_workers`, because each will require its own RAM. My current strategy is to allocate all available memory to 1 worker, which as far as I can see is more performant than splitting the memory over multiple workers (obviously only when memory constrained).

**Comment by jkatz** [comment]
> I don't think I can increase max_parallel_maintenance_workers, because each will require its own RAM.

The parallel workers are sharing memory available in the `maintenance_work_mem` pool. Using more workers on index build can significantly improve index build time (sharing a slide from one more my talks on this):

<img width="1025" alt="Screenshot 2024-09-24 at 8 20 05 AM" src="https://github.com/user-attachments/assets/57f7ca56-26a8-401a-9a34-adecd07dc16f">

**Comment by schuemie** [comment]
Thanks @jkatz ! I totally misunderstood. I think together with partitioning, using parallel workers should bring an HSNW index within my reach.

**Comment by schuemie** [comment]
@jkatz : Would you mind sharing how much memory you used? I'm having a hard time thinking of what a reasonable amount of memory is. I'm using cloud computing, so I could ask to scale the server up, but I would need some guidance on what to ask for.

**Comment by jkatz** [comment]
@schuemie It depends on the dataset, and if you're indexing the full vectors (no quantization), you'll need roughly 1.3x the size of the dataset of memory. So using the above dataset and very rough math (not accounting for page size here, which adds a bit more), you'd ~137GiB to hold the full set in memory:

```
SELECT (1.3 * (37000000::numeric * (768 * 4 + 8))) / 1024^3;
```

Thus, as Andrew suggests, partitioning the data would help reduce the overall amount of memory required. Given you need memory for other database operations and your shared buffers (I'll assume your shared buffers are set to `20GB`), let's say you set `maintenace_work_mem` to `20GB` - you can then build the dataset over 8 partitions while keeping the index in memory (again, rough math).

**Comment by schuemie** [comment]
Just reporting back: I ended up using 8 partitions, 10GB of `maintenance_work_mem`, and 4 `max_parallel_maintenance_workers`. With that setup, it took only 6 hours to create the index. Thanks all for your help!
