### ISSUE TITLE
Theory behind HNSW

### ISSUE THREAD

**Issue by ir2718** [pgvector/pgvector#503]
Hi,

I have a question regarding the HNSW index and its implementation in pgvector. If I understand everything correctly it uses a multilayer graph starting from the highest and sparsest layer. It finds the nearest neighbor in that layer and then starts from that point on the lower layer.

I've got two questions regarding this:
1. Can you do indexing online (eg. streaming data) with this index? Are there any indexes I should check out for an online use case? 
2. I understand how it finds the approximate closest neighbor, but how does it find the possible candidates for ranking? Is it just a BFS starting from the lowest layer and branching out to a certain number of neighbors, which are then ranked using some similarity function?

**Comment by jkatz** [comment]
> Can you do indexing online (eg. streaming data) with this index? Are there any indexes I should check out for an online use case?

Yes, this is one of the benefits of HNSW.

> I understand how it finds the approximate closest neighbor, but how does it find the possible candidates for ranking? Is it just a BFS starting from the lowest layer and branching out to a certain number of neighbors, which are then ranked using some similarity function?

I recommend reading the [HNSW paper](https://arxiv.org/ftp/arxiv/papers/1603/1603.09320.pdf) (which is also linked to from the [Thanks](https://github.com/pgvector/pgvector?tab=readme-ov-file#thanks) section) which describes how the search mechanism works.
