### ISSUE TITLE
HNSW index building slow for large table

### ISSUE THREAD

**Issue by mavalderrama** [pgvector/pgvector#504]
Hello, I've been working with pgvector for a while, and now we are giving a try to HNSW `0.6.0` latest version available on RDS, for a table with more than 170M rows and an embedding vector of 64 dimensions.

Our test bench:
- AWS instance `db.r6i.2xlarge`
- 64GB RAM
- 8 vcpu

We've made several attempts without success:

Default settings:
- Inserting data with the index in place: After 6 days, the progress was at 20%. I stopped the process
- Building the index with the data in place: After 4 days the progress was only ~24%. I stopped the process.

Setting `ef_construction` from `64` to `32`
- We've noticed the process was faster but after 4 days the progress was only at ~50%

Increasing workers:
- I didn't notice any real speed increase

What settings do you recommend guys?

Thanks in advance.

**Comment by jkatz** [comment]
A few things:

* Be sure to increase `maintenance_work_mem` to ensure the build is occurring in memory.
* With 8 vCPU, you will want to set `max_parallel_maintenance_workers` to `7` (as by default you'll get 8 with this setting)
* https://github.com/pgvector/pgvector/commit/3ea2ce89be54d7060684be2c93501515f647a7ba which is available in 0.6.2 improves locking contention, which will speed up the builds.

This in turn should let you _increase_ `ef_construction` as you'll see performance improve.

**Comment by ankane** [comment]
Hi @mavalderrama, also check out #500.
