### ISSUE TITLE
ERROR:  extension "vector" has no installation script nor update path for version "0.6.2" 

### ISSUE THREAD

**Issue by tr1621** [pgvector/pgvector#507]
Hi,
This Is Tejaswini V,

I am Data Science Engineering Trainee ,from last one week i am struggling about pgvector extension installation and integrate with PostgreSQL . i follow the instructions as you mentioned in the installation process of vector repository in GitHub  for windows. i am using pgvector-0.6.2 version & PostgreSQL 16 and have minGW and Microsoft Visuals studio community 2022 build tools are used for pgvector installation .the pgvector extension installation is completed ,but when i try to create Extension vector to postgreSQL database server it will showing error like this " ERROR:  extension "vector" has no installation script nor update path for version "0.6.2" ".
if you know the proper solution about pgvector extension installation. could you please share me through Gmail

ERRORS:
**postgres=# SELECT*FROM pg_extension WHERE extname = 'vector';**
 oid | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-----+---------+----------+--------------+----------------+------------+-----------+--------------
(0 rows)

ERROR:
**postgres=# CREATE EXTENSION IF NOT EXISTS vector;
ERROR:  extension "vector" has no installation script nor update path for version "0.6.2"**

Thank you,
Tejaswini V
tejaswinivaddi123@gmail.com

**Comment by ankane** [comment]
Hi @tr1621, it looks like the extension isn't installed. Make sure the installation commands completed successfully and that `PGROOT` points to the right Postgres installation (if you have multiple).
