### ISSUE TITLE
I have a question about vector structure 

### ISSUE THREAD

**Issue by chaewoonlim** [pgvector/pgvector#509]
Hello, sir

I have a question

If I need to change the vector structure, for example by changing the vector dimensions, 

which query function is best to use?

**Comment by jkatz** [comment]
Based on that, this may require the new [`subvector`](https://github.com/pgvector/pgvector/commit/d6044dd423f552c3591380c6fff8aae2591f93fa) function, e.g.:

```sql
SELECT subvector('[1,2,3,4]', 1, 3);
 subvector 
-----------
 [1,2,3]
(1 row)
```
