### ISSUE TITLE
Aggregate functions for vectors

### ISSUE THREAD

**Issue by mmcauliffe** [pgvector/pgvector#51]
I'm trying to generate means of vectors, but I'm getting the error message `ERROR:  function avg(vector) does not exist`.  Is this something that's easy to implement in pgvector, or should I rely on code outside the database for aggregation?

**Comment by ankane** [comment]
Hi @mmcauliffe, you'll currently need to rely on outside code. Can you share more about the use case?

**Comment by ankane** [comment]
Previous discussion: https://github.com/pgvector/pgvector/pull/13

**Comment by mmcauliffe** [comment]
So I'm working with ivectors for speaker recognition with databases of speech corpora,  The database has a table for utterances with audio data, along with a table of speakers of those utterances.  Ivectors are calculated initially over utterances, and then the ivector for a speaker is the mean of the utterance ivectors.  In the application, I'm using for running classification of "did this speaker actually speak this utterance?" and comparing between speakers for "is the metadata wrong and these should actually be treated as the same speaker" to clean up the speech corpus with better metadata.

Not too huge of a deal to do a query, aggregate, and update, but it'd be nice to have the speaker ivector be a function of the utterance ivectors inside the database so that speakers get updated more automatically.

**Comment by ankane** [comment]
Thanks for the context. Added in the commit above (and will be released with 0.4.0, likely sometime in January).
