### ISSUE TITLE
vector extension creation in docker image

### ISSUE THREAD

**Issue by humcqc** [pgvector/pgvector#512]
Hello, 

Do you think it could be a good idea to have in the docker image a SQL script that initialize automatically the pg vector ?
'''CREATE EXTENSION IF NOT EXISTS vector'''

Thanks

**Comment by ankane** [comment]
Hi @humcqc, thanks for the suggestion. The Postgres Docker image supports [initialization scripts](https://hub.docker.com/_/postgres/), so we could configure it to run `CREATE EXTENSION vector;` in `$POSTGRES_DB` (to make it available in future databases, it'd also need to update `template1`). However, I think it's better to keep things consistent across installations (and not create the extension automatically), but may revisit in the future.

**Comment by Nithur-M** [comment]
Hey @ankane any updates on this?

**Comment by ankane** [comment]
Same thoughts as before.
