### ISSUE TITLE
Unable to connect to server in pgadmin 4

### ISSUE THREAD

**Issue by tariksghiouri** [pgvector/pgvector#513]
I used `docker run  --name pgvector-demo -e POSTGRES_PASSWORD=TEST -p5432:5432 ankane/pgvector`  
to run the docker image 
and it runs successfully as you can see 
![image](https://github.com/pgvector/pgvector/assets/49345542/97288017-b03f-42da-a754-e77275d2240a)
 
and in pgadmin I cant connect to the server as it says:

![image](https://github.com/pgvector/pgvector/assets/49345542/c71c8e85-bb04-4f92-a5f8-3130c91f987a)

ps: i'm trying to implement the same thing as in this [video tutorial](https://www.youtube.com/watch?v=FDBnyJu_Ndg)

**Comment by ankane** [comment]
Hi @tariksghiouri, make sure the password is correct and there's not already a server running on the same port. Please use other resources for additional help.

**Comment by tariksghiouri** [comment]
I double checked everything, the issue persists ,
from my understanding the image is running in WSL and I'm trying to access it from pgadmin in my windows machine , could that be the issue?
If so , is there any solution?
