### ISSUE TITLE
Error when installing pgvector on M1 with Postgresql 15.2

### ISSUE THREAD

**Issue by rhunold** [pgvector/pgvector#516]
Hi also have an issue with a M1.
Is it the same issue that occur to [Lesley217](https://github.com/Lesley217) ? I don't know.

My postgres is 15.2
I installed some time ago and I'm pretty sure I installed it via the pgadmin website.

The make command give me an error saying MacOSX11.1.sdk was not found (so unsucessfull to install). 

I try to uninstall and reinstall xcode but it was worse  when reinstalled (older sdk not installed). 
Finally found a version of MacOSX11.1.sdk on a github account (https://github.com/phracker/MacOSX-SDKs).
I download it and copy it to /Library/Developer/CommandLineTools/SDKs

But got still few error when trying the make command :
15/lib -Wl,-dead_strip_dylibs -bundle_loader /Library/PostgreSQL/15/bin/postgres
ld: warning: -multiply_defined is obsolete
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/20220418/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: -multiply_defined is obsolete
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/20220418/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found

So indeed, can't finish the install with the command "make install". Here the message I get if I try :
(env) ➜ pgvector git:(v0.6.2) make install
/bin/sh /Library/PostgreSQL/15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/Library/PostgreSQL/15/lib/postgresql'
/bin/sh /Library/PostgreSQL/15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/Library/PostgreSQL/15/share/postgresql/extension'
/bin/sh /Library/PostgreSQL/15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/Library/PostgreSQL/15/share/postgresql/extension'
/usr/bin/install -c -m 755 vector.so '/Library/PostgreSQL/15/lib/postgresql/vector.so'
install: /Library/PostgreSQL/15/lib/postgresql/vector.so: Permission denied
make: *** [install-lib-shared] Error 71

Finally, there is no file named pgvector in /Library/PostgreSQL/15/share/postgresql/extension.

Any clue or process to do ?
Wonder if I should upgrade to Postgresql 16 because I've read that their is more extentions installed by default.

**Comment by BillSmith-EDB** [comment]
The "make install" is failing because the user doesn't have permission to copy the vector.so file to the lib directory.  You would likely need to run the install step as root.

Upgrading to PG16 won't solve the permission issue.

**Comment by ankane** [comment]
Hi @rhunold, try using `sudo` to solve the permissions error.

```sh
sudo --preserve-env=PG_CONFIG make install
```

**Comment by rhunold** [comment]
Thank's for the sudo response !
