### ISSUE TITLE
apt install pgvector is not found

### ISSUE THREAD

**Issue by s-triar** [pgvector/pgvector#517]
I got error
```
Unable to locate package pgvector
```

of course I run this command before:
```
apt update
```

**Comment by s-triar** [comment]
> Hi @s-triar, check out the [APT instructions](https://github.com/pgvector/pgvector?tab=readme-ov-file#apt).

@ankane , sorry typo, here this the one I trying

![image](https://github.com/pgvector/pgvector/assets/34316314/ac1f39d3-fcec-4baa-a004-1918a715b47d)

**Comment by ankane** [comment]
Make sure you've followed the instructions to setup the APT repo.

**Comment by s-triar** [comment]
Thank you. it works after I did the commands in 
```
Quickstart
TL;DR:
```
However I got error ` could not access file "$libdir/vector": No such file or directory`

**Comment by BillSmith-EDB** [comment]
Look in your PG installation lib directory.  Do you see a vector.so file? It doesn't look like it's present.  

Do `sudo apt list --installed | grep postgres` to see what's installed.



`runner@fe70a7eecd2e:/usr/lib/postgresql/16/lib$ pwd
/usr/lib/postgresql/16/lib
runner@fe70a7eecd2e:/usr/lib/postgresql/16/lib$ ls -al vec*
-rw-r--r-- 1 root root 116648 Mar 20 11:07 vector.so
runner@fe70a7eecd2e:/usr/lib/postgresql/16/lib$ sudo apt list --installed | grep postgre

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

postgresql-16-pgvector/bullseye-pgdg,now 0.6.2-1.pgdg110+1 amd64 [installed]
postgresql-16/bullseye-pgdg,now 16.2-1.pgdg110+2 amd64 [installed]
postgresql-client-16/bullseye-pgdg,now 16.2-1.pgdg110+2 amd64 [installed,automatic]
postgresql-client-common/bullseye-pgdg,now 257.pgdg110+1 all [installed,automatic]
postgresql-common/bullseye-pgdg,now 257.pgdg110+1 all [installed,automatic]
runner@fe70a7eecd2e:/usr/lib/postgresql/16/lib$`

**Comment by s-triar** [comment]
Here is my output
```
postgresql-16-pgvector/bookworm-pgdg,now 0.6.2-1.pgdg120+1 amd64 [installed]
postgresql-16/bookworm-pgdg,now 16.2-1.pgdg120+2 amd64 [installed,automatic]
postgresql-client-16/bookworm-pgdg,now 16.2-1.pgdg120+2 amd64 [installed,automatic]
postgresql-client-common/bookworm-pgdg,now 257.pgdg120+1 all [installed,automatic]
postgresql-common/bookworm-pgdg,now 257.pgdg120+1 all [installed]

```

**Comment by s-triar** [comment]
here is my vector.so
![image](https://github.com/pgvector/pgvector/assets/34316314/db97378b-e6b4-44c4-bb74-f1d64f08aeb0)

**Comment by BillSmith-EDB** [comment]
That looks good.  Can you show the output from running "psql postgres" and within psql "select version(); create extension vector;"

**Comment by s-triar** [comment]
I think I know the cause of the problem and I think it is my fault and I am sorry about it and thank you so much for your guidance.
it because I have 2 docker containers. first is contain the posgres and the second is contain my application (fastapi).
I got the $libdir/vector from the second container so I thought, I should install pgvector in it. but actually I should install it in the first container.

and I noted something that make error $libdir/vector not found re-appearing. 
it reappears each time I restore any table using dbeaver.

**Comment by BillSmith-EDB** [comment]
Glad you got it sorted out.  Yes, you need the pgvector package to be installed on the machine running the server.
