### ISSUE TITLE
ERROR:  extension "vector" has no installation script nor update path for version "0.6.2"

### ISSUE THREAD

**Issue by p2991459** [pgvector/pgvector#525]
postgres=# CREATE EXTENSION vector;
ERROR:  extension "vector" has no installation script nor update path for version "0.6.2"

After following below instructions I got above error while adding the extension to postgres,tried every possible way but seems there issue with the v0,6.2 

cd /tmp
git clone --branch v0.6.2 https://github.com/pgvector/pgvector.git
cd pgvector
make
make install

**Comment by legaltextai** [comment]
the same issue here 
ubuntu server 
postgres 14 

SELECT * FROM pg_available_extensions WHERE name = 'vector'; shows I have the extension 
but when try to run 
CREATE EXTENSION vector; I get this error

**Comment by legaltextai** [comment]
the issue is resolved if i don't specify a specific release during cloning

**Comment by ankane** [comment]
Hi @p2991459 and @legaltextai, I'm not able to reproduce the error. I don't think it's an issue with pgvector, but if you create a new issue with the exact commands you ran, their full output (with any personal info removed), and the output of `pg_config`, I can look into it more (make sure you haven't manually copied any files).

@legaltextai If you don't specify a branch, you'll get a non-release version, which isn't supported and will likely cause issues when trying to upgrade.

**Comment by legaltextai** [comment]
I am not sure I can reproduce since it's installed and working fine now after I used just git + clone https://github.com/pgvector/pgvector.git 
We reproduced the errors above. 
In my case, when I followed the original instruction, with the version, it got installed, showed in the list of extensions but when trying to enable, it showed that error.

**Comment by ankane** [comment]
I'd recommend dropping the extension (`DROP EXTENSION vector;`) and re-running the correct installation instructions from scratch (otherwise, you won't be able to upgrade ever).

**Comment by legaltextai** [comment]
sounds ominous. but i am not sure why i need to rerun everything if that
release generates an error.
let us know when you find the problem

**Comment by gabrielgalindor** [comment]
It ocurrs to me, so I follow the next steps:

https://github.com/gabrielgalindor/TutorialVectorPG

**Comment by gabrielladfi** [comment]
> It ocurrs to me, so I follow the next steps and it worked:
> 
> https://github.com/gabrielgalindor/TutorialVectorPG

It works !!
