### ISSUE TITLE
Support functions

### ISSUE THREAD

**Issue by hlinnaka** [pgvector/pgvector#527]
Currently, IvfflatGetType and HnswGetType functions do a syscache lookup to get the datatype, and then there is a bunch of code that do things like this based on the type:

```
		if (type == IVFFLAT_TYPE_VECTOR)
			qsort(samples->items, samples->length, samples->itemsize, CompareVectors);
		else if (type == IVFFLAT_TYPE_HALFVEC)
			qsort(samples->items, samples->length, samples->itemsize, CompareHalfVectors);
		else if (type == IVFFLAT_TYPE_BIT)
			qsort(samples->items, samples->length, samples->itemsize, CompareBitVectors);
		else
			elog(ERROR, "Unsupported type");
```

That's a bit of an unusual pattern in indexes, the usual pattern would be to have support function in the opclass to encapsulate any type-specific differences. 

To refactor this to use support functions, the minimal change to what's in 'master' would be to define one new support function, something like 'get_vector_type()', which returns a  HnswType or IvfflatType. The HnswGetType()/IvfflatGetType() function would then just call the support function. Those if-statements would remain unchanged.

A more proper way to use a support function would be to have support  functions like 'hnsw_get_max_dimensions' and 'hnsw_check_value', to  replace the places where we currently check the type (GetMaxDimensions  and HnswCheckValue).

A third approach would be to have just one support function like 'hnsw_type_support' that returns a struct like:

```
struct HnswTypeSupport
{
     int         max_dimensions;
     void      (*check_value)(Datum value);
};
```

That might be more handy than having a lot of support functions, and you get better type checking from the compiler as you don't need to convert all arguments to Datums. Ivfflat has "if (type == IVFFLAT_TYPE_VECTOR) ..." kind of checks, so it would need more support function, something like:

```
struct IvfflatTypeSupport
{
     int         max_dimensions;
     int         item_size;
     void      (*ApplyNorm)(Oid collation, Datum value);
     void      (*QuickCenters)(VectorArray samples, VectorArray centers);
     void      (*ComputeNewCenters)(VectorArray samples, VectorArray aggCenters, VectorArray newCenters, int *centerCounts, int *closestCenters);
     void      (*CheckCenters)(VectorArray centers);
};
```

**Comment by hlinnaka** [comment]
Those IvfflatTypeSupport functions could be refactored into smaller functions, e.g. one for sorting used in both QuickCenters and CheckCenters

**Comment by ankane** [comment]
Thanks @hlinnaka, this is really helpful. Going to spend time on it today to see which approach feels best.

**Comment by ankane** [comment]
Updated to approach 1 as a first step in the commit above (to get rid of the syscache call), while making it flexible enough to move to approach 3 at any time (since the functions accept and return `internal`). Going to see how approach 2 feels next.

**Comment by ankane** [comment]
Alright, everything has been moved to support functions (besides itemsize, which I think can be removed at some point). Still planning to do some more clean-up tomorrow.

I'm thinking it'd be better not to add the support functions for `vector` (to make sure things work for existing installations that never run `ALTER EXTENSION ... UPDATE`). However, it leads to a few functions like this: https://github.com/pgvector/pgvector/blob/c39cb25c32612205de5e8edaeb5599cba20b5d0c/src/ivfkmeans.c#L130-L137

Do you know if there's a way to generate `FmgrInfo *` from a `PG_FUNCTION_INFO_V1` function directly (or another approach) so two paths aren't needed?

**Comment by hlinnaka** [comment]
> Do you know if there's a way to generate FmgrInfo * from a PG_FUNCTION_INFO_V1 function directly (or another approach) so two paths aren't needed?

Hmm, FunctionCall3 only looks at FmgrInfo->fn_addr, so you could just create a FmgrInfo struct with all other fields left zero.

I think I'm leaning towards the 3rd option, though, with a single support function that returns a bunch of other functions. With that. The individual functions like UpdateCenter are not callable from SQL anyway since they're using `internal`.

**Comment by ankane** [comment]
I think that's the winner. Updated IVFFlat in the commit above.

**Comment by ankane** [comment]
Switched to `static const` in ec640f3b579927e77cdaf5758e8429529a514dcc.

**Comment by ankane** [comment]
Alright, reduced it down to a single support function for each type. Let me know if you have any other thoughts.

**Comment by ankane** [comment]
Closing this out. Thanks again for all of the guidance!
