### ISSUE TITLE
is it possible to import vectors from chroma into pgvector?

### ISSUE THREAD

**Issue by abcnow** [pgvector/pgvector#537]
I wonder if it is possible to import a vector db (chroma) into pgvector? If yes.. how? Thanks in advance!

**Comment by ankane** [comment]
Hi @abcnow, you should be able to fetch data from any data store and [insert or copy](https://github.com/pgvector/pgvector?tab=readme-ov-file#storing) it into Postgres. Please use other resources for help putting together a script.

**Comment by abcnow** [comment]
@ankane similar to this here is what you meant? https://github.com/pgvector/pgvector-python/blob/master/examples/bulk_loading.py

import numpy as np
from pgvector.psycopg import register_vector
import psycopg

# generate random data
rows = 1000000
dimensions = 128
embeddings = np.random.rand(rows, dimensions)

# enable extension
conn = psycopg.connect(dbname='pgvector_example', autocommit=True)
conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
register_vector(conn)

# create table
conn.execute('DROP TABLE IF EXISTS items')
conn.execute(f'CREATE TABLE items (id bigserial, embedding vector({dimensions}))')

# load data
print(f'Loading {len(embeddings)} rows')
cur = conn.cursor()
with cur.copy('COPY items (embedding) FROM STDIN WITH (FORMAT BINARY)') as copy:
    # use set_types for binary copy
    # https://www.psycopg.org/psycopg3/docs/basic/copy.html#binary-copy
    copy.set_types(['vector'])

    for i, embedding in enumerate(embeddings):
        # show progress
        if i % 10000 == 0:
            print('.', end='', flush=True)

        copy.write_row([embedding])

        # flush data
        while conn.pgconn.flush() == 1:
            pass

print('\nSuccess!')

# create any indexes *after* loading initial data (skipping for this example)
if False:
    print('Creating index')
    conn.execute("SET maintenance_work_mem = '8GB'")
    conn.execute('SET max_parallel_maintenance_workers = 7')
    conn.execute('CREATE INDEX ON items USING hnsw (embedding vector_cosine_ops)')

# update planner statistics for good measure
conn.execute('ANALYZE items')
