### ISSUE TITLE
could not load library "/usr/pgsql-16/lib/vector.so"

### ISSUE THREAD

**Issue by khsilent** [pgvector/pgvector#538]
Hi
My project was running smoothly, but suddenly it encountered a problem and gives this error:
could not load library "/usr/pgsql-16/lib/vector.so" 

What's the problem, and how can I solve it?

I also Reinstall vector... => sudo dnf remove pgvector_16 => sudo dnf install pgvector_16

**Comment by BillSmith-EDB** [comment]
@khsilent does the file /usr/pgsql-16/lib/vector.so exist?  If so, check the permissions on the file and parent directories.

**Comment by BillSmith-EDB** [comment]
Do you have the server logfile that shows the complete error message?  I wonder if it's something like this:
`2024-04-30 20:07:47.600 UTC [873] FATAL:  could not load library "/usr/pgsql-15/lib/vector.so": /usr/pgsql-15/lib/vector.so: undefined symbol: _xgetbv
`

**Comment by devrimgunduz** [comment]
@BillSmith-EDB @jkatz yeah that is the message on RHEL 8. Cannot reproduce this on the other distros.

**Comment by BillSmith-EDB** [comment]
@devrimgunduz I see this with my own build on RHEL 8 even though it was built with OPTFLAGS="".  I confirmed that I don't see -march=native on the gcc compilation line.  This does not happen with RHEL 9.

**Comment by khsilent** [comment]
> @khsilent does the file /usr/pgsql-16/lib/vector.so exist? If so, check the permissions on the file and parent directories.

@BillSmith-EDB 
![Screenshot 2024-05-02 154458](https://github.com/pgvector/pgvector/assets/69412226/c0b1b321-5e30-446d-96e1-ad138dcc19bb)
This is file permission

**Comment by BillSmith-EDB** [comment]
@khsilent we'll have to investigate it.  Glad you confirmed that you're seeing the same issue.

**Comment by ankane** [comment]
Hi all, thanks for reporting. What version of GCC are you seeing the error with? We may need to bump dispatching to GCC 8.2+ or 9+ (possibly [due to this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71659)).

For now, you can disable dispatching when compiling with:

```sh
PG_CFLAGS="-DDISABLE_DISPATCH" make
```

[Relevant code](https://github.com/pgvector/pgvector/blob/24c8a2ff40f2f520d018592a6909b57c0c04fb10/src/halfvec.h#L12)

**Comment by BillSmith-EDB** [comment]
@ankane I'm seeing it with 8.5
`gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)`

**Comment by ankane** [comment]
Thank you both. Should be fixed in the commit above, but I'd like to wait a bit before a new release to see if there are other issues.

**Comment by khsilent** [comment]
> Thank you both. Should be fixed in the commit above, but I'd like to wait a bit before a new release to see if there are other issues.

@ankane 
Thank you.
I'm new in linux server
I've insgalled pgvector with `apt`. How to solve this problem?

**Comment by devrimgunduz** [comment]
@ankane thanks! Pushed 0.7.0-2 RPMs to PGDG RPM RHEL 8 repository with that fix .

**Comment by ankane** [comment]
Thanks @devrimgunduz!

**Comment by khsilent** [comment]
> Thank you both. Should be fixed in the commit above, but I'd like to wait a bit before a new release to see if there are other issues.

@ankane Thankful. That Fix.
