### ISSUE TITLE
ERROR: operator class "vector_cosine_ops" does not accept data type sparsevec. on pgvector/pgvector:0.7.0-pg16

### ISSUE THREAD

**Issue by cho-thinkfree-com** [pgvector/pgvector#540]
I am using the Docker image `pgvector/pgvector:0.7.0-pg16`.

Here are my SQL statements.
```
CREATE TABLE items (id bigserial PRIMARY KEY, embedding sparsevec(3));
create index idx_items_emb on items using hnsw ( embedding vector_cosine_ops );
```

I received an error message as shown below.
```
[2024-05-03 00:25:57] [42804] ERROR: operator class "vector_cosine_ops" does not accept data type sparsevec
```

The `README` file explains that the `HNSW` indexing method can also be used with `sparsevec`.

Could someone help me?

**Comment by ankane** [comment]
Hi @cho-thinkfree-com, will improve the docs, but for sparsevec, use `sparsevec_cosine_ops`.

**Comment by cho-thinkfree-com** [comment]
As you suggested, I applied it and it worked well.

Thank you very much for your prompt reply. :-)

I was using the sparse vector feature in `paradedb`.
I am very pleased that the sparse vector has been implemented in `pgvector`.

Thank you for leading such a great project.

**Comment by ankane** [comment]
Thanks @cho-thinkfree-com! Added to the docs in the commit above.

**Comment by noahhai** [comment]
@cho-thinkfree-com also using it - thanks!!
