### ISSUE TITLE
Custom classification algorithm?

### ISSUE THREAD

**Issue by uninstallit** [pgvector/pgvector#542]
I do not know what it takes to write an extension for `postgres` but would it be possible to support other proximity algorithms - or even better allow a custom algorithm with `pgvector`? 

Just a thought.

**Comment by ankane** [comment]
Hi @uninstallit, can you share more context about what you're trying to do? (I don't really understand the question)

**Comment by uninstallit** [comment]
Yes, `pgvector` supports full nearest neighbor search - however, KNN comes with certain assumptions, i.e.: linearly separatable, etc. Let's say I want to apply `dbscan` instead of KNN for the vector search. It would be nice if I had some way to register a function that implements the search algorithm. At least for experimental purposes because I understand it would underperform in speed and other parameters that a database cares for.

**Comment by ankane** [comment]
You can / would need to implement a new [index access method](https://www.postgresql.org/docs/current/indexam.html) to do this.
