### ISSUE TITLE
Different results when doing a query with or without and HNSW index

### ISSUE THREAD

**Issue by jpbalarini** [pgvector/pgvector#543]
Hi! First, thanks for creating and maintaining this awesome extension 🚀 .

I'm having a strange issue where I get different results when my query uses the HNSW index than when it does not.

## This is my relevant table and relevant indexes:

```SQL
CREATE TABLE
  public."DocumentChunk" (
    id text NOT NULL,
    "documentId" text NOT NULL,
    text text NOT NULL,
    "order" integer NOT NULL,
    "documentSectionId" text NULL,
    embedding vector (1024) NOT NULL,

    CONSTRAINT "DocumentChunk_pkey" PRIMARY KEY ("id")
  );

CREATE INDEX "DocumentChunk_embedding_idx" ON "DocumentChunk" USING hnsw("embedding" vector_ip_ops) WITH (m = 4, ef_construction = 10);
...
```

```SQL
SELECT COUNT(*) FROM "DocumentChunk"
27500996
```

## Issue

Since I'm using normalized embeddings, I'm computing the distance with a dot product.
First, I was multiplying everything by * -1, since <#> returns the negative inner product:

```
SELECT "id", "text", "documentId", "documentSectionId", "order", (embedding <#> '[vector]') * -1 as distance
FROM "DocumentChunk"
WHERE (embedding <#> '[vector]') * -1 > 0.6
ORDER BY (embedding <#> '[vector]') * -1 DESC
LIMIT 50;
```

And I get some chunks where their content and distance make sense:

| id         | ... | distance
| ------ | --- | --------- |
| e8bec92d-6d75-43c0-a397-cc223136eb98 | ... | 0.8405799269676208
| e8d2ff73-fd86-4216-99c8-7dcdbaca4c5b | ... | 0.8213955163955688
| f31dbe3f-026c-45ed-baeb-328f98bdbad5 | ... | 0.8135669231414795

But it was taking too long, and I realized that it wasn't using the indexes:
```
Limit  (cost=3750383.24..3750389.08 rows=50 width=912) (actual time=515038.862..515040.239 rows=50 loops=1)
"  ->  Gather Merge  (cost=3750383.24..4641741.71 rows=7639682 width=912) (actual time=515038.860..515040.233 rows=50 loops=1)"
"        Workers Planned: 2"
"        Workers Launched: 2"
"        ->  Sort  (cost=3749383.22..3758932.82 rows=3819841 width=912) (actual time=515034.957..515034.962 rows=38 loops=3)"
"              Sort Key: (((embedding <#> '[vector]'::vector) * '-1'::double precision)) DESC"
"              Sort Method: top-N heapsort  Memory: 103kB"
"              Worker 0:  Sort Method: top-N heapsort  Memory: 95kB"
"              Worker 1:  Sort Method: top-N heapsort  Memory: 103kB"
"              ->  Parallel Seq Scan on ""DocumentChunk""  (cost=0.00..3622490.85 rows=3819841 width=912) (actual time=1.721..513971.360 rows=1491210 loops=3)"
"                    Filter: (((embedding <#> '[vector]'::vector) * '-1'::double precision) > '0.6'::double precision)"
"                    Rows Removed by Filter: 7675789"
```

I assumed it was because of the * -1 as explained [here](https://github.com/pgvector/pgvector?tab=readme-ov-file#why-isnt-a-query-using-an-index), so I changed my query to this, which I assumed should be equivalent (doing the `< -0.6` and `ASC`):

```
SELECT "id", "text", "documentId", "documentSectionId", "order", (embedding <#> '[vector]')
FROM "DocumentChunk"
WHERE (embedding <#> '[vector]') < -0.6
ORDER BY (embedding <#> '[vector]') ASC
LIMIT 50;
```

It started to use the indexes:
```
Limit  (cost=172.42..724.94 rows=50 width=912) (actual time=40.310..43.141 rows=50 loops=1)
"  ->  Index Scan using ""DocumentChunk_embedding_idx"" on ""DocumentChunk""  (cost=172.42..101305406.28 rows=9167618 width=912) (actual time=40.308..43.132 rows=50 loops=1)"
"        Order By: (embedding <#> '[vector]'::vector)"
"        Filter: ((embedding <#> '[vector]'::vector) < '-0.6'::double precision)"
Planning Time: 14.206 ms
Execution Time: 43.245 ms
```

But the results I get are totally different and don't make any sense (disregard that I might have some chunks with duplicate content):
| id         | ... | distance
| ------ | --- | --------- |
| 6eb54818-a54c-47c9-9955-96c1d8d2c170 | ... | -0.6589356660842896
| 4fae15c5-0f0d-4245-844b-4a0a6ee10331 | ... | -0.6589356660842896
| e52fc419-5520-43f4-911d-c688e53cec5d | ... | -0.6589356660842896

I should get an element with a distance of `-0.8405799269676208` since this should be the opposite of the previous query.

I read all the documentation, issues and PRs and can't figure out what is happening. What am I missing?
Thanks!

**Comment by ankane** [comment]
Hi @jpbalarini, you'll see different results for queries that use an approximate index ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#indexing)). You can try increasing `ef_construction` (and then `m` if that doesn't work) to see if it improves recall.

Do you have a lot of duplicate embeddings? It's possible that could be contributing to poor recall.

**Comment by ankane** [comment]
Just noticed you're using `m = 4` and `ef_construction = 10`. This is likely why recall is poor. Try using the defaults.

**Comment by jpbalarini** [comment]
Thanks @ankane . I found where I took those parameters from:
https://www.crunchydata.com/blog/hnsw-indexes-with-postgres-and-pgvector#tldr
No idea why they use those values.

Leaving the default values (partially) did the trick. I now get something that makes some sense, but I'm not getting the values that I need that are closer (0.84  and 0.82).

Without using the index (seq scan):

| id | distance |
| -- | --------- |
e8bec92d-6d75-43c0-a397-cc223136eb98 | 0.8405799269676208
e8d2ff73-fd86-4216-99c8-7dcdbaca4c5b | 0.8213955163955688
f31dbe3f-026c-45ed-baeb-328f98bdbad5 | 0.8135669231414795
d6534c95-523d-4255-b2e7-4dc1758cf5f3 | 0.8135632872581482
... | ...

Using the index:

| id | distance |
| -- | --------- |
f31dbe3f-026c-45ed-baeb-328f98bdbad5 | 0.8135669231414795
d6534c95-523d-4255-b2e7-4dc1758cf5f3 | 0.8135632872581482
fa29f109-dac3-49e0-ada3-e176efeb71f2 | 0.8135602474212646
d09dffd7-1d7e-4e33-aaca-a66253ae9043 | 0.8135518431663513
... | ...

I tried increasing the `ef_construction` from 64 to 96, but the results were the same. I'm now trying with 128 (still building the index). Do you have something to recommend? Maybe trying to increase the `m` size too?
Any recommendation is useful; thanks!

**Comment by ankane** [comment]
I'd recommend calculating recall programmatically over many queries to quantify the difference between sets of parameters. The best parameters will be different for each dataset. I'd try `ef_construction` = 64, 128, 256, and 512 (with `m` = 16) and then `m` = 32 and 64 (with `ef_construction` being at least 4 * `m`) until you reach your target recall.

**Comment by jpbalarini** [comment]
Thanks, Andrew, for your insights! I will try that 💪🏻

**Comment by Giorgi** [comment]
Does higher `m` increase only index building time or query time too? According to https://neon.tech/blog/understanding-vector-search-and-hnsw-index-with-pgvector

> Increasing m means that each point will be connected to more neighbors and would make the graph denser, which can **speed up search queries** at the cost of longer index build times and higher memory usage

But according to https://tembo.io/blog/vector-indexes-in-pgvector#hnsw 

> A big m **affects negatively during query time** since more connections need to be checked, but it also improves recall

Which one is correct?

**Comment by Giorgi** [comment]
@ankane Any thoughts?
