### ISSUE TITLE
Is there some doc to illustrate the storage layout in index file for HNSW ?

### ISSUE THREAD

**Issue by xingtanzjr** [pgvector/pgvector#545]
Hi,

Do you guys know where can I get the storage layout docs for HNSW in pgvector ? I want to know how the index file is organized and how the HNSW graph is stored in PG's index file. Is this similar to what this paper does ?
https://dl.acm.org/doi/pdf/10.1145/3318464.3386131

Thanks,
Jerry

**Comment by ankane** [comment]
Hi @xingtanzjr, the index alternates between [element tuples](https://github.com/pgvector/pgvector/blob/v0.7.0/src/hnsw.h#L307) and [neighbor tuples](https://github.com/pgvector/pgvector/blob/v0.7.0/src/hnsw.h#L321) - see the links for the exact layout of each. It places both tuples on the same page when possible to minimize the number of pages read during an index scan - see [this function](https://github.com/pgvector/pgvector/blob/v0.7.0/src/hnswbuild.c#L148) for more details.

**Comment by xingtanzjr** [comment]
Thank you @ankane ！
