### ISSUE TITLE
Fail to Use index query when add order by desc

### ISSUE THREAD

**Issue by GreateFang** [pgvector/pgvector#548]
Hi team, I found that In a query, when I add desc, It won't query with index, is that normal? I use 5.0.0
![image](https://github.com/pgvector/pgvector/assets/32962590/88b6c9af-a118-48cf-9874-792f30023734)

**Comment by williamhakim10** [comment]
Yes, as specified in the README you need to use an ASC order sort (i.e use `1 - dist`)

**Comment by jkatz** [comment]
The reason for this is that the approximate nearest neighbor (ANN) indexes provided by pgvector are designed to find *nearest* neighbors, which is an ascending sort. A descending sort would find a query vector's *furthest* neighbors, which would require a different indexing scheme.

**Comment by GreateFang** [comment]
> Yes, as specified in the README you need to use an ASC order sort (i.e use `1 - dist`)
thanks for quick reply! I have try 1 - dist while still not use index, Is it because the indexed column underwent mathematical operations?

**Comment by ankane** [comment]
Hi @GreateFang, yes, see the [troubleshooting docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#why-isnt-a-query-using-an-index).

**Comment by ankane** [comment]
Added a note about ascending order to that section as well.

**Comment by GreateFang** [comment]
got it ！thanks~
