### ISSUE TITLE
Can I order by dot product? And how large vector columns can I create?

### ISSUE THREAD

**Issue by polterguy** [pgvector/pgvector#55]
I need to create vector columns with thousands of values, what is the upper limit for the number of values a vector column can have?

And, can I do something similar to the following;

```sql
select * from xyz where dot_product(xyz.vectors, @some_argument) > @some_other_argument order by dot_product(xyz.vectors, @some_argument) desc
```

...?

**Comment by ankane** [comment]
Hey @polterguy, check out the readme.
