### ISSUE TITLE
Make function multiversioning configurable

### ISSUE THREAD

**Issue by aytekinar** [pgvector/pgvector#551]
### Current Behavior

As of `v0.7.0`, we can use `make OPTFLAGS=""` to disable native builds while still enjoying auto vectorization on select distance computations thanks to function multiversioning on Linux.

### Desired Behavior

Currently, the clone targets are hard coded to be `"default", "fma"`. It would be nice to be able to change the targets during build time. Because the targets are hard coded, we need to do something like the following

```sh
$ sed -E 's/target_clones\(([A-Za-z0-9 ,"]+)\)/target_clones(\1, "avx", "avx2", "avx512f")/' -i src/vector.c
$ make OPTFLAGS=""
```

which is a fragile approach. Instead, we would like to have the following

```sh
$ make OPTFLAGS="" CPPFLAGS='-D <SOME_VAR>=\'<SOME_VALUE>\''
```

_without_ changing anything in the checked-out source tree.

### Suggestions

The hard-coded target clones could be defined in a preprocessor directive, which could be overridden during build time.

A PR will follow for further discussions.

**Comment by ankane** [comment]
See #552
