### ISSUE TITLE
Support for multiquery?

### ISSUE THREAD

**Issue by tamis-laan** [pgvector/pgvector#554]
What if I have a batch of vectors I want to query against? I could query for each vector and then combine the results in code but this doesn't sound very efficient. 

I there some kind of batch vector query that is efficient and optimized?

**Comment by ankane** [comment]
Hi @tamis-laan, check out #59.

**Comment by jkatz** [comment]
@tamis-laan What are the results you're trying to achieve?

Here is one example of querying for multiple vectors and unioning the results, but unsure what outcome you're trying to get, so it's hard to make further recommendations:

https://github.com/pgvector/pgvector/issues/275#issuecomment-1732374112

**Comment by tamis-laan** [comment]
Thnx @ankane, that is exactly the problem I'm trying to solve (@jkatz). However my query would consist of 4000+ vectors I all would like to match. A query like:
``` sql
(SELECT 1 AS query, * FROM items ORDER BY embedding <-> '[1,2,3]' LIMIT 1)
UNION ALL
.
.
.
(SELECT 2 AS query, * FROM items ORDER BY embedding <-> '[4,5,6]' LIMIT 1);
```
would probably become very inefficient. So I was wondering can't we pass in a matrix where each row is a vector to be queried. Something like:
``` sql
(SELECT 1 AS query, * FROM items ORDER BY embedding <-> '[[1,2,3],...,[4,5,6]]' LIMIT 10)
```
I can imagine this would be way more efficient given that blocks of memory need to be loaded in and out of memory by postgresql. My database would be ~100GiB in size. My dataset would be much larger, but I'm planning to use multiple databases.

**Comment by arslanafzalch** [comment]
@tamis-laan Did you find any efficient solution for this?
