### ISSUE TITLE
Cannot install pgvector on windows no matter what is tried. 

### ISSUE THREAD

**Issue by antoine186** [pgvector/pgvector#555]
Tried NMAKE command and it threw a "case '4' value already used" error.

Tried using WSL and sudo apt install and it says package not found.

Tried installing homebrew on WSL Ubuntu, managed to download pgvector but extension is not found on PgAdmin for PostgreSQL 16.

Is there anything else to try?

**Comment by ankane** [comment]
Hi @antoine186, I'd try Docker.

**Comment by johnkamau** [comment]
@antoine186 Did you ever get it to compile. Stuck on the same "case '4'" error as well. 

Win 11 x64, 
vs2022, 
Postgres 16

**Comment by ankane** [comment]
@johnkamau See #593.

**Comment by johnkamau** [comment]
> [@johnkamau](https://github.com/johnkamau) See [#593](https://github.com/pgvector/pgvector/issues/593).
Hi, thanks for your post, sadly nothing has worked for me, same error, fresh install of Postgres 16, multiple times, tried running vcvars64.bat, for both vs2019 and vs 2022, no joy. Hoping to find compiled versions online, somewhere at this point, or just switch to docker.
