### ISSUE TITLE
pgvector Query Time Slower Than ChromaDB and pgvector Not Building HNSW Index on Small Number of Rows

### ISSUE THREAD

**Issue by annoyingCode** [pgvector/pgvector#556]
Hi community!

I was trying to shift to pgvector from ChromaDB for my project but I found out that despite having same vector index _(HNSW)_  with the same parameters, there is a significant difference in query time. The parameters that I used to build the HNSW index for pgvector and ChromaDB and the number of data-points with their embedding are as follows:

**1. Construction EF = 100
2. M = 16
3. Search EF = 10
4. Number of rows or datapoints = 99940
5. Embedding dimension = 128**

The query speed for getting top 10 data-points is:

**1. pgvector = 123 milliseconds
2. ChromaDB = 8 milliseconds**

Another problem that I am facing is pgvector is not building HNSW index on small number of data-points _(I tested with 100)_.

What could be the issues here?

**Comment by jkatz** [comment]
@annoyingCode This is challenging to debug without seeing the exact SQL commands (and ideally the EXPLAIN plain) of how you created your table, your index, and what your queries are, as well as the configuration settings for your PostgreSQL database. I do agree that pgvector is not using the index though, as with that size data set with the index, you should be getting single-digit ms queries.

**Comment by jkatz** [comment]
@annoyingCode The above query is using the index and, in this case, returning in < 3ms. I'm not exactly sure what the problem is from a performance perspective. Is there something else going on in your application that is doing some post-processing, or is there latency introduced between where the query runs and is returned?

FWIW, my personal recommendation (particularly with pgvector 0.6+) is to use `ef_construction=256`) as that seems to be the point of maximizing recall / diminishing returns. You may need to have a larger `hnsw.ef_search` to improve recall on the queries (pgvector defaults to `40`).

**Comment by jkatz** [comment]
>  I am still curious about the total query runtime which shows in pgAdmin. Why is it so high?

This depends on many factors, such as how the query is being timed, how busy the system that's timing the query is, and the network latency between your client and database.

> I noticed in the Jupyter notebook that even though pgvector does not build HNSW index on smaller dataset, it still returns the results in time as it would on a bigger dataset with HNSW index.

I'm not following the question. If you're asking why are the query times similar between an unindexed small dataset and an indexed large dataset, you're likely calculating the distance between a similar number of vectors in each query.

**Comment by annoyingCode** [comment]
> I'm not following the question. If you're asking why are the query times similar between an unindexed small dataset and an indexed large dataset, you're likely calculating the distance between a similar number of vectors in each query.

That makes sense. Thank you so much for bearing with me. I really appreciate it!

**Comment by jkatz** [comment]
@annoyingCode No problem - if you have recommendations on how to make this easier, please don't hesitate to provide suggestions.
