### ISSUE TITLE
Supported datatypes

### ISSUE THREAD

**Issue by beikov** [pgvector/pgvector#557]
The documentation doesn't mention why you need a special datatype, so here is the question..

Why can't I use `float(24)[]`/`float4[]` i.e. what is the difference between that and `vector`? Is it the nullability of elements? Or the ability to specify the array size as part of the type?

It would be great if the limitations could be reported to the core PostgreSQL dev team to enhance core types in a way that enables the use of existing core types. Maybe even `float(54)[]`/`float8[]` or `numeric[]` without you having to add explicit support?

**Comment by jkatz** [comment]
@beikov I've spoken at [great length numerous times on this topic](https://jkatz05.com/talks/) 😄 

The short answer is that pgvector provides indexable mechanisms for searching over vector data. The slightly longer answer is that while we're still sussing out the optimal ways to store vectors (storage format, indexing methods), pgvector can move a bit faster than the PostgreSQL project, which is released once a year. At the PostgreSQL developer conference last year, it this was also a strategic decision to let pgvector move faster than the project and get new vector support and functionality into the hands of developers faster.

The good news is that you can fast PostgreSQL array types to `vector`, and vice versa. Additionally, pgvector 0.7.0 added index support for `bit` strings, which are a native PostgreSQL type.

**Comment by beikov** [comment]
Thanks for sharing that. I was not aware that you spoke about this topic in your talks.

I just found [this documentation](https://github.com/postgres/postgres/blob/master/src/include/utils/array.h#L6) about how standard arrays are stored. I guess the main difference is that pgvector types store just the length, oid and array data. So the vector types are a specialization for a single dimension that allow no nulls. Is that a good summary?

**Comment by jkatz** [comment]
I forgot that this was [also discussed indirectly upstream](https://www.postgresql.org/message-id/20230422000723.GB1527017%40nathanxps13).

>  I guess the main difference is that pgvector types store just the length, oid and array data

Even less 😉 [`vector`](https://github.com/pgvector/pgvector/blob/master/src/vector.h#L11) is dimension and the vector itself (with some bits used for handling variable length types and reserved). [`halfvec`](https://github.com/pgvector/pgvector/blob/master/src/halfvec.h#L60) is similar, whereas [`sparsevec`](https://github.com/pgvector/pgvector/blob/master/src/sparsevec.h#L15) is set up for handling the absence of data.

The PostgreSQL array types have a bit more overhead, including OID.

> So the vector types are a specialization for a single dimension that allow no nulls. Is that a good summary?

Yes -- that's a vector in a nutshell (magnitude and direction) 😄 

While I do think it'd be great to have native vector search support in core PostgreSQL in the fullness of time, the current setup with pgvector allows us to go a bit faster. That said, there are likely some changes we need in core PostgreSQL to make things better (which I'm planning to [discuss @ PGConf.dev 2024 in a few weeks](https://www.pgevents.ca/events/pgconfdev2024/schedule/session/1-vectors-how-to-better-support-a-nasty-data-type-in-postgresql/)), such as how we search over data in TOAST tables that happen to be part of the hot path of a query, or dealing with indexing data that goes beyond 8KB.
