### ISSUE TITLE
ivfflat indexing takes 6-8x longer for halfvec than for vector

### ISSUE THREAD

**Issue by mschmidt23** [pgvector/pgvector#562]
Hi,
I have two identical tables: Each has 70 Million embeddings (dim 384). One is of type vector, the other is halfvec. I can confirm this also by the storage the tables take: approx 112G for the vector and approx. 64G for the halfvec table.
The issue is with the indexing with 
"...embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 1000);" 
vs. 
"embeddings USING ivfflat (embedding halfvec_cosine_ops) WITH (lists = 1000);". 
The vector one takes around 1 hour to finish, the halfvec takes 6 to 8 hours. 
Same RDS instance with pgVector 0.7.0 and PG 16.3 (128G mem and 32 CPUs)
Any idea why the halfvec takes that long? I would have expected less time.
Best
Martin

**Comment by ankane** [comment]
Hi @mschmidt23, which instance type are you using, and what are the values of `maintenance_work_mem`, `max_parallel_maintenance_workers`, and `shared_buffers`?

**Comment by mschmidt23** [comment]
@ankane Thanks for the fast response! I am using db.r5.4xlarge instance. I executed the index creation in the same session with
maintenance_work_mem 80GB
max_parallel_maintenance_workers 12
max_parallel_workers 13
shared_buffers  32575744kB
It took now 6 hours on halfvec. That is the same result agin observed yesterday when creating it the first time. Just vector type took 1 hour. Any idea?

**Comment by jkatz** [comment]
@mschmidt23 Curious what happens on a newer instance, either a newer Intel-based (r6i) or Graviton (r7g).

**Comment by ankane** [comment]
My initial thinking is F16C + FMA dispatching might not be happening. Another contributing factor could be using less parallel workers due to a smaller table size (possibly one less - `SET client_min_messages = DEBUG;` will print the worker information during a build).

**Comment by mschmidt23** [comment]
I have now restarted the indexing on halfvec with less workers:
maintenance_work_mem 80GB
max_parallel_maintenance_workers 7
max_parallel_workers 8
shared_buffers 32575744kB

Debug output gives:
DEBUG:  building index "embeddings_retrieval_small_index" on table "embeddings_retrieval_small" serially
DEBUG:  using 7 parallel workers
DEBUG:  RdsSuperUserCache invalidating
DEBUG:  RdsSuperUserCache invalidating
DEBUG:  RdsSuperUserCache invalidating
DEBUG:  RdsSuperUserCache invalidating
DEBUG:  RdsSuperUserCache invalidating
DEBUG:  RdsSuperUserCache invalidating
DEBUG:  RdsSuperUserCache invalidating
...
After 1:10 hour it is at:
"building index: assigning tuples"	18.0%
That's more or less the same slow speed...

**Comment by ankane** [comment]
@mschmidt23 Sorry for the delay. I just tried indexing 1M 384-dimension random vectors with 4 processes (`ivfflat`, 1000 lists, cosine distance) on a r5.xlarge EC2 instance and got the following results:

Type | Index Time
--- | ---
`vector` | 100 sec
`halfvec` | 80 sec

@jkatz Are you able to reproduce on RDS / any ideas?

**Comment by ankane** [comment]
@mschmidt23 If you're still seeing this issue, I'd recommend following up with AWS.
