### ISSUE TITLE
configuring the pgVector like an nightmare 

### ISSUE THREAD

**Issue by MubarakPatel** [pgvector/pgvector#563]
copy vector.dll "C:\Program Files\PostgreSQL\16\lib" The system cannot find the file specified. NMAKE : fatal error U1077: 'copy vector.dll "C:\Program Files\PostgreSQL\16\lib"' : return code '0x1' Stop.

everytime getting this error

**Comment by ankane** [comment]
Hi @MubarakPatel, can you paste all of the commands you ran and their full output (with any personal info removed)?
