### ISSUE TITLE
Issue about version

### ISSUE THREAD

**Issue by sinhnch2001** [pgvector/pgvector#57]
I have a issue about version 0.4.0, and I cannot solve it
```extension "vector" has no installation script nor update path for version "0.4.0"```

**Comment by ankane** [comment]
Hey @sinhnch2001, I'm not sure how to reproduce. A few questions:

1. What OS (including version) are you on?
2. What version of Postgres are you on, and how was it installed?
3. What commands are you running to install pgvector?

**Comment by sinhnch2001** [comment]
- Windows 11
- lastest version of Postgres
- I install pgvector by: 
git clone --branch v0.4.0 https://github.com/pgvector/pgvector.git
make
make install # may need sudo

**Comment by ankane** [comment]
For Windows, you'll need to use `nmake` ([instructions](https://github.com/pgvector/pgvector/issues/38#issuecomment-1343418068)) or install from [conda-forge](https://github.com/pgvector/pgvector#conda-forge). Support is only experimental at this point, so you'll need to run with it from here.
