### ISSUE TITLE
tuning the tmpCtx to improve HNSW build performance

### ISSUE THREAD

**Issue by tvondra** [pgvector/pgvector#570]
Hi,

I've been playing with build of HNSW build, and I think a trivial tuning of the tmpCtx memory context can yield significant performance improvement.

I have a moderately large table with embeddings - 9M embeddings, 28GB of embedding data (total table size is 40GB).

The first thing I tried is simple parallel build:

```
SET max_parallel_workers_per_gather = 8;
SET maintenance_work_mem = '1GB';
CREATE INDEX ON embeddings USING hnsw (e vector_l2_ops);
```

This takes about 13000 seconds. All the workers use 100% CPU, but the profile looks like this:

```
 92.81%  0.01%  postgres  postgres     [.] heapam_index_build_range_scan
   |    
    --92.80%--heapam_index_build_range_scan
        |    
        |--88.64%--BuildCallback
        |    |    
        |     --88.63%--InsertTuple (inlined)
        |      |    
        |       --88.42%--HnswInsertTupleOnDisk
        |        |    
        |        |--45.91%--HnswFindElementNeighbors
        |        |    |    
        |        |     --45.42%--HnswSearchLayer
        |        |      |    
        |        |      |--40.46%--HnswLoadElement
        |        |      |    |    
        |        |      |    |--27.11%--HnswLoadElementFromTuple
        |        |      |    |    |    
        |        |      |    |     --25.39%--datumCopy
        |        |      |    |      |    
        |        |      |    |      |--20.32%--memcpy (inlined)
        |        |      |    |      |    |    
        |        |      |    |      |     --20.30%--__memmove_avx_unaligned_erms_rtm
        |        |      |    |      |      |    
        |        |      |    |      |      |--11.10%--asm_exc_page_fault
        |        |      |    |      |      |    |    
        |        |      |    |      |      |     --10.67%--exc_page_fault
```

So there's a lot of time spent in memory allocation, which is ... surprising. This reminded me some recent experiments with glibc, so I tried running the database with this:

```
export MALLOC_TOP_PAD_=$((64*1024*1024))
export MALLOC_MMAP_THRESHOLD_=$((1024*1024))
export MALLOC_TRIM_THRESHOLD_=$((1024*1024))
```

which ensures the glibc (handling our malloc/free calls) does not return the memory to kernel so aggressively. And with this, the index build takes just ~8300 seconds, which means about 40% speedup.

Of course, tuning glibc by setting environment variables is not very practical. But mostly the same effect can be achieved by altering the memory context parameters a little bit. For example I tried this:

```
@@ -724,7 +724,7 @@ InitBuildState(HnswBuildState * buildstate, Relation heap, Relation index, Index
                                                                                                   1024 * 1024);
        buildstate->tmpCtx = AllocSetContextCreate(CurrentMemoryContext,
                                                                                           "Hnsw build temporary context",
-                                                                                          ALLOCSET_DEFAULT_SIZES);
+                                                                                          32 * 1024 * 1024, 32 * 1024 * 1024, 32 * 1024 * 1024);
 
        InitAllocator(&buildstate->allocator, &HnswMemoryContextAlloc, buildstate);
```

i.e. ensuring the memory context uses 32MB blocks, including the init block. With this, the build time is ~8400 seconds. Considering the build duration is somewhat variable, this is effectively the same as with the glibc tuning.

So perhaps the memory context parameters should be tuned a bit. I don't know if the 32MB is the optimal value, or if it should be tied to maintenance_work_mem or something like that. But clearly the default AllocSet parameters are not great.

Here's a couple more files:

1) flamegraph with default memcontext and no tuning
![default](https://github.com/pgvector/pgvector/assets/539575/2a183804-5992-4840-8bd9-936a63f827b4)

2) flamegraph with glibc tuning
![glibc-tuned](https://github.com/pgvector/pgvector/assets/539575/de0e0944-68eb-4084-93c4-03bd45a33023)

3) flamegraph with context using 32MB blocks (and no glibc tuning)
![context-32mb](https://github.com/pgvector/pgvector/assets/539575/cf735211-a545-4423-a32b-38e961797714)

4) patch to tweak the memory context parameters
[memcontext.txt](https://github.com/pgvector/pgvector/files/15444046/memcontext.txt)

**Comment by jkatz** [comment]
@tvondra To be pedantic, what kinds of embeddings are these (dimensions, dimension data type (fp32?)? My rough math says 768-dim, fp32.

Also, this looks really promising 😄 But the reason I'm being pedantic is I think it'd be good to test the contexts across some different dimensionalities. [VectorDBBench](https://github.com/zilliztech/VectorDBBench) has a few large datasets for 768/1536 dim, it may be worth to try it out on the 1536 dim to see if you still see a similar gain (my gut says there will be a gain).

**Comment by tvondra** [comment]
Yes, vector(768) with FP32.

**Comment by ankane** [comment]
Hi @tvondra, nice find! From some initial testing (and the profile), it looks like this affects the on-disk phase of the index build and can likely be applied to inserts as well. I also think we may be able to avoid copying vectors entirely if they are outside of the max candidate distance, so will take a look at that as well as part of this.

**Comment by ankane** [comment]
Pushed a version of less copying to the [hnsw-less-copy branch](https://github.com/pgvector/pgvector/compare/hnsw-less-copy). Initial results for 100k, 1536-dimension random vectors on my local machine (using 64MB for `maintenance_work_mem`): 189 sec before, 165 sec after.

**Comment by ankane** [comment]
Merged the branch in the commit above. There still may be some room to tune the memory context, but this should get most of the benefit from my testing.
