### ISSUE TITLE
Index vector_ip_ops does not work for halfvec

### ISSUE THREAD

**Issue by jadbox** [pgvector/pgvector#571]
When trying to create index:

-- Create an index for the semantic vector search
create index on documents using hnsw (embedding vector_ip_ops);

ERROR: 42804: operator class "vector_ip_ops" foes not accept data type halfvec

**Comment by jkatz** [comment]
@jadbox You need to use `halfvec_ip_ops`, e.g.:

```sql
CREATE INDEX ON documents USING hnsw (embedding halfvec_ip_ops);
```
