### ISSUE TITLE
Can the "LIMIT" statement be included as one of arguments when doing scan operation?

### ISSUE THREAD

**Issue by nkg114mc** [pgvector/pgvector#572]
Hi,

I notice that in the IVF scan methods, the argument like "LIMIT K" was not considered as input arguments. For example, in this function (https://github.com/pgvector/pgvector/blob/master/src/ivfscan.c#L158): 				
```
				tuplesort_puttupleslot(so->sortstate, slot);

				tuples++;
```
It basically adds every found tuple into the result list and sort. However, due to the LIMIT statement, sometimes we might just want to return top-K results. Then sorting all found tuples will be unnecessary and wastes a lot time. Think about an extreme case in IVF, where there might be 1 million items in all the nearest lists, but results only requires 3 due to a "LIMIT 3" in the query. Sorting a list of 1000000 and 3 will be non-trivially different.

So why "LIMIT K" is not considered in the scan methods?

I have some guesses:
1. It is natural of scan in Postgres index access method, where a scan is not supposed to know (or no way to know) the "K" in "LIMIT" statement?
2. It is possible but may come across some difficulties in the implementation?

If possible, can we add it when doing the `ambeginscan`?

**Comment by ankane** [comment]
Hi @nkg114mc, index scans don't know the limit, as they don't know which index tuples are visible to the current transaction or will be filtered by non-index conditions in the query (which needs to happen before the limit is applied).

I did some experiments a while back with setting a bound on the tuple sort ([bound branch](https://github.com/pgvector/pgvector/compare/bound)) as well as using a pairing heap ([pairingheap](https://github.com/pgvector/pgvector/compare/pairingheap) and [stages](https://github.com/pgvector/pgvector/compare/stages) branches), but from what I recall, the performance difference didn't justify the complexity. However, someone is welcome to submit a PR (with benchmarks) with a better approach.
