### ISSUE TITLE
A question about building index in background.

### ISSUE THREAD

**Issue by xingtanzjr** [pgvector/pgvector#576]
Hi,

I am new to postgres and new to pgvector. Currently I am reading the source code of pgvector. I noticed that pgvector supports building index in parallel with several processes. But the whole index build stage ( _implemented in ambuild_ ) is still in a sync mode. For example, when users run creating index in cmd line, it will wait until the index building finishes.

So...my question is: does pgvector supports building the index in background ? And a further question is, does postgres also index extension to build the index in background mode ?

I am not sure my question is suitable or not. Appreciate your any input ! Thanks !

**Comment by jkatz** [comment]
Yes:

```sql
CREATE INDEX CONCURRENTLY ...
```
