### ISSUE TITLE
Large vector data type will cause performance decline?

### ISSUE THREAD

**Issue by JackTan25** [pgvector/pgvector#578]
I use pgvector's vector type as my postgres's vector type. And my vector has 1025 dimensions. But I find out 'select id from vector_table where btree_id < 50 order by vector_col <-> vector_const limit 50;(use btree index to do query, and the number of tuples which satisfy `btree_id < 50` is 2092). The performance is very slow., costs 62ms(I use simd to improve) The raw vector can't overcome the raw array data type? It will cause high I/O?

**Comment by ankane** [comment]
Hi @JackTan25, use `EXPLAIN ANALYZE` to debug query performance ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#querying-1)).
