### ISSUE TITLE
A question regard table_open() in background worker when building index

### ISSUE THREAD

**Issue by xingtanzjr** [pgvector/pgvector#579]
Hi, 

I am reading the code of parallel build part. Thanks for writing such awesome and elegant code!

I have a question about the background worker. The question is, I noticed that background worker will fetch the heap_oid from DSM and call table_open() to open the table for preparing of table_scan. But I didn't saw the initailization code of data base connection. I read the doc the background worker and it said the bgworker should call `BackgroundWorkerInitializeConnection()` to connect to some database. So... how it works here ?

Thanks!

**Comment by ankane** [comment]
Hi @xingtanzjr, pgvector doesn't use the [background worker API](https://www.postgresql.org/docs/current/bgworker.html) for parallel builds.

**Comment by xingtanzjr** [comment]
@ankane When calling `LaunchParallelWorkers()`, it starts several background worker process. It seems that using `CreateParallelContext` will finally trigger background worker's creation. Is that correct ?

**Comment by ankane** [comment]
`LaunchParallelWorkers` creates the workers. Please see the [Postgres source code](https://github.com/postgres/postgres/blob/REL_16_3/src/backend/access/transam/parallel.c#L550) for additional questions.
