### ISSUE TITLE
scalability issues - any tests available?

### ISSUE THREAD

**Issue by shashi-netra** [pgvector/pgvector#58]
Hi, creator of [pgann](https://github.com/netrasys/pgANN) project here. 

Clearly `pgvector` is a much more sophisticated extension, but checking to see if you have scalability tests. With `pgann` we usually hit a limit at few million records, even with a powerful `pgsql` instance. Can anyone share any scalability related findings?

**Comment by ankane** [comment]
Hey @shashi-netra, there's not currently testing around scale, and the highest I've seen a user report was 25M records. Increasing the number of lists will improve query performance (but trades off recall). For a very large number of records, a common technique is [product quantization](https://mccormickml.com/2017/10/13/product-quantizer-tutorial-part-1/), which I'm planning to support at some point.
