### ISSUE TITLE
Type Error when working with Langchain (Missing Positional Argument: evalue)

### ISSUE THREAD

**Issue by danishzmalik** [pgvector/pgvector#581]
Hey,
Ive been trying to create and load data to Postgres through PgVector, using:

`db = PGVector.from_documents(documents = docs,embedding=embed_model, connection =CONNECTION_STRING, collection_name='test_vs' )`

This is the error (No further traceback) im getting:
![image](https://github.com/pgvector/pgvector/assets/8587744/31f06823-afc5-4e5e-b454-4eba37cef2dc)

**TypeError: AutoFormattedTB.structured_traceback() missing 1 required positional argument: 'evalue'**

Everything else checks out i.e. the Connection string, docs & embed model.

Databricks Runtime: 14
Aurora Postgres Version: 12.18
PGVector Installed: Yes
Vector Extension Created: Yes

Relevant Package Installations & Imports:
%pip install langchain==0.1.16
%pip install langchain_community==0.0.34
%pip install langchain_experimental==0.0.57
%pip install langchain_openai==0.1.3
%pip install langchain_postgres
%pip install pgvector

from langchain_postgres import PGVector
from langchain_postgres.vectorstores import PGVector

**Comment by jkatz** [comment]
There's nothing specific to pgvector here - the current error seems related to the [error handling library](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.ultratb.html#IPython.core.ultratb.TBTools.structured_traceback) being used. I'd suggest using LangChain resources to troubleshoot.
