### ISSUE TITLE
pgvector still use row-based storage instead of columnar storage ?

### ISSUE THREAD

**Issue by baiwfg2** [pgvector/pgvector#583]
Some people says columnar storage is more suitable for vector databases than row-based storage. It makes sense to me to some extent, because it probably reduce disk accesses for querying large amount of data.

Since pgvector is an extension of PG and still use the underlying storage mechanism such as using heap as tuple container, is it good for vector database scenario ? I wonder what opinions are about this.

**Comment by ankane** [comment]
Hi @baiwfg2, row-based storage is better for online transaction processing (OLTP). You could try using something like [Citus](https://github.com/citusdata/citus) that supports columnar storage to see if it makes a difference for your use case.
