### ISSUE TITLE
Comparison with high-precision data

### ISSUE THREAD

**Issue by galovics** [pgvector/pgvector#589]
Hi,

I found some closed issues where people are complaining about loss of data precision:
- https://github.com/pgvector/pgvector/issues/182
- https://github.com/pgvector/pgvector-python/issues/4

I'm in the exact same situation. If I do:

```
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(1));
INSERT INTO items (embedding) VALUES ('[-0.03210742026567459]');
SELECT * FROM items;
```

Then the output is:

```
id | embedding
1 | [-0.03210742]
```

I understand the fact that pgvector is using a 4-byte float to store the values (why though?) and this is a limitation. The suggestion in the GH issues and in the docs is to use a higher precision data type for the embedding and in the select statement when using a distance function, convert the higher precision to a vector type.

My question is - and this isn't clear based on the docs and the other GH issues - that, does this truncate the accuracy of the value as well when executing the distance function? I assume it does and even though the values are stored now with higher precision, the vector conversion still executes a 4-byte float conversion behind the scenes. This way the storage of data with high-precision is solved yet PGVector and the distance functions can't make any use of the higher precision.

Is my assumption correct?

Thanks.

**Comment by ankane** [comment]
Hi @galovics, yes, when you convert a higher precision type to `vector`, the resulting value will have the precision of `vector`.
