### ISSUE TITLE
Question: is it possible to infer value for multiple points?

### ISSUE THREAD

**Issue by JDRanpariya** [pgvector/pgvector#59]
```SELECT * FROM items ORDER BY embedding <-> '[3,1,2]' LIMIT 1;```

In above case we are getting nearest neighbour for [3,1,2]. Is there a way I can provide multiple embeddings like ('[3,1,2]'), ('[9,5,4]') and get neighbours for all of them?

**Comment by ankane** [comment]
Hey @JDRanpariya, you can use `UNION ALL` to combine queries in Postgres.

```sql
(SELECT 1 AS query, * FROM items ORDER BY embedding <-> '[1,2,3]' LIMIT 1)
UNION ALL
(SELECT 2 AS query, * FROM items ORDER BY embedding <-> '[4,5,6]' LIMIT 1);
```

**Comment by JDRanpariya** [comment]
Thanks @ankane. Will try using that but seems like it would be big of a query if I have 1k+ vectors for inference.

**Comment by ankane** [comment]
It shouldn't be an issue for Postgres, but you could also try creating a function to see if it reduces overhead.

**Comment by SKLC1** [comment]
works great for a handful of vectors, cheers
