### ISSUE TITLE
Weight in the filters

### ISSUE THREAD

**Issue by skhaz** [pgvector/pgvector#590]
Would it be possible to have weight in the filters? Let's suppose I would like one to have maximum weight and another to have half.

Thank you.

Related: https://github.com/pgvector/pgvector/issues/88

**Comment by ankane** [comment]
Hi @skhaz, can you share more context? I don't really understand the question.

**Comment by skhaz** [comment]
Please take a look on AWS Kendra boost property

https://aws.amazon.com/blogs/machine-learning/relevance-tuning-with-amazon-kendra/

**Comment by ankane** [comment]
You can use any valid SQL in the `ORDER BY` clause.

```sql
SELECT * FROM items
    ORDER BY (embedding <-> '[3,1,2]') * (CASE WHEN category_id = 1 THEN 0.5 ELSE 1 END)
    LIMIT 5;
```

**Comment by skhaz** [comment]
I'm sorry, but I don't think this query is equivalent. I would like to have multiple filters, each with its own weight.

**Comment by ankane** [comment]
You can use the approach above with multiple filters. Please use other resources if you need help adapting it to your use case.
