### ISSUE TITLE
src\bitvec.c(43): warning C4141: 'dllexport': used more than once

### ISSUE THREAD

**Issue by a1ryang** [pgvector/pgvector#593]
I'm installing it on Windows 11 with PostgreSQL 16. I got the git clone to work, but when I ran the nmake command (nmake /F Makefile.win) I'm getting a few errors:

src\bitvec.c(43): warning C4141: 'dllexport': used more than once
C:\Program Files\PostgreSQL\16\include\server\access/tupmacs.h(65): error C2196: case value '4' already used
C:\Program Files\PostgreSQL\16\include\server\access/tupmacs.h(197): error C2196: case value '4' already used
src\hnsw.c(190): warning C4141: 'dllexport': used more than once
NMAKE : fatal error U1077: 'cl /nologo /I"C:\Program Files\PostgreSQL\16\include\server\port\win32_msvc" /I"C:\Program Files\PostgreSQL\16\include\server\port\win32" /I"C:\Program Files\PostgreSQL\16\include\server" /I"C:\Program Files\PostgreSQL\16\include" /O2 /fp:fast /c src\hnsw.c /Fosrc\hnsw.obj' : return code '0x2'
Stop.

Can anyone please provide assistance?

Thank you.

Aaron

**Comment by ankane** [comment]
Hi @a1ryang, it looks like you may have another extension installed that exports `hamming_distance` and `hnswhandler` functions.

**Comment by a1ryang** [comment]
Thank you for that. Here's my list of installed extensions. Are you able to advise regarding the way forward?

                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

**Comment by ankane** [comment]
What's the output of the following query?

```sql
SELECT * FROM pg_available_extensions ORDER BY name;
```

**Comment by a1ryang** [comment]
Oh. ChatGPT misled me. Here you go:

"name"	"default_version"	"installed_version"	"comment"
"adminpack"	"2.1"		"administrative functions for PostgreSQL"
"amcheck"	"1.3"		"functions for verifying relation integrity"
"autoinc"	"1.0"		"functions for autoincrementing fields"
"bloom"	"1.0"		"bloom access method - signature file based index"
"bool_plperl"	"1.0"		"transform between bool and plperl"
"bool_plperlu"	"1.0"		"transform between bool and plperlu"
"btree_gin"	"1.3"		"support for indexing common datatypes in GIN"
"btree_gist"	"1.7"		"support for indexing common datatypes in GiST"
"citext"	"1.6"		"data type for case-insensitive character strings"
"cube"	"1.5"		"data type for multidimensional cubes"
"dblink"	"1.2"		"connect to other PostgreSQL databases from within a database"
"dict_int"	"1.0"		"text search dictionary template for integers"
"dict_xsyn"	"1.0"		"text search dictionary template for extended synonym processing"
"dummy_index_am"	"1.0"		"dummy_index_am - index access method template"
"dummy_seclabel"	"1.0"		"Test code for SECURITY LABEL feature"
"earthdistance"	"1.1"		"calculate great-circle distances on the surface of the Earth"
"file_fdw"	"1.0"		"foreign-data wrapper for flat file access"
"fuzzystrmatch"	"1.2"		"determine similarities and distance between strings"
"hstore"	"1.8"		"data type for storing sets of (key, value) pairs"
"hstore_plperl"	"1.0"		"transform between hstore and plperl"
"hstore_plperlu"	"1.0"		"transform between hstore and plperlu"
"hstore_plpython3u"	"1.0"		"transform between hstore and plpython3u"
"insert_username"	"1.0"		"functions for tracking who changed a table"
"intagg"	"1.1"		"integer aggregator and enumerator (obsolete)"
"intarray"	"1.5"		"functions, operators, and index support for 1-D arrays of integers"
"isn"	"1.2"		"data types for international product numbering standards"
"jsonb_plperl"	"1.0"		"transform between jsonb and plperl"
"jsonb_plperlu"	"1.0"		"transform between jsonb and plperlu"
"jsonb_plpython3u"	"1.0"		"transform between jsonb and plpython3u"
"lo"	"1.1"		"Large Object maintenance"
"ltree"	"1.2"		"data type for hierarchical tree-like structures"
"ltree_plpython3u"	"1.0"		"transform between ltree and plpython3u"
"moddatetime"	"1.0"		"functions for tracking last modification time"
"old_snapshot"	"1.0"		"utilities in support of old_snapshot_threshold"
"pageinspect"	"1.12"		"inspect the contents of database pages at a low level"
"pg_buffercache"	"1.4"		"examine the shared buffer cache"
"pg_freespacemap"	"1.2"		"examine the free space map (FSM)"
"pg_prewarm"	"1.2"		"prewarm relation data"
"pg_stat_statements"	"1.10"		"track planning and execution statistics of all SQL statements executed"
"pg_surgery"	"1.0"		"extension to perform surgery on a damaged relation"
"pg_trgm"	"1.6"		"text similarity measurement and index searching based on trigrams"
"pg_visibility"	"1.2"		"examine the visibility map (VM) and page-level visibility info"
"pg_walinspect"	"1.1"		"functions to inspect contents of PostgreSQL Write-Ahead Log"
"pgcrypto"	"1.3"		"cryptographic functions"
"pgrowlocks"	"1.2"		"show row-level locking information"
"pgstattuple"	"1.5"		"show tuple-level statistics"
"pldbgapi"	"1.1"		"server-side support for debugging PL/pgSQL functions"
"plperl"	"1.0"		"PL/Perl procedural language"
"plperlu"	"1.0"		"PL/PerlU untrusted procedural language"
"plpgsql"	"1.0"	"1.0"	"PL/pgSQL procedural language"
"plpython3u"	"1.0"		"PL/Python3U untrusted procedural language"
"plsample"	"1.0"		"PL/Sample"
"pltcl"	"1.0"		"PL/Tcl procedural language"
"pltclu"	"1.0"		"PL/TclU untrusted procedural language"
"postgres_fdw"	"1.1"		"foreign-data wrapper for remote PostgreSQL servers"
"refint"	"1.0"		"functions for implementing referential integrity (obsolete)"
"seg"	"1.4"		"data type for representing line segments or floating-point intervals"
"spgist_name_ops"	"1.0"		"Test opclass for SP-GiST"
"sslinfo"	"1.2"		"information about SSL certificates"
"system_stats"	"2.0"		"EnterpriseDB system statistics for PostgreSQL"
"tablefunc"	"1.0"		"functions that manipulate whole tables, including crosstab"
"tcn"	"1.0"		"Triggered change notifications"
"test_bloomfilter"	"1.0"		"Test code for Bloom filter library"
"test_copy_callbacks"	"1.0"		"Test code for COPY callbacks"
"test_custom_rmgrs"	"1.0"		"Test code for custom WAL resource managers"
"test_ddl_deparse"	"1.0"		"Test code for DDL deparse feature"
"test_ext1"	"1.0"		"Test extension 1"
"test_ext2"	"1.0"		"Test extension 2"
"test_ext3"	"1.0"		"Test extension 3"
"test_ext4"	"1.0"		"Test extension 4"
"test_ext5"	"1.0"		"Test extension 5"
"test_ext6"	"1.0"		"test_ext6"
"test_ext7"	"1.0"		"Test extension 7"
"test_ext8"	"1.0"		"Test extension 8"
"test_ext_cine"	"1.0"		"Test extension using CREATE IF NOT EXISTS"
"test_ext_cor"	"1.0"		"Test extension using CREATE OR REPLACE"
"test_ext_cyclic1"	"1.0"		"Test extension cyclic 1"
"test_ext_cyclic2"	"1.0"		"Test extension cyclic 2"
"test_ext_evttrig"	"1.0"		"Test extension - event trigger"
"test_ext_extschema"	"1.0"		"test @extschema@"
"test_ext_req_schema1"	"1.0"		"Required extension to be referenced"
"test_ext_req_schema2"	"1.0"		"Test schema referencing of required extensions"
"test_ext_req_schema3"	"1.0"		"Test schema referencing of 2 required extensions"
"test_ginpostinglist"	"1.0"		"Test code for ginpostinglist.c"
"test_integerset"	"1.0"		"Test code for integerset"
"test_lfind"	"1.0"		"Test code for optimized linear search functions"
"test_parser"	"1.0"		"example of a custom parser for full-text search"
"test_pg_dump"	"1.0"		"Test pg_dump with an extension"
"test_predtest"	"1.0"		"Test code for optimizer/util/predtest.c"
"test_rbtree"	"1.0"		"Test code for red-black tree library"
"test_regex"	"1.0"		"Test code for backend/regex/"
"test_shm_mq"	"1.0"		"Test code for shared memory message queues"
"test_slru"	"1.0"		"Test code for SLRU"
"tsm_system_rows"	"1.0"		"TABLESAMPLE method which accepts number of rows as a limit"
"tsm_system_time"	"1.0"		"TABLESAMPLE method which accepts time in milliseconds as a limit"
"unaccent"	"1.1"		"text search dictionary that removes accents"
"uuid-ossp"	"1.1"		"generate universally unique identifiers (UUIDs)"
"worker_spi"	"1.0"		"Sample background worker"
"xml2"	"1.1"		"XPath querying and XSLT"

**Comment by ankane** [comment]
It looks like you have a lot of custom extensions, so I'm guessing it's due to one of those (or something else specific to your installation).

**Comment by a1ryang** [comment]
Thank you for the prompt responses here. I don't recall installing anything on top of the base PostgreSQL, so I was confused when I saw all of these listed.

**Comment by ankane** [comment]
It looks like the warning wasn't the issue here (and has been addressed in #598).

The error seems to be something with your Postgres installation:

```text
C:\Program Files\PostgreSQL\16\include\server\access/tupmacs.h(65): error C2196: case value '4' already used
```

It looks like `sizeof(Datum)` is returning 4, even though that condition should only be added if `SIZEOF_DATUM == 8`.

https://github.com/postgres/postgres/blob/REL_16_3/src/include/access/tupmacs.h#L64-L67

(in any case, it doesn't seem like an issue with pgvector)

**Comment by siddagra** [comment]
same error not sure why. I installed Postgres 5min ago and connected it to Python. doesn't work

**Comment by siddagra** [comment]
"name"	"default_version"	"installed_version"	"comment"
"adminpack"	"2.1"	"2.1"	"administrative functions for PostgreSQL"
"amcheck"	"1.3"		"functions for verifying relation integrity"
"autoinc"	"1.0"		"functions for autoincrementing fields"
"bloom"	"1.0"		"bloom access method - signature file based index"
"bool_plperl"	"1.0"		"transform between bool and plperl"
"bool_plperlu"	"1.0"		"transform between bool and plperlu"
"btree_gin"	"1.3"		"support for indexing common datatypes in GIN"
"btree_gist"	"1.7"		"support for indexing common datatypes in GiST"
"citext"	"1.6"		"data type for case-insensitive character strings"
"cube"	"1.5"		"data type for multidimensional cubes"
"dblink"	"1.2"		"connect to other PostgreSQL databases from within a database"
"dict_int"	"1.0"		"text search dictionary template for integers"
"dict_xsyn"	"1.0"		"text search dictionary template for extended synonym processing"
"dummy_index_am"	"1.0"		"dummy_index_am - index access method template"
"dummy_seclabel"	"1.0"		"Test code for SECURITY LABEL feature"
"earthdistance"	"1.1"		"calculate great-circle distances on the surface of the Earth"
"file_fdw"	"1.0"		"foreign-data wrapper for flat file access"
"fuzzystrmatch"	"1.2"		"determine similarities and distance between strings"
"hstore"	"1.8"		"data type for storing sets of (key, value) pairs"
"hstore_plperl"	"1.0"		"transform between hstore and plperl"
"hstore_plperlu"	"1.0"		"transform between hstore and plperlu"
"hstore_plpython3u"	"1.0"		"transform between hstore and plpython3u"
"insert_username"	"1.0"		"functions for tracking who changed a table"
"intagg"	"1.1"		"integer aggregator and enumerator (obsolete)"
"intarray"	"1.5"		"functions, operators, and index support for 1-D arrays of integers"
"isn"	"1.2"		"data types for international product numbering standards"
"jsonb_plperl"	"1.0"		"transform between jsonb and plperl"
"jsonb_plperlu"	"1.0"		"transform between jsonb and plperlu"
"jsonb_plpython3u"	"1.0"		"transform between jsonb and plpython3u"
"lo"	"1.1"		"Large Object maintenance"
"ltree"	"1.2"		"data type for hierarchical tree-like structures"
"ltree_plpython3u"	"1.0"		"transform between ltree and plpython3u"
"moddatetime"	"1.0"		"functions for tracking last modification time"
"old_snapshot"	"1.0"		"utilities in support of old_snapshot_threshold"
"pageinspect"	"1.12"		"inspect the contents of database pages at a low level"
"pg_buffercache"	"1.4"		"examine the shared buffer cache"
"pg_freespacemap"	"1.2"		"examine the free space map (FSM)"
"pg_prewarm"	"1.2"		"prewarm relation data"
"pg_stat_statements"	"1.10"		"track planning and execution statistics of all SQL statements executed"
"pg_surgery"	"1.0"		"extension to perform surgery on a damaged relation"
"pg_trgm"	"1.6"		"text similarity measurement and index searching based on trigrams"
"pg_visibility"	"1.2"		"examine the visibility map (VM) and page-level visibility info"
"pg_walinspect"	"1.1"		"functions to inspect contents of PostgreSQL Write-Ahead Log"
"pgcrypto"	"1.3"		"cryptographic functions"
"pgrowlocks"	"1.2"		"show row-level locking information"
"pgstattuple"	"1.5"		"show tuple-level statistics"
"pldbgapi"	"1.1"		"server-side support for debugging PL/pgSQL functions"
"plperl"	"1.0"		"PL/Perl procedural language"
"plperlu"	"1.0"		"PL/PerlU untrusted procedural language"
"plpgsql"	"1.0"	"1.0"	"PL/pgSQL procedural language"
"plpython3u"	"1.0"		"PL/Python3U untrusted procedural language"
"plsample"	"1.0"		"PL/Sample"
"pltcl"	"1.0"		"PL/Tcl procedural language"
"pltclu"	"1.0"		"PL/TclU untrusted procedural language"
"postgres_fdw"	"1.1"		"foreign-data wrapper for remote PostgreSQL servers"
"refint"	"1.0"		"functions for implementing referential integrity (obsolete)"
"seg"	"1.4"		"data type for representing line segments or floating-point intervals"
"spgist_name_ops"	"1.0"		"Test opclass for SP-GiST"
"sslinfo"	"1.2"		"information about SSL certificates"
"system_stats"	"3.0"		"EnterpriseDB system statistics for PostgreSQL"
"tablefunc"	"1.0"		"functions that manipulate whole tables, including crosstab"
"tcn"	"1.0"		"Triggered change notifications"
"test_bloomfilter"	"1.0"		"Test code for Bloom filter library"
"test_copy_callbacks"	"1.0"		"Test code for COPY callbacks"
"test_custom_rmgrs"	"1.0"		"Test code for custom WAL resource managers"
"test_ddl_deparse"	"1.0"		"Test code for DDL deparse feature"
"test_ext1"	"1.0"		"Test extension 1"
"test_ext2"	"1.0"		"Test extension 2"
"test_ext3"	"1.0"		"Test extension 3"
"test_ext4"	"1.0"		"Test extension 4"
"test_ext5"	"1.0"		"Test extension 5"
"test_ext6"	"1.0"		"test_ext6"
"test_ext7"	"1.0"		"Test extension 7"
"test_ext8"	"1.0"		"Test extension 8"
"test_ext_cine"	"1.0"		"Test extension using CREATE IF NOT EXISTS"
"test_ext_cor"	"1.0"		"Test extension using CREATE OR REPLACE"
"test_ext_cyclic1"	"1.0"		"Test extension cyclic 1"
"test_ext_cyclic2"	"1.0"		"Test extension cyclic 2"
"test_ext_evttrig"	"1.0"		"Test extension - event trigger"
"test_ext_extschema"	"1.0"		"test @extschema@"
"test_ext_req_schema1"	"1.0"		"Required extension to be referenced"
"test_ext_req_schema2"	"1.0"		"Test schema referencing of required extensions"
"test_ext_req_schema3"	"1.0"		"Test schema referencing of 2 required extensions"
"test_ginpostinglist"	"1.0"		"Test code for ginpostinglist.c"
"test_integerset"	"1.0"		"Test code for integerset"
"test_lfind"	"1.0"		"Test code for optimized linear search functions"
"test_parser"	"1.0"		"example of a custom parser for full-text search"
"test_pg_dump"	"1.0"		"Test pg_dump with an extension"
"test_predtest"	"1.0"		"Test code for optimizer/util/predtest.c"
"test_rbtree"	"1.0"		"Test code for red-black tree library"
"test_regex"	"1.0"		"Test code for backend/regex/"
"test_shm_mq"	"1.0"		"Test code for shared memory message queues"
"test_slru"	"1.0"		"Test code for SLRU"
"tsm_system_rows"	"1.0"		"TABLESAMPLE method which accepts number of rows as a limit"
"tsm_system_time"	"1.0"		"TABLESAMPLE method which accepts time in milliseconds as a limit"
"unaccent"	"1.1"		"text search dictionary that removes accents"
"uuid-ossp"	"1.1"		"generate universally unique identifiers (UUIDs)"
"worker_spi"	"1.0"		"Sample background worker"
"xml2"	"1.1"		"XPath querying and XSLT"

**Comment by ankane** [comment]
Seems like that would explain it. Thanks for sharing @steventhorne.

**Comment by apoorvam** [comment]
@ankane  I am see the same issue with Postgres 17.5 and pgvector in Windows. I cloned and running `nmake /F Makefile.win` gives me error as: 

```

        cl /nologo /I"C:\Program Files\PostgreSQL\17\include\server\port\win32_msvc" /I"C:\Program Files\PostgreSQL\17\include\server\port\win32" /I"C:\Program Files\PostgreSQL\17\include\server" /I"C:\Program Files\PostgreSQL\17\include"   /O2 /fp:fast /c src\hnsw.c /Fosrc\hnsw.obj
hnsw.c
C:\Program Files\PostgreSQL\17\include\server\access/tupmacs.h(65): error C2196: case value '4' already used
C:\Program Files\PostgreSQL\17\include\server\access/tupmacs.h(197): error C2196: case value '4' already used
NMAKE : fatal error U1077: 'cl /nologo /I"C:\Program Files\PostgreSQL\17\include\server\port\win32_msvc" /I"C:\Program Files\PostgreSQL\17\include\server\port\win32" /I"C:\Program Files\PostgreSQL\17\include\server" /I"C:\Program Files\PostgreSQL\17\include"   /O2 /fp:fast /c src\hnsw.c /Fosrc\hnsw.obj' : return code '0x2'
Stop.
```
I dont understand what this meant from above comment:

> I ran into the same issue and realized I accidentally called `vcvars32.bat` instead of `vcvars64.bat` before running nmake.

Any suggestions on what could be missing in my setup? I dont see any mismatch in arch because i installed postgresql for win-64. But i do see this path `C:\Program Files\PostgreSQL\17\include\server\port\win32_msvc` exists in my machine

**Comment by ankane** [comment]
Check out the [installation notes](https://github.com/pgvector/pgvector?tab=readme-ov-file#mismatched-architecture) (your Postgres installation is 64-bit, but you're trying to compile pgvector for 32-bit).

**Comment by apoorvam** [comment]
@ankane Thanks, it would be nice to add in documentation there that we need to use "x64 Native Tools Command Prompt for VS 2022" (replace the right version number). That wasnt obvious to me as first time building this. 

Running above command prompt as administrator and then compile as below worked for me:
 
```
set "PGROOT=C:\Program Files\PostgreSQL\17"
nmake /F Makefile.win clean
nmake /F Makefile.win 
nmake /F Makefile.win install
```

**Comment by ankane** [comment]
Glad it's working. fwiw, you shouldn't need to use the x64 command prompt if you run `vcvars64.bat` (but that works as an alternative).

**Comment by ankane** [comment]
Updated the docs to use the command prompt instead of calling `vcvars64.bat` in the commit above (as I think it's probably easier). Thanks for the suggestion.
