### ISSUE TITLE
Porting indexes from pinecone to pgvector

### ISSUE THREAD

**Issue by TitasDas** [pgvector/pgvector#594]
I recently read about the [performance gain](https://www.timescale.com/blog/pgvector-is-now-as-fast-as-pinecone-at-75-less-cost/) pgvector has over Pinecone and am opening this issue to understand if it is applicable to our use case. We have 3-4 serverless indexes in Pinecone using ada002 embeddings (1536 dim vectors). We also have a RAG powered by this vectordb and are considering shifting to pgvector.

What is the best way to set up or port vectors from Pinecone to pgvector? What factors should we consider? While pgvector shows a performance gain, it may have an elaborate setup. Any tips on that? Feel free to ask for more specifications if needed.

**Comment by ankane** [comment]
Hi @TitasDas, you should be able to fetch data from any data store and [insert or copy](https://github.com/pgvector/pgvector?tab=readme-ov-file#storing) it into Postgres. Please use other resources for help putting together a script. There's also a section on [performance tips](https://github.com/pgvector/pgvector?tab=readme-ov-file#performance).

**Comment by ankane** [comment]
Just fyi, Supabase recently released a tool for this: https://supabase.com/blog/vec2pg
