### ISSUE TITLE
Ability to skip/offset probes (in ivfflat)

### ISSUE THREAD

**Issue by demipixel** [pgvector/pgvector#597]
If I have `probes=10`, I find that's not enough results, and I want the next 5-10 probes, pgvector is forced to rank and serve me all results I already got from `probes=10`. It would be nice to have something that's the equivalent of OFFSET for probes to improve performance.

I'm guessing it would look something like `SET LOCAL ivfflat.offset_probes = 10;`

**Comment by ankane** [comment]
Hi @demipixel, thanks for the suggestion. However, I don't think it's common enough to add.
