### ISSUE TITLE
Question about generating embeddings

### ISSUE THREAD

**Issue by aminst** [pgvector/pgvector#599]
Hello,
Thanks for your awesome work on pgvector.
I have a question regarding generating vector embeddings. Does pgvector support connecting to an embedding model and generating the vectors based on a column's data?
Do you think it would help if pgvector could also handle this part for easier integration?

**Comment by ankane** [comment]
Hi @aminst, check out #313.

**Comment by aminst** [comment]
Got it. Thank you so much.
