### ISSUE TITLE
Create Extention doesnt work 

### ISSUE THREAD

**Issue by pasa13142** [pgvector/pgvector#60]
Hello! Thanks for this repo firstly, 

i would like to run 

`conn.execute('CREATE EXTENSION IF NOT EXISTS vector')`

but it returns:

`could not open extension control file "/usr/local/share/postgresql@14/extension/vector.control": No such file or directory`

I run pgvector as :

`docker run -e POSTGRES_PASSWORD=password ankane/pgvector`

Any help will be appreciated, thanks for in advance.

**Comment by ankane** [comment]
Hey @pasa13142, it looks like you're connected to a local Postgres instance instead of the Docker image.

**Comment by pasa13142** [comment]
Hi, I dont have local Postgres

**Comment by Hoss3770** [comment]
I have the same issue
An I am sure I am in the docker container
