### ISSUE TITLE
Confusing results returned when using ORDER BY and LIMIT

### ISSUE THREAD

**Issue by marusic1514** [pgvector/pgvector#600]
I am running a few different permutations of the following query:

```
SELECT  i.asset_id, embedding <=> (SELECT embedding FROM embedding.issue_test WHERE asset_id = '6642ce17982eeedf2dec7653') as score, cc.cluster_id
FROM embedding.issue_test i, embedding.center_test cc
WHERE cc.issue_id = i.asset_id
ORDER BY i.embedding <=> (SELECT embedding FROM embedding.issue_test WHERE asset_id = '6642ce17982eeedf2dec7653')
LIMIT 1;
```

And I notice the following results:
1. If my limit is 1, I get no results, i.e. the above query returns nothing when it should be returning
`asset_id = 6641620d982eeedf2db9ca08, score = 0.000004082918531711499, cluster_id = 6671e970a9f73021ec2999e4`

2. With limit over 1, I get the correct number of results and in the correct order
3. With no limit, I also get all the results in the correct order
4. With limit of 1, if I add asset_id into order by as in the following query, then I also get results:
```
SELECT  i.asset_id, embedding <=> (SELECT embedding FROM embedding.issue WHERE asset_id = '6642ce17982eeedf2dec7653') as score, cc.cluster_id
FROM embedding.issue i, embedding.cluster_center cc
WHERE cc.issue_id = i.asset_id
ORDER BY i.embedding <=> (SELECT embedding FROM embedding.issue WHERE asset_id = '6642ce17982eeedf2dec7653'), asset_id
LIMIT 1
```

Is there an explanation to this?

The tables were created as follows:

  ```
CREATE TABLE IF NOT EXISTS embedding.issue_test
   (
       asset_id   text     NOT NULL,
       md5        text,
       embedding  vector(1536),
       PRIMARY KEY (asset_id)
   );
CREATE INDEX IF NOT EXISTS vdx_issue_test ON embedding.issue_test USING hnsw (embedding vector_cosine_ops);
  ```
  
  ```
CREATE TABLE IF NOT EXISTS embedding.center_test(
    issue_id   char(24) NOT NULL,
    cluster_id char(24) NOT NULL,
    PRIMARY KEY (issue_id)
)
   ```
   
   Attached are the files with datain csv format (issue test one is compressed due to it being a large file -- it has ~7000 rows)
[issue_test.zip](https://github.com/user-attachments/files/15903468/issue_test.zip)
[cluster_center.csv](https://github.com/user-attachments/files/15903477/cluster_center.csv)
Pg vector version is 0.7.0 but this was also happening on version 0.5.1

**Comment by ankane** [comment]
Hi @marusic1514, it's likely due to [this](https://github.com/pgvector/pgvector?tab=readme-ov-file#why-are-there-less-results-for-a-query-after-adding-an-hnsw-index). You can use `EXPLAIN ANALYZE` to see how the execution plans differ.
