### ISSUE TITLE
pgvector远程连接报错超时

### ISSUE THREAD

**Issue by fvtfvy** [pgvector/pgvector#601]
psql  :  error  : connection to server at 'XXX.XXX.XXX.XXX', port 5432 failed : connection timed out 
Is the server running on that host and accepting TCP/IP connections

从dockerhub拉取的pgvector/pgvector:pg16。指令如下：docker pull pgvector/pgvector:pg16
容器启动指令：docker run --name pgvector --restart=always -e POSTGRES_USER=pgvector -e POSTGRES_PASSWORD=pgvector -v /srv/tlw/pgvectordata:/var/lib/postgresql/data -p 5432:5432 -d pgvector/pgvector:pg16

问题：在同台服务器上启动两个容器，可以在一个容器上通过psql连接到另一台容器。分别在两台服务器上启动容器，通过psql无法连接另一台容器中的pg数据库，报错如上所示。

尝试解决：根据网上资料：1.修改 pg_huba.cnf 添加 host all all 0.0.0.0/0 trust。无法解决。2.postgresql.cnf文件中listen_addresses=’*'
重启容器，仍无法解决？有大佬知道如何解决吗

**Comment by ankane** [comment]
Hi @fvtfvy, this doesn't seem specific to pgvector. Please use other resources for help.
