### ISSUE TITLE
In file included from src/bitutils.c:3:0: src/bitutils.h:8:2: 错误：#error "Requires PostgreSQL 12+"  #error "Requires PostgreSQL 12+"   ^ src/bitutils.c:5:30: 致命错误：port/pg_bitutils.h：没有那个文件或目录  #include "port/pg_bitutils.h"

### ISSUE THREAD

**Issue by Abecedariann** [pgvector/pgvector#608]
In file included from src/bitutils.c:3:0:
src/bitutils.h:8:2: 错误：#error "Requires PostgreSQL 12+"
 #error "Requires PostgreSQL 12+"
  ^
src/bitutils.c:5:30: 致命错误：port/pg_bitutils.h：没有那个文件或目录
 #include "port/pg_bitutils.h"

**Comment by Abecedariann** [comment]
Why is there always a problem?

**Comment by ankane** [comment]
It looks like you're trying to install it on an unsupported version of Postgres.
