### ISSUE TITLE
Ensure PostgreSQL Uses HNSW Index Before Falling Back to B-tree Index for Nearest Neighbor Search

### ISSUE THREAD

**Issue by gkourie** [pgvector/pgvector#609]
When performing a nearest neighbor search in PostgreSQL using the HNSW index provided by pgvector, PostgreSQL sometimes bypasses the HNSW index and directly uses the B-tree index on the `category_id `column. This is not the desired behavior, as we want to prioritize the HNSW index for the initial search and only fall back to the B-tree index if the HNSW search returns no results.

hnsw index:
`CREATE INDEX test_table_my_idx ON test_table using hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 256);`

B-tree index:
`CREATE INDEX ON test_table (category_id);`

test_table:
```
CREATE TABLE test_table (
             document_id INTEGER,
             category_id INTEGER,
             embedding vector,
)
```

Query: 
```
SELECT document_id, (embedding <=> '[-2.5680833, ,.....]') AS distance
FROM test_table 
WHERE category_id IN (1, 2)
ORDER BY distance
LIMIT 100
```
Dropping the hnsw index in a single transaction forces PostgreSQL to use the B-tree index, but how can we ensure that PostgreSQL uses the HNSW index first and only falls back to the B-tree index if no results are found?

thank you

**Comment by ankane** [comment]
Hi @gkourie, you can use a materialized CTE to prioritize the ANN search:

```sql
WITH ann AS MATERIALIZED (
    SELECT *, (embedding <=> '[1,2,3]') AS distance FROM test_table ORDER BY distance LIMIT 500
)
SELECT * FROM ann WHERE category_id IN (1, 2) ORDER BY distance LIMIT 100;
```

(and perform second query if no results are found)
