### ISSUE TITLE
Efficient exporting?

### ISSUE THREAD

**Issue by kennon** [pgvector/pgvector#610]
Does anyone have a suggestion for the most efficient way of **exporting** vectors out of a pgvector database? The method described in bulk_loading using COPY ... FROM STDIN works great for efficiently importing embeddings as binary, but the corresponding method (not documented in the examples here) of COPY TO STDOUT requires an ongoing connection to the database server and we were running into some complicates with data types etc.

The 'simplest' method of COPY TO using CSV does "work", but when your embedding length is relatively long (e.g. 768 for CLIP embeddings) and you have a large number of embeddings (10s of millions), the sheer size of floats represented as number characters instead of binary becomes overwhelming and super slow for both exporting and then reading back in.

We were able to use COPY TO ... FORMAT BINARY to store a binary dump file from postgres, but then could not find any way of actually reading this back into e.g. numpy arrays.

Any suggestions? Thanks!

**Comment by jkatz** [comment]
@kennon What is the end goal of what you're trying to do with the export? Is it to load it into another PostgreSQL database, or are you using it for some other operation?

**Comment by jkatz** [comment]
@kennon Thanks for the explanation, but this leads me to more questions 😄 

* Why are you building so many different indexes a day? Do you persist these indexes, or are they just used temporarily? If temporarily, how long do you use them for before deleting them?
  *  How many vectors / what size of vectors do you store in these indexes?
* Are you looking to build these indexes once and then continuously query them?

**Comment by ankane** [comment]
Hi @kennon, `COPY ... TO STDOUT WITH (FORMAT BINARY)` is the best way to do this. With Psycopg 3:

```python
cur = conn.cursor()
with cur.copy("COPY items (embedding) TO STDOUT WITH (FORMAT BINARY)") as copy:
    copy.set_types(['vector'])
    for row in copy.rows():
        print(row)
```

You can then serialize the Numpy arrays however you want.

> COPY TO STDOUT requires an ongoing connection to the database server

You can write them all to a file first before loading into another source.

**Comment by kennon** [comment]
@ankane Thank you! I think that was the missing piece that either I just missed in the documentation/examples or didn't get the specifics correctly. One question: does pgvector with "FORMAT BINARY" actually send an array of floats down the wire or does it send a 'binary representation' of a json string representing an array of numbers?

**Comment by kennon** [comment]
@jkatz 
>   * How many vectors / what size of vectors do you store in these indexes?

Dozens of millions of vectors, dimensions=768.

> * Why are you building so many different indexes a day? Do you persist these indexes, or are they just used temporarily? If temporarily, how long do you use them for before deleting them?

In order to query many different filter sets with HNSW we need something like the power set of possible filter values 😬. I know that there are various algorithmic approaches to filtered ANN searches, but none of them seem to work fast enough (<10ms query latency). We currently have to rebuild these every day since the filter parameters can and do change daily as well.

Our testing with pgvector searching in general was just too slow for us, even after taking the optimization steps we could find, searching still took hundreds of ms to multiple seconds, compared to our benchmark of raw faiss indices which usually have query latencies of 5-8ms. It wasn't clear how much of this was just PG overhead with serialization/deserialization/etc. Additionally, it was challenging to prevent query slowdowns while rebuilding the indices in the PG instance.

While it did seem possible to create multiple HNSW indices onto a single vector table, this seemed to get very complex in pgvector, requiring specific GIN indices, etc, and it seems as if the main use case in pgvector is for a single ANN index per embedding table.

> * Are you looking to build these indexes once and then continuously query them?

Yes we query these hundreds of times per second, although with built faiss indices it's trivial to horizontally scale this.

In any case, I am so impressed with pgvector what it does and I'm very grateful to the developers for working on this, it's a great product!

**Comment by ankane** [comment]
It sends an array of floats (4 bytes for each dimensions + an 8 byte header).
