### ISSUE TITLE
How to get the vector length from information schema

### ISSUE THREAD

**Issue by B4nan** [pgvector/pgvector#611]
I am trying to add support for the vector type for https://github.com/mikro-orm/mikro-orm, and to implement proper diffing support, I need to get the length option for the given column from the information schema. 

Currently, I can't find any information about the length in there, e.g. when the column type is defined as `vector(1024)`, all I can see is `udt_name: 'vector'` and `data_type: 'USER-DEFINED'`.

This is the SQL I was using so far:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlSchemaHelper.ts#L134

**Comment by jkatz** [comment]
@B4nan This will be in the [`pg_attribute`](https://www.postgresql.org/docs/current/catalog-pg-attribute.html) table, unto `atttypmod`.

**Comment by B4nan** [comment]
Thanks!
