### ISSUE TITLE
how to build a arm docker images

### ISSUE THREAD

**Issue by FunkyYang** [pgvector/pgvector#615]
I need  install pgvector on arm system 。which docker image can be used？

**Comment by ankane** [comment]
Hi @FunkyYang, check out the readme for how to pull (for `arm64`) or build the Docker image.

**Comment by FunkyYang** [comment]
I did't find

**Comment by FunkyYang** [comment]
can you give me a idea?

**Comment by jkatz** [comment]
You can find the Docker tags available here: https://hub.docker.com/r/pgvector/pgvector/tags
