### ISSUE TITLE
docker 安装pvector 提示错误

### ISSUE THREAD

**Issue by ssy040504** [pgvector/pgvector#618]
docker 安装pvector 提示错误：
 => ERROR [3/3] RUN apt-get update &&   apt-mark hold locales &&   apt-get install -y --no-install-recommends bui  3.0s
------
 > [3/3] RUN apt-get update &&          apt-mark hold locales &&                apt-get install -y --no-install-recommends build-essential postgresql-server-dev-16 &&          cd /tmp/pgvector &&             make clean &&           make OPTFLAGS="" &&             make install &&                 mkdir /usr/share/doc/pgvector &&                cp LICENSE README.md /usr/share/doc/pgvector &&                 rm -r /tmp/pgvector &&          apt-get remove -y build-essential postgresql-server-dev-16 &&           apt-get autoremove -y &&                apt-mark unhold locales &&              rm -rf /var/lib/apt/lists/*:
0.724 Err:1 http://deb.debian.org/debian bookworm InRelease
0.724   400  Bad Request [IP: 151.101.110.132 80]
0.945 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
0.945   400  Bad Request [IP: 151.101.110.132 80]
1.182 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
1.182   400  Bad Request [IP: 151.101.110.132 80]
2.949 Err:4 http://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease
2.949   400  Bad Request [IP: 72.32.157.246 80]
2.952 Reading package lists...
2.960 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
2.960 E: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  400  Bad Request [IP: 151.101.110.132 80]
2.960 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
2.960 E: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  400  Bad Request [IP: 151.101.110.132 80]
2.960 E: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  400  Bad Request [IP: 151.101.110.132 80]
2.960 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
2.960 E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/bookworm-pgdg/InRelease  400  Bad Request [IP: 72.32.157.246 80]
2.960 E: The repository 'http://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease' is not signed.
------
Dockerfile:7
--------------------
   6 |
   7 | >>> RUN apt-get update && \
   8 | >>>              apt-mark hold locales && \
   9 | >>>              apt-get install -y --no-install-recommends build-essential postgresql-server-dev-$PG_MAJOR && \
  10 | >>>              cd /tmp/pgvector && \
  11 | >>>              make clean && \
  12 | >>>              make OPTFLAGS="" && \
  13 | >>>              make install && \
  14 | >>>              mkdir /usr/share/doc/pgvector && \
  15 | >>>              cp LICENSE README.md /usr/share/doc/pgvector && \
  16 | >>>              rm -r /tmp/pgvector && \
  17 | >>>              apt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR && \
  18 | >>>              apt-get autoremove -y && \
  19 | >>>              apt-mark unhold locales && \
  20 | >>>              rm -rf /var/lib/apt/lists/*
  21 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && \t\tapt-mark hold locales && \t\tapt-get install -y --no-install-recommends build-essential postgresql-server-dev-$PG_MAJOR && \t\tcd /tmp/pgvector && \t\tmake clean && \t\tmake OPTFLAGS=\"\" && \t\tmake install && \t\tmkdir /usr/share/doc/pgvector && \t\tcp LICENSE README.md /usr/share/doc/pgvector && \t\trm -r /tmp/pgvector && \t\tapt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR && \t\tapt-get autoremove -y && \t\tapt-mark unhold locales && \t\trm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by ankane** [comment]
Hi @ssy040504, this looks like a network issue (not an issue with pgvector).
