### ISSUE TITLE
Multi-vector search

### ISSUE THREAD

**Issue by branaway** [pgvector/pgvector#623]
Hi, I'm wondering if pgVector support complex multi-vector search similar to what MS does in https://github.com/microsoft/MSVBASE?

Our app is one of those that requires search across multiple vectors and scalers.  We're researching new options in addition to Milvus hybrid search. Vbase from MS promises superior performance but it does not look mature enough.

**Comment by ankane** [comment]
Hi @branaway, you can order by multiple vectors with:

```sql
... ORDER BY (embedding <-> '[1,2,3]') + (other_embedding <-> '[4,5,6]') ...
```

However, it won't be able to use an index.

**Comment by branaway** [comment]
> Hi @branaway, you can order by multiple vectors with:
> 
> ```sql
> ... ORDER BY (embedding <-> '[1,2,3]') + (other_embedding <-> '[4,5,6]') ...
> ```
> 
> However, it won't be able to use an index.

Thank for the reply @ankane . What the consequence then for not using an index? Does it fall back to brute force?

**Comment by ankane** [comment]
Yes, it'll perform exact nearest neighbor search.

**Comment by branaway** [comment]
> Yes, it'll perform exact nearest neighbor search.

and performavery badly?

**Comment by jkatz** [comment]
@branaway It's difficult to discuss this without understanding more about what you're trying to search for. What is the outcome of your search? Do you need to search over multiple embeddings in the same query? Are you applying different filters to the query? What would an example SQL statement look like?

It's hard to discuss performance without having a better understanding of what you're trying to accomplish.

**Comment by branaway** [comment]
> @branaway It's difficult to discuss this without understanding more about what you're trying to search for. What is the outcome of your search? Do you need to search over multiple embeddings in the same query? Are you applying different filters to the query? What would an example SQL statement look like?
> 
> It's hard to discuss performance without having a better understanding of what you're trying to accomplish.

Yes, I'd like to search on multiple vectors in one query. e.g.:

find me the top 100 jobs that 1) match my skills 2) close to my salary expectation 3) company has good reputation, 4) close to where I live, etc... and the importance in that order (using a weighting notation)

It seems to me the MS VBase has developed an extension for pg to attack difficult queries like this. I'm wondering if this objective is in the near future scope of pgVector, or has there already a feature for that.

**Comment by branaway** [comment]
One might say we can use simple scaler filter for salary, locations etc, but I'd like to vectorize everything ( I would like to treat simple scaler as a sparse vector ) and use a uniformed weighted system for AI based apps. That's the idea.

**Comment by branaway** [comment]
Another use case could as be to find a good date: the look, education, age, ethnicity, character. etc. all can be vectors.

**Comment by ernests** [comment]
@ankane I'm actually also interested in this question. Ability to do sort of matching across multiple vectors. In a way it is a weighted similarity search where one dimension has closer similarity than other. One items having multiple dimensions (e.g. 5) and weighted result based on individual dimension similarity.

**Comment by jkatz** [comment]
You can also use a multiple-search / reranking technique (which can leverage the index) - an example of this is with [hybrid search](https://jkatz05.com/post/postgres/hybrid-search-postgres-pgvector/), but you can apply a similar technique if the goal is to weight independent scores.

**Comment by branaway** [comment]
> You can also use a multiple-search / reranking technique (which can leverage the index) - an example of this is with [hybrid search](https://jkatz05.com/post/postgres/hybrid-search-postgres-pgvector/), but you can apply a similar technique if the goal is to weight independent scores.
Can the technique be used on merging searches over more than one vector fields?
