### ISSUE TITLE
Out of sync documentation on vector dimensions?

### ISSUE THREAD

**Issue by ifsheldon** [pgvector/pgvector#624]
Hi! I'm new to pgvector. When I read the README, I found these two lines, but which one is the currently supported limit of vector dimension? Perhaps the documentation is out of sync after some updates?

https://github.com/pgvector/pgvector/blob/8772c8de68cf11fba59b381db8f262951222358f/README.md?plain=1#L863

https://github.com/pgvector/pgvector/blob/8772c8de68cf11fba59b381db8f262951222358f/README.md?plain=1#L254

**Comment by ankane** [comment]
Hi @ifsheldon, the `vector` type supports up to 16,000 dimensions, and vectors with up to 2,000 dimensions can be indexed.
