### ISSUE TITLE
XX000 Error when adding more than a thousand records to an `sparsevec` HNSW index

### ISSUE THREAD

**Issue by Tibiritabara** [pgvector/pgvector#625]
We are currently running a Postgres 14 database with PGVector 0.7.0 enabled on top. 

We created our own `vector_store` tables that contain the embedded representation of our database objects. 
These tables have the next rough structure:

```sql
CREATE TABLE IF NOT EXISTS "table_vector_store" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "text" character varying COLLATE pg_catalog."default" NOT NULL,
  "metadata" jsonb,
  "embedding" vector(1536),
  "sparse" sparsevec(30522),
  "created_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
```

The `embedding` column uses a dense vector, and the `sparse` column a sparse vector using the `SPLADE++` strategy .

Despite having a size of 30522 in our `sparsevec` column, the number of objects on the sparse representation is never above 200 items.

These tables have two indexes:

```sql
CREATE INDEX IF NOT EXISTS table_vector_store_idx ON table_vector_store USING hnsw (embedding vector_l2_ops);

CREATE INDEX IF NOT EXISTS table_vector_store_sparse_idx ON table_vector_store USING hnsw ("sparse" sparsevec_l2_ops);
```

We have a set of e2e tests running regularly that create a bunch of new entries in these tables. These e2e records could be close to 2k records created on an hourly basis.

Now the error: some of this records are throwing the next exception

```
message: failed to add index item to "table_vector_store_sparse_idx"
status_code: XX000
```

After some retries, the entry is inserted into the database, but not without failing first a given amount of times. We check the CPU performance, and it peaks at 30%, much higher than before adding the sparse index, but still below a value that could alert us. Memory on our Postgres remains stable, with more than 50% free memory.

We decided to remove the `sparse` index to see if we could pinpoint the issue on the index, and after removal, everything has been working as expected.

What could be the source of the issue? is calculating the index expensive? Shall we increase resources? and why is the index creation process not reflected on memory nor CPU usage?

Thank you so much for your support.

**Comment by Tibiritabara** [comment]
Thank you so much for your response. The database where the errors ocurred is running postgres 14.12, 4 GB of RAM, 2 vCPUs, and 20 GB of Storage. A db.t3.medium on AWS RDS.

Regarding the language, my code is in Typescript, but the DB is the one throwing the exception.

I wonder if for the use case, is important to have both columns, `embedding`, and `sparse`, as both hit different indexes.

```
import psycopg
from pgvector.psycopg import register_vector, SparseVector
from random import random, randrange
from langchain_community.embeddings import FakeEmbeddings # pip install langchain-community

conn = psycopg.connect(dbname="repro", autocommit=True)
conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
register_vector(conn)

conn.execute('DROP TABLE IF EXISTS items')
conn.execute('CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(1536), sparse sparsevec(30522))')
conn.execute("CREATE INDEX ON items USING hnsw (vector vector_l2_ops)")
conn.execute("CREATE INDEX ON items USING hnsw (sparse sparsevec_l2_ops)")

for _ in range(10000):
    d = {}
    for _ in range(randrange(200)):
        d[randrange(30522)] = random()
    embedding = FakeEmbeddings(size=1536)
    sparse = SparseVector(d, 30522)
    conn.execute("INSERT INTO items (embedding, sparse) VALUES (%s)", (embedding, sparse))
```

**Comment by ankane** [comment]
Hi @Tibiritabara, unfortunately, the script doesn't run (or reproduce it when the errors are fixed). Happy to look into this more if someone is able to create a script to reproduce.

**Comment by ankane** [comment]
Found the issue, and am working on a fix.

**Comment by ankane** [comment]
Fixed in the commit above. Thanks for reporting.

**Comment by Tibiritabara** [comment]
Thank you so much!!
