### ISSUE TITLE
Unable to install pgvector extension for Postgres 16 in Ubuntu 22.04 

### ISSUE THREAD

**Issue by gpriyank1** [pgvector/pgvector#626]
postgresql-16-pgvector is already the newest version (0.7.2-1.pgdg22.04+1).

I get this error while installing the pgvector extension ...

psql -U devuser -h localhost -d pgvector -c "CREATE EXTENSION pgvector;"
Password for user devuser: 
ERROR:  extension "pgvector" has no installation script nor update path for version "0.7.2"

**Comment by jkatz** [comment]
@gpriyank1 Try:

```sql
CREATE EXTENSION vector;
```

**Comment by gpriyank1** [comment]
Thank you @jkatz! It worked!
