### ISSUE TITLE
Squared L2 distance to avoid the square root?

### ISSUE THREAD

**Issue by jonny-d** [pgvector/pgvector#627]
Hello, 

Is it possible to query and get the nearest neighbours with squared L2 distance to avoid the square root?

**Comment by jonny-d** [comment]
This is what faiss does https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances#metric_l2

**Comment by jkatz** [comment]
@jonny-d The `vector_l2_squared_distance` does this. It's also used automatically when building and querying the indexes.

**Comment by jonny-d** [comment]
Ah great, that works. When you say it's used automatically I'm guessing you mean for HNSW of IVFFlat indexes? I wasn't using these. Also I noticed that `vector_l2_squared_distance` does not appear in the [reference](https://github.com/pgvector/pgvector?tab=readme-ov-file#reference). 

Thanks for your help!

**Comment by ankane** [comment]
fwiw, the function is considered private, which is why it's not in the reference (the performance benefit is likely insignificant).
