### ISSUE TITLE
FYI: It was (maybe) necessary to fully remove my previous docker installs to utilize new column types (halfvec)

### ISSUE THREAD

**Issue by pmalacho-mit** [pgvector/pgvector#628]
Hello!

I'm not a very experienced docker developer, so perhaps this is expected behavior. 

But I was aiming to use the new 'halfvec' type (awesome work!) and after pulling the latest version of the `pgvector/pgvector:pg16` I expected to be able to use it after restarting the container. 

But I kept getting the error:

```
ERROR:  type "halfvec" does not exist at character 92
```

I even opted to use different images (e.g. `pgvector/pgvector:0.7.2-pg16`), which also did not work with the same error. Notably, when pulling those manually or seeing `docker compose` pull them, only the last two (?) 'layers' were being updated. 

Only after fully removing the previous images (and thus all pre-built layers, I assume) could I start to utilizing the new 'halfvec' type. 

I found that a little unexpected, so wanted to raise it. Please enlighten me though if this should be expected.  

Thanks for all you're doing with this project -- such a huge help / asset!

**Comment by pmalacho-mit** [comment]
Actually -- this seems perhaps more related to having a persistent volume associated with the db. Does that sound right? That persisting `/var/lib/postgresql/data` the folder as volume between image upgrades would cause the type to not be found? 

That could make sense to me, but was it very weird is the following happens:
1. I start a fresh instance of `pgvector/pgvector:0.7.2-pg16` (meaning I fully removed it and allow it to re-pull) with NO persistent volume -- type loads fine
2. I restart the instance, but now WITH the persistent volume -- type not found error
3. I restart the instance, but NO volume anymore -- type not found error

Any ideas? I'm both not very experienced with docker nor postgres, so I have no clue what's going on,,,

**Comment by pmalacho-mit** [comment]
Ah (sorry to be having a conversation with myself) -- I just did a dump of my database and see there is a line:

```
COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';
```

I assume that's the culprit. 

With that in mind, what is the best strategy for 'upgrading' a database with the newest versions of pgvector? Is there some procedure to remove and then re-add the vector extension?

**Comment by pmalacho-mit** [comment]
Ope, nope! I don't think that's it either, as that line looks the same from a database where the type is working. I'll stop replying and wait for someone who knows more to chime in, lol

**Comment by ankane** [comment]
Hi @pmalacho-mit, see the [upgrading docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#upgrading).

**Comment by pmalacho-mit** [comment]
ah, great, thank you @ankane ! sorry I missed that in that in the readme.
