### ISSUE TITLE
creating a new hnsw index over 30 mln entries

### ISSUE THREAD

**Issue by legaltextai** [pgvector/pgvector#629]
Somehow, still not sure how, I 've lost my previous hnsw index over 30 mln row table. 1024 dimensions. 
vector version 7
I am trying to reindex but it's been going on for a couple of days now. 
My server is 12 core CPU, 128 RAM, I 've set: 
SET work_mem = '512MB';

SET effective_cache_size = '96GB';

SET max_parallel_workers_per_gather = 12;

SET checkpoint_timeout = '1h';

SET max_wal_size = '8GB';

SET effective_io_concurrency = 200;

Is there anything else I could do to speed up the creation of the new index? 
As an alternative, what do you think if I create a new table, copy just a few rows from the previous table, create hnsw on those few rows, and then start inserting from the old table and let hnsw pick up new rows automatically? 

Thank you

**Comment by ankane** [comment]
Hi @legaltextai, see the docs on [index build time](https://github.com/pgvector/pgvector?tab=readme-ov-file#index-build-time).

**Comment by legaltextai** [comment]
I tried all of that. but creating hnsw over 30 mln 1024 dimension vectors is just not feasible, it is slowing down as it progresses. I am looking for alternative approaches.
