### ISSUE TITLE
Inconsistent filter behaviour for different limits.

### ISSUE THREAD

**Issue by Sankar-A** [pgvector/pgvector#630]
Our project has a table with embeddings for semantic search. We have added a HNSW index (m=16, ef_construction 64). Our embeddings size is 1536 and we have ~1m embeddings.
We are facing issue with the search query returning inconsistent results based on the limit. We show the semantic results on a paginated search. We have a select query with limit of 10 and offset which will be the page number. Our count query will be the standard search query with limit of 200 as we show a max of 200 results for the users to scroll.

For example,

Select query:
SELECT id, text
FROM semantic_vector
WHERE <filter conditions>
ORDER BY embedding <=> $2
LIMIT 10 offset 0;

Count query:
select count(*) from (
  SELECT id, text
  FROM semantic_vector
  WHERE <filter conditions>
  ORDER BY embedding <=> $2
  LIMIT 200
)

For certain filters, the select query returns between 1-10 records for offset 0. For offset 10-40, we get no results. But after increasing the offset (>40-50), we start getting more results. The count query returns the correct count till which the offset returns results. The filter condition returns ~1000 records without semantic search (same select query without the order by clause).

By using explain, we noted that when less results are returned, the query plan is using the index. For higher offset, where the query returns proper results, the index is not being used.

I understand that there is a similar issue opened in the repo already(https://github.com/pgvector/pgvector/issues/259). 
But this ticket does not explain this specific scenario of records not being returned for specific limits. There might be an issue with when the index is applied vs not applied.

**Comment by ankane** [comment]
Hi @Sankar-A, improving when indexes are and aren't used for queries with filtering is being tracked in #263.
