### ISSUE TITLE
ERROR:  extension "vector" has no installation script nor update path for version "0.7.3"

### ISSUE THREAD

**Issue by pradeepdev-1995** [pgvector/pgvector#631]
I installed postgressdb in my ubuntu machine like this
```
sudo apt install postgresql
```
version
```
PostgreSQL 12.19 (Ubuntu 12.19-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0, 64-bit
```
Then started it
```
sudo systemctl restart postgresql.service
```
Installed postgress header
```
sudo apt install postgresql-server-dev-12
```
Installed pgvector
```
cd /tmp
git clone --branch v0.7.3 https://github.com/pgvector/pgvector.git
cd pgvector
sudo make install
```
And now when i try to install vector extension from psql terminal, 
```
CREATE EXTENSION IF NOT EXISTS vector;
```
Its getting the below error
```
ERROR:  extension "vector" has no installation script nor update path for version "0.7.3"
```

**Comment by ankane** [comment]
Hi @pradeepdev-1995, I'm not able to reproduce the issue. Can you delete `/tmp/pgvector`, re-run the installation instructions, and paste the full output?

**Comment by Backsylisk** [comment]
You're missing the `make` command.

```
cd /tmp
git clone --branch v0.7.3 https://github.com/pgvector/pgvector.git
cd pgvector
make
sudo make install
```

I had the same error, adding `make` solved it.

**Comment by ankane** [comment]
Thanks @Backsylisk! Pushed a fix in the commit above so this won't happen with future versions.

**Comment by op2adi** [comment]
Still gettting THis error
