### ISSUE TITLE
some questions about 'heaptids[HNSW_HEAPTIDS]' in HnswElementData struct

### ISSUE THREAD

**Issue by ViolaElrics** [pgvector/pgvector#632]
Hi :)
when I learn code about storage in pgvector, I feel puzzled about **ItemPointerData heaptids[HNSW_HEAPTIDS];** in structure **HnswElementData**
what is it used for? I guess it maybe used for HOT mechanism, and I want to construct test cases that allows it to change  , such as **heaptids[i++]=heap_tid**, and I notice that it only ocuurs in funciton HnswAddHeapTid, HnswAddHeapTid is called by **AddDuplicateInMemory**. I wonder what means **Duplicate**? Index item duplicate? 
how can I construct test cases which can make heaptids[i++]?
thanks!  :)

**Comment by ankane** [comment]
Hi @ViolaElrics, pgvector attempts to store vectors that are exactly the same in the same HNSW graph element. This is useful for non-HOT updates, as well as if the table has duplicates. You can run the code path with:

```sql
CREATE TABLE items (embedding vector(3));
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[1,2,3]');
CREATE INDEX ON items USING hnsw (embedding vector_l2_ops);
```
