### ISSUE TITLE
how to delete or update a vector node?

### ISSUE THREAD

**Issue by ViolaElrics** [pgvector/pgvector#634]
When I want to update or delete a node in the hnsw index, the index actually hides the node, and repair graph in vacuum. 
1. I wonder before vacuum, how to hide the node? It seems that each element has a deteled attribute, but I cannot find when to change "etup->delete = 1" except in the "MarkDeleted" function, which only works in vacuum process actually. 
2. I am also curious about how to skip the hide node when searching neighbor nodes? 
I would be greatly appreciated your help in this matter. :)

**Comment by ankane** [comment]
Hi @ViolaElrics, dead tuples aren't removed from the index until a vacuum. Check out #244 for more info.
