### ISSUE TITLE
Question about using existing PostgreSQL database

### ISSUE THREAD

**Issue by xueshanf** [pgvector/pgvector#638]
I plan to run this in Kuernetes cluster and using an existing  PostgreSQL. I looked through documentation but could not  find a way to configure connection string with env.  which would allow me to put the external server's IP address. 

Is it supported or we have to use the db comes with the image?

Thanks!

**Comment by ankane** [comment]
Hi @xueshanf, you can add the extension to an existing database. This isn't really specific to pgvector (it'll be the same as other extensions), so please use other resources for help.
