### ISSUE TITLE
Minimum value for similarity ?

### ISSUE THREAD

**Issue by IqbalLx** [pgvector/pgvector#64]
Hi, I would like to ask if it is possible for us to filter the minimum similarity value of the embeddings used. I just used pgvector in my project https://newsgpt.mbts.dev/ and found that some of the recommended news doesn't discuss similar things. So I wonder maybe it's because of low similarity score, but not zero so it's still returned. Is there a way to set this minimum similarity score from the query?

**Comment by ankane** [comment]
Hey @IqbalLx, check out #16.

**Comment by IqbalLx** [comment]
ah i see, great, thankyou. Maybe we should add it on the readme ?

**Comment by ankane** [comment]
Added in the commit above.
