### ISSUE TITLE
Late interaction embedding support

### ISSUE THREAD

**Issue by az-arteria** [pgvector/pgvector#640]
Hi,

I wanted to ask a question: does pgvector currently support working with late interaction text embeddings, like the ones that come from a ColBERT model for example? This is an example of a vector that I would be referring to:
``` 
[
    [-0.013,  0.020, -0.007, -0.111],
    [-0.030, -0.055,  0.001,  0.072],
    [-0.041,  0.014, -0.032, -0.062],
    ....
]
```

Currently when inserting such a vector I seem to get `ValueError: expected ndim to be 1`, with this usage:
```python
conn.execute("INSERT INTO documents (content, embedding) VALUES (%s, %s)", (content, embedding))
# content = text, embedding = vector
```

**Comment by jkatz** [comment]
@az-arteria You can have an array of vectors (similar to a PostgreSQL [multi-dimensional array[(https://www.postgresql.org/docs/current/arrays.html)) e.g.

```sql
SELECT ARRAY[
[
    '[-0.013,  0.020, -0.007, -0.111]'::vector,
    '[-0.030, -0.055,  0.001,  0.072]'::vector,
    '[-0.041,  0.014, -0.032, -0.062]'::vector
]
```

where `embedding` would be a `vector[]` type.

but I'm curious how you would intend to use / search over this data.

**Comment by az-arteria** [comment]
Hi, thanks for the reply

So if I'm understanding correctly I should be able to do something like this?
```python
conn.execute("CREATE TABLE documents (id bigserial PRIMARY KEY, content text, embedding vector[])")
conn.execute("INSERT INTO documents (content, embedding) VALUES (%s, %s)", ("example content", [[0.08865993, 0.16410036], [0.0221169, 0.1254668]]))
```
I'm still getting `ValueError: expected ndim to be 1` from this block of code, so I'm assuming syntax-wise maybe I'm doing something wrong here.

As for how to use / search, I see that some vector databases like [here](https://qdrant.tech/documentation/concepts/vectors/#multivectors) support multiple vectors for a single text, and have a function for computing similarity score for two separate lists of vectors (shown in url). This is particularly useful for models like colbert, which output multiple vectors for one piece of text.

Do you know if this sort of functionality is supported by PGVector as well?

**Comment by ankane** [comment]
Hi @az-arteria, with Psycopg, you'll need to pass a list of NumPy arrays for the `vector[]` type.

```python
embeddings = [np.array([1, 2, 3]), np.array([4, 5, 6])]
conn.execute('INSERT INTO documents (embedding) VALUES (%s)', (embeddings,))
```

For searching, you could write a SQL function to compute MaxSim.

**Comment by ankane** [comment]
Added a [full example](https://github.com/pgvector/pgvector-python/blob/master/examples/colbert_exact.py) for exact search.

For approximate search, you could store each vector in a separate row and use the approach described in Section 3.6 of the [ColBERT paper](https://arxiv.org/abs/2004.12832).

**Comment by olad32** [comment]
@az-arteria have you any findings or limitation to share about this ? did you try exact or approximate search ? does it scale well with pgvector ?

**Comment by CarterBurns33** [comment]
@ankane Is this something that can work with binary quantization as well? multi-dimensional embeddings do not scale well on a large enough dataset due to their sheer size - for example each ColQwen embedding is [755,128]. I haven't been able to insert data into a BIT[] type column, although that may be user error on my part.

**Comment by ankane** [comment]
@CarterBurns33 Not sure what error you're seeing, but it should work for `bit`.

```sql
CREATE TABLE items (embeddings bit(3)[]);
INSERT INTO items (embeddings) VALUES ('{"000", "111"}');
```

**Comment by CarterBurns33** [comment]
Thanks for the reply! Yes, it was just some formatting error since it's slightly different than the vector syntax. Got it to work with a slight tweak to the max_sim function as well.

**Comment by blobgetblob** [comment]
@CarterBurns33 hey can you share your snippet working on colipali with pgvector, thx

**Comment by ankane** [comment]
Added an example of ColPali (ColQwen2) with binary quantization [here](https://github.com/pgvector/pgvector-python/blob/master/examples/colpali/exact.py).

**Comment by matheusft** [comment]
Hello,

I'm struggling to add my Multi-Vector (ColBERT) embedding into my Postgres DB.
Below is a demo version of the python code I'm using.

```python
from dotenv import load_dotenv
import os
import psycopg
import numpy as np

load_dotenv()

# Connect to your postgres DB
conn = psycopg.connect(
    "dbname={} user={} password={} host={}".format(
        os.getenv("DB"),
        os.getenv("USER"),
        os.getenv("PASSWORD"),
        os.getenv("HOST"),
    )
)

# Open a cursor to perform database operations
cur = conn.cursor()

embedding = [np.random.rand(3, 128)]

# Insert the formatted string into the database
conn.execute('INSERT INTO SCHEMA.TABLE (content, embeddings) VALUES (%s, %s)',
             ("content", embedding))
```

This is what my table looks like


```bash
MY_DB=# \d SCHEMA.TABLE;
                               Table "SCHEMA.TABLE"
   Column   |     Type      | Collation | Nullable |                Default                
------------+---------------+-----------+----------+---------------------------------------
 id         | bigint        |           | not null | nextval('documents_id_seq'::regclass)
 content    | text          |           |          | 
 embeddings | vector(128)[] |           |          | 
Indexes:
    "documents_pkey" PRIMARY KEY, btree (id)
```

This is what the python code above gives me.
⚠️⚠️⚠️
`psycopg.ProgrammingError: cannot adapt type 'ndarray' using placeholder '%s' (format: AUTO)`
⚠️⚠️⚠️

Any help?

**Comment by jkatz** [comment]
You need to use the `pgvector` python adapter, which will convert the `ndarray`:

https://github.com/pgvector/pgvector-python

Instructions for [psycopg3 are here](https://github.com/pgvector/pgvector-python?tab=readme-ov-file#psycopg-3).

**Comment by matheusft** [comment]
The problem has been now solved 🎉.

I was having issues with to main things:

1. I was not registering vector types with the database connection `register_vector(conn)` 
2. The multi-vector embedding format accepted by `psycopg` is a list of one-dimensional vectors `[List[rows*np.array(columns)]`, not a list of a single multi-dimensional vector `[List[np.array(rows,columns)]` as I was doing.

The code below works fine.

```python
from dotenv import load_dotenv
import os
import psycopg
from pgvector.psycopg import register_vector
import numpy as np


load_dotenv()

# Connect to your postgres DB
conn = psycopg.connect(
    "dbname={} user={} password={} host={}".format(
        os.getenv("DB"),
        os.getenv("USER"),
        os.getenv("PASSWORD"),
        os.getenv("HOST"),
    )
)

# Register vector types with the database connection
register_vector(conn)

# Create a multi-dimensional vector (list of one-dimensional vectors)
input_multi_vector = [np.random.rand(128) for _ in range(10)]

with conn.cursor() as cur:
    cur.execute("""
        INSERT INTO SCHEMA.TABLE (content, embeddings)
        VALUES (%s, %s);
    """, ("content", input_multi_vector,))


conn.commit()
conn.close()
```

**Comment by winstxnhdw** [comment]
Can we get index support for Late Interaction Embeddings too?

**Comment by ankane** [comment]
There's an example of approximate search [here](https://github.com/pgvector/pgvector-python/blob/master/examples/colbert/approximate.py) (using the approach described in Section 3.6 of the ColBERT paper). The example uses the `vector` type, but the approach can be applied to `bit` as well.

**Comment by ankane** [comment]
The examples vary to show how to implement max sim with either type, but you can use either type for either model. `bit` will use less space but have lower recall than `vector` or `halfvec`. I'd recommend trying and measuring recall for `bit` and `halfvec`, as well as binary quantization with reranking, to see which is best for your application.
