### ISSUE TITLE
Does IVFFlat index changes when deleting some vectors

### ISSUE THREAD

**Issue by Dawn-seagull** [pgvector/pgvector#644]
I'm testing pgvector with annbenchmark. I create an IVFFlat index with learning set. And for the base vector data, I should first delete the original data and then insert the base data. So i'm wondering if IVFFlat index changes when deleting vectors.

**Comment by ankane** [comment]
Hi @Dawn-seagull, the data won't be visible to future transactions, and will be removed when `VACUUM` is run (see resources on Postgres' MVCC for more info). The list centers won't change unless `REINDEX` is run.
