### ISSUE TITLE
What is the best way to find nearest-neighbor for N vectors (batch query)?

### ISSUE THREAD

**Issue by matan-airis** [pgvector/pgvector#645]
I have a situation where I have a bunch of embeddings I want to lookup. So far, the fastest way I managed to do that is by making a database query per vector, which is reasonably fast (looking 100 vectors up in a table with 1M rows takes ~30 seconds if I run the queries serially and even faster if I parallelize the queries).

Trying to do this with one query takes several times longer, about 3 minutes. The query I have so far looks something like this, where `t_temp` is a temp table with 100 vectors and `t` is a table with 1M vectors. For this application I need exact nearest-neighbor, so I'm not using an index.

```sql
SELECT t_results.* FROM (
  SELECT embedding
  FROM t_temp
) t_v
JOIN LATERAL (
  SELECT (t_v.embedding <#> embedding) * -1 AS similarity
  FROM t
  ORDER BY similarity DESC
  LIMIT 1
) t_results ON true
```

Is there a better way to do this query, or should I keep using multiple queries?

**Comment by ankane** [comment]
Hi @matan-airis, I suspect parallelizing the queries will be the fastest approach in terms of wall time. You could try minimizing networks requests by combining multiple queries with `UNION ALL`, but it probably won't make much of a difference for exact search over 1M vectors.

**Comment by ankane** [comment]
Also, if you're trying to find near duplicates over most / all vectors, you may want to use an in-memory library with optimized matrix operations. https://github.com/pgvector/pgvector-python/issues/85

**Comment by CorentinvdBdO** [comment]
The lack of batch search (100/1000 query vectors) is the sole reason we moved back to Qdrant in my company. Performances are horrendeous.
I prefer managing pgvector over two different databases but we have to go back.
