### ISSUE TITLE
Changing User and Group ID from 999 to Custom ID.

### ISSUE THREAD

**Issue by syed-al** [pgvector/pgvector#646]
I am facing the difficulty of the data folder which is mapped to host system from the pgvector docker, changing the owner. The pgvector docker creates a new user `postgres` with uid and gid `999`. The value of 999 on the host system is taken by something else, hence on the host the owner of the folder is changing. 

To avoid this I would want to provide my local host user as a parameter to the pgvector docker such that it used that uid and gid instead of the `999` present in the dockerfile.

Also, it would be helpful if you can update the dockerfile in the git repo to the latest docker file being used in the docker hub.

**Comment by ankane** [comment]
Hi @syed-al, these values are set in the [Dockerfile](https://github.com/docker-library/postgres/blob/3a94d965ecbe08f4b1b255d3ed9ccae671a7a984/16/bookworm/Dockerfile#L10-L13) for the `postgres` image, so any changes would need to happen there.
