### ISSUE TITLE
sqladmin - pgvector field converter

### ISSUE THREAD

**Issue by spsoni** [pgvector/pgvector#649]
I am using https://pypi.org/project/sqladmin/ to generate the admin web portal.

It is failing for table container VECTOR field.

"sqladmin/forms.py", line 274, in get_converter
    raise NoConverterFound(  # pragma: nocover
sqladmin.exceptions.NoConverterFound: Could not find field converter for column embedding (<class 'pgvector.sqlalchemy.vector.VECTOR'>).

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.8.2"
sqlmodel = "^0.0.21"
pgvector = "^0.3.2"
psycopg2-binary = "^2.9.9"
sqladmin = {extras = ["full"], version = "^0.18.0"}
uvicorn = "^0.30.6"

**Comment by jkatz** [comment]
@spsoni This would be on sqladmin to implement. The database/application converters for Python are available here: https://github.com/pgvector/pgvector-python - any additional work will be on the sqladmin side, not pgvector.

**Comment by ankane** [comment]
Hi @spsoni, it looks like you could use the `form_converter` option in the `ModelView`.

https://aminalaee.dev/sqladmin/configurations/#form-options
