### ISSUE TITLE
Table Size Estimate Doesn't Match Actual Size

### ISSUE THREAD

**Issue by wahajali** [pgvector/pgvector#653]
I have a table with a single vector(1536) column with 500K rows. According to the size estimation provided in the [documentation](https://github.com/pgvector/pgvector?tab=readme-ov-file#vector-type), the size of the table should add up to: 
((4 * 1536 + 8) * 500000) = 3076000000 bytes or ~2.86 GB. However, when I check the table size after insertion using the following command, I get 3978 MB, which is significantly more than the estimation:

```
ann=> SELECT pg_size_pretty(pg_table_size('public.dupe_pg_c')) as table_size;
 table_size 
------------
 3974 MB
(1 row)
```

Following is the table information for reference:
```
ann=> \d dupe_pg_c;
                 Table "public.dupe_pg_c"
  Column   |     Type     | Collation | Nullable | Default 
-----------+--------------+-----------+----------+---------
 embedding | vector(1536) |           |          | 
 
 ann=> select count(*) from public.dupe_pg_c;
 count  
--------
 500000
(1 row)
```

I did also try moving storage to plain `ALTER TABLE public.dupe_pg_c ALTER COLUMN embedding SET STORAGE PLAIN;` but still got similar results.

I am using pgvector v0.7.3. Is there something I am missing?

**Comment by jkatz** [comment]
@wahajali You have to account for the PostgreSQL page size (which defaults to 8KB). For simplicity, as you can only fit one `vector(1536)` per page:

`8192 * 500000` => `4096000000` / (1024 ^ 3) => 3.81GB. (or 3906 MB). The remainder is some overhead around table metadata.
