### ISSUE TITLE
Docker release using CI?

### ISSUE THREAD

**Issue by SamuelMarks** [pgvector/pgvector#656]
Happy to send you a PR if you're interested - https://github.com/SamuelMarks/pgvector-builds/blob/master/.github/workflows/docker_build.yml

Helps keep your hub.docker.com aligned with latest pgvector releases. E.g., every new tag you might want to trigger a Docker Hub release. There are also tools like [goreleaser](https://goreleaser.com) that'll give you nice releases on GitHub with changelogs and everything integrated ([example](https://github.com/goreleaser/goreleaser/releases/tag/v2.2.0)).

**Comment by ankane** [comment]
Hi @SamuelMarks, thanks for the suggestion, but I'm happy with the current release process (Docker Hub already gets every tag).
