### ISSUE TITLE
Thoughts on StreamingDiskANN?

### ISSUE THREAD

**Issue by philippemnoel** [pgvector/pgvector#659]
Hi team,

I’ve recently noticed the pgvectorscale extension. I’m not as familiar with this work, and am curious what the maintainers of pgvector think. Is it a valuable addition to pgvector, and if so are you thinking of eventually implementing support for it natively in pgvector?

Thank you!

Philippe

**Comment by ankane** [comment]
Hi @philippemnoel, check out #285 and #650.
