### ISSUE TITLE
Submission to postgres-contrib

### ISSUE THREAD

**Issue by kfiles** [pgvector/pgvector#66]
Would it be possible to submit pgvector to postgres-contrib? Many hosting providers (e.g., MS Azure) base their inclusion of PG extensions largely on whether the extension is part of the postgres-contrib collection.

Is there interest on the part of the authors in having pgvector included? Are there licensing or governance issues with submitting?

**Comment by ankane** [comment]
Hey @kfiles, the project is licensed under the PostgreSQL license, so it could be included in contrib in the future. For now, it should be faster to iterate as a separate project. Also, SQL doesn't really have the concept of approximate indexes (indexes that change the results when used), so I'm not sure it would be accepted. That being said, if any core team members want to discuss it, I'd be more than happy to chat.

**Comment by ericsmalling** [comment]
@ankane Sorry to resurrect an old discussion here, but if this is true, why isn't doesn't the LICENSE file list PostgreSQL in for this repo?

**Comment by ankane** [comment]
It does.

**Comment by ericsmalling** [comment]
Forgive my ignorance, but I don't see it in [LICENSE](https://github.com/pgvector/pgvector/blob/master/LICENSE)

Is it implicit in the copyright somehow?

```
Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group

Portions Copyright (c) 1994, The Regents of the University of California

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose, without fee, and without a written agreement
is hereby granted, provided that the above copyright notice and this
paragraph and the following two paragraphs appear in all copies.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
```

**Comment by ankane** [comment]
That's the text of the PostgreSQL license. https://opensource.org/license/postgresql

**Comment by ericsmalling** [comment]
Ok, thanks for that clarification.

It might reduce confusion to include a mention of the license as recommended in the OSI license description:
> ... To use it, say that it is The PostgreSQL License, and then substitute the copyright year ...
