### ISSUE TITLE
IVFFLAT QPS too low

### ISSUE THREAD

**Issue by bantmen** [pgvector/pgvector#661]
I am using IVFFLAT for 1200 dimensional embeddings of vector type. I have 20 million rows.

The query that is slow takes a user provided vector and finds the top 100 matching vectors. There are 4200 lists and 10 probes. The query **takes 30 seconds** when it's cold and 100ms if it's a repeat query. I confirmed with EXPLAIN that the index is being used. 

The issue is very slow IO. All of the query time is spent reading in the blocks that are buffer misses during the `Index Scan` operation. The throughput is about 6 mb/s. The hardware configuration is r5.2xlarge from AWS RDS.

Here is an example `EXPLAIN (ANALYZE, BUFFERS)` result:

```
Limit  (cost=106671.48..106680.48 rows=800 width=57) (actual time=11957.952..13229.665 rows=800 loops=1)
  Buffers: shared hit=17539 read=16834
  I/O Timings: shared/local read=13154.684
  ->  Index Scan using table_name_idx on table_name
        Buffers: shared hit=17539 read=16834
        I/O Timings: shared/local read=13154.684
Planning:
  Buffers: shared hit=104
Planning Time: 1.011 ms
Execution Time: 13230.135 ms
```

Given that the IO should be on SSD, I am puzzled at the extremely low throughput.

What am I doing wrong? Should I be using HNSW? Is it a huge performacne issue that most of my rows are stored as TOAST?

**Comment by jkatz** [comment]
@bantmen A r5.2xlarge has 64GB of RAM, and if you're using the PostgreSQL defaults, this would mean 16GB is allocated for shared buffers.

An IVFFlat index for this dataset would be ~89GiB in size (excluding the size of the data in the table itself), so your entire index won't fit into memory. Additionally, the data access pattern for IVFFlat can be oversimplified as "random" - using your description above, out of 4,200 centers,  you're trying to find the 10 closest to a query vector. Amongst those centroids, you're looking at ~48K vectors, which is ~220MB of data. Given each query could lead to a complete different set of 10 out of the 4,200 centers, you could end up in a situation where you're swapping data in/out of memory fairly rapidly.

Could HNSW help? In this case, you're likely keeping the top layers of your graph in memory, and while the lower level may involve more fetches to disk, it's likely to be lower. For example, if you're using `hnsw.ef_search` on the default setting (40), you'll likely scan far fewer vectors (without seeing empirical data around your embedding model, I can't give an estimated convergence). I can't comment on if you'll meet your recall target without more information.

**Comment by bantmen** [comment]
@jkatz Thank you, this is very helpful and your estimates are accurate.

`SHOW shared_buffers;` gives me `5463726`. Assuming that the unit is a 8 kb page, this is 43.7 gb.

I did not expect the IO to be really fast but the 6 mb/s throughput is puzzling to me. I guess this all depends on the physical layout. Let's say that we have 4200 centers and trying to find the 10 closest. I assume that the centroids will most likely be already in memory. That leaves us with 10 sets out of 4200 centers. Let's say that none of them are in memory. In that case, are we not going to have 10 memory seeks and for each of them high throughput sequential reads? Is pgvector not colocating the members of a list physically next to each other?

On that topic, does the index scan only look at the vectors in the index or does it have to fetch the vectors from the table? I am seeing about 43 gb cached in the buffer for the index and basically nothing (just 12 mb) cached for the underlying table. I am assuming that this split is fine if the scan is an index-only scan.

**Comment by jkatz** [comment]
@bantmen Assuming you've performed your index build and haven't added any data to the index since, the vectors associated with a list should be colocated - but note given the size of these vectors, PostgreSQL will only store one per index page.

For your second question, it depends on what your query looks like - if you're including the vector itself in your select list (`SELECT ... , vector_column , ...`), PostgreSQL will have to fetch the vector from the table. You mentioned you're using TOAST - if you're not planning to return the vector itself, then TOAST should make sense. If you're just using the vector for the distance operation (`SELECT ... FROM ... ORDER BY vector_column <=> $1`), then you shouldn't be loading the vectors stored as part of the table into memory. Given you're TOASTing the vectors, you'd have to check the associated TOAST table to see what data is in resident cache.

(Separately, if you're using an Amazon Aurora instance, you could evaluate using an [Optimized Reads](https://aws.amazon.com/blogs/database/accelerate-generative-ai-workloads-on-amazon-aurora-with-optimized-reads-and-pgvector/) instance, e.g. an r6gd.2xlarge - if your workload characteristics match the target profile, this will reduce fetches to network storage as data evicted from memory may be cached in the local NVMe.)

**Comment by bantmen** [comment]
> Assuming you've performed your index build and haven't added any data to the index since

That's correct. Given the colocation, I would expect much better IO throughput. I am checking in with AWS to understand if some configuration is throttling my IOPS.

My queries are like this:
``` sql
SELECT table.metadata1, table.metadata2, table.embedding <=> CAST({INLINED_LIST} AS vector(1152)) AS distance 
FROM table ORDER BY distance
LIMIT 800;
```

I am inlining the list in the query which is resulting in 24 kb queries. I am assuming that would not cause other strange issues? 

I am using the vectors only for the distance operation but I am reading other auxiliary columns which are of negligible size in comparison. Are the metadata columns also being stored in the index? If not, that would also result in reads directly to table which is not in the buffer (i.e. always a cache miss).

Here is what the cache residency looks like:


Table Name | Buffers | MB in Cache
-- | -- | --
table_index | 5,437,137 | 42,477
toast_table | 22,000 | 171
toast_table_index | 2,187 | 17
table | 1,641 | 12

Almost none of the TOAST'd data is in the buffer as almost all of the space is used for the index. Does the access pattern of pgvector replace the above breakdown? The toast table is 93 gb.

Thank you for the recommendation. I'll run that by the team.

**Comment by ankane** [comment]
Hi @bantmen, if you're testing performance on a snapshot, [lazy loading](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RestoreFromSnapshot.html) could be the issue.

> If you access data that hasn't been loaded yet, the DB instance immediately downloads the requested data from Amazon S3, and then continues loading the rest of the data in the background.

If that's the case, you can use [pg_prewarm](https://www.postgresql.org/docs/current/pgprewarm.html) to preload the data.

Also, HNSW should provide better query performance in most cases, and I'd recommend trying the `halfvec` type (and possibly binary quantization) so more of the data fits into memory.

**Comment by bantmen** [comment]
Hi @ankane, I have not been testing on a snapshop but I'll keep that in mind for future benchmarks.

I had previously used pg_prewarm to load the embedding table index into memory, which might explain why almost all of the buffer blocks are assigned to it. What table would you recommend prewarming with? I can also try flushing the buffers and running some queries to reset what's cached.

I think HNSW, quantization, and halfvec are all going to be beneficial here. I was hesitating to make my setup more complicated before understanding the above issue as something looks either misconfigured or poorly behaving for my use case for some reason. Let me know if you would suggest going for HNSW sooner rather than later. I do not have a good understanding of how much IO throughput to expect for these workloads.

**Comment by ankane** [comment]
If lazy loading isn't the issue, just prewarming the index should be fine.

I agree figuring out what's going on with I/O is a good first step.

**Comment by bantmen** [comment]
I migrated the database from `r5.2xlarge` to `r6gd.2xlarge` and performance characteristics are identical:
- The query performance is entirely determined by how many blocks were a cache miss
- We have the same ratio of I/O duration to number of blocks that were read

This is telling me that the query was not dependent on the I/O throughput to begin with so there is no difference between using EBS backed storage and local NVME SSD. For the former, the network latency is sub-millisecond so even with burst of many small reads we would not see a difference as the overall I/O timing is on the order of several seconds.

To double check, I stripped my query to its barebones and confirmed that the QPS is identical.

``` SQL
SET ivfflat.probes = 15;

SELECT table_name.embedding <=> CAST('{vector}' AS vector(1200)) AS distance
FROM table_name ORDER BY distance
LIMIT 800;
```

My conclusion from all of that is the way I/O is done is seemingly very inefficient as even though I/O is the clear bottleneck, the I/O throughput is not nearly saturated. For both the r5 and r6gd, I am seeing 6-7 mbps read throughput.

I am not sure if this is a consequence of how the IVFFLAT index reads are implemented or something deeper with PostgresQL but it is looking pretty concerning as the summary of it all is "if you are using the IVFFLAT index and want good p99 latency, you need the data to fit in memory". This is unfortunately cost prohibitive for us so I'll have to scratch off IVFFLAT as being performant enough for our use cases unless I can justify spending more money. Let me know if I am misinterpreting anything and I am happy to share more details if that is useful.

I will follow up with the (2) experiment.

**Comment by ankane** [comment]
Cleaning up issues (don't think there's anything for pgvector to do here).

**Comment by sandys** [comment]
@bantmen did you finally figure this out ? we are seeing the same problem on AWS and wondering what is happening.

**Comment by bantmen** [comment]
@sandys I don't think we reached a consensus in the above discussion but my understanding is there is a very significant read IO bottleneck for the IVFFLAT index implementation. I could not try HNSW because index building was demanding too much memory. I think you have three options: get a machine with more memory, reduce the space taken by your tuples and/or index (I have not experimented with this), or partition your data. None of these are satisfying. I've also tried EBS vs local storage and found no difference as the issue is strictly with the IO bandwidth and unaffected by the latency. Let me know if something works for you.

**Comment by sandys** [comment]
We are getting the same problem with HNSW btw.
The first query takes 2 minutes and then goes down to 10 seconds for
subsequent queries.

I'm not sure if I should be trying out provisioned IOPS on AWS.

Is this an AWS issue? Or is this happening with any postgresql?

**Comment by bantmen** [comment]
That's a good question. I was just in the process of setting up a database outside of AWS. I'll report back with my results comparing the same query + data. However, I think this is an issue with the implementation and not with AWS/RDS.

**Comment by jeonghyeon00** [comment]
We're getting same problem with ivfflat index, (lists = 1500) 

## Info
- 2.3 million rows, 512 dimensions
- RDS Instance t4g.medium, gp2, 150GB

```
        ('  Buffers: shared hit=375 read=3264'),
        ('  I/O Timings: shared read=2129.655'),
        ('Query Identifier: -6720460290259290568'),
        ('Planning:'),
        ('  Buffers: shared hit=1'),
        ('Planning Time: 0.101 ms'),
        ('Execution Time: 2177.252 ms');
```
We've tryed switching vector(512) -> halfvec(512), and there was some improvement but it didn't completely solve the problem.

**Comment by jkatz** [comment]
@jeonghyeon00 a t4g.medium has 1GB of shared buffers by default, whereas your index is over 4GB (which doesn't include the size of the table). Based on your query access pattern, you'll be going to storage quite frequently, which shows in the sample you provide where your cache it ratio is only 10%. In other words, based on your configuration, your performance numbers are expected.

**Comment by bantmen** [comment]
> Is this an AWS issue? Or is this happening with any postgresql?

Using the same configuration, I reproduced similar results outside of AWS. @sandys

**Comment by jeonghyeon00** [comment]
> @jeonghyeon00 a t4g.medium has 1GB of shared buffers by default, whereas your index is over 4GB (which doesn't include the size of the table). Based on your query access pattern, you'll be going to storage quite frequently, which shows in the sample you provide where your cache it ratio is only 10%. In other words, based on your configuration, your performance numbers are expected.

Is scale-up the only solution?

**Comment by bantmen** [comment]
You can do the following
- have your data take less space
- configure number of lists and number of probes
- can the data be partitioned somehow? is there a temporal access pattern by which you can partition by date and mostly only have to hold recent data in memory?
- better hardware

**Comment by kbrandes45** [comment]
So is this fixed yet?
