### ISSUE TITLE
difference in output with seq scan and index scan on vector column.

### ISSUE THREAD

**Issue by avulasaikiran** [pgvector/pgvector#664]
Hi,

I am seeing following behavior with vector extension. Is this expected or is this a known issue?

postgres=# set enable_seqscan = on;
SET
postgres=# SELECT * FROM t ORDER BY val <=> (SELECT NULL::vector);
 id |   val   
----+---------
  1 | [0,0,0]
  2 | [1,2,3]
  3 | [1,1,1]
  4 | 
  5 | [1,2,4]
(5 rows)

postgres=# 
postgres=# 
postgres=# set enable_seqscan = off;
SET
postgres=# SELECT * FROM t ORDER BY val <=> (SELECT NULL::vector);
 id |   val   
----+---------
  2 | [1,2,3]
  3 | [1,1,1]
  5 | [1,2,4]
(3 rows)

Following is my setup:

CREATE EXTENSION vector;
CREATE TABLE t (id SERIAL, val vector(3));
CALL rds_aurora.limitless_table_alter_type_sharded_and_wait('t', ARRAY['id']);
INSERT INTO t (val) VALUES ('[0,0,0]'), ('[1,2,3]'), ('[1,1,1]'), (NULL);
CREATE INDEX ON t USING ivfflat (val vector_cosine_ops) WITH (lists = 1);
INSERT INTO t (val) VALUES ('[1,2,4]');

postgres=# select * from pg_extension where extname = 'vector';
  oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+---------+----------+--------------+----------------+------------+-----------+--------------
 16403 | vector  |       10 |         2200 | t              | 0.7.3      |           | 
(1 row)

**Comment by ankane** [comment]
Hi @avulasaikiran, `NULL` vectors are not indexed, as well as zero vectors for cosine distance ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#why-are-there-less-results-for-a-query-after-adding-an-hnsw-index)).
