### ISSUE TITLE
Server crash when creating index on vector(1536)

### ISSUE THREAD

**Issue by LonnyX** [pgvector/pgvector#67]
Hi,

I don't know why but when I try to create an index on a `vector(1536)` column, the server crash:
`CREATE INDEX ON contents USING ivfflat (embedding vector_cosine_ops);`

And this is the error:
```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Currently running on PGVector  version 0.4, PGSsql 14 & Ubuntu 22.04 with 4GB memory (just a test server).

There is nothing on log `/var/log/postgresql/postgresql-14-main.log`

PS: please note that everything works fine with `vector(3)`

**Comment by ankane** [comment]
Hey @LonnyX, the most likely cause is the server running out of memory by having `maintenance_work_mem` set higher than the available memory on the machine. The Postgres server log will have the details.

**Comment by LonnyX** [comment]
I increased on a bigger memory server and it works fine
