### ISSUE TITLE
embedding::vector精度损失

### ISSUE THREAD

**Issue by Onethought1** [pgvector/pgvector#674]
HI，之前的问题，确实是服务器显示的问题，感谢您的解答，可是我又遇到了其他的问题：
SELECT * FROM embeddings WHERE model_id = 123 ORDER BY embedding::vector(3) <-> '[3,1,2]' LIMIT 5;
向量匹配的时候需要进行embedding::vector(3) 向量格式的转化，而经过向量格式转化，我的全精度内容，又变成了半精度内容，甚至连数据都变了之前是四舍五入，请问一下，这个该如何解决呢？
部分内容示例：
{0.01619569957256317，0.01705833524465561，-0.011137214489281178}
{0.016189575，0.017059326，-0.011138916}

**Comment by jkatz** [comment]
pgvector supports up to 4-byte float precision.

**Comment by Onethought1** [comment]
请问一下，可以进行源码修改来使其可以支持全精度吗？

**Comment by ankane** [comment]
You could fork and add, but it's not something I'd like to include in the project (most users don't need this).
