### ISSUE TITLE
Error - Could not find function "l2_normalize" in file "/usr/pgsql-15/lib/vector.so"

### ISSUE THREAD

**Issue by fabiombfonseca** [pgvector/pgvector#676]
Hi Team,

It has been tried to upgrade our pgvector extension from 0.6.2 to 0.7.3.1, but we have faced this issue: Could not find function "l2_normalize" in file "/usr/pgsql-15/lib/vector.so".

![screenshot](https://github.com/user-attachments/assets/4321e0f4-203e-429c-ae56-a3efec116606)

Follow environment info:
- OS: OEL 8
- PostgresSQL 15

After installed 0.7.3.1 package, it has been tried to run the following command in postgres: alter extension vector update; Then, it has been faced described error message and it was necessary to rollback to 0.6.2. Same issue already faced in 0.7.0.

What's the recommendation to fix this issue and upgrade extension to the latest one ?

**Comment by jkatz** [comment]
`0.7.3.1 ` is not a standard pgvector tag, though from the above it looks like you're using the PGDG package and installing the package that's versioned `0.7.3-1`, but that's independent of the pgvector tag.

That said, have you restarted your PostgreSQL instance after upgrading the package?

**Comment by ankane** [comment]
Hi @fabiombfonseca, it seems like your `vector.so` is outdated / on a previous version (not sure why it wouldn't be updated with the rest of the extension, but this doesn't seem like an issue with pgvector).
