### ISSUE TITLE
Q: How do PGVector indexes work internally?

### ISSUE THREAD

**Issue by MMeent** [pgvector/pgvector#68]
I'm trying to understand the computational complexity of pgvector's indexes, on what data structures they are built, and what data access patterns to expect, but I can't seem to find much in the repository that explains the data structure.

I see that k-means clustering is being used, but there is little that explains why (or how) this index is better than e.g. a set of custom operator classes for GIST indexes using the same 'vector' struct. Could you explain the index, add links to literature, and/or provide some specific search terms I can use to increase my understanding of what's happening internally?

**Comment by ankane** [comment]
Hey @MMeent, the index type is called IVFFlat, and there are more details in the first two resources [here](https://github.com/pgvector/pgvector#thanks). Here's [the description](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#cell-probe-methods-indexivf-indexes) from Faiss.
