### ISSUE TITLE
Push Postgres 17 Image?

### ISSUE THREAD

**Issue by bendangelo** [pgvector/pgvector#683]
Will a newer image be pushed?

**Comment by ankane** [comment]
Hi @bendangelo, will push a new image once [this issue](https://github.com/docker-library/postgres/issues/1272) is resolved.

**Comment by ankane** [comment]
Just pushed a new image (`pg17` / `0.7.4-pg17`).

**Comment by nithin8702** [comment]
Hi @ankane Is it possible to create new tag for pg17 changes?
