### ISSUE TITLE
Can't call 'avg' function in multi-domain schema

### ISSUE THREAD

**Issue by Stevod** [pgvector/pgvector#685]
Can't figure out how to make this query work:
select avg(embedding) from schema1.tableA

Error is:
SQL Error [42883]: ERROR: function avg(company_domains.vector) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8

pgvector extension is installed in the same (non-public) schema1 where the query is running.

Suspect its similar issue to: https://github.com/pgvector/pgvector/issues/417.

Advice would be really appreciated.

Postgres version is 16.4 and OS is Ubuntu 22.04.

Many thanks.

**Comment by ankane** [comment]
Hi @Stevod, if `schema1` is not in your search path, you'll need to use `schema1.avg` instead of `avg`.

**Comment by gwenshap** [comment]
Just to clarify, did you try the solution in the linked issue? Add 'schema1' to the 'search_path'?

**Comment by Stevod** [comment]
Hi Gwen, I didn't try search path as I assumed that the default was the local schema, but now resolved successfully. Many thanks for quick response.
