### ISSUE TITLE
HNSW partial index build?

### ISSUE THREAD

**Issue by bantmen** [pgvector/pgvector#689]
I am trying to build an HNSW index over ~18m vectors with `maintenance_work_mem` set to 32gb. Even at lower `ef_construction`, I am getting the memory pressure warning at `6524826 tuples` with the indexing getting stuck at 38%. I considered using `halfvec` but even then the memory fall short. 

Is it possible to partially build the HNSW index somehow so that I can alleviate the RAM needs? I am trying not to increase the RAM because I'd keep having to do that given that this database size will go up to 100m vectors.

Open to suggestions - thanks!

**Comment by ankane** [comment]
Hi @bantmen, check out [this recent discussion](https://github.com/pgvector/pgvector/issues/500#issuecomment-2370265830) for some ideas. I'd also recommend using `halfvec` if it doesn't affect recall much (which it shouldn't in most cases).
