### ISSUE TITLE
halfvec queries taking more time than vector

### ISSUE THREAD

**Issue by gs-vkrishnasrujan** [pgvector/pgvector#691]
Hello, Indexed ~2L embeddings using halfvec and vector using hnsw. 
I wanted to see the performance and quality of the outputs. 
The quality is same for both the indexes but the average query execution time using vector is 2.7 seconds while it is 3.9, 5.7 seconds for halfvec (checked twice)
Also, when I fired 100 queries to the DB parallely, it took 66 seconds to execute the pool using vector and 172 seconds using halfvec. This statistic is the mean derived from 100 runs. 

I was hoping that halfvec would give better performance over vector. 

My embedding dimension is 2000. 

Clarification is much appreciated.

**Comment by ankane** [comment]
Hi @gs-vkrishnasrujan, search performance should be similar for `halfvec` and `vector` in many cases (@jkatz has some numbers in [this post](https://jkatz05.com/post/postgres/pgvector-scalar-binary-quantization/)), especially if all of the data fits in memory. The main benefit is `halfvec` consumes less memory and space.

If `halfvec` is slower, it could be due to:

- the hardware
- the compiler used to compile pgvector
- the compiler flags

What OS and architecture are you on, and how was pgvector installed?

**Comment by gs-vkrishnasrujan** [comment]
Hi @ankane, thanks for responding. 
I'm running the Postgres in a container in AWS machines. The container is running in Linux Machines. Connected to it from local via tunnelling. 

If the performance of the `halfvec` and the `vector` are same, is there anything in `pgvector` that I could do it get better performance with slightly lower recall? A slight improvement in the performance will help me a lot.

**Comment by jkatz** [comment]
@gs-vkrishnasrujan It's very hard to provide guidance without more specific info. A few things to help here:

* How many vectors are you storing? Are you storing any other data next to the vectors? Are you querying any other data as well? Are you storing the data as `halfvec` in the table? For your tests, do you have separate tables for the `vector` and the `halfvec` data, or did you keep them in the same table?
* How much memory have you allocated to the container?
* Are you storing the vector using `SET STORAGE PLAIN` or just the defaults?
* Are you using any indexing?
* Do you have an example query plan for each run (preferably `EXPLAIN ANALYZE`) - please redact any sensitive information.

**Comment by gs-vkrishnasrujan** [comment]
Thanks for the help @ankane @jkatz.  I'm closing the issue.
