### ISSUE TITLE
Is scalar x vector multiplication planned ?

### ISSUE THREAD

**Issue by cigaly** [pgvector/pgvector#696]
It was long time ago when I've studied math, but if I correctly remember multiplication of vector by scalar was one of basic operations in vector definition. Is it intentionally omitted from pgvector, or just not implemented? In later case, I can implement it. Otherwise, forget this question.

**Comment by jkatz** [comment]
@cigaly Previous discussions on this are found here:  https://github.com/pgvector/pgvector/issues/157

Is there a particular use case you need this for?

**Comment by cigaly** [comment]
Apart from that this is one of fundamental operations on vectors, and that implementation is next to trivial, no.

**Comment by berndhopp** [comment]
@cigaly you marked this as completed. Is scalar multiplication available now? Is it documented somewhere?

**Comment by cigaly** [comment]
@berndhopp I've just closed this issue since there is obviously no interest to implement that and I am no interested to start just another "religious war" on the net by arguing if this is needed or not.

**Comment by berndhopp** [comment]
@cigaly alright, thanks for the answer. I also find it to be frustrating having to argue for the most mundane features that one would simply expect to be available in the first place. But for the time being, pg_vector has little competition and so we have to play along with this bullshit, unfortunately.
