### ISSUE TITLE
Discussion: understanding pgvector

### ISSUE THREAD

**Issue by ivanstepanovftw** [pgvector/pgvector#704]
pgvector stores embeddings in binary or text format? Is it normal that vector-to-compare is a plain text both in the SQL query and response? Is GPU utilized to perform dot product, or computation is not bottleneck, but memory bandwidth?
Thank you!

**Comment by ankane** [comment]
Hi @ivanstepanovftw,

1. Vectors are stored in a binary format ([docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#vector-type))
2. You can pass the vector to compare and get results as text or binary (the Postgres protocol supports both)
3. GPU isn't supported #291 (most database servers don't have a GPU)

**Comment by ivanstepanovftw** [comment]
And what is the best way to dump the database to restore it at another machine? With `pg_dump -F p > dump.sql` I see that vectors are just a string representation, which may cause loss in precision and consume more disk space than required.

**Comment by ivanstepanovftw** [comment]
`-F t` gives text representation too.

**Comment by ivanstepanovftw** [comment]
I managed to rsync old database directory to the new server and run it.

As I inspect in hexdump, `pg_dump` with all "plain", "tar", "custop" and "directory" formats, dumps floats in vectors that are written as a **decimal** representation of IEEE 754 floating point, i.e. 0.1234 or 1.234e-1, and **not** in hexadecimal formats like 0x1.9p+6 or something like that. The rest "binary" formats are just gzipped, like "custom" and "directory". IEEE 754 32-bit floating point is not using decimal numbers, so not all floats may be represented in decimal base as a string because of math.

With "custom" format issue comes quickly - it gzips vectors, while they are not compressible with gzip. I got around 6 MiB/sec at peak, while db is like 100+ GB of embeddings.

You can try yourself that "custom" binary format and see that vectors are decimal string representation:
```shell
pg_dump -U user -p port -d database -h address -F custom --compress=none
```

However, I found that there is [`pg_dumpbinary`](https://www.postgresql.org/about/news/pg_dumpbinary-v27-2422/), but I did not found that command on Ubuntu 24.04 and decided just to rsync postgres folders to a new server.

**Comment by hlinnaka** [comment]
> IEEE 754 32-bit floating point is not using decimal numbers, so not all floats may be represented in decimal base as a string because of math.
> ...
> pg_dump loses precision, takes more memory or CPU, and is not optimal to use with pgvector.

This is incorrect. You're right that not every IEEE 754 number can be accurately represented as a decimal. But it's still possible to have non-lossy round-trip conversion, IEEE754 -> decimal -> IEEE754.

The trick is that for any 32-bit floating point number, you can construct a decimal number that is closer to the the original 32-bit floating point number than any other 32-bit floating point number. That's sufficient. See "Ryū algorithm".  That's what the PostgreSQL float datatype and pgvector's vector datatype uses. It converts a float to the "shortest decimal" that represents the original floating point number in a non-lossy way.

The text representation does not lose precision.


You're probably right that you'd get better performance without that conversion. I haven't tried measuring it, but the conversion to decimal and back is not free.

**Comment by ivanstepanovftw** [comment]
Thank you, I was indeed wrong. By the way, someone tried pg_dumpbinary? Cause pg_dump takes a lot more space without compression or very slow with compression.
