### ISSUE TITLE
Debian Packages for 0.8.0

### ISSUE THREAD

**Issue by gwenshap** [pgvector/pgvector#706]
Very excited about the new release! I noticed that the new packages are not up on pgdg yet... any ETA on when we should expect them?

**Comment by ankane** [comment]
Hi @gwenshap, this isn't managed by pgvector (#449), but the team does a great job keeping it up-to-date (0.7.4 was updated the same day).

https://salsa.debian.org/postgresql/pgvector/-/commits/develop/?ref_type=HEADS
