### ISSUE TITLE
Database is drop when restarting container

### ISSUE THREAD

**Issue by brauliodiasribeiro** [pgvector/pgvector#707]
When restarting container, database is drop.

Version: pgvector/pgvector:pg16

**Comment by ankane** [comment]
Hi @brauliodiasribeiro, check out the [Docker docs](https://docs.docker.com/get-started/docker-concepts/running-containers/persisting-container-data/) for how persistence works.

**Comment by brauliodiasribeiro** [comment]
Sorry, I wrote the docker path wrong so it didn't save...tks
