### ISSUE TITLE
Normalized Performance stats

### ISSUE THREAD

**Issue by GitIgnoreMaybe** [pgvector/pgvector#715]
Hey folks, I hope you are doing well!

I am working on a comprehensive comparison of top vector databases, and PGVector absolutely needs to be included. We plan to widely distribute this comparison, highlighting the strengths of each solution.

Here's the situation: 
We have already gathered information on the features of most platforms, including PGVector. However, we are missing crucial performance metrics and pricing details, which need to be normalized for a fair comparison.

**What we need for performance data:**
P99 @10 Performance Data (99th percentile latency for the top 10 nearest neighbors) for:
- 1024-dimensional vectors
- 1 million vector dataset
- 98.5% recall rate
- Nearest neighbors based on best practices for PGVector

**Setups for a normalized comparison:**
CPU Configuration:
- 8 vCPUs
- 32 GiB RAM
- NVMe SSD

**GPU Configuration:**
- Same as CPU, but with an additional NVIDIA A100

**Regarding pricing:**
Prices for 100,000 vectors with 1024 dimensions

I'm getting thosestats from the other providers, but for PGVector I would need some help from the community.

If you have these normalized performance figures and pricing details, fantastic! If not, could you help generate them? Attributions will be given.

**Comment by ankane** [comment]
Hi @GitIgnoreMaybe, I'd recommend running your own benchmarks if you're trying to do a comprehensive comparison between databases. For pricing, pgvector is free, so the cost will depend on your hardware.

**Comment by jkatz** [comment]
@GitIgnoreMaybe Also, just measuring on dimensions with a specified target recall won't really tell you much. Recall is first dependent on the actual embedding (or other) model that generates the vectors. Without specifying the model or dataset, the test results won't show you much.
