### ISSUE TITLE
Confirming cosine distance vs cosine similarity as output?

### ISSUE THREAD

**Issue by conoremclaughlin** [pgvector/pgvector#72]
In the readme, it's specifically noted that <=> returns cosine distance. As such, can we assume the range of values is [0, 2] and **not** [-1, 1] as would be the case with cosine similarity?

I found out about your incredible extension pgvector from the following example that got passed around on Twitter a few weeks back:

https://github.com/mckaywrigley/paul-graham-gpt/

But its formula for calculating cosine distance seems to assume cosine similarity is returned, not cosine distance. Another person in one of the other closed issues for the pgvector repo also used the terms interchangeably. 

https://github.com/mckaywrigley/paul-graham-gpt/blob/main/schema.sql

```sql
-- RUN 3rd after running the scripts
create or replace function pg_search (
  query_embedding vector(1536),
  similarity_threshold float,
  match_count int
)
returns table (
  id bigint,
  essay_title text,
  essay_url text,
  essay_date text,
  essay_thanks text,
  content text,
  content_length bigint,
  content_tokens bigint,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    pg.id,
    pg.essay_title,
    pg.essay_url,
    pg.essay_date,
    pg.essay_thanks,
    pg.content,
    pg.content_length,
    pg.content_tokens,
    1 - (pg.embedding <=> query_embedding) as similarity
  from pg
  where 1 - (pg.embedding <=> query_embedding) > similarity_threshold
  order by pg.embedding <=> query_embedding
  limit match_count;
end;
$$;
```

If I'm reading this correctly, we're getting `1 - (1 - cosine_similarity(pg.embedding, query_embedding))` vs the proper result of simply `1 - cosine_similarity(pg.embedding, query_embedding)` == `cosine_distance(pg.embedding, query_embedding)` == `pg.embedding <=> query_embedding`. 

So the code snippet from the above example, that uses pgvector, is wrong. Is that correct?

Thanks so much for the awesome PG extension and your help! I may have thoroughly misunderstood something so apologies if that's the case.

**Comment by conoremclaughlin** [comment]
I'll take that back and close this issue. I just checked the OpenAI embedding docs, and they recommend using cosine similarity, so my assumption is they're using `1 - cosine_distance(embeddingA, embeddingB)` in order to restore cosine similarity even though it's effectively only changing the range of comparison.

Thanks again for the fantastic library!

**Comment by ankane** [comment]
Hey @conoremclaughlin, correct, the range of `<=>` / cosine distance is [0, 2], and the query above looks good.
