### ISSUE TITLE
Can the performance of index creation be improved?

### ISSUE THREAD

**Issue by frg01** [pgvector/pgvector#720]
When will it be possible to parallelize the work of creating an index? Now only one logical processor will be used to create the index.

**Comment by lfloeer** [comment]
Did increasing the maintenance workers help to speed up the index creation?
https://github.com/pgvector/pgvector?tab=readme-ov-file#index-build-time-1

**Comment by frg01** [comment]
> Did increasing the maintenance workers help to speed up the index creation? https://github.com/pgvector/pgvector?tab=readme-ov-file#index-build-time

I learned about the usage of this parameter and practiced it. as follows:
```SET maintenance_work_mem = '32GB';
SET max_parallel_maintenance_workers = 32;

CREATE INDEX ON pg_vector_collection USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
```


Judging from the CPU situation, it is still only a single postgres process that uses up a single logical processor, and no other logical processors are used.

>     PID      USER      PR  NI    VIRT    RES    SHR S        %CPU  %MEM     TIME+ COMMAND                              
> 2859799 postgres  20   0  480644 387724 155904 R 100.0     0.6            2:12.22 postgres

And I learned from this link that this parameter is only for B-tree use (https://postgresqlco.nf/doc/en/param/max_parallel_maintenance_workers/)

**Comment by ankane** [comment]
Hi @frg01, make sure you're on pgvector 0.6.0+ and don't have any other settings that limit parallel workers.
