### ISSUE TITLE
If i run CREATE INDEX again will the new records added incorporated in index?

### ISSUE THREAD

**Issue by svim-ig** [pgvector/pgvector#723]
i run CREATE INDEX ON items USING ivfflat (embedding vector_l2_ops) WITH (lists = 100) at time t1;...If i run CREATE INDEX again at time t2 (t2>t1) will the new vectors upserted at time t2 incorporated in ivfflat index?

**Comment by svim-ig** [comment]
i run CREATE INDEX ON items USING ivfflat (embedding vector_l2_ops) WITH (lists = 100) at time t1;...If i run CREATE INDEX again at time t2 (t2>t1) will the new vectors upserted at time t2 incorporated in ivfflat index?

**Comment by ankane** [comment]
Hi @svim-ig, running `CREATE INDEX` again will create another index (same as other Postgres index types).
