### ISSUE TITLE
options to specify hnsw.ef_search

### ISSUE THREAD

**Issue by geuis** [pgvector/pgvector#726]
I'm using Prisma migrations for schema management.
It doesn't seem that we're able to do something like this in a migration file:
```
ALTER SYSTEM SET hnsw.ef_search = 400;
SELECT pg_reload_conf();
```

We have a need to keep as many changes to db structure and settings in source control, also because all replicas need to have the same settings etc.

Is there a recommended way to do this? 

Should we perform every query as a transaction and do `SET hnsw.ef_search = 400` at the query level?

Or is it possible to do the equivalent when creating the index?
```
CREATE INDEX CONCURRENTLY hnsw_vector_embedding_idx ON cake_table USING hnsw (vector_embedding vector_cosine_ops) WITH (...); 
// (the "WITH (...)" being something we can set here)?
```

**Comment by ankane** [comment]
Hi @geuis, if the value is static, you'll probably want to set it on the system, database, or user level (#167) instead of the query level. There isn't currently a way to set it on the index level (#235).

**Comment by geuis** [comment]
Thanks @ankane. 

Got a followup. We're using Pulumi for overall infra management including Postgres deploys so that seems the way to go for this.

GCP supports the pgvector extension, but they have no documentation on whether setting `hnsw.ef_search` as a databaseFlag is supported or not. https://cloud.google.com/sql/docs/postgres/extensions

Do you have any information about the topic?

**Comment by ankane** [comment]
I don't (but it's a regular GUC variable).

**Comment by geuisbackbone** [comment]
Thanks @ankane I haven't been able to test yet but I suspect this is the way. Will report back either way. 
Would a PR to add this to the documentation be welcome if it works out?
