### ISSUE TITLE
Why is the hnsw index not used?

### ISSUE THREAD

**Issue by aropb** [pgvector/pgvector#727]
**PostgreSQL 16
pgvector 0.7.4
OS Windows**

**Table:**

CREATE TABLE IF NOT EXISTS public."km-default"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    tags text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    content text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    embedding vector(1536),
    CONSTRAINT "km-default_pkey" PRIMARY KEY (id)
)

CREATE INDEX IF NOT EXISTS idx_embedding
    ON public."km-default" USING hnsw
    (embedding vector_cosine_ops)
    TABLESPACE pg_default;

SELECT count(*) FROM public."km-default"
Count: 18 286

**Use case:**

SET enable_seqscan = OFF;
SET enable_indexscan = ON; 
SET enable_bitmapscan = ON;
SET enable_indexonlyscan = ON;

**1. Order By**

EXPLAIN ANALYZE 
SELECT id,tags,content,payload
FROM public."km-default"
ORDER BY embedding <=> '[...]' desc
LIMIT 1;

**Result:**

"Limit  (cost=10000002801.71..10000002801.71 rows=1 width=998) (actual time=188.376..188.378 rows=1 loops=1)"
"  ->  Sort  (cost=10000002801.71..10000002847.24 rows=18212 width=998) (actual time=188.375..188.375 rows=1 loops=1)"
"        Sort Key: ((embedding <=> '[...]'::vector)) DESC"
"        Sort Method: top-N heapsort  Memory: 30kB"
"        ->  Seq Scan on ""km-default""  (cost=10000000000.00..10000002710.65 rows=18212 width=998) (actual time=0.093..182.550 rows=18286 loops=1)"
"Planning Time: 0.114 ms"
"Execution Time: 188.403 ms"

**2. Where and Order By**

EXPLAIN ANALYZE 
SELECT id,tags,content,payload
FROM public."km-default"
WHERE "embedding" <=> '[...]' < 0.001
ORDER BY "embedding" <=> '[...]' desc
LIMIT 1;

**Result:**

"Limit  (cost=10000002801.71..10000002801.72 rows=1 width=998) (actual time=184.837..184.839 rows=1 loops=1)"
"  ->  Sort  (cost=10000002801.71..10000002816.89 rows=6071 width=998) (actual time=184.836..184.837 rows=1 loops=1)"
"        Sort Key: ((embedding <=> '[...]'::vector)) DESC"
"        Sort Method: top-N heapsort  Memory: 27kB"
"        ->  Seq Scan on ""km-default""  (cost=10000000000.00..10000002771.36 rows=6071 width=998) (actual time=37.617..184.802 rows=4 loops=1)"
"              Filter: ((embedding <=> '[...]'::vector) < '0.001'::double precision)"
"              Rows Removed by Filter: 18282"
"Planning Time: 0.131 ms"
"Execution Time: 184.870 ms"

Why is the hnsw index not used?

**Comment by aropb** [comment]
Strangely, I made a backup of the database and the index started working. Although I had run vacuum several times before.

**Comment by jkatz** [comment]
Yes,the ordering needs to be in ascending order.

Additionally, if you use the default storage type for larger vectors (EXTERNAL), PostgreSQL may determine that a sequential scan is cheaper as it undercounts the amount of effort to complete the scan.

Additionally, pgvector 0.8.0 improves the overall costing methodology for calculating the cost of a HNSW scan.

**Comment by aropb** [comment]
Please explain this "larger vectors (EXTERNAL)"?

**Comment by aropb** [comment]
Also, please tell me where can I download pcvector 0.8.0 binaries for linux/windows?
