### ISSUE TITLE
User-defined distance functions

### ISSUE THREAD

**Issue by michaelbautin** [pgvector/pgvector#729]
It would be great to have a way to define custom distance functions and plug them into existing HNSW and IVFFlat implementations. As far as I can see, the current code already incurs Postgres function call overhead when computing the distance.

**Comment by jkatz** [comment]
What distance functions are you looking for?

**Comment by michaelbautin** [comment]
I thought it would be great to override the distance function at least during prototyping/testing of user apps, and even evaluating various approaches for improving pgvector itself, for example, implementing product quantization outside of pgvector. A distance function could treat each coordinate of a uint8 vector as a centroid in a product quantization subspace, and the result would be computed based on such centroids of two vectors. But I guess that specific use case would require support for int8/uint8 vectors first.

In general, however, algorithms such as HNSW do not even require elements to be vectors. All that is required is distance computation. For example, the [usearch](https://github.com/unum-cloud/usearch) C++ library fully abstracts the distance function. Postgres is not C++, of course, but nonetheless it is very extensible too, and certainly users are very comfortable with defining their own functions.
