### ISSUE TITLE
Comprehensive description of required performance tests

### ISSUE THREAD

**Issue by michaelbautin** [pgvector/pgvector#730]
Is there a comprehensive description of pgvector performance tests, perhaps based on ann-benchmarks or big-ann-benchmarks, that contributors could use prior to submitting their changes to catch possible performance regressions ahead of time and maximize the chance of changes being accepted? Ideally, this description should specify test system configuration (VM instance type/specs, or memory/CPU type for a physical machine).

**Comment by jkatz** [comment]
I've discussed benchmarking [fairly extensively on my blog](jkatz05.com), and typically the methods are discussed on issues that impact performance (e.g. https://github.com/pgvector/pgvector/issues/678).
