### ISSUE TITLE
Building of hnsw sparse index is very slow

### ISSUE THREAD

**Issue by hzhua** [pgvector/pgvector#731]
I'm building both dense index and sparse index for about 5 million records. The dense and sparse vectors are generated from BGE-m3, whose dense embedding has a dimension of 1024, and sparse embedding has a dimension of 250002.

```
SET max_parallel_maintenance_workers = 15;
SET maintenance_work_mem = '32GB';

CREATE INDEX IF NOT EXISTS report_sparse_hnsw_idx
        ON vector_report
        USING hnsw (sparse_vector sparsevec_cosine_ops)
        WITH (m = 48, ef_construction = 96)

CREATE INDEX IF NOT EXISTS report_dense_hnsw_idx
        ON vector_report
        USING hnsw (dense_vector vector_cosine_ops)
        WITH (m = 48, ef_construction = 96)
````

With the same hnsw parameters, the building of dense index is fast (<30 mins), but the sparse index is very slow (the building progress is only 36% in one hour).

**Comment by ankane** [comment]
Hi @hzhua, sparse vector indexes can take longer to build. I'd recommend using the default `m` for faster build times unless you're seeing poor recall with a higher value of `ef_construction`.
