### ISSUE TITLE
Are the provided functions meant to be part of the public interface?

### ISSUE THREAD

**Issue by k0nserv** [pgvector/pgvector#732]
Hey,

Thanks for creating this project, it's great!

I wanted to ask if the functions provided by extension are meant to be part of the pubic API e.g. `array_to_vector`?

If so is there documentation about them somewhere, in particular I haven't been able to figure out the third boolean argument in `array_to_vector`.

Happy to help write some documentation for these if they are intended to be public

**Comment by ankane** [comment]
Hi @k0nserv, all of the functions considered public are documented in the [Reference](https://github.com/pgvector/pgvector?tab=readme-ov-file#reference) section.

`array_to_vector` is used for casts.

```sql
SELECT ARRAY[1,2,3]::vector;
```

The [Postgres docs](https://www.postgresql.org/docs/current/sql-createcast.html) explain the arguments.

**Comment by k0nserv** [comment]
Ah, that's even better than directly using `array_to_vector`, didn't realise that was possible
