### ISSUE TITLE
How to bypass approximate index for certain query? 

### ISSUE THREAD

**Issue by mitya12342** [pgvector/pgvector#734]
A bit of opposite thing of what everyone asked about. What is the correct way to control whether results are always exact, or approximate index might be used? How to disable only pgvector's indexes per query?

**Comment by ankane** [comment]
Hi @mitya12342, you can change the `ORDER BY` clause to an expression that isn't indexed, like:

```sql
ORDER BY (embedding <=> $1) + 0
```

Alternatively, for IVFFlat, you can set `ivfflat.probes` to the number of lists.
