### ISSUE TITLE
HNSW index returns different values ​​when adding a where condition

### ISSUE THREAD

**Issue by sieudx** [pgvector/pgvector#740]
My table: pg_embedding_question_answers
Column: embedding, document, cmetadata,id, document_id

Query 1: 
            SELECT document, cmetadata, (embedding::halfvec(1024) <-> :vector) AS distance
            FROM pg_embedding_question_answers
            WHERE (embedding::halfvec(1024) <-> :vector) <= :threshold
            ORDER BY distance
            LIMIT :limit
Query 2:
            SELECT document, cmetadata, (embedding::halfvec(1024) <-> :vector) AS distance
            FROM pg_embedding_question_answers
            WHERE (embedding::halfvec(1024) <-> :vector) <= :threshold
            AND document_id = :document_id
            ORDER BY distance
            LIMIT :limit

I execute 2 queries with the same input parameters

Vector version: 0.7.2

Result query 1: always returns 48 records no matter what limit value I set, and can't get the record with the smallest distance value

![image](https://github.com/user-attachments/assets/d9914542-5953-4556-be24-2350d5b8adb3)

Result query 2:  Returns the correct value according to limit and gets the value with the smallest distance

![image](https://github.com/user-attachments/assets/c9e8463c-afa8-4fb1-8edb-ea4d925d8c94)

I don't know why, and how to fix the query so that query 1 can get the smallest value and the records return according to the parameter of limit

**Comment by ankane** [comment]
Hi @sieudx, it sounds like the second query isn't using an approximate index (you can use `EXPLAIN ANALYZE` to confirm). Removing the approximate index will give exact results for the first query. Also, check out the [troubleshooting docs](https://github.com/pgvector/pgvector?tab=readme-ov-file#why-are-there-less-results-for-a-query-after-adding-an-hnsw-index) for more info.
