### ISSUE TITLE
Which index types are available for bit vectors?

### ISSUE THREAD

**Issue by ivanstepanovftw** [pgvector/pgvector#742]
Or nearest neighbors search by Hamming distance in bit vectors is implemented as brute-force?

**Comment by ankane** [comment]
Hi @ivanstepanovftw, it's in the readme.

**Comment by ivanstepanovftw** [comment]
Both HNSW and IVFFlat indexes are supported for bit vectors in pgvector. That means you **can** index bit vectors (i.e. binary vectors) for fast approximate nearest neighbor searches by Hamming distance—not just brute force.

For example, HNSW indexing for Hamming distance:

```sql
CREATE INDEX ON items USING hnsw (embedding bit_hamming_ops);
```

and IVFFlat indexing:

```sql
CREATE INDEX ON items USING ivfflat (embedding bit_hamming_ops) WITH (lists = 100);
```

You can then query using the `<~>` operator for Hamming distance:

```sql
SELECT *
FROM items
ORDER BY embedding <~> '101'
LIMIT 5;
```

**Comment by ivanstepanovftw** [comment]
Thank you!
