### ISSUE TITLE
Response time rise when retrieving raw text associated with embedding (without index)

### ISSUE THREAD

**Issue by olad32** [pgvector/pgvector#744]
Hi, i'm not a postgresql expert but i want to know if the following behavior is expected from the query planner/optimizer : 

I have a simple table containing vector and raw text chunk (no HNSW index)
`CREATE TABLE IF NOT EXISTS embeddings (
                    id SERIAL PRIMARY KEY,
                    chunk TEXT NOT NULL,
                    embedding vector(1536) NOT NULL
                )`
I inserted around 600k rows in it. 

In order to retrieve relevant shunk semantically, i first naively submit this query : 
`SELECT 
		id,
                chunk,
		RANK () OVER (ORDER BY embedding <=> %s::vector) AS rank,
	FROM embeddings
	ORDER BY rank
	LIMIT 10`
this gives me 7s response time, but before going through HNSW index stuff, i tried this instead (**without chunk being selected)** : 
`SELECT 
		id,
                -- chunk, 
		RANK () OVER (ORDER BY embedding <=> %s::vector) AS rank,
	FROM embeddings
	ORDER BY rank
	LIMIT 10`
and i get below 1.5s response time

so i ended up with this solution :
`WITH vector_search AS (
	SELECT 
		id,
		RANK () OVER (ORDER BY embedding <=> %s::vector) AS rank,
	FROM embeddings
	ORDER BY rank
	LIMIT 10
)
SELECT vector_search.id, embeddings.chunk
FROM vector_search LEFT JOIN embeddings ON vector_search.id = embeddings.id;`
which thanksfully gives the same response time 1.5s

Is this behavior expected from the query planner ? isn't the query planner able to optimize the original query (without WITH) ?

**Comment by olad32** [comment]
Original query plan : 
`"Limit  (cost=280819.39..280820.75 rows=10 width=1132) (actual time=6371.982..7093.264 rows=10 loops=1)"
"  ->  WindowAgg  (cost=280819.39..350050.26 rows=509776 width=1132) (actual time=6371.980..7093.261 rows=10 loops=1)"
"        ->  Gather Merge  (cost=280819.39..341129.18 rows=509776 width=1124) (actual time=6371.968..7093.238 rows=10 loops=1)"
"              Workers Planned: 3"
"              Workers Launched: 3"
"              ->  Sort  (cost=279819.35..280230.46 rows=164444 width=1124) (actual time=6274.350..6274.360 rows=42 loops=4)"
"                    Sort Key: ((embedding <=> 'OMITTED'::vector))"
"                    Sort Method: external merge  Disk: 139872kB"
"                    Worker 0:  Sort Method: external merge  Disk: 136896kB"
"                    Worker 1:  Sort Method: external merge  Disk: 141056kB"
"                    Worker 2:  Sort Method: external merge  Disk: 148240kB"
"                    ->  Parallel Seq Scan on embeddings  (cost=0.00..103697.55 rows=164444 width=1124) (actual time=0.097..1535.580 rows=127464 loops=4)"
"Planning Time: 0.085 ms"
"Execution Time: 7115.736 ms"`

Final query plan : 
`"Nested Loop Left Join  (cost=122882.31..122967.80 rows=10 width=1519) (actual time=1493.491..1498.082 rows=10 loops=1)"
"  ->  Limit  (cost=122881.89..122883.30 rows=10 width=28) (actual time=1493.458..1497.995 rows=10 loops=1)"
"        ->  WindowAgg  (cost=122881.89..194661.64 rows=509776 width=28) (actual time=1493.457..1497.992 rows=10 loops=1)"
"              ->  Gather Merge  (cost=122881.89..183191.68 rows=509776 width=30) (actual time=1493.448..1497.974 rows=10 loops=1)"
"                    Workers Planned: 3"
"                    Workers Launched: 3"
"                    ->  Sort  (cost=121881.85..122292.96 rows=164444 width=30) (actual time=1479.872..1479.965 rows=813 loops=4)"
"                          Sort Key: ((embeddings_1.embedding <=> '[-0.019915458,0.01779791,-0.006479524,-0.004606981,0.003346952,0.045501046,-0.018585427,0.0029860062,-0.013492811,0.019810455,0.037905872,-0.036295835,0.021350492,0.015522857,0.010403989,0.010631494,0.008229564,-0.016441628,0.04312099,-0.013177803,0.024605567,0.0076389257,0.018497925,0.0005042303,-0.02259302,0.009616471,-0.002670999,0.019460447,-0.037975874,-0.006650153,-0.031553227,0.016222874,-0.019495448,-0.024868071,0.05733132,0.00805456,0.0073632943,0.021052985,-0.033373266,-0.044101015,-0.02782564,-0.039200902,-0.0102464855,-0.021682998,-0.011252759,0.051241178,0.011051504,0.03344327,-0.0002696156,0.042455975,0.013816568,0.007840181,0.011165257,-0.024973074,-0.008137687,0.0044297893,0.005140743,0.13573313,0.038045876,-0.020230465,0.034895804,-0.0037078978,0.008522696,-0.005770758,0.007450796,-0.041860964,0.013422809,0.0013398746,-0.003112884,0.0034213287,-0.040390927,-0.018200418,-0.011077755,-0.005145118,0.013370307,-0.01477909,0.057996333,0.025568089,0.08323191,-0.010263986,0.0004022358,0.0077614286,-0.046866078,0.040600933,0.00587576,0.030170694,-0.028175648,-0.033793278,0.014569085,-0.010920251,-0.0067157797,-0.014735339,-0.0032441372,0.04651607,0.016292876,0.005683256,0.03748586,-0.022295512,0.027248127,0.0120227765,-0.03001319,-0.037415862,-0.034003284,0.012232781,0.02829815,0.004834486,0.00910896,0.035280813,0.019407947,0.049316134,0.012189031,-0.021227987,0.014131575,0.060201384,-0.006015763,-0.032445747,-0.014271578,-0.045116037,-0.037240855,0.00064423354,0.010342738,-0.011926524,0.032095738,0.060341388,-0.034650795,0.04210597,0.004961364,-0.012267782,-0.017894162,-0.011637768,-0.0038413384,-0.031063214,-0.02821065,0.02565559,-0.027668137,-0.029698184,0.0071051633,-0.020545473,-0.027038122,0.005180119,-0.039760914,-0.021087985,0.040250927,0.052011196,-0.014271578,-0.009467718,-0.012224031,0.020930482,-0.06303645,0.05180119,0.009948979,-0.043716006,-0.022103008,0.047251087,-0.003283513,0.008824578,-0.013746566,0.05957137,0.006825157,0.0260581,-0.009738974,-0.029838186,-0.00892958,0.028053146,-0.010447741,-0.052466206,0.034948304,0.009625222,-0.02128049,-0.002773814,0.020475471,0.0108765,0.021070484,-0.061391413,-0.0074814223,-0.020702977,-0.032918256,0.049666144,0.002246614,-0.020615473,-0.07189165,0.038850892,0.019355444,0.0058932607,0.022663021,0.027108124,0.018655429,0.0217005,-0.06492649,-0.033268265,0.008050185,-0.008872704,0.020055462,-0.011585266,-0.037625864,0.037905872,-0.036680844,-0.040985942,-0.0014853467,-0.057576325,-0.055266272,0.033880778,0.01176027,-0.0033447645,0.008382693,0.015610359,0.014595335,0.0056045037,0.01260904,-0.038920894,-0.04004092,-0.03818588,-0.0004402445,0.05120618,-0.020282967,0.032428246,-0.03255075,-0.04007592,0.039410908,-0.030958211,0.04221097,-0.070246615,0.0039835293,0.015531607,-0.03211324,-0.013694065,-0.01128776,0.021227987,-0.0024981825,0.015776614,-0.005363873,0.029488178,-0.057121314,-0.012189031,-0.05092617,-0.021402992,-0.006571401,0.02560309,0.028805662,-0.011191508,-0.038955897,-0.0039091525,-0.003955091,4.6451263e-05,0.010333988,0.07588174,0.006860158,0.061181407,-0.032393243,-0.0017106644,0.0074595464,-0.0008777546,-0.0035000804,-0.020772979,0.04917613,0.08064186,0.014665337,0.038500886,-0.0022969279,-0.025148079,-0.028438155,-0.004372913,-0.06415647,0.02653061,0.027318127,0.034510795,0.026478108,-0.03734586,-0.048091106,-0.04872112,-0.015417854,-0.05610629,-0.03738086,-0.051136177,-0.025813093,-0.034440793,-0.009826476,0.035735823,0.004812611,0.034178287,-0.03568332,0.015776614,-0.014542835,0.04637607,-0.02780814,-0.012110279,-0.0028022518,0.0050707418,0.03773087,0.061496414,0.0053594983,0.032900758,0.008925205,-0.019355444,-0.009870227,-0.011541516,0.037205856,-0.05484626,-0.054321248,-0.014437832,-0.054671258,0.010351488,0.002154737,-0.012941548,0.020737978,-0.011034003,-0.0072407913,0.06576651,-0.004208847,0.020142963,0.0049526137,-0.030065691,-0.023275536,-0.053026218,0.03391578,-0.022908026,-0.018812932,-0.007398295,0.053201225,-0.03218324,-0.00050669134,-0.014306579,-0.10143233,0.0012994049,0.058486346,-0.048126105,0.040775936,0.00958147,-0.048056107,0.0006611871,-0.015321602,-0.006619527,0.04515104,0.03127322,-0.011690269,0.009467718,0.016774137,-0.040845938,-0.03305826,0.003303201,0.012687792,-0.003430079,-0.00089525495,0.020842979,-0.006269519,0.026443109,0.013877819,-0.005692006,-0.022453016,-0.05778633,0.0009926009,-0.003331639,0.027090622,-0.027580634,0.022260511,-0.0018276983,0.03213074,0.025970597,0.0031806983,-0.0737817,-0.002412868,-0.031955734,0.008391443,0.035560817,0.03650584,0.0040404056,-0.047951102,-0.024465563,-0.03564832,-0.0014973782,-0.00401853,0.054986265,0.009905227,-0.006002638,-0.002878816,-0.047286086,0.0019381696,-0.055336274,-0.00954647,-0.00029258485,0.016826637,-0.05092617,0.015829114,-0.007901432,-0.008535821,0.044626027,-0.052851215,-0.008579573,0.0139740715,-0.011926524,-0.004202284,0.0078008045,0.011786521,-0.020247966,-0.047706097,-0.029383175,0.04655107,-0.013650314,-0.017675407,0.0027059997,0.019722953,-0.00520637,-0.05134618,0.01304655,0.03745086,0.008562072,-0.029278174,-0.016012868,0.028420653,-0.013405308,0.015137848,-0.020580472,0.035350814,-0.05383124,0.012294033,0.021017984,0.025848094,0.045571048,-0.018357921,-0.027965643,0.018655429,0.024465563,-0.061531413,0.016310375,-0.012049027,0.031115716,-0.010421489,0.025043076,0.0052501205,-0.036715843,0.019495448,-0.018497925,-0.012827795,0.023573043,0.017342899,0.034073282,-0.01867293,-0.0055301273,0.01825292,0.010727746,-0.061881423,-0.0030516328,-0.021000482,-0.012740293,0.063701466,-0.042525977,-0.02040547,-0.053236224,0.017990414,-0.009415217,0.013729066,-0.019372946,-0.00010035387,-0.029278174,-0.030975712,0.0014930031,0.015032846,-0.047706097,0.019337945,-0.01652913,-0.015531607,0.03794087,0.0035744573,-0.019827956,0.041930966,0.019775454,-0.004099469,0.023083031,0.0034082034,0.05838134,0.04445102,-0.022838024,0.08652199,0.051626187,0.030835709,0.01825292,-0.049211133,0.0024150556,-0.055406272,-0.032848254,0.02350304,0.03263825,0.034475792,0.008868329,-0.00031172592,-0.02259302,0.047286086,-0.052291203,0.01085025,0.034598295,0.024185557,-0.023765547,-0.012451536,0.005521377,0.015925366,-0.0057663824,0.051451184,0.06569651,0.008343317,-0.043681003,0.015330353,0.03521081,-0.016572881,-0.034633297,0.012512788,0.051451184,-0.029050669,0.056281295,0.060551394,-0.032428246,0.028455654,-0.03571832,-0.02740563,0.034143284,-0.0028022518,-0.025025576,0.017150395,-0.007792054,0.010543993,0.014910343,0.024238057,-0.0036619592,-0.053726237,-0.025008075,0.009432717,-0.0032616374,-0.016319126,-0.0062345183,0.12950298,0.0025506837,-0.03515831,0.032900758,0.00085095706,0.027983144,0.0017522278,-0.0047601094,-0.0261106,0.033793278,-0.003672897,-0.021718,0.02299553,-0.012757793,-0.023730546,-0.0151991,-0.0027956893,0.0011944025,0.012757793,0.0117165195,-0.0039135274,-0.028963165,-0.06331646,-0.0061951424,-0.016852887,-0.017246647,-0.028875664,0.036855847,-0.035438314,0.0008110343,0.0055301273,0.0005154415,-0.020510472,0.04042593,0.010535242,0.013160302,-0.004908863,-0.016397877,0.02950568,0.034878302,-0.025725592,0.02261052,0.0124690365,0.007980184,0.011646518,-0.008977707,-0.016774137,0.004821361,-0.023205534,0.0013934695,-0.0135978125,0.024693068,-0.01954795,-0.04256098,0.021105485,-0.0174304,-0.022068007,0.014542835,0.015347853,-0.015522857,0.003521956,-0.024255557,-0.00955522,0.0012764356,0.019005436,-0.039725915,-0.037310857,-0.011454013,-0.04389101,0.0064532734,0.04515104,-0.047216088,0.00868895,0.036120832,0.0034278913,0.02831565,0.018830433,-0.00016447644,0.042315975,0.02394055,-0.017640406,0.0047076084,0.007879556,-0.012259032,0.028455654,-0.004576355,0.02082548,0.03001319,-0.013755316,0.010596493,-0.027283128,-0.025043076,0.06307145,-0.0063788965,0.010806498,-0.013982821,-0.00031391348,0.031483226,0.0012578415,0.017342899,-0.027020622,-0.036015827,-0.011427763,-0.012705293,0.009817726,-0.019495448,0.038605887,0.021472994,-0.002885379,0.021998005,-0.0029860062,-0.011891523,-0.009931479,-0.017789159,-0.018865434,0.040180925,-0.031395722,-0.021437993,0.008977707,0.005740132,0.007267042,-0.011594017,0.0057488824,0.04648107,0.01348406,0.0348083,-0.013326556,-0.038500886,0.03178073,-0.0061951424,-0.0128452955,0.020685475,-0.02129799,0.023573043,0.0052938717,-0.011147756,-0.0102464855,0.002081454,-0.009957729,-0.01993296,0.016214123,-0.014236578,0.027738137,-0.039410908,0.012854045,-0.011165257,-0.0104827415,0.003088821,-0.03216574,0.014840341,-0.027983144,0.011279009,0.0391659,-0.02912067,-0.015549107,0.014131575,-0.02388805,0.0056701303,-0.028875664,-0.029225672,0.0009647097,-0.021647997,-0.004169471,0.0094239665,-0.037870873,0.038465884,0.0009510375,-0.012775294,0.01651163,-0.00013904617,-0.0008175969,0.018182918,-0.003069133,-0.009380216,-0.014586586,-0.009948979,-0.02000296,-0.012539038,-0.016887888,0.01655538,0.00088103587,-0.004014155,-0.0152166,-0.021560496,0.0003191089,0.013282806,0.044171017,0.036715843,-0.0018134792,0.018410424,-0.020615473,0.0048476113,0.0069170343,-0.00959897,-0.016039118,-0.045921057,-0.020720476,0.021998005,0.077211775,0.0304857,0.00079462765,0.0065013994,-0.0040010293,0.0064007724,-0.0010057263,0.019477949,-0.014455332,0.054881264,-0.013344057,-0.026233103,-0.019355444,0.043155994,0.013440309,0.01782416,0.0017194145,-0.014744089,-0.022890527,0.00052446517,-0.010500241,-0.014411582,0.008960206,-0.014035323,-0.0082251895,-0.029313175,0.04469603,0.014411582,-0.01863793,-0.02780814,0.009213962,-0.0028985043,0.009380216,-0.04133595,-0.036680844,0.010465241,0.02341554,0.01132276,0.0023516165,0.04431102,0.013134052,-0.022803025,0.0035110184,-0.0053332476,-0.024063053,0.03223574,0.02740563,-0.038955897,-0.018060416,0.017570404,0.024063053,-0.031990737,-0.001240341,0.0022127072,0.030608203,-0.009695223,-0.043751005,0.016607882,0.025305582,0.018882934,0.025690591,-0.032883257,0.018427923,-0.0024741194,-0.03745086,-0.0013344057,0.00825144,0.027265627,0.00478636,0.051241178,0.04700608,0.06713154,-0.042035967,0.005757632,-0.012792794,-0.03874589,0.03395078,-0.021017984,0.035735823,0.030188194,-0.014394081,-0.02044047,-0.018585427,-0.0009504906,-0.04480103,0.029488178,-0.014026573,-0.006864533,-0.008233939,0.026705613,0.022925528,-0.02992569,0.028000643,-0.02868316,-0.04392601,-0.009677722,0.03227074,-0.041580956,0.016240373,-0.026355606,0.010185234,0.03227074,0.035945825,0.009441467,-0.038920894,0.021630498,0.0130378,0.012871546,0.00565263,0.035980828,0.009362715,0.025008075,-0.02737063,-0.018602928,-0.022523018,-0.0154791055,-0.017220397,0.0059326366,-0.0035591444,0.0035700821,0.019950459,-0.021665499,-0.016397877,0.03997092,0.007485797,0.019827956,0.014236578,0.009940228,0.009852727,-0.00910896,0.0075339233,0.059256364,-0.021420492,-0.040215924,0.014700338,0.06216143,0.008115811,0.0024675569,0.026880618,0.02346804,-0.024500564,-0.04172096,0.020475471,0.016607882,-0.02871816,-0.011191508,-0.0088595785,0.02780814,0.05743632,0.016432878,0.020545473,0.0084833205,0.0066326526,-0.029733185,-0.030660706,-0.003712273,-0.04833611,0.00849207,-0.01215403,-0.01652038,-0.03734586,0.00044680716,-0.02560309,-0.07143664,0.006466399,0.035385814,-0.019880457,0.016677884,0.009528969,-0.0075820494,-0.025568089,-0.061636418,-0.0033819529,-0.01086775,-0.02481557,-0.022750523,0.014604086,-0.022243012,0.01647663,-0.054111246,-0.011392762,0.03206074,0.024658067,-0.0067595304,-0.018952936,0.02388805,0.021087985,0.0063613965,0.021420492,0.018042915,-0.022453016,-0.011261509,-0.045466047,0.01480534,-0.030765707,-0.014000322,0.023730546,0.021490494,0.011987776,-0.009520219,-0.011769021,-0.039060898,0.04175596,-0.0034847676,-0.010780248,-0.03143072,-0.01695789,-0.004368538,0.00059774815,-0.0019852018,0.004913238,-0.016144121,0.007962683,-0.06485649,-0.001371594,-0.014901592,0.04998115,0.0021667685,0.018567927,-0.0061513917,0.002213801,-0.0032966384,-0.05187119,-0.0071051633,0.041440953,0.01863793,0.00046239345,-0.008220814,-0.011821521,0.0021755188,-0.012906547,-0.029243173,0.008365192,0.04004092,0.0120227765,0.0039091525,-0.029960688,0.005954512,-0.009773975,-0.0088595785,0.003001319,0.031535726,0.016607882,0.029488178,-0.04833611,0.0070526623,0.019775454,0.007656426,0.0032966384,0.027073123,0.005473251,-0.018620428,0.03304076,0.041195948,0.006654528,0.007936433,-0.029523179,-0.01608287,0.0017205083,-0.02567309,0.0018987936,0.04301599,-0.026390607,0.02691562,0.009975229,-0.0011987776,0.024203056,0.018007914,0.0077658035,-0.004003217,0.048091106,-0.04567605,-0.047671095,0.0005004021,-0.021192987,0.008089561,-0.056701303,0.06671154,0.012722793,-0.008426444,-0.049806144,0.020195464,0.0050751166,0.039340906,-0.0048169857,-0.007218916,0.019722953,-0.0015083159,-0.021437993,-0.00826019,0.056281295,-0.015531607,-0.0022728648,0.020300467,-0.010036481,0.022925528,0.03001319,-0.0390959,-0.0030363197,0.00027699856,-0.03255075,-0.005963262,0.0143153295,-0.029278174,-0.002222551,-0.0021416117,0.008758951,0.014814091,-0.008299566,0.00097072544,0.025008075,-0.0050707418,-0.020545473,-0.01916294,-0.020160465,-0.03395078,-0.036120832,-0.02045797,-0.010841499,-0.008115811,0.028350651,0.0304507,0.03689085,0.0029925688,0.0010226797,-0.034895804,0.008041435,0.015155349,0.012775294,0.015750362,-0.027860641,-0.008968956,0.02262802,0.008772077,0.0045894803,-0.024220558,-0.033338267,-0.008732701,-0.021192987,-0.045396045,-0.0076433006,0.0073282938,0.010237736,0.034650795,0.016739136,0.007008911,0.013134052,-0.010543993,-0.02262802,0.0348433,0.0052238703,0.0009865852,0.007389545,0.01173402,0.0052807466,-0.017272897,0.010736497,0.002583497,-0.04560605,-0.0065189,0.022190511,0.03825588,0.020387968,-0.012092778,-0.023608044,0.024273058,0.011147756,-0.00017336337,-0.014525334,-0.030345699,0.019320445,0.021595497,0.023328036,-0.00033797653,-0.027948143,-0.009310214,-0.004738234,0.005998263,-0.013449059,-0.012259032,0.014822841,0.0032331995,0.0054995012,0.004484478,-0.0054601254,-0.005770758,-0.038080875,0.011637768,0.0008405662,0.0013825318,0.0005315747,-0.01785041,0.01392157,0.0056876307,-0.0037669616,-0.022033006,-0.023398038,0.017640406,-0.0012381534,-0.018165417,-0.025130577,0.020930482,0.015969118,-0.0027344378,0.009205212,-0.010859,-0.009703973,0.0053726234,-0.004484478,-0.0010943221,-0.005451375,0.00048344862,0.014691588,0.025008075,-0.050541162,0.0017084768,-0.005267621,-0.020492971,0.020667976,0.0021930193,0.0076651764,0.009362715,-0.0061163907,0.011156507,-0.0043269745,-0.00717079,-0.01001023,0.007897057,0.006479524,0.017229145,0.008400193,-0.0056876307,0.010981503,-0.029960688,-0.0056263795,-0.028910665,0.030975712,0.002953193,0.005035741,0.008513946,0.00056493486,-0.02654811,0.010657745,0.025830595,-0.023853049,-0.011226508,-0.01993296,0.010307737,-0.030380698,-0.008334567,0.010132733,-0.0020847355,0.03206074,-0.0025353709,0.03137822,-0.055406272,0.022435516,-0.026775615,0.012959048,-0.024605567,-0.014639087,0.013702815,0.019775454,-0.0009887727,-0.022768024,-0.008286441,-0.022050507,-0.0005332154,-0.008855204,-0.040670935,-0.02476307,-0.031938236,0.014831591,0.011480264,-0.012539038,0.0217005,-0.006571401,-0.013842818,0.006908284,0.019337945,-0.01909294,0.0039769663,-0.01603037,-0.012486537,-0.0045369794,-0.020422969,0.008763326,-0.026303105,-0.007901432,0.026810616,-0.011112755,-0.008575197,-0.031010713,0.02087798,-0.03829088,-0.006912659,-0.012005276,-0.0045807306,-0.0029313173,0.003235387,0.027283128,0.009607721,0.04000592,0.0004126267,-0.0217355,0.02348554,0.008452694,0.042385973,-0.009712723,0.037765868,-0.023993053,-0.004042593,0.0017544153,0.02392305,0.006186392,0.004865112,0.015916616,-0.013720316,0.020807978,0.008579573,0.035018306,-0.024325559,-0.004014155,0.037660867,0.013326556,0.028508157,0.0348083,0.027125623,0.011970275,-0.003478205,-0.02259302,0.019302944,-0.019320445,-0.0029925688,-0.030258195,0.0261281,-0.006077015,0.027965643,-0.0034935179,0.018567927,-0.021788001,0.002198488,0.0046726074,0.018987937,0.020230465,-0.008470194,0.02128049,0.020475471,0.011226508,-0.008570822,-0.015899116,0.018340422,-0.023748046,-0.01821792,0.0046594823,0.029418176,-0.01825292,0.015295352,-0.02740563,-0.02352054,0.0036269585,2.3977602e-05,0.012425286,-0.011524015,0.021595497,0.011436513,0.026145602,-0.014822841,-0.023118032,-0.007835805,-0.0218055,0.014402831,0.005919511,0.0027891267,0.009791475,0.0015203474,-0.03129072,-0.027895642,-0.0048519867,0.01961795,0.0105527425,-0.0050138654,0.011821521,0.06366646,-0.032690752,-0.0023341163,-0.0077220527,0.013239054,0.0010543993,0.008443944,0.0046201064,0.00032321055,-0.02040547,-0.00029887407,0.015321602,-0.025463086,0.005166994,-0.029278174,-0.015295352,-0.021525495,0.03396828,-0.0001655702,-0.0011129163,0.008220814,0.012084028,0.0020180151,-0.011506515,0.010325237,-0.024028054,0.026040599,0.019880457,0.021910504,-0.002388805,0.04081094,0.056316294,0.008229564,-0.00015381213,-0.034125786,-0.0035591444,-0.026320605,-0.0072801677,-0.028088147,0.00039375905,-0.0130553,0.017097894,-0.014455332,0.0017248834,0.00912646,0.016354127,0.016616631,-0.031465724,-0.010675246,0.0025113078,0.004873862,-0.009870227,-0.030555703,0.0008290816,0.0013661252,-0.0024084928,0.02567309,-0.012574039,-0.005473251,-0.0032528874,-0.013335307,-0.047146086,-0.009318965,0.00046485444,0.01606537,-0.0006300145,0.011786521,0.0012753418,0.023380538,0.07098163,0.023608044,0.011357761,-0.007293293,0.0030603828,-0.010745247,0.009913978,0.007621425,0.01781541,0.003935403,-0.024833072,0.031028213,-0.011979026,-0.011445263,-0.008527071,0.023555541,0.0027694388,0.016450379,-0.03643584,0.009493968,-0.014936593,0.030993212,-0.017447902,0.016870389,0.0016231623,-0.004469165,0.016362876,-0.0010926814,-0.015330353,0.008470194,0.012285283,-0.0150678465,-0.012364035,0.022715522,-0.008006434,0.022400515,-0.01958295,-0.009345215,-0.03267325,-0.006492649,0.009590221,-0.025060575,-0.012539038,0.031238219,0.00456323,0.017334148,-0.009730224,-0.00035766448,-0.01692289,-0.0014897217,0.010447741,-0.0077176774,0.01867293,0.014770339,0.022488017,0.02955818,0.013090301,0.0024544315,0.014936593,-0.032935757,-0.0108765,-0.02957568,0.008793952,-0.009283964,-0.037695866,0.009178961,0.012635291,0.0053944993,-0.023170533,-0.004396976,-0.025585588,-0.019670453,0.0015105035,-0.0035044556,0.012040277,0.044031013,-0.005534502,-0.004838861,-0.008207689,0.014927844,0.0054951264,0.011130256,-0.005696381,-0.007844555,0.012049027,0.018060416,-0.017325398,0.0043751006,0.004799485,-0.02779064,0.0082951905,-0.005902011,-0.0045107286,0.001250185,-0.013081551,0.019670453,0.03262075,-0.020142963,0.018287921,-0.020335468,-0.007621425,-0.023573043,-0.021175487,-0.019215442,0.023170533,0.027528133,-0.009030208,0.0057270066,0.0037538363,0.03696085,-0.03340827,-0.029820686,0.055021264,0.02523558,0.0123990355,-0.009415217,-0.01132276,0.00033004666,0.008741451,-0.005622004,0.01603037,-0.038010873,0.021980505,0.031518225,-0.013790317,-0.014980344,-0.020247966,-0.00827769,-0.014429082,0.019285444,0.032778256,-0.01390407,0.0006639215,0.017552903,-0.018042915,0.031920735,-0.011436513,0.0071051633,0.0061120153,-0.034108285,-0.01174277,0.023258034,-0.016599132,0.03643584,-0.00954647,0.036575843,-0.019880457,0.0047119833,0.01695789,-0.0076914267,0.004606981,-0.002110986,0.032095738,-0.02350304,-0.021122986,-0.0154441055,-0.0143853305,0.011279009]'::vector))"
"                          Sort Method: external merge  Disk: 5240kB"
"                          Worker 0:  Sort Method: external merge  Disk: 5088kB"
"                          Worker 1:  Sort Method: external merge  Disk: 4832kB"
"                          Worker 2:  Sort Method: external merge  Disk: 4840kB"
"                          ->  Parallel Seq Scan on embeddings embeddings_1  (cost=0.00..103697.55 rows=164444 width=30) (actual time=0.090..1416.149 rows=127464 loops=4)"
"  ->  Index Scan using embeddings_pkey on embeddings  (cost=0.42..8.44 rows=1 width=1503) (actual time=0.007..0.007 rows=1 loops=10)"
"        Index Cond: (id = embeddings_1.id)"
"Planning Time: 0.327 ms"
"Execution Time: 1499.332 ms"`

**Comment by ankane** [comment]
Hi @olad32, as far as I know, Postgres isn't able to internally execute the first query like the second (delay retrieving `chunk` until after the sort + gather). This behavior won't be specific to pgvector.
