### ISSUE TITLE
create index failed

### ISSUE THREAD

**Issue by GPF199541** [pgvector/pgvector#75]
CREATE INDEX ON test_vectors USING ivfflat (embedding vector_l2_ops) WITH (lists = 10000);
canceling statement due to lock timeout
CONTEXT:  while inserting index tuple (12,67) in relation "pg_class_relname_nsp_index"
Time: 70.117s (1 minute 10 seconds), executed in: 70.117s (1 minute 10 seconds)

**Comment by ankane** [comment]
Hi @GPF199541, it looks like the `CREATE INDEX` statement is being canceled by a lock timeout. See [this article](https://pganalyze.com/docs/log-insights/locks/L72) for more info (this error isn't specific to pgvector).

**Comment by GPF199541** [comment]
thanks
