### ISSUE TITLE
Add official RPM package and inclusion in PGDG YUM repository

### ISSUE THREAD

**Issue by Vonng** [pgvector/pgvector#76]
I want to express my appreciation for the `pgvector` project, an amazing extension for PostgreSQL. I have been using & testing it for a while and found it very useful for vector similarity search with great performance beyond my expectation.

I would like to ask if the project team can provide an official RPM package for `pgvector`, and add it to the official YUM repository of PGDG. This would make it much easier for users to install and manage the extension, especially for those unfamiliar with building from source.

I would also like to invite @devrimgunduz, the PostgreSQL Major Contributor and RPM packager, to consider adding `pgvector` to the official repository. I believe this would benefit the PostgreSQL community and make it easier for users to adopt this great extension.

Thank you for your attention and consideration. Best regards~

**Comment by devrimgunduz** [comment]
@Vonng ,

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=commit;h=061d9fd2a1f408157094117378bd6c8f3c78bb95


Packages will appear in next 24 hours.

**Comment by ankane** [comment]
Amazing, thanks @devrimgunduz!!

Just tried it out on Rocky Linux and Fedora and it's working great. Added instructions to the readme in the commit above.

**Comment by ankane** [comment]
And thanks for suggesting this @Vonng!
