### ISSUE TITLE
Sparse vectors

### ISSUE THREAD

**Issue by olirice** [pgvector/pgvector#81]
We've had feedback from some users of pg_vector on the supabase platform that they'd like to be able to store additional metadata along with embeddings like token counts, TFIDF, etc, that are best encoded as sparse vectors.

Is there any plan to incorporate sparse vector support and/or ops for related retrieval methods e.g. [BM25](https://en.wikipedia.org/wiki/Okapi_BM25)?

--

Thanks for the project, working with it has been a great experience

**Comment by ankane** [comment]
Hi @olirice, thanks for sharing! Will take a look at this, but it’d likely be a separate extension (since I don’t think there’d be any overlap in the implementation)

**Comment by ankane** [comment]
Closing this issue for now, but let me know if any other interesting feedback/use cases come up

**Comment by xunfeng1980** [comment]
https://github.com/paradedb/paradedb

**Comment by ankane** [comment]
Support for sparse vectors is now merged (abac7a3f776d4edbb423a000ba5234d3e8eab465) and will be included in 0.7.0 (#508).
