### ISSUE TITLE
the io is so high

### ISSUE THREAD

**Issue by GPF199541** [pgvector/pgvector#85]
### Table:
test_db=# \d test_vectors
                                 Table "public.test_vectors"
  Column   |      Type      | Collation | Nullable |                 Default                  
-----------+----------------+-----------+----------+------------------------------------------
 id        | bigint         |           | not null | nextval('test_vectors_id_seq'::regclass)
 embedding | vector(256)    |           |          | 
 biz       | character(255) |           |          | 
 pic       | character(255) |           |          | 
 url       | character(700) |           |          | 
 cls       | character(2)   |           |          | 
 loc       | character(128) |           |          | 
Indexes:
    "test_vectors_pkey" PRIMARY KEY, btree (id)
    "test_vectors_embedding_idx" ivfflat (embedding) WITH (lists='10000')

**data rows:one hundred million**

### query sql:
SELECT pic, embedding <-> '[1.5480459,1.4474366,0.19782779,0.96862954,-0.50939023,1.3571116,0.9757625,-0.2950206,0.83807796,1.7181916,1.055248,0.19448665,0.2330742,0.29954755,-0.48509938,-0.21575205,0.20185062,0.025159609,0.1798321,-1.978417,-1.7216454,-0.8223836,-0.5745151,-0.7258259,-1.3066716,0.7737701,-0.0680943,-0.30846494,-0.021950854,2.2165768,0.80664235,-0.96202403,-0.7840045,0.84112,2.3442373,-0.807576,1.59326,-0.6146176,-0.592563,-0.6699481,-0.23328912,-1.6169469,-1.1363878,2.8223796,-0.030575441,0.22029978,0.9413671,-0.71853864,-1.7151661,1.1385486,-0.10956493,0.65317076,1.8994924,0.24540828,0.043510742,-0.15686099,-1.2859524,-1.5659163,-0.4921992,1.2763612,-0.49756578,0.3947538,2.1142836,-0.019597042,0.46105537,0.9230742,0.64801854,-0.94999653,1.423858,-0.46387374,-0.47765097,1.2439967,1.2236086,0.10781672,-0.4239975,-0.021381674,1.3261949,0.21216334,0.8827301,0.9279429,1.4068856,0.76523477,-0.694803,-0.28584042,0.99292725,-0.92477363,-0.32517207,-1.0970912,0.2434911,-0.62807024,-1.5170047,-0.31989533,-0.8532654,1.4799668,-0.045863852,0.91222554,0.20404471,-0.25697124,0.9481956,-0.7365003,1.5732839,1.2672782,-0.6215398,0.18874064,-0.5565666,-2.0249624,-0.32358718,0.13846198,0.62445855,-0.9513652,0.20747803,-1.3671088,1.1093471,1.9892441,-0.42028528,0.13918677,0.9235859,-0.27885425,-0.31527916,0.44901124,-1.0298952,-0.36298835,-1.3972273,1.1510568,0.35386512,0.48794734,-0.29148743,0.20873588,0.07437206,0.0066225375,-0.22184443,-0.54655004,-0.47200894,-0.047967162,1.7597328,-1.2179211,-0.030680161,-2.0240645,-0.32339022,0.43819517,0.4711605,-0.26257384,-0.8436738,-0.49306166,0.8027538,-2.1280477,0.5047927,-0.0438089,-0.4307181,1.6272619,1.8025223,1.6332513,-1.7276917,-1.7230319,0.5169006,-1.0117515,-0.13374032,0.73420715,-0.8246429,0.4889636,-0.5061277,0.0320578,-1.4481028,0.5151214,0.5633529,-0.060932625,0.527958,0.20709732,0.97526723,-1.4395158,-1.5813943,0.57487136,-2.2638686,0.4436628,0.6008968,1.705204,2.2433994,0.92633545,0.9352424,1.4118164,-0.6105928,-0.9679845,0.14289826,0.08676394,1.471428,0.788413,-0.4621716,1.1203252,1.2047123,0.15176599,-1.6866659,0.59890753,-0.6094545,-0.29253477,-0.16374749,-0.81613356,-1.2975507,-0.10367436,1.2724738,-0.108223364,1.504333,1.19931,-0.014899006,0.6618823,1.2611048,-1.4470469,0.23790024,1.3033361,1.6238172,-0.7231472,0.72538453,-0.9875008,2.2381427,-1.8000705,-1.1207933,0.35311425,1.9009365,-0.8469877,0.22306013,-0.22122398,0.6727176,1.0954474,-0.15975504,-0.6423177,0.9367918,-1.0203831,-0.18052842,-0.6839648,0.49754587,-0.2498425,-0.11385068,1.3689955,-0.78263724,-0.5306991,-1.9017428,0.46759382,0.3253896,0.22753389,-0.8020414,-1.1603668,-1.5747116,0.123895675,-0.14995678,-0.5328575,1.0998642,-0.3739631,-0.86529386,0.67537785,0.18217218,2.179223,0.2121638,-0.25331226,-0.8602829,0.92228466,1.0028591,-1.3842623]' as score FROM test_vectors ORDER BY embedding <-> '[1.5480459,1.4474366,0.19782779,0.96862954,-0.50939023,1.3571116,0.9757625,-0.2950206,0.83807796,1.7181916,1.055248,0.19448665,0.2330742,0.29954755,-0.48509938,-0.21575205,0.20185062,0.025159609,0.1798321,-1.978417,-1.7216454,-0.8223836,-0.5745151,-0.7258259,-1.3066716,0.7737701,-0.0680943,-0.30846494,-0.021950854,2.2165768,0.80664235,-0.96202403,-0.7840045,0.84112,2.3442373,-0.807576,1.59326,-0.6146176,-0.592563,-0.6699481,-0.23328912,-1.6169469,-1.1363878,2.8223796,-0.030575441,0.22029978,0.9413671,-0.71853864,-1.7151661,1.1385486,-0.10956493,0.65317076,1.8994924,0.24540828,0.043510742,-0.15686099,-1.2859524,-1.5659163,-0.4921992,1.2763612,-0.49756578,0.3947538,2.1142836,-0.019597042,0.46105537,0.9230742,0.64801854,-0.94999653,1.423858,-0.46387374,-0.47765097,1.2439967,1.2236086,0.10781672,-0.4239975,-0.021381674,1.3261949,0.21216334,0.8827301,0.9279429,1.4068856,0.76523477,-0.694803,-0.28584042,0.99292725,-0.92477363,-0.32517207,-1.0970912,0.2434911,-0.62807024,-1.5170047,-0.31989533,-0.8532654,1.4799668,-0.045863852,0.91222554,0.20404471,-0.25697124,0.9481956,-0.7365003,1.5732839,1.2672782,-0.6215398,0.18874064,-0.5565666,-2.0249624,-0.32358718,0.13846198,0.62445855,-0.9513652,0.20747803,-1.3671088,1.1093471,1.9892441,-0.42028528,0.13918677,0.9235859,-0.27885425,-0.31527916,0.44901124,-1.0298952,-0.36298835,-1.3972273,1.1510568,0.35386512,0.48794734,-0.29148743,0.20873588,0.07437206,0.0066225375,-0.22184443,-0.54655004,-0.47200894,-0.047967162,1.7597328,-1.2179211,-0.030680161,-2.0240645,-0.32339022,0.43819517,0.4711605,-0.26257384,-0.8436738,-0.49306166,0.8027538,-2.1280477,0.5047927,-0.0438089,-0.4307181,1.6272619,1.8025223,1.6332513,-1.7276917,-1.7230319,0.5169006,-1.0117515,-0.13374032,0.73420715,-0.8246429,0.4889636,-0.5061277,0.0320578,-1.4481028,0.5151214,0.5633529,-0.060932625,0.527958,0.20709732,0.97526723,-1.4395158,-1.5813943,0.57487136,-2.2638686,0.4436628,0.6008968,1.705204,2.2433994,0.92633545,0.9352424,1.4118164,-0.6105928,-0.9679845,0.14289826,0.08676394,1.471428,0.788413,-0.4621716,1.1203252,1.2047123,0.15176599,-1.6866659,0.59890753,-0.6094545,-0.29253477,-0.16374749,-0.81613356,-1.2975507,-0.10367436,1.2724738,-0.108223364,1.504333,1.19931,-0.014899006,0.6618823,1.2611048,-1.4470469,0.23790024,1.3033361,1.6238172,-0.7231472,0.72538453,-0.9875008,2.2381427,-1.8000705,-1.1207933,0.35311425,1.9009365,-0.8469877,0.22306013,-0.22122398,0.6727176,1.0954474,-0.15975504,-0.6423177,0.9367918,-1.0203831,-0.18052842,-0.6839648,0.49754587,-0.2498425,-0.11385068,1.3689955,-0.78263724,-0.5306991,-1.9017428,0.46759382,0.3253896,0.22753389,-0.8020414,-1.1603668,-1.5747116,0.123895675,-0.14995678,-0.5328575,1.0998642,-0.3739631,-0.86529386,0.67537785,0.18217218,2.179223,0.2121638,-0.25331226,-0.8602829,0.92228466,1.0028591,-1.3842623]' LIMIT 100;
### query plan:
Limit  (cost=2218.72..2340.67 rows=100 width=267) (actual time=32.057..32.315 rows=100 loops=1)
   ->  Index Scan using test_vectors_embedding_idx on test_vectors  (cost=2218.72..121953237.72 rows=100000000 width=267) (actual time=32.056..32.307 rows=100 loops=1)
         Order By: (embedding <-> '[1.5480459,1.4474366,0.19782779,0.96862954,-0.50939023,1.3571116,0.9757625,-0.2950206,0.83807796,1.7181916,1.055248,0.19448665,0.2330742,0.29954755,-0.48509938,-0.21575205,0.20
185062,0.025159609,0.1798321,-1.978417,-1.7216454,-0.8223836,-0.5745151,-0.7258259,-1.3066716,0.7737701,-0.0680943,-0.30846494,-0.021950854,2.2165768,0.80664235,-0.96202403,-0.7840045,0.84112,2.3442373,-0.807576
,1.59326,-0.6146176,-0.592563,-0.6699481,-0.23328912,-1.6169469,-1.1363878,2.8223796,-0.030575441,0.22029978,0.9413671,-0.71853864,-1.7151661,1.1385486,-0.10956493,0.65317076,1.8994924,0.24540828,0.043510742,-0.
15686099,-1.2859524,-1.5659163,-0.4921992,1.2763612,-0.49756578,0.3947538,2.1142836,-0.019597042,0.46105537,0.9230742,0.64801854,-0.94999653,1.423858,-0.46387374,-0.47765097,1.2439967,1.2236086,0.10781672,-0.423
9975,-0.021381674,1.3261949,0.21216334,0.8827301,0.9279429,1.4068856,0.76523477,-0.694803,-0.28584042,0.99292725,-0.92477363,-0.32517207,-1.0970912,0.2434911,-0.62807024,-1.5170047,-0.31989533,-0.8532654,1.47996
68,-0.045863852,0.91222554,0.20404471,-0.25697124,0.9481956,-0.7365003,1.5732839,1.2672782,-0.6215398,0.18874064,-0.5565666,-2.0249624,-0.32358718,0.13846198,0.62445855,-0.9513652,0.20747803,-1.3671088,1.1093471
,1.9892441,-0.42028528,0.13918677,0.9235859,-0.27885425,-0.31527916,0.44901124,-1.0298952,-0.36298835,-1.3972273,1.1510568,0.35386512,0.48794734,-0.29148743,0.20873588,0.07437206,0.0066225375,-0.22184443,-0.5465
5004,-0.47200894,-0.047967162,1.7597328,-1.2179211,-0.030680161,-2.0240645,-0.32339022,0.43819517,0.4711605,-0.26257384,-0.8436738,-0.49306166,0.8027538,-2.1280477,0.5047927,-0.0438089,-0.4307181,1.6272619,1.802
5223,1.6332513,-1.7276917,-1.7230319,0.5169006,-1.0117515,-0.13374032,0.73420715,-0.8246429,0.4889636,-0.5061277,0.0320578,-1.4481028,0.5151214,0.5633529,-0.060932625,0.527958,0.20709732,0.97526723,-1.4395158,-1
.5813943,0.57487136,-2.2638686,0.4436628,0.6008968,1.705204,2.2433994,0.92633545,0.9352424,1.4118164,-0.6105928,-0.9679845,0.14289826,0.08676394,1.471428,0.788413,-0.4621716,1.1203252,1.2047123,0.15176599,-1.686
6659,0.59890753,-0.6094545,-0.29253477,-0.16374749,-0.81613356,-1.2975507,-0.10367436,1.2724738,-0.108223364,1.504333,1.19931,-0.014899006,0.6618823,1.2611048,-1.4470469,0.23790024,1.3033361,1.6238172,-0.7231472
,0.72538453,-0.9875008,2.2381427,-1.8000705,-1.1207933,0.35311425,1.9009365,-0.8469877,0.22306013,-0.22122398,0.6727176,1.0954474,-0.15975504,-0.6423177,0.9367918,-1.0203831,-0.18052842,-0.6839648,0.49754587,-0.
2498425,-0.11385068,1.3689955,-0.78263724,-0.5306991,-1.9017428,0.46759382,0.3253896,0.22753389,-0.8020414,-1.1603668,-1.5747116,0.123895675,-0.14995678,-0.5328575,1.0998642,-0.3739631,-0.86529386,0.67537785,0.1
8217218,2.179223,0.2121638,-0.25331226,-0.8602829,0.92228466,1.0028591,-1.3842623]'::vector)
 Planning Time: 0.727 ms
 Execution Time: 32.523 ms

### but the io is so high:
the server : 32c64G
work_MEM:48G
io_util:100% 350M/s
cpu: 5%

**Comment by ankane** [comment]
Hi @GPF199541, pgvector doesn’t do anything special around IO (besides using sequential pages for list entries on index creation), but happy to review changes if anyone has improvements (with benchmarks).
