### ISSUE TITLE
ERROR: type "vector" does not exist under not postgres user

### ISSUE THREAD

**Issue by morozovsk** [pgvector/pgvector#87]
I can use type vector only under user postgres and in default database but under other users in other databases I have error:
>ERROR: type "vector" does not exist

So what privileges and how I can give to other users and databases?

**Comment by dreambo8563** [comment]
I got the same error , just exec `CREATE EXTENSION vector`

**Comment by morozovsk** [comment]
Yes. I used postgres for about 15 years (triggers, stored procedures, etc) but didn't know that I need install extension for each database :)
