### ISSUE TITLE
[Question] Distance Weights

### ISSUE THREAD

**Issue by ShadiestGoat** [pgvector/pgvector#88]
Hello! 

I was looking at this project with interest. I had an idea for an application, however, I am not sure about the plausibility of it, and wanted to ask if pgvector supports such a thing. 

Suppose I have user table, which includes a profile, an ideal profile, and 'weights' for that ideal profile, all of which are vectors. The point of the application is to match users.

I was thinking that to do this, I would get the distance between the ideal profile for user A (vector A) and the profile for user B (vector B). This is slightly more complicated with weights (vector W) however, since to get the distance one would now have to multiply by the vector W before getting the magnitude.

$$
\left|
\begin{pmatrix}
    A_{0} - B_{0} \\
    \vdots \\
    A_{N} - B_{N}
\end{pmatrix}
W
\right|
$$

How would I do such a thing with pgvector? How could I apply indexing or similar techniques to make queries fast?

**Comment by ankane** [comment]
Hi @ShadiestGoat, pgvector doesn't support weighted distance functions, so you'd need to store the weighted vectors in a separate column, which you could then query (and index if needed) by L2 distance.
