### ISSUE TITLE
How to install pgvector on an existing docker container without docker-compose

### ISSUE THREAD

**Issue by pthieu** [pgvector/pgvector#91]
I have an existing pg12 running in a docker container. This was created using CLI and not `docker-compose` so I won't be able to follow this instruction: https://github.com/pgvector/pgvector/issues/56#issuecomment-1416886424

I tried to ssh into the docker container and install it, but the furthest I got was following the `Installation Notes` and installing brew on Debian (the OS in the container), then doing `brew install pgvector` and copying the files extension `.control` and `.sql` over to the `pg_config --sharedir`

However, instead of a `no such file or directory` error, I'm now getting:
```
could not access file "$libdir/vector": No such file or directory
```

Looks like `brew install pgvector` within the docker container actually installed `postgresql@14`, which probably is the wrong direction since the docker container is running 12.

Might be an easier way to do this, would appreciate some tips.

**Comment by ankane** [comment]
Hi @pthieu, you'll likely want to create a new Docker image from your existing image (with `docker build`).

```Dockerfile
FROM your-image

RUN apt-get update && \
        apt-get install -y --no-install-recommends build-essential ca-certificates git postgresql-server-dev-12 && \
        git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git /tmp/pgvector && \
        cd /tmp/pgvector && \
        make clean && \
        make OPTFLAGS="" && \
        make install && \
        mkdir /usr/share/doc/pgvector && \
        cp LICENSE README.md /usr/share/doc/pgvector && \
        rm -r /tmp/pgvector && \
        apt-get remove -y build-essential git postgresql-server-dev-12 && \
        apt-get autoremove -y && \
        rm -rf /var/lib/apt/lists/*
```

Then, restart the running container with the new image.

If you install it directly on the running image, it won't persist if the container is ever stopped (due to how Docker works).

**Comment by pthieu** [comment]
Oh man I totally forgot about that, been a while since I did anything serious with Docker.

Let me try this and report back, thanks.

**Comment by pthieu** [comment]
I ended up just building a new image with the latest Postgres, here's the `Dockerfile`:

```
ARG PG_MAJOR=15
FROM postgres:$PG_MAJOR
ARG PG_MAJOR

RUN apt-get update && \
		apt-get install -y --no-install-recommends build-essential ca-certificates git postgresql-server-dev-$PG_MAJOR && \
    git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git /tmp/pgvector && \
		cd /tmp/pgvector && \
		make clean && \
		make OPTFLAGS="" && \
		make install && \
		mkdir /usr/share/doc/pgvector && \
		cp LICENSE README.md /usr/share/doc/pgvector && \
		rm -r /tmp/pgvector && \
		apt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR && \
		apt-get autoremove -y && \
		rm -rf /var/lib/apt/lists/*
```

Then I just spun up a container with the new image.

My old container was using `postgres:latest` but for some reason on restart, it doesn't reset anything, so I'll probably have to refresh my setup.
