### ISSUE TITLE
Sponsorships

### ISSUE THREAD

**Issue by tucnak** [pgvector/pgvector#93]
Hey, @ankane all the vector database shilling on HN is pissing me off. Would you be open to receiving sponsorships for this project? If not, I think we may get something started for people like @jeadie who [has divulged][1] that he's working on HNSW-IVF and HNSW index support, or fund future SPLADE work for that matter. I just want to see pgvector succeed in this space, and although clearly there's benefit in implementing foreign data wrappers for Pinecone and the like, at scale where it would matter in principle— it's still managing yet another cluster. Timescale people have employed Postgres partitioning for [distributed hypertables][2] quite successfully, including PARALLEL SAFE aggregation and stuff like that so it leaves me wondering what is the upper bound for pgvector in terms of scaling, Postgres data and aggregate model, etc.?

[1]: https://news.ycombinator.com/item?id=35551684
[2]: https://docs.timescale.com/use-timescale/latest/distributed-hypertables/about-distributed-hypertables/

**Comment by ankane** [comment]
Hey @tucnak, I appreciate the offer, but I'm not looking for sponsorship. Also, fwiw, I'm working on product quantization, which should provide better recall/speed than HNSW (think [IVFPQ/ScaNN](https://github.com/erikbern/ann-benchmarks#glove-100-angular)), while using less memory, which is a good quality to have for a general purpose database.

**Comment by Jeadie** [comment]
I'm glad people are interested in pgvector, I certainly am. I didn't realise you were working on a PQ-IVF approach for pgvector. As @tucnak mentioned, I had started working on a HNSW improvement for pgvector. In essence using the C api within FAISS to do centroid search via HNSW to improve the scalability of search operations. The details of which are described in https://arxiv.org/abs/1802.02422v2. I might reach out to you ankane@ to discuss how I can best contribute. I think PQ-IVF could be a great approach too.

**Comment by tucnak** [comment]
Hey, thanks for keeping the conversation going and given that nobody would allow me to give them money I might as well chime in, & get involved myself. I'm currently building a complete inference layer for open source AI capability type, "free" software system etc, and what I'd discovered has significantly changed my approach to this set of tasks. So let's say you can do _complete_ and _embed_ what do you do next with it? I would potentially want to at least log every completion, and otherwise have vectors for most documents but just by adding a few triggers / agent rules, documents seem to grow very quickly! I.e. it wouldn't be unheard of to get anywhere from 5-15 documents in our current setup for one of our power tasks so your starting just with a simple document, and very soon you're doing 10 rounds of completion and another 10 rounds of embeddings, and obviously if you get some 200 GB of these you would end up with another 2 TB of embedded secondary documents which is a whole different story altogether. I explicitly didn't want to go horizontal for this in the spirit of free software and trusted computing so that leaves a single very powerful option— to utilise a high bandwidth PCIe4 NVMe as tablespace for all vector indexes but also potentially normalised vector data itself if capacity would allow this. There's an offering from Samsung that is [PM1735][1] which has some pretty amazing specs to offer 3.2-12.8 TB of storage with 3.2 TB option in HHHL form-factor at $600 price point. What's more impressive is the numbers it has to offer, namely 8 Gbit / 3.8 Gbit sequential, 1500/250 kiops random, and there's also free drivers under [OpenMPDK][2] project by Samsung. My point is: if we're looking to have some kind of sovereign AI workstation that is also self-sufficient, it does not only have to perform inference but also optimise for search and perhaps some modes of graph retrieval for ever-so intricate optimisations in the usage patterns department.

I've realised among other things is that all this AI data is not simply `order by a <-> b limit k` but it's also deeply relational, all kinds of time series datasets pop up all over the place if you're trying to schedule/prioritise inference orders, calculate some kind of ROI, cost/reward estimates for your memory vertices; I digress. I guess for now one question that I would like to ask is: how much can you push a NVMe-backed pgvector store in this, or similar position? Given that you're simply not going to be able to fit your indexes in memory, you might as well focus to dedicate a spare x8 slot to some fast 3.2 TB worth of cache and there's your unit. I think it doesn't take a genius to plug a bunch of storage, have a tablespace and create an index in it but surely you must be able to do better than this with a clever index memory layout, or some parallel/fusion ops provided by the NVMe driver itself allowing to extract as much juice as possible from it. And please do correct me if I'm wrong but in terms of bandwidth and parallelism, the bird's eye evaluation of the various aforementioned algorithms would like like this?

- IVF organizes the vector space into a set of clusters/quantizers. Each quantizer has an inverted list that stores the references to vectors of that cluster. Does this mean that IVF can be optimized for sequential reads by storing the inverted lists in a sorted order based on their similarity?
- IVF and PQ-IVF have a memory layout that is more amenable to sequential reads compared to HNSW, but they still require plenty of random I/O due to the distribution across multiple inverted lists.
- HNSW is more efficient for nearest-neighbour search, but its graph-based memory layout is not well-suited for sequential reads. However, it would seem that since the graph traversals are independent of each other, HNSW can effectively utilise parallelism for search operations.

I'm not an expert in index access methods so please do correct me if I'm wrong.

So to sum it up, my primary concern with trusted computing is that AI is very hard to get right already with only a handful hardware options but even if you get to do it, you're still in a position where you want and would get absolutely loads of data, not all of it vector, and it doesn't matter if you can establish a ROI view if you're not able to do the economical low- and performant high-recall searches; an argument for tiering— I can keep a small high-recall index for only but most recent documents in RAM to have good latency on them, & also have a big NVMe index for all documents tuned towards lower-recall, and high-bandwidth considerations when in concurrent use. I know Postgres does some optimisations where it re-arranges disk reads but I also wonder if something more advanced like what they did with [lsm3 index][3] for Postgres that requires a background worker to merge. NVMe seems to offer a powerful foundation for all kinds of decisions re: access patterns, bandwidth v. latency, or so I'm led to believe.

I wonder if there's much sense in this approach, however and what it would take to further leverage it?

[1]: https://semiconductor.samsung.com/ssd/enterprise-ssd/pm1733-pm1735/mzplj3t2hbjr-00007/
[2]: https://github.com/OpenMPDK/KVSSD
[3]: https://github.com/postgrespro/lsm3
