### ISSUE TITLE
Why do queries with cosine distance miss indexes?

### ISSUE THREAD

**Issue by gasabr** [pgvector/pgvector#96]
First of all thanks for a great project, that was a beautiful idea to embed ann into postgres!

I have a question about using distances other than l2, why does the query with cosine distance does not use index at all?

Env:
* y.cloud managed postgres https://cloud.yandex.com/en/docs/managed-postgresql/operations/extensions/cluster-extensions
* pgvector v0.2.5

Here are my indexes, selected via `select * from pg_indexes where tablename = 'products';`
```
products,products_pkey,CREATE UNIQUE INDEX products_pkey ON public.products USING btree (product_id),
products,product_l2_idx,CREATE INDEX product_l2_idx ON public.products USING ivfflat (embedding) WITH (lists='500'),
products,products_cosine_idx,CREATE INDEX products_cosine_idx ON public.products USING ivfflat (embedding vector_cosine_ops) WITH (lists='500'),
```

request with l2
```
explain
select product_id as foundProduct,
       embedding,
       embedding <-> (select embedding from products where product_id = :productId) as similarityScore
from products
where product_id != :productId
order by similarityScore
limit :limit;
```

Query plan for l2 request
```
Limit  (cost=273.82..280.57 rows=10 width=1048)
  InitPlan 1 (returns $0)
  ->  Index Scan using product_l2_idx on products  (cost=271.37..439306.79 rows=650160 width=1048)
    ->  Index Scan using products_pkey on products products_1  (cost=0.42..2.44 rows=1 width=1032)
        Order By: (embedding <-> $0)
        Filter: (product_id <> 1375773)
          Index Cond: (product_id = 1375773)
```

Request with cosine distance

```
select product_id as foundProduct,
       embedding,
       1 - (embedding <=> (select embedding from products where product_id = :productId)) as similarityScore
from products
where product_id != :productId
order by similarityScore
limit :limit;
```

Its explain
```
Limit  (cost=643398.27..643399.44 rows=10 width=1048)
  InitPlan 1 (returns $0)
    ->  Index Scan using products_pkey on products products_1  (cost=0.42..2.44 rows=1 width=1032)
          Index Cond: (product_id = 1375773)
  ->  Gather Merge  (cost=643395.83..706610.24 rows=541800 width=1048)
        Workers Planned: 2
        Params Evaluated: $0
        ->  Sort  (cost=642395.81..643073.06 rows=270900 width=1048)
              Sort Key: (('1'::double precision - (products.embedding <=> $0)))
              ->  Parallel Seq Scan on products  (cost=0.00..636541.76 rows=270900 width=1048)
                    Filter: (product_id <> 1375773)
```

As you can see, request with cosine distance does not use index, from my limited testing it is caused by `1 - cosine_dist` expression, because, index will be used, if I remove `1 -` part, but without it although index is used results are incorrect.

**Comment by ankane** [comment]
Hi @gasabr, the index isn't used since it's ordering by an expression. Use `ORDER BY embedding <=> (SELECT embedding FROM products WHERE product_id = :productId)` to use the index.

I'm not completely sure what you mean by "results are incorrect," but an index switches it to approximate nearest neighbor search. Also, the original query starts with furthest distance, and the index can only be used to start with nearest distance (since Postgres only supports `ASC` order index scans on operators).
