### ISSUE TITLE
Is it possible to query for vectors using Spring/hibernate user types?

### ISSUE THREAD

**Issue by ssuukk** [pgvector/pgvector#97]
When trying to query a database for closest vector, converting the vector to string of the format '[x,y,z...]' I'm getting an error:

ERROR: operator does not exist: vector <-> character varying

There supposedly is a way to convert client side data to proper datatype (see: https://medium.com/@diee.roman.22/using-custom-hibernate-types-in-native-queries-364f9120b79a), but it requires stating JDBC type returned in `public int[] sqlTypes() {` of that interface. So is any of java.sql.Types a proper one to use for vector type in such query?

**Comment by ssuukk** [comment]
You mean something like this would work:
`    @Query(value = "SELECT * FROM items ORDER BY embedding <-> :vec::vector LIMIT :pval", nativeQuery = true)
    Iterable<Embedding> findClosest(@Param("vec")String v, @Param("pval") int p);`
?

**Comment by ankane** [comment]
For named parameters, you may need to use `CAST(:vec AS vector)`.

**Comment by ssuukk** [comment]
OK, that solves it, although I would prefer

`Iterable<Embedding> findClosest(@Param("vec")EVector v, @Param("pval") int p);`

to

`Iterable<Embedding> findClosest(@Param("vec")String v, @Param("pval") int p);`

But I guess, you can't have everything. Thanks for help!

**Comment by ankane** [comment]
Yeah, will try to add an example/integration to [pgvector-java](https://github.com/pgvector/pgvector-java) at some point.

**Comment by beikov** [comment]
Not yet, but will be once https://hibernate.atlassian.net/browse/HHH-17357 is done. Should be part of Hibernate ORM 6.4

**Comment by ankane** [comment]
Great to hear, thanks @beikov!

**Comment by ankane** [comment]
It looks like the Hibernate Vector module is now out: https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#vector-module

Big thanks @beikov!
